- CODEOWNERS
> update codeowners temp

- android-whitelist.json
- "com.bugsnag:bugsnag-plugin-android-okhttp:15.13.0"
- "com.bugsnag:bugsnag-android:5.15.0" (Se actualizó de la 5.11.0 a la 5.15.0)
- "com.bugsnag:bugsnag-android-core:5.15.0" (Se actualizó de la 5.11.0 a la 5.15.0)
- [Mobile-Commons-Android](https://github.com/mercadolibre/fury_mobile-commons-android/pull/707)
- [Config-Provider-MP](https://github.com/mercadolibre/fury_mp-config-provider-android/pull/716)
- [Config-Provider-ML](https://github.com/mercadolibre/fury_ml-config-provider-android/pull/639)
- [Mobile-Commons-Android](https://github.com/mercadolibre/fury_mobile-commons-androi …
> Bump bugsnag version and bugsnag plugin

- android-whitelist.json
- - "com.mercadopago.android.cashin:commons:5.+"
- - "com.mercadopago.android.cashin:seller:5.+"
- - "com.mercadopago.android.cashin:payer:5.+"
> add modules cashin

- android-whitelist.json
Se deja sólo esta dependencia ya que las anteriores no se van a usar más, ya que se migra components a minapi 23, y ya se actualizó en la libs que los usan
com.mercadolibre.android.cardscomponents:cards-components:7.+
...
> cards-acquisition bump

- android-whitelist.json
- - "com.mercadolibre.android:picasso-disk-cache:1.+"
...
> Adds PX Picasso Disk Cache library

- android-whitelist.json
Se realiza la migración a API 23:
- com.mercadolibre.android.insu_flox_components:**6.+**
- com.mercadolibre.android.insu_qpage_on:**7.+**
Se coloca fecha de deprecado a la librería:
- com.mercadolibre.android.insu_proxy
- _No_
> [Insurance] Update version

- android-whitelist.json
Se sube el major ya que se migra a kotlin 1.5 y gradle 7, además de cambiar un método público lo que genera un breaking change.
- - "com.mercadolibre.android.recommendations:13.0.0"
...
> recos whitelist

- android-whitelist.json
bookmarks
history
navigationcp
comparator
...
> new versions

- ios-whitelist.json
...
- [fury_addresses-ios](https://github.com/mercadolibre/fury_addresses-ios/pull/155)
- [fury_discounts-center-ios](https://github.com/mercadolibre/fury_discounts-center-ios)
- [fury_buyingflow-mobile-ios](https://github.com/mercadolibre/fury_buyingflow-mobile-ios)
> Support Addresses iOS v6.0.0

- android-whitelist.json
Migración libreria Mpos Android a nuevo repositorio.
* "com.mercadolibre.android.payment_flow_fcu.mpos:3.x.x"
* "com.mercadolibre.android.payment_flow_fcu.paymentflowfcu:3.x.x"
* "com.mercadolibre.android.point.mpos:1.x.x"
- No, mi Lib no requiere inicialización en el `Application`
-  no tiene código con NDK
- Tiene Min API level 23
- No impacta
- [FCU](https://github.com/mercadolibre/fury_payment-flow-fcu-android)
- [MPOS](https://github.com/mercadolibre/fury_fcu-flow-mpos-android) …
> [POINTMPOS-4367] Mpos Migracion

- android-whitelist.json
- - "com.mercadolibre.android.point_smartpos_scanner"
...
> Se agrega la libreria Smartpos-Scanner a la whitelist

- android-whitelist.json
- "com.mercadolibre.android.risk_management:riksmanagement:2.0.0"
https://github.com/mercadolibre/fury_risk-management-android/blob/master/README.md
> [MOSS-1109] Se agrega la version de riksmanagement para Android

- ios-whitelist.json
- RiskManagement: 2.0.0
https://github.com/mercadolibre/fury_risk-management-ios/blob/master/README.md
> Nuevo modulo RiskManagement, para el registro de las anomalías iOS

- ios-whitelist.json
Se agregan nuevos majors para las libs de MLBiometricSecurity y BiometricSecurityUI por la migración a iOS 13.
- "MLBiometricSecurity"
- "BiometricSecurityUI"
No
No
iOS 13
No
No
- https://github.com/mercadolibre/fury_biometric-security-ios/pull/434
- https://github.com/mercadolibre/fury_biometric-security-ui-ios/pull/54
- MercadoPago / MercadoLibre monolithic
> Updated and added new majors for MLBS and BSUI

- android-whitelist.json
Se arregla typo en la definición del módulo de Risk Management. 
- "com.mercadolibre.android.risk_management:riskmanagement:2.0.0"
https://github.com/mercadolibre/fury_risk-management-android/blob/master/README.md
> [MOSS-1109] FIX: Se arregla typo el módulo riskmanagement para Android

- android-whitelist.json
- com.mercadolibre.android.usersections:3.+
> navigation-section 3.+

- ios-whitelist.json
Se agrega un expire a MLBFFloxComponent ya que no vamos a poder salir esta semana con la version nueva por problemas que tuvimos con CI.
https://github.com/mercadolibre/fury_bf-flox-components-ios
> Add expire to MLBFFloxComponent

- android-whitelist.json
- "com.facebook.android:facebook-applinks:13.2.0"
- we need this dependency because the current one is about to expire
- only dependency with CAL
> Bump SDK Facebook

- android-whitelist.json
- "com.mercadolibre.android.wallet.home:api:2.+"
> Update home api 2.+

- android-whitelist.json
- "com.mercadolibre.android:carousel:1.0.0"
> Add carousel to whitelist

- ios-whitelist.json
> Update MLRemedy / MLUserBlocker lib version 

- android-whitelist.json
- "com.mercadolibre.android.recommendations_combo:recommendations_combo:1.+"
- [VPP Android Library](https://github.com/mercadolibre/fury_vpp-android)
> Add recommendations_combo lib.

- ios-whitelist.json
> add User blocker 2.x

- ios-whitelist.json
StaticResources -> 2.x
CommonUIComponents -> 2.x
_No_
_Si tiene soporte para diferentes arquitecturas de devices_
> CommonUIComponents and StaticResources up to version 2.x

- android-whitelist.json
- - "com.mercadolibre.authentication:19.0.0"
- - "com.mercadolibre.authentication-enrollment:19.0.0"
...
- [Authentication](https://github.com/mercadolibre/fury_auth-android-authentication)
> Authentication 19.+

- android-whitelist.json
- "discounts_touchpoint:mercadolibre-3.+"
- "discounts_touchpoint:mercadopago-3.+"
- "instore_home_sections:mercadopago-3."
- "instore_ui_components:4.+"
[Buying Flow](https://github.com/mercadolibre/fury_buyingflow-mobile-android)
[Homes](https://github.com/mercadolibre/fury_homes-android)
> Bump proximity libs

- android-whitelist.json
> Update Libs CHO - API 23

- ios-whitelist.json
> Expires MLScanner

- android-whitelist.json
- - "com.mercadolibre.android.pos_readers:pos_readers:6.0.0"
...
> [Point] Bump Pos Reader v6.0.0

- ios-whitelist.json
- - "DeveloperMode"
...
- No aplica.
- [Developer Mode](www.github.com/mercadolibre/fury_developer-mode-ios)
> Bump DevMode to 1.0.0 

- README.md
Readme Change
Add expires info to iOS readme!
> feature/ add expires info for iOS readme

- ios-whitelist.json
- FBSDKCoreKit 13.2.0
- [Cross App Links](https://github.com/mercadolibre/fury_cross-app-links-ios/pull/46)
- [Cross App Links](https://github.com/mercadolibre/fury_cross-app-links-ios)
> Update FBSDKCoreKit to v13.2.0

- android-whitelist.json
- "com.mercadolibre.android:melidata-sdk:14.+"
> Bump MelidataSDK to 14

- android-whitelist.json
- ios-whitelist.json
Se eliminaron dependencias con fecha de expiracion
- Android 
- "com.mercadolibre.android.insu_flox_components:"
- "com.mercadolibre.android.insu_qpage_on:"
- IOS
- "InsurtechFloxComponents:"
Se eliminaron dependencias por deprecado de lib
- Android
- "com.mercadolibre.android.insu_proxy:"
- _No_
> Delete expired Insurance libs

- android-whitelist.json
- "com.mercadolibre.android.cross_app_links:core:4.0.0"
> Update Cross App Link 4.0.0

- android-whitelist.json
- - "com.mercadolibre.login:15.0.0"
- - "com.mercadolibre.authentication:20.0.0"
- - "com.mercadolibre.authentication-enrollment:20.0.0"
- - "com.mercadolibre.android.mobile_cryptography:test-utils:1.0.0"
- - "com.mercadolibre.android.testing:core:13.0.0"
...
- [Authentication](https://github.com/mercadolibre/fury_auth-android-authentication)
> Login 15.+ - Authentication 20.+ - TestingUtils

- android-whitelist.json
- - "com.mercadolibre.android.credits.floxclient:3.0.0"
Subio la lib a 3.0 a raiz de los bumps de min api level 23 y de kotlin + gradle
> Bump Floxclient 1.0 & maintain 0.0

- android-whitelist.json
"com.mercadolibre.android.devices_sdk:devices:3.+"
Sin impacto
- [PR](https://github.com/mercadolibre/fury_devices-sdk-android/pull/93)
> bump devices major

- android-whitelist.json
- - "com.mercadolibre.android:multiimageview:5.0.0"
...
- [[[example fend](www.github.com/mercadolibre)](https://github.com/mercadolibre/fury_sell-mobile-android)](https://github.com/mercadolibre/fury_sell-mobile-android)
- [ x] Ya existe, no tengo que agregar ni modificar nada.
> Update Multi-Image Version

- ios-whitelist.json
> Adding CardsBanking 2x to iOS allowlist

- ios-whitelist.json
iOS: DevicesSdk
- https://github.com/mercadolibre/fury_registration-ios
- https://github.com/mercadolibre/fury_auth-ios-login
- https://github.com/mercadolibre/auth-ios_authentication
> add devicesSdk lib

- ios-whitelist.json
MobileDeviceSecurity
No
No
iOS 13
No
No
- [Breaking Change] iOS Target Deployment ios13](https://github.com/mercadolibre/fury_mobile-devices-security-ios/pull/32)
- MercadoPago / MercadoLibre monolithic
> update mods libs

- android-whitelist.json
Update 
https://github.com/mercadolibre/fury_configuration-manager-android
https://github.com/mercadolibre/fury_developer-mode-android
https://github.com/mercadolibre/fury_dynamic-features-android
https://github.com/mercadolibre/fury_local-storage-android
https://github.com/mercadolibre/fury_mobile-commons-android
https://github.com/mercadolibre/fury_mobile-notifications-android
https://github.com/mercadolibre/fury_mobile-place-android
https://github.com/mercadolibre/fury_notification-center-android
https://github.com/mercadolibre/fury_restclient-android
https://github.com/mercadolibre/fury_mobile-cryptography-android
https://github.com/mercadolibre/fury_ignite-android
https://github.com/mercadolibre/fury_remote-configuration-android …
> Update libs (fundation + services)

- README.md
- android-whitelist.json
- "com.mercadolibre.android.andesui:coachmark:5.+"
- "com.mercadolibre.android.andesui:components:5.+"
> Andes 5.+ added (API 23 major)

- android-whitelist.json
Minor correction on-demand-resources version
...
> Update version on-demand

- android-whitelist.json
- - "com.mercadolibre.inappupdates:in-app-updates:5.+"
> Se agrega la version de restart flow

- android-whitelist.json
- - "com.mercadolibre.android.credits.behaviour:4.0.0"
...
- Para version 3.+ minApiLevel = 21 y maxApiLevel=29
- - Para version 4.+ minApiLevel = 23 y maxApiLevel=30
- [MercadoLibre Configuration Providers](https://github.com/mercadolibre/fury_ml-config-provider-android)
> Update Credits Behaviour

- android-whitelist.json
- "com.mercadolibre.android.uicomponents"
> Bump UiComponent 14.0.0

- android-whitelist.json
- - "com.mercadolibre.android.cart:manager:11.+"
...
> [Updated] Bump manager version

- ios-whitelist.json
> Mercado Coin Updated

- android-whitelist.json
- - "com.mercadopago.android.ml_esc_manager:ml_esc_manager:4.0.0"
- [px-android](https://github.com/mercadolibre/fury_px-android)
- [px-business-addons-android](https://github.com/mercadolibre/fury_px-business-addons-android)
- [mp-config-provider-android](https://github.com/mercadolibre/fury_mp-config-provider-android)
- [instore-android](https://github.com/mercadolibre/fury_instore-android)
> [Update] Add ESC Manager version 4+ and add expires to version 3+

- ios-whitelist.json
...
- [] _Tiene Min API level xx_
> Update version of credits behaviors ios

- ios-whitelist.json
> Update version of Credits Core iOS

- android-whitelist.json
Se actualizan las siguientes dependencias ya que actualizamos a Min API 23, Gradle 7.4 y Kotlin 1.5
- - "com.mercadolibre.android.milestone-tracker:5.0.0"
- -  "com.mercadolibre.android.progress-circle:5.0.0"
- - "com.mercadolibre.android.multiimageview:6.0.0"
> Update supply dependencies Gradle 7.4

- android-whitelist.json
- - "com.mercadolibre.android.fluxclient:flux-client:4.+""
...
- _No, xxLib no tiene código con NDK_
- _Tiene Min API level 23_, _Tiene Max API level 30_
- _Minimo, se hizo sólo migración de Kotlin 1.5, Gradle 7.4 y min API level 23._
> Flux Client update

- android-whitelist.json
- - "com.mercadolibre.android.buyingflow.flox.components:core:6.+"
...
> Flox components new version

- android-whitelist.json
- "com.mercadolibre.android.recommendations_combo:recommendations_combo:1.+"
- [VPP Android Library](https://github.com/mercadolibre/fury_vpp-android)
> Fix recommendations_combo lib.

- ios-whitelist.json
Se modifica la versión de MLNetworking para incluir el patch dentro de este. 
> Modified version of MLNetworking.

- ios-whitelist.json
Se modifica la versión de MLLocalStorage para incluir el patch dentro de esta. 
> MLLocalStorage version modified

- android-whitelist.json
> [Updated] spirtech lib to 3.0.0

- android-whitelist.json
- - "com.mercadolibre.android.ml_scanner"
...
> ml-scanner version modified (v5.0)

- android-whitelist.json
- - "com.mercadolibre.android.gamification.gamification:1.0.0"
...
- [Gamification](https://github.com/mercadolibre/fury_gamification-android/pull/66/files)
> added gamification

- .github/pull_request_template.md
- README.md
Se actualiza README y PR template para dar visibilidad al nuevo proceso mediante atención por ticket
> Update readme and pr template

- android-whitelist.json
Se corrige la regex del versionado en la librería de spirtech
> [Fix] spirtech version regex

- android-whitelist.json
> Bump modals-engine v5.+

- android-whitelist.json
Se corrige el group de la libreria gamification
- - #....
> Fix Gamification Group

- ios-whitelist.json
Es por la migración de una lib a iOS 13, esta lib es un FE que no tiene equipo de iOS y estamos ayudando a migrarla. Estamos dando suficiente tiempo de expiración por cualquier tipo de problema con los podfiles de otros equipos que lo usen para sus testapps y no haya migrado aún.
- - #....
> SecurityOptions - Migración ios 13

- android-whitelist.json
Se corrige el version de la librería gamification
- - #....
> Fix Gamification Version

- android-whitelist.json
> Deprecate: kotlin-extensions

- android-whitelist.json
- - "com.mercadopago.android.ml_esc_manager:ml_esc_manager:mercadopago-4.+"
- - "com.mercadopago.android.ml_esc_manager:ml_esc_manager:mercadolibre-4.+"
- [px-android](https://github.com/mercadolibre/fury_px-android)
- [px-business-addons-android](https://github.com/mercadolibre/fury_px-business-addons-android)
- [mp-config-provider-android](https://github.com/mercadolibre/fury_mp-config-provider-android)
- [instore-android](https://github.com/mercadolibre/fury_instore-android)
> [Fix] Add ESC Manager version 4+ using mercadopago and mercadolibre prefix

- ios-whitelist.json
Se modifica la versión de StartUPInitializer para incluir el patch en esta.
> Modified version of StartupInitializer to include the patch.

- .pre-commit-config.yaml
- android-whitelist.json
com.mercadolibre.android.local.storage:core:$localStorageVersion
com.mercadolibre.android.local.storage:kvs-defaults:$localStorageVersion
> corrections deps

- ios-whitelist.json
Por Inconvenientes con las actualizaciones de las lib a iOS 13 , se pospone la expiración de la version previa de esta lib
- - #....
> new expire date credits behaviour ios

- android-whitelist.json
- - "com.mercadolibre.login:16.0.0"
- - "com.mercadolibre.authentication:21.0.0"
- - "com.mercadolibre.authentication-enrollment:21.0.0"
...
- [Authentication](https://github.com/mercadolibre/fury_auth-android-authentication)
> Login 16.+ - Authentication 21.+

- android-whitelist.json
implementation "com.mercadolibre.android.cardsbanking:card-widget:4.+"
implementation "com.mercadolibre.android.cardsbanking:cards-home-section:4.+"
> Update cardsbanking to 4.+

- ios-whitelist.json
Se agrega Google Ads ima SDK para reproducir client side ads en VOD.
- #7537917
> Google Ads ima SDK is added 

- android-whitelist.json
- Se agrega la lib de history manager.
- #7538510
> Add history manager lib

- android-whitelist.json
Se agrega nueva version de pos-sdk para point smart, y se agrega fecha de expiracion para versiones anteriores.
- #7538510
> + Se agrega nueva version de pos-sdk para Point Smart

- ios-whitelist.json
Se actualiza la version de Bugsnag de la 6.14.3 a la version 6.19.0
- - #....
> Update Bugsnag version iOS

- android-whitelist.json
In this PR, update with the new version of mercado coin 2.+ and set expire date to the mercado coin 1.+ library.
- - #....
> Adding Mercado Coin Expire Date

- ios-whitelist.json
...
- - #....
- [X ] Mercado Pago
> Whitelist merch realstate 2.0

- ios-whitelist.json
Actualizacion version inAppReport
Version: https://github.com/mercadolibre/fury_in-app-report-ios/releases/tag/2.0.0
- - #....
> InAppReport V2 - Update ios-whitelist.json

- android-whitelist.json
Se agrega un nuevo paquete (compats) al módulo de Search
- - #7539586
> Add new package compats

- android-whitelist.json
Actualización de las librerías de mPos. paso de Rx java a coroutinas.
[POINTMPOS-4384] Actualización de mpos a coroutinas
[POINTMPOS-4384]: https://mercadolibre.atlassian.net/browse/POINTMPOS-4384?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> upated mpos dependencies

- android-whitelist.json
- Update version metrics-android
- Se agrega fecha de deprecado de la lib de metrics-Android actual.
- - #....
> Update lib metrics android

- ios-whitelist.json
Se agrega New Relic nuevamente para tener tiempo de modificar las librerías que hacen uso de esta. No se requerirá más adelante ya que se agregó OpenTelemetry. 
- - #....
> Added New Relic again.

- android-whitelist.json
Adjust android lib bumped
- #7540103
> Adjust android version bumped

- ios-whitelist.json
Agregando FBSDKCoreKit_basics, lib incorporada con la actualización de FBSDKCoreKit para una versión más reciente.
- - #....
> Add FBSDKCoreKit_basics

- ios-whitelist.json
Estamos agregando un fix en el JSON de la lib FBSDKCoreKit_basics.
- - #....
> Fix FBSDKCoreKit_basics

- ios-whitelist.json
Se sube la version de PXAddon a 2.*
- - #7540059
> PXAddon v2.* added

- ios-whitelist.json
Agregando FBAEMKit, librería incorporada con la actualización de la lib de facebook FBSDKCoreKit.
- - #....
> Add FBAEMKit

- android-whitelist.json
Add information to migration lib play-core
> Add description to migration play-core lib

- ios-whitelist.json
Bump MerchRealestates
- - #....
> bump merchrealestates

- android-whitelist.json
com.mercadolibre.android.flox:7.0.0
- - #....
> Flox 7 enabled and Flox 6 deprecated

- android-whitelist.json
Se actualiza la versión de la SDK de Braze para corregir un bug que ocurre en las apps MP y ML
- - #....
> Update Braze SDK version

- ios-whitelist.json
Se actualiza la fecha de expiración del MLScanner de Instore
- - #....
- [ X] Mercado Pago
> Actualizar fecha de expiración de MLScanner

- android-whitelist.json
This library is created to display a new screen at the end of the payment flow, based on the AndesUI and replacing the current congrats with the intention of create a single, unique and centralized FeedBack Screen that can be used across all other teams.
- #7541554
> PXN-3783: [Feat] Add Congrats-sdk

- android-whitelist.json
- Adding Dami Ui Components library 
- #7541686
> Adding Dami Ui Components lib to Android Whitelist

- ios-whitelist.json
This library is created to display a new screen at the end of the payment flow, based on the AndesUI and replacing the current congrats with the intention of create a single, unique and centralized FeedBack Screen that can be used across all other teams.
#7541632
> PXN-4621: [Feat] Add CongratsSDK

- android-whitelist.json
Bum lib rxandroidble2 1.12.0
- - #7541699
> bum rxandroidble2

- android-whitelist.json
Bump Static Resources 5
- solves [DATRAN-312](https://mercadolibre.atlassian.net/browse/DATRAN-312)
- #7541989
> Static Resources 5

- android-whitelist.json
- - [Update version cashin](https://github.com/mercadolibre/fury_cashin-android/issues/400)
> Update version cashin

- CODEOWNERS
> add codeowner

- android-whitelist.json
Se aumenta major de Analytics por migraciones de providers
> Bump Analytics

- .github/CODEOWNERS
- CODEOWNERS
Se resuelve el fix en relación a code Owner, para que solamente pueda mergear los PRs el squads de platform updates.
- - #....
> Update code owner team platform updates

- android-whitelist.json
Update QADB version for android
- - #....
> Add QADB version

- ios-whitelist.json
Modificaciones para la librería [`MLNotifications iOS`](https://github.com/mercadolibre/fury_mobile-notifications-ios).
- Agrego nuevo regex para versión `~> 4+`, a ser releaseada próximamente.
- Modifico regex para major actual `~> 3+`, agregandole `expires` para el 30 de septiembre de 2022.
- [MSF-1732](https://mercadolibre.atlassian.net/browse/MSF-1732) 
> MLNotifications Bump

- android-whitelist.json
- Implementación librería services-ads y modificación eventBus.
- - #....
> BeaconManager dependencies

- android-whitelist.json
- Se actualiza a la versión 2 la libreria de point smart helpers
- Se agrega la fecha de expiración a la versión 1
> Actualizar la libreria de point-smart helpers

- android-whitelist.json
"com.mercadolibre.android.ml_scanner"
- - #....
> scanner bump

- .pre-commit-config.yaml
- android-whitelist.json
- - com.mercadolibre.android.payment_flow_fcu:paymentflowfcu:5.0.0
- - com.mercadolibre.android.payment_flow_fcu:entities_fcu:5.0.0
- - com.mercadolibre.android.point.mpos:mpos:3.0.0
> [Point] Bump paymentFlow FCU v5.0.0 and MPOS v3.0.0

- android-whitelist.json
> Bump Metrics

- android-whitelist.json
…si-billing-info-android
Agregando una nueva biblioteca de Android para facturación de terceros en el flujo de checkout, nuestro repositorio es:
https://github.com/mercadolibre/fury_si-billing-info-android
Lo agregaré después de generar el PR.
> Added new billing info library

- android-whitelist.json
- ios-whitelist.json
Se actualiza la versión de la SDK de Braze para [ IOS 4.5.0](https://github.com/Appboy/appboy-ios-sdk/blob/master/CHANGELOG.md).
- - #7544758 -> Actualizar Lib braze-sdk IOS WhiteList
> Update Braze SDK version IOS 

- ios-whitelist.json
Esta correção resolve um tipo de crash que ocorre na versão 6.19 e habilita a atualização de versões minors de forma automática.
- - #7544902
> Updated Bugsnag in IOS

- ios-whitelist.json
Se migra la logica del Config Provider de ML al modulo (plan de migracion de Foundations)
- - #7545560
> Update Metrics version

- ios-whitelist.json
Se sube la version a 2.0.0 debido a migracion de clases del MPConfigProvider a la lib (plan de migracion del equipo de Foundations)
- - #7545553
> Update Traceability version

- android-whitelist.json
update expiration day 
- - com.polidea.rxandroidble:rxandroidble:1.5.0
- - io.reactivex:rxjava:1.3.6
- - io.reactivex:rxandroid:1.2
- - #....
> update libs expiration day

- android-whitelist.json
Migration to API 32 (Android 12)
- - #....
> Bump Android Melidata 15.0.0

- ios-whitelist.json
Add MLReviews whitelist
...
- - #....
> Add MLReviews whitelist

- android-whitelist.json
> New version for commons

- ios-whitelist.json
- Revert MLMetrics version upgrade from v2.x to v1.x
- - #7545954
> Revert MLMetrics version upgrade

- android-whitelist.json
> Add recommendations v2

- android-whitelist.json
Se crea la v1 de reviews con los package de core y form
- - #....
> [Reviews] Create version reviews

- android-whitelist.json
- ios-whitelist.json
MLCheckoutFlow: 0.+
- - #7546215
> Add MLCheckoutFlow lib

- ios-whitelist.json
Bump de versión debido a la migración a IOS13
- - #....
> Bump melidata to 1.+

- ios-whitelist.json
MLScanner: Soporte de viejo scanner hasta finalizar el rollout al nuevo scanner en InStore
- - #....
> Actualizar fecha de expiración de la lib MLScanner para métricas

- ios-whitelist.json
AdvertisingADN: 0.+
- #7546343
> [New] - AdvertisingADN integration.

- android-whitelist.json
Se cambia el nombre de paquete del nuevo repo de reviews para que no haya conflictos con el viejo repositorio
- - #....
> [Reviews 3.0] Update version new reviews

- ios-whitelist.json
Se actualiza la lib Chart a 4.1.0
- - #....
> Bump Chart lib

- android-whitelist.json
Migración
- Export
- Gradle
- Android 12
Repositorios
- Checkout SDK
- Marketplace Maps
- Rule Engine
- Flox Components
- - #....
> [ANDROID 12] - Prepare update version

- android-whitelist.json
- Migration API 32
- Migration to viewbinding
- Gradle plugin migration
- - #....
> Edit totpinapp version and expired date

- android-whitelist.json
> Update FCN libs

- android-whitelist.json
- ios-whitelist.json
Bump recommendationsCombo
Bump Ml cards iOS
Add Nl cards Android
> Add libraries to white list

- android-whitelist.json
Deprecado de lib BiometricsSdk, ya no recibe mantenimiento
- - #....
> deprecate biometricsSdk

- android-whitelist.json
Updated SmartPos Scanner version to 2.0.0 and created expiration date for version 1.0.0
> SmartPos Scanner version updated

- android-whitelist.json
> Update totp version and added expiration date

- android-whitelist.json
Se realiza ajuste en el nombre del modulo de ML-Cards-android
- - #....
> fixed ML-Cards name

- android-whitelist.json
Incrementa major por migracion a API 32    
- - #....
> bump devices-sdk

- ios-whitelist.json
- Adding new Lib DANetworking with [Concurrency](https://docs.swift.org/swift-book/LanguageGuide/Concurrency.html) Async Await support. 
This library is going to be used in all our repositories, MoneyOut, MoneyIn, CashIn, CashOut, DaManagement, CommonUIComponent among others. [further information here](https://mercadolibre.atlassian.net/wiki/spaces/DMR/pages/1943470508/DANetworking)
##
Also you can see this [PR](https://github.com/mercadolibre/fury_money-out-ios/pull/745) with the migration in one of our repositories WIP.
> Adding new Lib DANetworking

- android-whitelist.json
Se agrega Google Ads ima SDK para reproducir client side ads en VOD.
- - #7545124
- [x ] Meli Store
> added google IMA SDK

- android-whitelist.json
> Bumps Notif

- android-whitelist.json
> Bump Restclient

- android-whitelist.json
Se agrega la lib de cupones, utilizada por CHO ON
- - #....
> add smart coupons lib

- android-whitelist.json
- ios-whitelist.json
Se agrega la librería de challenges de Account Relationships para Android y para iOS.
- - #7548018
> Add Account Relationships library

- android-whitelist.json
* Se agrega fecha de expiración para la lib Instore Reviews.
* Se agrega la nueva version de la lib Instore Reviews.
-  #7547744
> Update Instore Reviews

- android-whitelist.json
Se agrega version 6 de User Biometric con soporte para api 32
- - #....
> UserBiometric v6 (API 32 migration)

- android-whitelist.json
Deprecated Security Preferences v6
Added Security Preferences v6
- - #....
> Security Preferences v6 (API 32 migration)

- android-whitelist.json
> - com.mercadolibre.android.pos_readers
> - com.mercadolibre.android.payment_flow_fcu
> - com.mercadopago.android.point_ui
> - com.mercadolibre.android.point.mpos
#
> [Point] Bump PointUI v3+ mpos v4+ FCU v6+ PosReaders v7+  (API 32 migration)

- android-whitelist.json
- Add new version instore_ui_components and mlbusinesscomponents 
- Add expiration day in old version
> Update libs: instore and mlbusinesscomponents

- android-whitelist.json
Deprecated Security UI v5
Added Security UI v6
- - #....
> Security UI v6 (API 32 migration)

- android-whitelist.json
Se agrega la librería Google Cast, la cual permite transmitir contenido VOD desde un celular a una TV, es requerida para la app Mercado Play, dejo PR de la implementación del Bitmovin, ya que tiene que ver con esta misma.
PR Bitmovin - https://github.com/mercadolibre/mobile-dependencies_whitelist/pull/1404
- - #7545124
> Added google cast implementation

- android-whitelist.json
A pedido de un par de equipos que no se pudieron migrar dado que tienen un fuerte acople y con el compromiso que lo tomaban durante Q4, hacemos el extend de esta lib deprecada por google.
- - #....
> Extend kotlin extensions

- android-whitelist.json
Matt Android lib bumped to 9+ (Android 12 migration)
> Matt version update (Android 12 migration)

- android-whitelist.json
Se actualizan versiones de
- com.mercadolibre.android.point_smart_helpers.hardware_buttons
- com.mercadolibre.android.point_smart_helpers.point_commons
#7548781
[SMARTY-6308](https://mercadolibre.atlassian.net/browse/SMARTY-6308)
> [SMARTY-6308] Upgrade point_smart_helpers up to 3.+

- android-whitelist.json
"com.mercadolibre.android.fluxclient:flux-client:5.+""
> New expires date

- android-whitelist.json
Actualización de las versiones de las librerías core de Foundation & Services que contienen la migración a API 32.
- - #....
> Core libraries versions updated - API 32 migration

- android-whitelist.json
Versions update for migrade to target API 32.
> Versions update for migrade to target API 32

- android-whitelist.json
meli-chart Android lib bumped to 4+ (Android 12 migration)
> Bump meli-chart library (Android 12)

- android-whitelist.json
Migración a Android 12 para adjust-android
> Android 12 migration for adjust-android lib

- android-whitelist.json
> Bump up risk management. (API 32 Migration)

- android-whitelist.json
com.mercadolibre.android.milestone-tracker:6.0.0
com.mercadolibre.android.multiimageview:7.0.0
- - #....
> Migration API32 Supply

- android-whitelist.json
Se extiende fecha de expiracion para las libs de MODS
- - #....
> Expired date MODS libs (API 32 migration)

- android-whitelist.json
- Se cambia la fecha de los expired, ya que esta bloqueando el CI.
- - #....
> [Android 12] - Update bump date

- android-whitelist.json
Se solicita la ampliación de expiración de las librerías por apertura de dead line para migración a android 1, esto debido a que bloquea PRs que no tienen relación con dicha migración 
- - #....
> [No-ticket] Update expiration dates

- android-whitelist.json
Update FCN libs dates
- - #....
> Update FCN libs dates

- android-whitelist.json
Migration API 32 `com.mercadolibre.android.maps:core`
- - #....
> Migration API 32 Maps 8.0.0

- android-whitelist.json
Migration API 32 `com.mercadolibre.android.credits.ui_components`
- - #....
> Migration API 32 Credits UI Components 4.0.0

- android-whitelist.json
Aplazo de fecha de expiracion de la lib biometrics sdk
- - #7549445
> biometrics expiration date

- ios-whitelist.json
AdvertisingADN: Major updated to 1.x.x.
- #7549274
> [Update] - AdvertisingADN: Major updated to 1.x.x.

- android-whitelist.json
Versions update for migrade to target API 32.
> Update credits version

- android-whitelist.json
Migración a api 32 de Credits Flox Client
- - #....
> Bump Credits Flox Client

- android-whitelist.json
> expire robolectric 4.0.1

- android-whitelist.json
expires 6.0.0 of addresses and add 7.0.0 with flavors# Ticket ID
- - #....
> expires 6.0.0 of addresses and add 7.0.0 with flavors

- android-whitelist.json
- Update Cards Banking Android-Whitelist Dependencies
- #7550069
> Update Cards Banking Android-Whitelist Dependencies

- android-whitelist.json
Se actualiza el expire de robolectric debido a que hay algunas libs que estan terminando de actualizar los test.
- - #....
> Update expire robolectric

- android-whitelist.json
Allow Flox 8 to support Android API 32
- - #7550241
> Added Flox 8 allowed dependency

- android-whitelist.json
Change expires data of migration to target API 32.
> [Expires Data] change expires data

- ios-whitelist.json
Se agrega dependencia de Google Cast para reproducir películas en TVs desde player de MercadoPlay
- - #7545100
> google-cast-sdk is added

- android-whitelist.json
Solicitamos se extienda el plazo de deprecación de las librerías **security_preferences** y **remote configuration**  debido a que el plazo para la migración de Android 12 está para el 13/10 y nuestro equipo aun no soporta android 12 por lo que no podemos hacer uso de la versión 4.0
`Para más información visitar [Wiki.](https://sites.google.com/mercadolibre.com/mobile/arquitectura/allowlist) `
- - #7550678
> [PR] Update deprecate date

- android-whitelist.json
Migración a api 32 de Credits Toolkit.
- - #....
> Bump version credits toolkit

- android-whitelist.json
Add new version instore and add expiration day in old version
- - #7550694
> update instore lib

- android-whitelist.json
Bump de Static Resources 6 que ahora soporta API 32 y Meli Gradle Plugin.
- #7550627
> Static Resources 6

- android-whitelist.json
Se depreca la version 5.+ de progress-circle.
> Progress circle update to 6.+

- android-whitelist.json
> New commons version

- android-whitelist.json
Feature/user blocker 4.0.0
- - #....
> Feature/user blocker 4.0.0

- android-whitelist.json
Deleted expiration date totp and added to whitelist faceauth
- - #....
> Edit libraries security_two_fa expiration

- android-whitelist.json
Se agregan dependencias de navigation component para el desarrollo de funcionalidad de pago de servicios. Estas librerias estan limitadas hasta fin de Q2 donde se estima que ya haya un reemplazo por parte de meli para la navegacion de fragmentos.
[SMARTY-6349](https://mercadolibre.atlassian.net/browse/SMARTY-6349)
> [SMARTY-6349] Add nav component to whitelist

- android-whitelist.json
Se añade librería viewability:
incluye wrapper que contiene OMSDK de iAb para medición de viewability en Ads 
- - #7550900
> new Library Viewability for android

- ios-whitelist.json
Se agrega Gamification 1x
- 7550825
> Adding Gamification 1x to iOS allowlist

- android-whitelist.json
-  Se actualiza la versión productiva de NFC. 
-  Se incorpora flavors, por el momento continuamos únicamente importándola en MP.  
- Se agrega description para los expires.
> Updating NFC Version

- android-whitelist.json
Se agrega nueva version valida para ser usada en el repositorio de SmartPos. 
[SMARTY-6324](https://mercadolibre.atlassian.net/browse/SMARTY-6324)
- #7550914
> [SMARTY-6429] Add new version of Spirtech 4.+

- ios-whitelist.json
> Updating Spirtech Version

- android-whitelist.json
Se actualiza la fecha de deprecado de la lib para no bloquear a otras iniciativas.
- - #....
> Search update expires date

- android-whitelist.json
Added expires date in mlwebkit version 2
```com.mercadolibre.android.mlwebkit:2.+```
- - #....
> Added expires date in mlwebkit version 2

- android-whitelist.json
Estiramos las fechas de expiracion de las dependencias de CHO para poder subirnos al tren del 13/10
- - #....
> change date of expiry checkout dependencies

- android-whitelist.json
Bump de Digital Accounts Components 4 con soporte para API 32
- #7551055
> Bump Da Components 4

- android-whitelist.json
Se actualiza la versión de reviews legacy y el nuevo reviews dandole soporte a api 32
- #7551278
> [Reviews] Bump version

- android-whitelist.json
Se da soporte a api 32
- - #7551149
> [QADB] Bump version to 6

- android-whitelist.json
Se agregó recommendation y comparator compatibles con api32
- - #....
> reco + compa

- android-whitelist.json
`com.mercadolibre.android.cross_app_links:core` --> 6.0.0
- - #....
> Bump Cross App Link 6.0.0

- android-whitelist.json
com.mercadolibre.android.cross_app_links:core
- - #....
> Fix flavor CAL

- android-whitelist.json
- Update mercado coin dependency por Android 32
- - #....
> Bump mercadocoin

- android-whitelist.json
Se agrega ml-cards-android compatibles con api32
- - #....
> bump polycards version

- android-whitelist.json
Se añade Open Measurement SDK.
OMSDK de iAb para medición de viewability en Ads 
- - #7546019 
> add new om sdk for android

- android-whitelist.json
Se agregan a la whitelist las nuevas version de Loyalty que incrementaron incrementaron su major debido a la migración a API 32
- - #....
> Loyalty changes

- ios-whitelist.json
-     Se actualiza regex para subir a major la versión de la lib BSUI (BiometricSecurityUI)
#7551225
> [MODS] Updated major for BSUI

- android-whitelist.json
> Scanner Bump to 7.0

- ios-whitelist.json
Reverts mercadolibre/mobile-dependencies_whitelist#1530
Abrimos revert de este PR dado que no salió la versión mayor como lo habíamos planeado inicialmente
> Revert "[MODS] Updated major for BSUI"

- android-whitelist.json
Fix scanner modules versions to match core version.
- - #....
> Fix scanner modules versions

- android-whitelist.json
Se agrega el SDK de Globe para la integración en el modulo de spp-prepaid. Este SDK va tener una sola versión que es la que está definida en el PR. La idea es que se utilice en el modulo de prepaid pero se integre como Dynamic Feature en la app azul
- - #....
> [Feature] added single player prepaid globe module

- android-whitelist.json
Update UI version to 10.+, mark old version with expire and description
- #7553968
> [Feature] Update UI version to 10.+

- ios-whitelist.json
Este PR agrega la dependencia de MPlay al listado de dependencias permitidas para poder incluir el nuevo módulo en la app de MercadoLibre
- #7553999
> Added Mplay dependency

- ios-whitelist.json
Actualización del nombre de `CongratsSdk` a `FeedbackScreen`
- - #7554298
> Update CongratsSDK pod name to FeedbackScreen

- android-whitelist.json
Se necesita subir esta version de Cards Banking para poder que este pueda funcionar correctamente en Home.
Se realizo bump de la lib debido a cambio de nombre de Folder.
- #7554521
> Cards Banking v5 to v6

- android-whitelist.json
update fcu-core to version 7.+
> Update fcu-core version

- android-whitelist.json
Nueva libraria de equipo MLB Sellers Growth. Esa libraria va contener en las proximas versiones algunas Custom Actions que van soportar nuestros Webviews. En la primera version de eso PR, salimos con una Custom Action que retorna la ubicación del device cuando llamada por  MobileWebKit.executeNative
- - #7555025
> adding library for project mp_sellers_growth

- android-whitelist.json
Nueva lib: Behavioral. 
- - #7555628
> add behavioral lib

- android-whitelist.json
> DataBinding Libraries

- android-whitelist.json
Remover de la whitelist la version 4.+ de Spirtech. y quitar la fecha de expiración de la version 3.+
- #7556110
> Rollback spirtech version 4.+

- ios-whitelist.json
Nueva librería de Andes  AndesIntegrations  
Por ahora contiene las configuraciones de Colores, fuentes (no la carga de fuentes .. esta esta en MLUI por ahora) y andescurrencies.
este es uno de los pr que aplica
https://github.com/mercadolibre/fury_mp-config-provider-ios/pull/491
https://github.com/mercadolibre/fury_ml-config-provider-ios/pull/396
que estan en wip pero no estan pasando el linter por la whitelist..
repositorio 
https://github.com/mercadolibre/fury_andes-integrations-ios
- - #....
> andesintegrations

- android-whitelist.json
Se crea una nueva major version de la lib security preferences android, y se le pone una fecha de expiración a la actual.
- - #....
> se actualiza major de security preferences

- android-whitelist.json
Agregamos el nuevo módulo [andes-integrations-android](https://github.com/mercadolibre/fury_andes-integrations-android).
Este módulo contiene la lógica para la configuración de colores de MercadoLibre y MercadoPago, además de las clases necesarias para integrar data de countries y currencies provenientes de la lib de Commons dentro de la lib de Andes.
- #7557039
> [Feature] New module: andes-integrations-android

- android-whitelist.json
Se actualizan los major post migracion de agp 7 y java 11, por retrocompatibilidad, para evitar issues en los integradores de nuestra lib.
- - #....
> Se actualiza el major de user biometrics y security ui

- android-whitelist.json
> Updated version of Leakcanary, necessary for the correct function of the [Developer Mode](https://github.com/mercadolibre/fury_developer-mode-android) inside TestApps with API 32
- - #7556773
> Updated Leakcanary version

- android-whitelist.json
Se agrega un expiration date para la lib de remedies y liveness previas a la migración de API 32 (Android 12).
- - #....
> Add remedies & liveness expiration date

- ios-whitelist.json
change cardform to private in whitelist
- - #7557817
> migrate cardform to private

- android-whitelist.json
Desde proximity queremos agregar la posibilidad de animar las imagenes para descar a los sellers desde arquitectura nos propusieron usar WebP sobre gif y creemos que es lo mas asertado ya que reduce el peso del file en un 50 %
[Documento de analisis](https://docs.google.com/document/d/1buZRQRzGTkYWaXOPdDCO9GCY52UNj7evkDIkkc0d-kk/edit#heading=h.l201m9ki2pcy)
- - #7556242
Peso del modulo 2,7MB para todas las arquitecturas pero en diff se puede ver que el peso real seria menor a 800kb por procesador 
Apk universal release con webp integrado
Apk universal release sin webp
Analisis Lib
> WebP animated - Fresco module.json

- android-whitelist.json
> bump expire date firebase ads

- android-whitelist.json
https://github.com/mercadolibre/fury_configuration-manager-android
https://github.com/mercadolibre/fury_dynamic-features-android
https://github.com/mercadolibre/fury_local-storage-android
https://github.com/mercadolibre/fury_ml-config-provider-android
https://github.com/mercadolibre/fury_mobile-cryptography-android
https://github.com/mercadolibre/fury_mobile-commons-android
https://github.com/mercadolibre/fury_mobile-notifications-android
https://github.com/mercadolibre/fury_mobile-place-android
https://github.com/mercadolibre/fury_mp-config-provider-android
https://github.com/mercadolibre/fury_notification-center-android
https://github.com/mercadolibre/fury_restclient-android
AGP 7.2.2 Update
> Update foundations libs for AGP 7.2.2

- ios-whitelist.json
Se agrega wrapper con la libreria para Globe-ABT
- #7557515
> Added SPGlobeWrapper

- android-whitelist.json
- ios-whitelist.json
La librería de SellerHomeSection contiene secciones relacionada a información del Seller, que se visualizarán dentro de la Home de MP.
- - #....
> Add Seller Home Section library

- ios-whitelist.json
Changed fury private card drawer
- - #....
> Added private card drawer

- android-whitelist.json
> upgrade devices-sdk 5.0.0

- android-whitelist.json
> [MPoC PoC] Whitelist lib testing 

- android-whitelist.json
Se hace downgrade de la librería de Bitmovin por inconvenientes de librerías transitorias con la integración a la App Amarilla
- - #....
> downgrade Bitmovin library

- android-whitelist.json
- Se actualiza dami ui components lib a versión 2.0.0
- - [#7558061]()
> - Bump Dami Ui lib to 2.0.0

- android-whitelist.json
Se agrega dependencia para el flujo de pago de servicios, nueva funcionalidad de smartpos
[SMARTY-7034](https://mercadolibre.atlassian.net/browse/SMARTY-7034)
Ticket fury #7559352
> [SMARTY-7034] Add bill payments dependency

- android-whitelist.json
- `com.mercadolibre.android:authentication:23.0.0`
- `com.mercadolibre.android:authentication-enrollment:23.0.0`
> Modify import for authentication

- android-whitelist.json
- Added CxDaisy to whitelist
- #7559569
> Added CxDaisy to whitelist

- android-whitelist.json
> Daisy-whitelist

- android-whitelist.json
> Add new repo in white list

- android-whitelist.json
PR para hacer bump a Melidata a 16.+ debido a cambios en config-providers
- - #....
> Bump MelidataSDK to 16.+

- android-whitelist.json
Restored for 1 day, library deprecated in order to generate a hotfix.
#7560722
> Add common lib deprecated temporally

- android-whitelist.json
Se actualiza AGP a 7.2.2
- - #7560825
> [Reviews] Bump version to 4

- android-whitelist.json
Se actualiza la versión de globe SDK desde 2.2.1-52 a 2.2.5-55
- - #....
> [Feature] updated globe lib from 2.2.1-52 to 2.2.5-55

- android-whitelist.json
-Se hace update a la versión 17.6.0 que es la versión que siempre estuvo usando ml scanner
- - #....
> update play-services-base to 17.6.0

- android-whitelist.json
Se construyo un nuevo modulo llamado configurer para desacoplar el configprovider de la libreria OnDemandResources
#7561172
> add new module configurer OnDemandResources

- android-whitelist.json
Bump QADB Version
- - #7561085
> bump qadb version

- android-whitelist.json
Added the new Hub Engine library, which contains logic to support the security-options deeplink for redirection to a hub-engine
- - #....
> Add: dependence hub-engine

- ios-whitelist.json
- Se actualizo la fecha de expire para SPPSpirtech
- - #....
> SPPSpirtech 2.0

- android-whitelist.json
Update search repo for the migration  Java 11 with gradle 7
- - #....
> update search for migration AGP

- android-whitelist.json
Desde arquitectura aumentaron el Major debido a la integración de AGP7.
[POINTMPOS-6713](https://mercadolibre.atlassian.net/browse/POINTMPOS-6713)
[POINTMPOS-6713]: https://mercadolibre.atlassian.net/browse/POINTMPOS-6713?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [POINTMPOS-6713] Mpos version update to 5.+

- android-whitelist.json
CCAP-SDK It is a new library that will allow to centralize the flow of tokenization and DAO of the ESC (Encrypted security code)
- #7563322
> [Feat]: CCAP-1253 Add CCAP-SDK library

- android-whitelist.json
Provide a solution similar to Secure Inputs Web but in the native mobile context.
> [Feat]: CCAP-1253 Add Secure Inputs library 

- ios-whitelist.json
Provide a solution similar to Secure Inputs Web but in the native mobile context.
> [Feature] CCAP-1368 iOS Add Secure Inputs library

- android-whitelist.json
> Bumped whitelisted tfs commons dependency

- android-whitelist.json
Starting [FBM WMS Mercury](https://github.com/mercadolibre/fury_fbm-wms-android) (FULL's App) modularization
1. Adding new group library fury yuca authentication android ([GitHub](https://github.com/mercadolibre/fury_yuca-authentication-android)) with module
- `:yuca`
- #7562904
> Add yuca new library

- android-whitelist.json
Add AppMonitoring and datadog SDK.
- - 7565359
> Add lib AppMonitoring and Datadog SDK

- ios-whitelist.json
Se agrega fecha de expiración de esta lib debido a que será reemplazada por Andes Feedback Screen.
- - #...
> add wallet congrats expiration date and description

- ios-whitelist.json
- Add the new Dogfooding iOS library. (Internal) 
> Add dogfooding lib

- android-whitelist.json
- ios-whitelist.json
> added expiration date to draftModal library

- android-whitelist.json
Se solicita el cambio debido a que hicimos un cambio en la librería de FCU por lo que debemos subir el major a 8.+
- - #....
> Actualizacion de versión para FCU 

- ios-whitelist.json
Librería privada para aplicaciones de MercadoLibre que sirve como wrapper del framework OMSDK. 
- #7566052
> [Added] - Viewability integration.

- android-whitelist.json
Se actualiza la librería de DAMI UI Components. La version 3 contiene la migración a AGP 7 y Java 11
- - #....
> Bump DAMI UI to v3

- android-whitelist.json
Add new Credits Flux version. 
Add expire date for last one version.
- - #....
> Credits Flux version

- android-whitelist.json
Update startup initializer application and splash 9+ | 10+
> Update Startup Initializer

- android-whitelist.json
Rename name and group from secureinputs lib
...
- - #....
> [TRIVIAL ] Rename lib secure inputs

- android-whitelist.json
Add analytic library to work with analytics in Melidata.
- - #7568161
> Add analytic library in whitelist.

- android-whitelist.json
Rename name and group from ccap-sdk lib
- - #....
> [TRIVIAL] Rename lib ccap sdk

- android-whitelist.json
Added mlwebkit version 4 and added expire to mlwebkit 4
```com.mercadolibre.android.mlwebkit:6.+``
7568046
> added mlwebkit 6.+ and added expire on mlwebkit 4.+

- android-whitelist.json
Se agrega la librería platform de Everest para poder ser utilizada.
[EVEREST-140](https://mercadolibre.atlassian.net/browse/EVEREST-140)
[EVEREST-140]: https://mercadolibre.atlassian.net/browse/EVEREST-140?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [EVEREST] Add Everest Platform library

- android-whitelist.json
Java fue actualizado a la version 11
#7568387
> flox version was updated to version 9

- ios-whitelist.json
Add Everest Bundles to the allow list
- [EVEREST-139](https://mercadolibre.atlassian.net/browse/EVEREST-139)
- #7568904
[EVEREST-139]: https://mercadolibre.atlassian.net/browse/EVEREST-139?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Add Everest bundles to the iOS allow list

- android-whitelist.json
Se agrega nuevo flavor para contemplar nueo dispositvo  en pos-sdk y su respectivo controlador en printer
...
- - #7569205
> [FEATURE] Add mp600 flavor to pos-sdk and mp600 controller to printer

- android-whitelist.json
It is a library which contains the implementation of LeakCanary.
- - #7568789
> [ADD] Performance Tools Library

- android-whitelist.json
Se realiza el update de libs android x AppCompat, Fragment, Activity & Lifecycle & Se agrega expire a cada libs q se realiza el update . 
Este update es parte de la migración que se esta llevando a cabo en platform update con el fin de ir sentando las bases para soportar jetpack compose.
- - #....
- [] Mercado Libre
- [] Mercado Pago
- [] SmartPOS
- [] Alicia: Flex / Logistics
- [] WMS
> Update libs android X

- android-whitelist.json
Se produce un cambio a la hora de usar nuestras librerías, a causa de un refactor.
- https://mercadolibre.atlassian.net/browse/PBLCDD-19416?atlOrigin=eyJpIjoiN2FlNDY4YTE0YWQ3NDc1ODlmYmJlZjg3OTdhOGYwZTUiLCJwIjoiaiJ9
> Bump Library Version ADN 3.+

- ios-whitelist.json
Se añade librería OMSDK.
- - #7569501
> [Added] - OMSDK.

- android-whitelist.json
Se actualiza la versión de notifications_helpers y se agrega el nuevo modulo. 
- - #....
> updated notifHelpers version

- android-whitelist.json
> Feature/behavioral 1.0.0

- android-whitelist.json
Se hace upgrade a la ultima version de bitmovin y una actualizacion de la libreria de Cast 
- - #....
> Update bitmovin version and cast version

- android-whitelist.json
Se agrega esta dependencia por necesidad transitiva de la ultima version de Bitmovin 3.33.0.
Build Scan: https://gradle.adminml.com/s/tco64pm5c2xf2
MDS MeliStore: Mercado Play Dev ->  version de 09/03/2023
- - #7570651
> Added parcelize-runtime library

- android-whitelist.json
Se actualiza libs de commons por la migración a android x
- - #....
> Update libs commons

- android-whitelist.json
Se modifica la fecha de expiración de la lib de attestation.
- - #7570669
> Fix change expire attestation

- ios-whitelist.json
Adding PxPmselector library
https://github.com/mercadolibre/fury_px-pm-selector-ios
- - #7570795
> Add PxPmselector library

- android-whitelist.json
Migración AGP 7.2.2 de Credit-Toolkit
- - #....
> Update version Credits-Toolkit

- android-whitelist.json
Bump ml_scanner lib to 8.+
- - #....
> bump ml_scanner to 8.+

- android-whitelist.json
Added the correct version for the ErrorHandlerV2 library.
> Feature/MASS-626 Added the correct version for the ErrorHandlerV2 library.

- android-whitelist.json
`Migration to AGP 7 in Credits UI Components`
- - #....
> Bump version credits ui components

- android-whitelist.json
Se agrega nueva libraria para manejo del skd del fabricante newland (ya en nexus). Adicionalmente se modifica el controllador mp600(proyecto cancelado) por el del dispostivo de newland n950
...
- - #7571502
> Newland library and changes to printer controller

- android-whitelist.json
En la lib navigation-menu actualizamos a AGP 7.2.2, es por eso que se generó una nueva versión -> 9.+
- - #7572262 
> Update navigation-menu library version 7.+ to 9.+

- android-whitelist.json
Se hace el update de las libs que necesitaban cambios para soportar la migracion de android x con su correspondiente expire.
- - #....
> Update expire and new version libs android x

- android-whitelist.json
Se actualiza la libreria de mpos version de 5 a 6 por nuevo cambio para remover cambios de payment flow legacy.
...
https://mercadolibre.atlassian.net/browse/POINTMPOS-6899
- - #....
> [POINTMPOS-6899] Upgrade Mpos Library Version

- android-whitelist.json
Reverts mercadolibre/mobile-dependencies_whitelist#1756. Se encuentra una mejor solución en reviews que evita generar modificaciones en la instanciación de ReviewsDelegate
> Revert "Updated reviews version"

- android-whitelist.json
> Add commons module

- android-whitelist.json
Se cambia el expiration date de la dependencia `com.mercadopago.android.congrats` para el 2 de mayo .. https://meli.workplace.com/groups/andesUI/permalink/5637093373085527/
- #7572868
> Updated congrats wallet expiration date

- ios-whitelist.json
Added Matt library.
- - #7572863
> Added matt-ios dependency

- android-whitelist.json
Actualizacion de version de helpers con los cambios de Android 13 :D 
...
- - #....
> updated notif helpers

- android-whitelist.json
- Se agrega la libreria de shadowapi de robolectric, misma version que ya tenemos 4.5.1
> Shadowapi robolectric

- android-whitelist.json
- ios-whitelist.json
Agregar la libreria Qualtrics
- Android #7572099
- iOS #7572128
> Add Qualtrics 2.9

- android-whitelist.json
> Update multi image version 8.0.1

- android-whitelist.json
Se requiere aumentar la version whitelisteada de la librería gamification por bump.
- #7572519
> Bump whitelisted gamification version

- android-whitelist.json
hacemos extension de la lib networking, para dar mas tiempo a que los equipos hagan una guia de migracion y planificacion de la migracion
...
- - #....
> Restore Networking lib

- android-whitelist.json
- Migration to AGP 7.2.2. and Java 11
- Se realizo el update del Bump Versión meliPluginGradleVersion=16.+- Se realizo el update del Bump Versión robolectric = "4.5.1"
`com.mercadolibre.android.cross_app_links:core`
- - #7573841
> Bump CrossAppLinks 7.0.0

- android-whitelist.json
Bump the scanner version to 9.+.
- - #....
> Bump the scanner version to 9.+

- android-whitelist.json
Actualizacion del library y adicion de la fecha de vencimiento de la version 6.0.0
- Use andes ui colors instead of ui and ui legacy color resources.
- Migration to AGP 7.2.2. and Java 11
- Se realizo el update del Bump Versión meliPluginGradleVersion=16.+
7573707
> Versão CPG-UI 7.0.0

- android-whitelist.json
Se actualiza Instore UI Components to 7.+
- - #....
> Instore UI Components version bump

- android-whitelist.json
Se actualizan la librería Login a la versión 17 con la migración a AGP
- - #7574250
> Bump Login 17

- ios-whitelist.json
Add XProdModules 0.+
- # 7573695
> [Feature] Add XProdModules 0.+

- android-whitelist.json
Bump version cardform 4.+ 
bug fix and migración a AGP
- - #....
> Bump version cardform 4.+

- android-whitelist.json
Se actualizan las librerías Authentication y Enrollment de Authentication a la versión 24 con la migración a AGP
- - #7574182
> Authentication 24

- android-whitelist.json
Update OpenTelemetry to version 5.0.0
- - #7574557
> Bump OpenTelemetry

- android-whitelist.json
Se genera una extensión para la fecha de deprecado de la lib de Globe
> [Feature] Globe lib deprecation extension

- android-whitelist.json
Se agrega el modulo de Feedback en cash-rails
- - #....
> add feedback module to whitelist

- android-whitelist.json
Se eliminó el uso de la lib `com.mercadolibre.android.reviews:reviews`, el cual fue reemplazada por `com.mercadolibre.android.reviews3:form`.
- - #....
> [Feature] Remove old reviews.

- android-whitelist.json
Se agrega libreria de **push-notifications:mqtt** para poder usarse en el los repositorios de **point-smartpos-fcu** y en **point-smartpos-android**
- - #....
> [SMART-2895] Add push-notifications:mqtt library to whitelist

- android-whitelist.json
Rename name ccap-sdk to smart-tokenization
- - #....
> [TRIVIAL] Rename lib ccap sdk to smart-tokenization

- ios-whitelist.json
Renaming CcapSdk library to SmartTokenization
- - #....CCAP-2526
> [CCAP-2526] Renaming CcapSdk library to SmartTokenization

- android-whitelist.json
Bump the MLKit barcode lib to the version 17.0.1.
- - #....
> Bump MLKit to 17.0.1

- android-whitelist.json
... Bump FCU version to 10 from 9
- - #....
> Bump FCU version to 10 from 9

- android-whitelist.json
Se corrige numero de versión de la lib mqtt, ya que se pueden ir creando versiones `0.1, 0.2, 0.3, etc.`
- - #....
> Fix mqtt number version

- android-whitelist.json
Update the MLKit OCR lib (17.0.1) to maintain the same version of MLKit Barcode.
- - #....
> bump: MLKit ocr to 17.0.1

- android-whitelist.json
...Bump posreaders version to 8 from 7
- - #....
> Bump posreaders version to 8 from 7

- android-whitelist.json
Extiendo la fecha de expiración de green robot, ya que aun lo seguimos usando
- - #....
> Updated Greenrobot expire date

- android-whitelist.json
Bump navigationcp Version
- - #....
> Bump navigationcp

- android-whitelist.json
Update andes integrations 2.+ for migration agp 7 and java 11
- - #....
> Andes integrations 2.+ (agp 7 and java 11)

- android-whitelist.json
`com.mercadolibre.android.navigation_manager`
- N/A
> Bump Navigation Manager 4.+

- android-whitelist.json
- Se agrega nueva libreria interna de acceso a mapa a travez de deeplink 
- Se incremaenta el major de marketplace-map por migraciones
> Nueva libreria external access map y aumento de major marketplace map

- android-whitelist.json
Adding new library fury wms crashlytics android for register of exceptions in WMS ([GitHub](https://github.com/mercadolibre/fury_fbm-wms-crashlytics-android)) with module
- `:core`
- - #....
> Add lib crashlytics

- android-whitelist.json
- "com.mercadolibre.android.smart_coupons:coupons:3.+"
- "com.mercadolibre.android.rule.engine:rule-engine:9.+"
- - #....
> Smart-coupons and Rule-engine new versions

- android-whitelist.json
Nueva expiración para Kotlin 1.5.32
- - #....
> New expire

- android-whitelist.json
Se actualiza la fecha de expiración de la librería, ya que actualmente nos encontramos en el piloto y hay que subir fixes
- - #....
> Update expires libs androidx navigation

- android-whitelist.json
Updated: **zebra** + **honeywell** scanner libraries to 2.+
Internal libraries
> [FEATURE] Update scanner libraries to 2.+

- android-whitelist.json
* Added "android:export" by @gussrivero in https://github.com/mercadolibre/fury_cpg-android/pull/162
* Versão 5.2.0 by @chrisluccas in https://github.com/mercadolibre/fury_cpg-android/pull/166
* [Trivial] Bump new Plugin of Gradle by @gussrivero in https://github.com/mercadolibre/fury_cpg-android/pull/163
* Criando a TAG 5.3.0 by @chrisluccas in https://github.com/mercadolibre/fury_cpg-android/pull/167
* Migration to API 32 (Android 12) by @gussrivero in https://github.com/mercadolibre/fury_cpg-android/pull/165
* Release v6.0.0 by @chrisluccas in https://github.com/mercadolibre/fury_cpg-android/pull/168
* Versão 7.0.0 by @chrisluccas in https://github.com/mercadolibre/fury_cpg-android/pull/172
* Trocando url base para chamada a api de header by @chrisluccas in …
> Nueva version CPG-Android 8.0.0

- android-whitelist.json
El equipo the playMobile necesita de más tiempo para actualizar ésta librería, adicional, en el repositorio de FCU está fallando el CI por ésta librería expirada que es traída transitoriamente por la librería de lottie, con ese tiempo adicional se da la posibilidad de revisar que cambios son necesarios en el repositorio.
- - #....
> Updating viewBinding 4.+ expiration date to May 29th-2023

- android-whitelist.json
Bump de la libreria Credits Flox Client v3.+
> Credits Flox Client bump version v3.+

- android-whitelist.json
Migrations of In App Updates
- - #....
> In App Updates

- android-whitelist.json
Se requiere habilitar las nueva version major 4.+ para point-ui
- - #[POINTMPOS-7744](https://mercadolibre.atlassian.net/browse/POINTMPOS-7744)
[POINTMPOS-7744]: https://mercadolibre.atlassian.net/browse/POINTMPOS-7744?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [POINTMPOS-7744]add Point-Ui library version 4.+

- android-whitelist.json
Se agrega libreria de exoplayer como iniciativa para implementar video player nativo android en mercado libre.
- - #....
- [ x] Meli Store
> update library exoplayer

- android-whitelist.json
`com.mercadolibre.android.credits.behaviour`
- Use andes ui colors instead of ui and ui legacy color resources.
- Migrated to the new libraries organization implementing a version catalog (gradle/libs.toml file).
- Migration to AGP 7.2.2. and Java 11
- Migration to the new Plugin of Gradle --> 16.+.
- Migration to Android 13
> Bump Credits Behaviour 5.0.0

- android-whitelist.json
Adding WMS Flan library 2.+ to allowlist.
- WMS Internal Library
> [FEATURE] Added wms flan library 2.+

- android-whitelist.json
Updating wms oem device library 2.+    
WMS Internal Library
> [FEATURE] OEM library bump version

- android-whitelist.json
Se aumenta la versión de la lib de ADN por breaking change de 3.+ a 4.+
- - #....
> Bump ADN V4.+

- android-whitelist.json
PR para hacer bump a Melidata a 17.+
- - #....
> Feature/Bump Melidata version 17.0.0

- android-whitelist.json
Add new library datamiSDK, responsable for navigation without costs.    
- #7579553
> SPMR-244 - add datami in allowlist

- android-whitelist.json
Se actualiza la versión de cash-rails
- - #....
> bump cash-rails dependency

- android-whitelist.json
Wrapper library hecha para que no se llame directamente datamiSDK
Nota: Mirar el ticket #7579553
https://web.furycloud.io/help/tickets/84269
- - #7580933
> add free navigation library

- android-whitelist.json
Se agrega el nuevo modulo de Report en el repo de Cash-rails
> Add cash-rails report library

- android-whitelist.json
Se extiende la fecha de expiración de la lib globe por tres meses más
- - #....
> [Feature] update expiration date globe lib

- android-whitelist.json
> Update expires event bus

- android-whitelist.json
Se agrega un nuevo módulo al proyecto de search
- - #....
> Add More Like This module

- ios-whitelist.json
Se agrega un nuevo módulo llamado MLAutosuggest al proyecto de search-ios
- - #....
> Add autosuggest ios module

- ios-whitelist.json
Se agrega un nuevo módulo llamado More Like This al proyecto de search-ios
- - #....
> Add more like this ios module

- ios-whitelist.json
> Adding SDKmi and wrapper in ios whitelist

- android-whitelist.json
Actualmente en Instore Payment Smartpos tenemos en desarrollo e integracion un nuevo dispositivo el N950. Todo este desarrollo provoca un breaking change en las librerias de pos-sdk y printer. Debido a esto requerimos la actualización de su mayor. Se deja el expire en al 31/10/23 por estimar un Q para culminar el desarrollo.
- - # 7581852
> Update library version of pos-sdk and printer

- ios-whitelist.json
Update **MLPurchases/Integration** lib from `2.X.X` to `3.X.X`
- - #....
> Update MLPurchases/Integration version to 3.X.X

- android-whitelist.json
Bump recommendation_combo to 3.+
- - #....
> bump recos lib to 3.+

- android-whitelist.json
> Update expire date firebase ads

- android-whitelist.json
Agregar librerías Android de Instore Payments - Selling Framework.
- - #7582878
> [PSF-211] Add Selling Framework libraries

- android-whitelist.json
Uptade Gson and Grpc Versions
- - #7582872
> Update Gson and Grpc versions

- android-whitelist.json
Due to Recharge library's Kotlin migration to 1.8.10, it's necessary to update the version major number because even thought it won't cause a breaking change on our app (since smartpos is already migrated), it can cause a crash if this library were used in previous releases of the app.
- - #....
> Update version: point-ui 4.+ -> 5.+

- android-whitelist.json
New module from [Selling Framework Android](https://github.com/mercadolibre/fury_isp-sf-lib-android)
> Add print_buyer_ticket module from selling framework

- android-whitelist.json
Adding the ptm-toolkit libraries in fcu core.
- [SMART-3546](https://mercadolibre.atlassian.net/browse/SMART-3546)
[SMART-3546]: https://mercadolibre.atlassian.net/browse/SMART-3546?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [SMART-3546] Added ptm toolkit in allow list

- ios-whitelist.json
> Actualiza version major disponible de MLCheckoutSDK y MLCheckout v6

- android-whitelist.json
`com.mercadolibre.android.usersections:ui-sections:mercadolibre-5.5.0`
- Internal library
> Nav section - Add Flavor ML

- android-whitelist.json
Se necesita subir de version congrats, integrator_sdk, shipping a la 7.+ 
- - #....
> Update version checkout congrats, integrator_sdk, shipping ->  7.+

- .idea/modules.xml
- android-whitelist.json
Se agrega el parámetro +jason para poder diferenciar la implementación de dependencias transitivas de la librería de bitmovin de las librerías de exoplayer
- - #7583589
- [ x] Meli Store
> added +jason for new library implementation

- android-whitelist.json
Se agrega un fix para validar el correcto comportamiento del CI
- - #7583589
- [ x] Meli Store
> fix path in upgrade lib Bitmovin

- android-whitelist.json
> Rollback bitmovin version. Removing +jason

- android-whitelist.json
Se cambia la versión de play integrity.
- - #82430
> Change version play integrity

- android-whitelist.json
Nueva version de la lib de flox components a 9.+
> Update version checkout flox components -> 9.+

- android-whitelist.json
Se necesita subir de version marketplace-map lib a la 13.+
- - #....
> Update version checkout marketplace-map -> 13.+ 

- android-whitelist.json
Tenemos un breaking change que mejora la medicion para recyclerviews y apoya una mejor medicion de visualizacion humana para vistas no recyclerview. 
Tambien se agregaron enventos para medicion de video.
Se agrega nueva version  de viewability y se da fecha de expiracion a la version antigua
- - #....
> add viewability v2 and expires date to v1

- android-whitelist.json
Se fixea la fecha de expiracion de la version 6.+ de las libs de checkout sdk
> Fix en la fecha de expire en las libs de checkout sdk

- ios-whitelist.json
Se agrega un nuevo módulo llamado [MLEShops](https://github.com/mercadolibre/fury_eshops-ios)
- - #....
> Add MLEShops IOS

- ios-whitelist.json
> Se agregan nuevas versiones de MLCheckout y BfSplitPayment

- ios-whitelist.json
Agregar nueva librería para redireccionar al flujo de OAuth en la app de MP y no abra el browser primero
[PSFO-2029](https://mercadolibre.atlassian.net/browse/PSFO-2029)
[PSFO-2029]: https://mercadolibre.atlassian.net/browse/PSFO-2029?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Add new lib to iOS MP app for redirect oauth flow

- ios-whitelist.json
Bump version of SecureInputs on iOS
- - #....
> [iOS] bump SecureInputs lib

- android-whitelist.json
se agrega un nuevo modulo [autosuggest](https://github.com/mercadolibre/fury_search-android/tree/master/autosuggest) android 
- - #....
> Add AutoSuggest android

- android-whitelist.json
Se necesita subir de version native-reauth-android lib a la 5.+
- - #....
> Nueva version de native reauth

- android-whitelist.json
Bump Tensorflow-Lite from 2.6.0 to 2.12.0 (Latests)
[Ticket](https://web.furycloud.io/help/tickets/87447)
> Add tensorflow 2.12.0

- android-whitelist.json
Se agrega version 1.0.0 de la lib mqtt
- - #....
> Add MQTT version 1.0.0

- android-whitelist.json
Extendemos el deadline de DraftModal debido a un bug visual encontrado en la variante de carousel en MP. Más información en: https://meli.slack.com/archives/CSKCPM30R/p1688151242098479
> DraftModal Deadline extension

- ios-whitelist.json
Add XProdFloxComponents
- - #....
> [Feature] Add XProdFloxComponents 0.+

- android-whitelist.json
Se agregan nuevas versiones para las libs de checkout
> Nuevas versiones de libs de Checkout

- android-whitelist.json
Aumentamos la versión de la biblioteca Traceability.
- - #....
> Update Traceability Android Lib 

- android-whitelist.json
- ios-whitelist.json
Add new components, screens and behaviours for Home Seller in MP 
- - #7585004
> Add HubSeller lib

- ios-whitelist.json
> Fix shorts target and delete description

- ios-whitelist.json
Changes:
- We needed to update Datami to final version 4.1.3
- We needed to update FreeNavigation, from now its going to production, so its not 0.x.x anymore, we are bumping to 1.x.x
- - #....
> Bumping versions of Datami and FreeNavigation

- android-whitelist.json
- (ML) Esta en la versión 4.
- (ML) Se realizaron una serie de cambios donde las librerías que usan ADN (Home y Search) deben hacer ciertos cambios para poder utilizar la nueva versión 5.
- (MP) Esta en proceso de migrar de la 3 -> 5 (por eso dejo el expirado de la versión 3).
> Nueva version de ADN 5 

- android-whitelist.json
Se actualiza la versión de CashIn, CashOut y Cash-Rails
> Update Cash versions

- android-whitelist.json
Se agrega dependencia components 0.+
> Added version 0.+ of xprod-components library

- android-whitelist.json
Adding new Selling Framework Modules
[PSF-409](https://mercadolibre.atlassian.net/browse/PSF-409)
- - #....
[PSF-409]: https://mercadolibre.atlassian.net/browse/PSF-409?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [PSF-409] Add new selling framework modules

- ios-whitelist.json
...
- https://web.furycloud.io/help/tickets/89330?page=1&teams=false
> add variation for fixes in the  bitmovin dependency

- ios-whitelist.json
Se habilita el uso de versiones mayores a 1.x.x de librería [Viewability](https://github.com/mercadolibre/fury_viewability-ios).
- #7586647
> [Advertising] - Viewability ~> 1.x.x

- ios-whitelist.json
Add library which will be used on mPOS to allow list
- - #....
> feature:: Add IspSf library to whitelist

- android-whitelist.json
Update Braze SDK to -> 26.1.0.
- - #7585386
> Update Braze SDK to -> 26.1.0.

- android-whitelist.json
Se actualiza versión de la librería Clips, se detalla fecha de expiración de versión anterior.
La versión 2.+ quedó desestimada, por eso se pasa a 3.+
- - #....
> Update clips lib version

- android-whitelist.json
Se cambia el expire de kotlin & room debido a que se extendio la migración.
- - #....
> Update expire version kotlin & room

- android-whitelist.json
actualizar la lib de exoplayer para trailer home mplay para que mantenga la consistencia con la versión bitmovin , a fin que no bloqueemos chromecast
- #7587562
> Update exoplayer version

- android-whitelist.json
Se hace upgrade de la lib de bitmovin a la 3.40.0
- - #....
- [x ] Meli Store
> upgrade bitmovin lib 3.40.0

- android-whitelist.json
- ios-whitelist.json
- Se actualizan los majors de las librerías de MPContacts y Realm
- Se agregan las expiration dates para las versiones anteriores
[DATRAN-3826](https://mercadolibre.atlassian.net/browse/DATRAN-3826)
[DATRAN-3826]: https://mercadolibre.atlassian.net/browse/DATRAN-3826?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Update MPContacts version to 5.0.0 and Realm version to 10.38.0

- android-whitelist.json
Add library to allow list:
* Payments 0.1.0
* Core Flox 0.3.0
- - #....
> Feat - Add payments and core-flox libs to whitelist

- ios-whitelist.json
Se agrega como nueva dependencia la lib BuyingflowCoreFlox.
- - #....
> Added core-flox lib to whitelist

- android-whitelist.json
Modificar inicio de versionamiento de librería YUCA
- - [PSFO-2555](https://mercadolibre.atlassian.net/browse/PSFO-2555): Cambiar versionamiento del lib de YUCA
[PSFO-2555]: https://mercadolibre.atlassian.net/browse/PSFO-2555?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Change version YUCA lib

- ios-whitelist.json
Se agrega la dependencia BuyingflowPayments para checkout
- - #....
> Added new BuyingflowPayments dependency to whitelist

- android-whitelist.json
Se suma el nuevo repo [fury_request-watcher-android](https://github.com/mercadolibre/fury_request-watcher-android)
- - #....
> Added Request Watcher Library

- .idea/.gitignore
- android-whitelist.json
se agrega la version 15 de recommendations y se pone fecha de expiracion a la version 14
- - #....
> recommendations bump

- android-whitelist.json
Se actualiza el major de riskmanagement
- - #....
> Se actualiza el major de riskmanagement

- ios-whitelist.json
- Add pod 'PortableWidget' in whitelist (https://github.com/mercadolibre/fury_portable-widget-ios)
- - #....
> [ADDED] - Add portable widget in whitelist

- android-whitelist.json
- Adding `setup` module 4.x.+
- Adding `device` module 4.x.+
- Removing `device` version 2.x.+ and switching to 3.x.+
- WMS Internal Library (it doesn't affects other apps)
> [FEATURE] OEM Setup and Device updates.

- android-whitelist.json
Common place for dependencies, helpers and more useful tools used by the CCAP team.
- - #....
> feat: add ccap-commons's dependence

- android-whitelist.json
Actualización de la librería Pos Readers version de 8 a 9
> Update PosReaders library version 9.+

- android-whitelist.json
Actualización de la librería mPOS Readers version de 10 a 11
> Update mPOS library version 11.+

- android-whitelist.json
Bump AppMonitoring to version 1.+
- - #7589443
> Bump app_monitoring

- ios-whitelist.json
Se actualiza la nueva version de la librería Risk Management
- - #....
> Update Risk Management version

- android-whitelist.json
Se agregan las nuevas versiones de checkout y checkout sdk
> Checkout y checkout sdk, nuevas versiones

- ios-whitelist.json
Common place for dependencies, helpers and more useful tools used by the CCAP team.
- - #....
> Add CcapCommons

- android-whitelist.json
Se actualizaron las dependencias de carrito, por la migración de la version de kotlin
- - #....
> Dependencies cart upgrade - Version kotlin

- android-whitelist.json
Update Braze SDK to -> 26.1.1.
- - #7590085
> Update Braze SDK to -> 26.1.1.

- android-whitelist.json
Se hace upgrade a la version mas actualizada de Ads Interactivemedia para estar alineado a las dependencias de la libreria de BItmovin
- - #https://web.furycloud.io/help/tickets/93660
- [x ] Meli Store
> update version interactivemedia Ads library

- ios-whitelist.json
Added Mobile Permissions library
> Added Mobile Permissions library

- ios-whitelist.json
Updated  MobilePermissions  regex.
> Update MobilePermissions Regex

- ios-whitelist.json
Changed the target to production
> Changed the target to production

- ios-whitelist.json
Se actualizó la versión de MLEShops que contiene el soporte para followers
- - #....
> Update MLEShops whiteList

- android-whitelist.json
Added new selling data module from selling framework to white list
- - #....
> [ISPFSF] Added selling data library

- android-whitelist.json
Se actualiza la versión de CashIn, CashOut y Cash-Rails
- [ ✅ ] Mercado Pago
- [ ✅ ] SmartPOS
> Update Cash Version

- android-whitelist.json
Se actualizaron las versiones de:
* core-flox v1.0
- - #....
> Bump Core Flox

- android-whitelist.json
Con la[ iniciativa de payments 2.0 de checkout](https://www.figma.com/file/zwwWuSUoR6wNE4tcqICicc/Split-proactivo?type=design&node-id=2907-398181&mode=design&t=98KpIUwz1800vcuD-0) se crea el flujo nuevo de pantallas con bricks atómicos de la [lib de core-flox](https://github.com/melisource/fury_buyingflow-core-flox-android). 
Se lanza la primera versión productiva de payments 1.0 y se deja de usar las versiones 0.+ que eran para pruebas de integración de forma local. 
- - #....
> Bump Payment

- android-whitelist.json
- Se agrega la nueva lib para el guardado de sesiones scopeadas.
- - #....
> Se agrega la Nueva librería Scoped Session Android

- android-whitelist.json
> Bump major oem

- android-whitelist.json
> extension library version 6

- android-whitelist.json
> Add lib wishlists Android

- ios-whitelist.json
Adding SmartTokenization version 2
- - #....
> Adding SmartTokenization v2

- android-whitelist.json
[Migracion de OkHttp 4](https://meli.workplace.com/groups/meliandroiddevs/permalink/6371788846192610/)
- - #....
> Bump Restclient and OkHttp

- android-whitelist.json
Bump smart tokenization to 2.+ and expires v1 
- - #....
> [Feat]: Bump smart tokenization v2 and expires v1

- android-whitelist.json
Se agrega una nueva lib de scanner de codigo de barras para el flujo de pago de servicios desde una webview en Smart
- - #....
> Add meliscanbarcodeui lib

- android-whitelist.json
Se actualizan las versiones de Payments Checkout a v2.0.
> Update Version Payment Checkout

- android-whitelist.json
Se subió el mayor de la versión de libs de `reviews` y `shorts`, por migración de kotlin 1.8.
> [Feature] Upgrade version to reviews lib and shorts lib.

- android-whitelist.json
Add `exoplayer-common` dependency.
7593123
> Add exoplayer common dependency

- android-whitelist.json
Upgrade version securityTwoFa from 7+ to 8+
- - #....
> [SAFE] BUMP securityTwoFa to version 8+

- android-whitelist.json
> Bump Login 18.0.0

- android-whitelist.json
Upgrade Lib Push Provisioning
- - #....
> upgrade lib version

- android-whitelist.json
Revert [PR](https://github.com/mercadolibre/mobile-dependencies_whitelist/pull/1949) and [PR](https://github.com/mercadolibre/mobile-dependencies_whitelist/pull/2050)
- - #....
> Revert Restclient OkHttp and Everest

- android-whitelist.json
> Adding cpg version

- android-whitelist.json
Se agrega SDK de Visa Sensory Branding.
Que nos da este SDK? Simplemente acceso a una custom view creada por el equipo de Visa para mostrar el logo bajo sus estandares definidos de forma simple.
Lo necesitamos para poder cumplir con la norma de Visa en cuanto al uso de la marca
- - #7593900
> add visa sensory branding

- android-whitelist.json
> Update everest version

- android-whitelist.json
> Bump Variations versions 

- android-whitelist.json
The fbm-wms-app-monitoring library is added.
- WMS Internal Library (it doesn't affects other apps)
> Added app monitoring

- ios-whitelist.json
> Update buyingflow payment version

- android-whitelist.json
Bump AppMonitoring version 2 
- - #....
> Bump AppMonitoring version 2

- android-whitelist.json
- merchrealestates version: 5.0.0
- mprealestates version: 5.0.0
- dismisscontent version: 5.0.0
- - #....
> Bumps major Rael Estates Everywhere repositories

- android-whitelist.json
onboarding version: 3.0.0
pendingsview version: 4.0.0
pendingscontainer version: 4.0.0
- [MPFM-602](https://mercadolibre.atlassian.net/browse/MPFM-602)
- [MPFM-604](https://mercadolibre.atlassian.net/browse/MPFM-604)
[MPFM-602]: https://mercadolibre.atlassian.net/browse/MPFM-602?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[MPFM-604]: https://mercadolibre.atlassian.net/browse/MPFM-604?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Bumping Onboarding and Pendings - Kotlin 1.8

- android-whitelist.json
Updated Insurance QPageOn version to 10 and created expiration date for version 9, migration Kotlin `1.8.10`.
- - #....
> [Insurance] QPageOn

- android-whitelist.json
Se subió el mayor de la versión de libs de `qadb`, por migración de kotlin 1.8.
> [Feature] Upgrade version to qadb lib.

- android-whitelist.json
Deprecado de versiones debido a la migración de Kotlin.
- [Ticket en JIRA](https://mercadolibre.atlassian.net/browse/SXCOSTOSSL-97)
> update fees version

- ios-whitelist.json
Se incorpora la librería AuthScopedSession a la whitelist
- - #....
> Add ScopedSession lib

- android-whitelist.json
Deprecado de versiones debido a la migración de Kotlin.
- - #....
> Update version due to kotlin migration

- android-whitelist.json
Se actualiza la librería de DAMI UI Components. La version 4 contiene la migración a Kotlin 1.8 y el deprecado de Meli UI
- - #....
> Bump DAMI UI to v4

- android-whitelist.json
Update Firebase-Perf and Traceability Expires Date
- - #....
> Update Firebase-Perf and Traceability Expires Date

- android-whitelist.json
Se esta trabajando en mejoras para el nuevo dispositivo N950 y se actualiza el Major debido que provoca un breaking change en la libreria de helpers. Se deja el expire en al 31/12/23 por para versiones recientes.
- - #....
> Update point helpers

- android-whitelist.json
usersections:sections -> 6.0.0
usersections:ui-sections -> 6.0.0
- [MPFM-607](https://mercadolibre.atlassian.net/browse/MPFM-607)
[MPFM-607]: https://mercadolibre.atlassian.net/browse/MPFM-607?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Bumping usersections due to kotlin migration

- android-whitelist.json
merchengine -> 8.0.0
- Ticket ID
[MPFM-606](https://mercadolibre.atlassian.net/browse/MPFM-606)
[MPFM-606]: https://mercadolibre.atlassian.net/browse/MPFM-606?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Bumping merchengine - Kotlin 1.8

- android-whitelist.json
> bump seller-home-sections dashboards tfs-commons collaboratorsui kotlin 1.8 migration

- android-whitelist.json
com.mercadolibre.android.credits.behaviour 6.0.0
- Migration kotlin 1.8.10 and update libs room 2.4.3.
https://mercadolibre.atlassian.net/browse/CFEC-354
> Bump Credits Behaviour 6.0.0

- android-whitelist.json
We have a new module to handle with an inhouse implementation from contactless payment read.
- - #....
> [mPOC] Add sdk contactless dependency to whitelist

- android-whitelist.json
From mPOC team we decided to update the group id to align with expected responsability of mPOC services in this scenario we just change the group id.
- - #....
> [mPOC] Update dependency library group id.

- android-whitelist.json
**Bump version - Kotlin 1.8.10**
* Smart tokenization v3
* Congrats sdk v2
* Esc Manager v7
- - #....
> [Feat]: bump smart tokenization v3, congrats-sdk v2 and esc manager v7

- android-whitelist.json
Se agrega MLHome a pedido del equipo de Webkit
TL: Dario Chamorro
- - #....
> Home added

- ios-whitelist.json
Se agrega MLHome a pedido del equipo de Webkit 
TL: Dario Chamorro
- - #....
> MLHome added

- android-whitelist.json
Migración Kotlin 1.8 de Credit-Toolkit-Android
- - #....
> bump libs credit-toolkit

- android-whitelist.json
I cannot now update this dependency because for us it is a break change and we are working an fix.
- - #....
> Postpone expire date to errorhandler v2 core

- android-whitelist.json
Melicharts es una lib que quedo desactualizada con migraciones como agp 7 o Android 13, actualmente es utilizada en más de un repo.
- - #....
> bumped melicharts

- android-whitelist.json
Agregamos esta dependencia por un error en CI de este [PR](https://mercadolibre.atlassian.net/jira/software/c/projects/PMGR/boards/8240?modal=detail&selectedIssue=PMGR-1144&assignee=6283577eba5c2500682cd084#:~:text=Esta%20pendiente%20este-,PR,-Actividad) correspondiente a ML-Scanner-android. 
Cabe aclarar que dicha version [ya se encontraba](https://github.com/mercadolibre/mobile-dependencies_whitelist/pull/1799/files) implementada, pero se ve que no habia fallado anteriormente. 
- - #....
> Barcode mlkit dependency added

- android-whitelist.json
Added new available ptm-toolkit version to `1.+`
- - #....
> Add new ptm-toolkit version

- android-whitelist.json
> Update hub seller due to kotlin 1.8.10 migration

- android-whitelist.json
-  Bump Integration V3
-  Expiration for integration V2
- - #
> Integration Form V3.0.0

- android-whitelist.json
- Bump Card Form V5
- Expiration date for V4
- [CCAP-3763](https://mercadolibre.atlassian.net/browse/CCAP-3763)
[CCAP-3763]: https://mercadolibre.atlassian.net/browse/CCAP-3763?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Card Form V5.0.0

- ios-whitelist.json
Add Wishlists ios lib
- - #....
> Add wishlists ios lib

- ios-whitelist.json
En braze se esta utilizando esta lib de Meli para poder gestionar los thumbnails en la push del provedor Braze con el proyecto fury-braze-ios. 
**Como esta construido nuestro Braze.podspec?** En este [link](https://github.com/melisource/fury_braze-ios/blob/3b9db3306199f76617a308bceab677dc6522395c/Braze.podspec) se puede observar. 
Este desarollo se hizo en colaboracion del equipo de Notifications de mobile liderado por Marcos Crispino.
**Porque este pr? :** tenemos un error en el Pipeline de este tipo: [Link Pipeline](https://rp-ci-ios.furycloud.io/blue/organizations/jenkins/braze-ios/detail/braze-ios/52/pipeline/126/)
```
Running dependencies lint...
Verifying dependencies in Braze
OK
Verifying dependencies in Braze/Core
Error: Found dependencies not allowed:
- MLRichNotifications (~> …
```
> Update ios-whitelist.json MLRichNotifications

- ios-whitelist.json
-     Add AppMonitornigSetup
[AppMonitornigSetup](https://github.com/melisource/fury_app-monitoring-setup-ios)
The setup layer of app-monitoring-ios was removed and a new wrapper library (app-monitoring-setup-ios) was created to deal with the static dependencies and to configure app-monitoring-ios in ML and MP.
- Internal Library
> Add AppMonitoringSetup 0.X

- android-whitelist.json
New major version 4.0.0 for Credits FloxClient with the Kotlin 1.8 update
> Floxclient core new version 4

- ios-whitelist.json
Bump version of CardForm on iOS
- - #....
> update cardForm to v6

- android-whitelist.json
- Updated daisy android
- - #....
> Updated daisy android

- android-whitelist.json
Se aumenta la version de RMF a 5.+
Se depreco la version de RMF 4.+
- - #....
> Updated rmf version

- android-whitelist.json
- ios-whitelist.json
Se habilito la version  4.0 de Everest que incluye el update de Kotlin 1.8.
- - #....
> Everest libs 4 added.

- android-whitelist.json
Updated Insurance FloxComponent version to 9 and created expiration date for version 8, migration Kotlin `1.8.10`.
- - #....
> Update version InsuFloxComponent

- android-whitelist.json
Bump version - Kotlin 1.8.10
- Smart tokenization v2
- - #....
> [Feat]: bump SecureInputs v2

- android-whitelist.json
Se agrega la libreria mobile permissions a la whitelist
- - #....
> Add mobile permissions

- android-whitelist.json
Se expira la versión 6.+ y se agrega la 8.+    
- - #....
> Nueva versión de Flux Client

- android-whitelist.json
Adding library remote config in whitelist
- [SMART-4801](https://mercadolibre.atlassian.net/browse/SMART-4801)
[SMART-4801]: https://mercadolibre.atlassian.net/browse/SMART-4801?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Add remote config in white list

- android-whitelist.json
Fix name of module from repository remote-config
- [SMART-4801](https://mercadolibre.atlassian.net/browse/SMART-4801)
[SMART-4801]: https://mercadolibre.atlassian.net/browse/SMART-4801?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [SMART-4801-1] Fix name of module

- android-whitelist.json
Agregar librería Android de Instore Payments - Integration SDK.
[fury_isp-integration-sdk-android](https://github.com/melisource/fury_isp-integration-sdk-android)
- - #....
> [SMARTI-987] Add the nativesdk library to the whitelist.

- android-whitelist.json
Bump printer lib to 5.0.0
- [SMART-4822](https://mercadolibre.atlassian.net/browse/SMART-4822)
[SMART-4822]: https://mercadolibre.atlassian.net/browse/SMART-4822?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> BUMP point-printer

- ios-whitelist.json
Se actualiza la librería Charts a la versión 5.0.0 en que su nombre ha cambiado para evitar conflictos con la librería Charts de Swift.
7597298
> Update Charts dependency in ios-whitelist.json

- android-whitelist.json
Added new library: Pm Selector at whitelist
Added new library at allowlist: Pm Selector.
- - #7599130
> Added  Pm Selector Android library

- android-whitelist.json
Se agrega la version 11.0 de la lib de bf-flox-components.
> Nueva version - bf-flox-components

- android-whitelist.json
> datadog gradle plugin mappers

- android-whitelist.json
Restauramos OkHttp 4 en whitelist
[EVEREST-1718](https://mercadolibre.atlassian.net/browse/EVEREST-1718)
[EVEREST-1718]: https://mercadolibre.atlassian.net/browse/EVEREST-1718?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Bump Restclient and OkHttp4

- ios-whitelist.json
Se incorpora la librería SplashScreen a la whitelist.
- - #....
> Add splashscreen to whitelist

- android-whitelist.json
Add the CameraX [preview](https://developer.android.com/reference/androidx/camera/view/package-summary) to use this lib in Scanner project.
- - #....
Para más información visitar [ticket.](https://web.furycloud.io/help/tickets/95688?page=1&teams=false)
> Adding CameraX preview

- android-whitelist.json
- Breaking Change por Migración de Kotlin 1.8
> New Version ADN V6

- android-whitelist.json
Se expira la versión 2.+ y se agrega la 3.+
- - #....
> Bump ehops 3.+ 

- android-whitelist.json
- Breaking Change por Migración de Kotlin 1.8
> Add new version Viewability 4.0.0

- android-whitelist.json
Se incorpora la librería Portable Widget a la whitelist.
- - #....
> [ADDED] Portable Widget to whitelist

- android-whitelist.json
- Adding CardForm v6
- Expiration date for CardForm v5
- https://mercadolibre.atlassian.net/browse/CCAP-4275
> [CCAP-4275] Adding Card Form V6

- android-whitelist.json
> Bump proximity libs due to Kotlin migration

- android-whitelist.json
Update Credits Components UI to new major v6
> Update Credits Components UI to v6

- android-whitelist.json
- ios-whitelist.json
Adjust Android & iOS names
- - #....
> Adjust Android & iOS names

- android-whitelist.json
Se actualizan las version del SDK de Checkout a la 10.+
- - #....
> Update Checkout SDK version

- android-whitelist.json
Adds a performance-traces-android lib created by the performance team that centralizes communication with the providers that manipulate traces.
- - #....
> Added performance traces android to whitelist

- android-whitelist.json
Version con kotlin 1.8 / okhttp 4 
- - #....
> Bump MELI open-telemetry version

- ios-whitelist.json
Nueva version de MobilePermissions
- - [Everest-1667](https://mercadolibre.atlassian.net/jira/software/c/projects/EVEREST/boards/7795?assignee=62fcfcbcb582d07a14a86a08&selectedIssue=EVEREST-1667)
> Update MobilePermissions version

- android-whitelist.json
> [SmartIntegrations] Add alarm-pingsender courier dependencies for push-notifications lib

- ios-whitelist.json
Se agrega referencia a una nueva lib desarrollada por el equipo de Device (device@mercadolibre.com), análoga a behavioral-sdk-android.
Se encuentra más info en https://github.com/melisource/fury_behavioral-sdk-ios/pull/1.
- - #....
> [iOS] Adds new lib BehavioralSdk

- ios-whitelist.json
Se agrega una nueva lib para el manejo de la fecha de vencimiento de tarjeta de credito, CreditCardDuedate.
Repo link: https://github.com/melisource/fury_credit-card-duedate-ios?
- - #....
> [iOS] Added new lib CreditCardDuedate
