android-whitelist.json

Bump ml_scanner to version 13.+
- - #....

bump: the new version of ml_scanner

---

android-whitelist.json

Se expira la versión 5.+ y se agrega la 6.+
- - #....

Bump charts 6.+ 

---

android-whitelist.json

Se agrega la nueva versión de Reauth con kotlin 1.8
- - #....

Reauth version con kotlin 1.8

---

ios-whitelist.json

Se agrega una nueva lib para agregar una nueva feature de DeveloperMode, RequestWatcher.
Repo link: https://github.com/melisource/fury_request-watcher-ios
- - #....

[iOS] Add new lib RequestWatcher

---

android-whitelist.json

Migracion a Kotlin 1.8
- - #....

Security Preferences 9 - Kotlin migration

---

android-whitelist.json

Se extiende la fecha expiración de uiComponents version 16 en android.
- - #....

Se extiende la fecha de uiComponents version 16

---

android-whitelist.json
ios-whitelist.json

Update the expires date of CardForm v5 on iOS & Android
- - #....

cardForm - Updating v5 cardForm expires date

---

android-whitelist.json
ios-whitelist.json

Se agrega la lib AmountScreen
- - #....

Add AmountScreen lib

---

android-whitelist.json

Migracion a Kotlin 1.8
- - #....

User Biometrics v8 - Kotlin migration

---

ios-whitelist.json

[iOS] Bump IspSf to 2.0

---

android-whitelist.json

- Extendemos el inminente vencimiento de esta dependencia, ya que su eliminación esta programada para Q1. Incluso, he validado con quienes llevaran este track, y estimaron seria para fin de Q. 
- - #....

Zxing expire date change

---

android-whitelist.json

Actualización de la version de in app updates
- - #....

Update in app updates version

---

android-whitelist.json

Se bumpean las dependencias:
- MLKit (unbundled) 
- - #....

Unbundled MLKit Barcode dependencie bumped

---

android-whitelist.json

Library has break change and it is needed to increase version
- https://mercadolibre.atlassian.net/browse/SMART-5082

Include version 7 of POS-SDK.

---

android-whitelist.json

Soporte para nuevas versiones Cashin y Cashout
- - #....

Bump CashRails

---

android-whitelist.json

Se actualizan las librerías de Selling Framework.
Se agrega fecha de expiración a librerías que no deben ser consumidas, solo se debe utilizar el módulo **facade**, por este motivo, solo se actualiza este módulo y expirarán los demás.
Internal library. No ticket.

Update Selling Framework libraries

---

android-whitelist.json

Fix group declaration to px.pmselector lib
- NO TICKET

Fix pmselector group

---

ios-whitelist.json

We need to add to add our new feature to the withe list in order to use it on ML and MP
- - #....

Adding SafeGuard iOS

---

android-whitelist.json
ios-whitelist.json

updating cardForm v6 expires date
- - #....

updating cardForm v6 expires date

---

ios-whitelist.json

Actualización para la lib de NavigationRouter para que haga uso de versiones 2.x 
- [-] SmartPOS
- [-] Alicia: Flex / Logistics
- [-] WMS
- [-] Meli Store

Navigation Router support for 2.x versions

---

android-whitelist.json

Se vuelve agregar version de libs de credits, debido a que es usada en los config providers, y olvidaron actualizarla y termino removiendose.
- - #....

Update credit version

---

ios-whitelist.json

Se actualiza las libs BfSplitPayment, MLCheckoutSDK, BuyingflowPayment, por el cambio de MLCardForm

Update BfSplitPayment, MLCheckoutSDK, BuyingflowPayment

---

android-whitelist.json

Con la inclusión de las versiones de work-runtime 2.8.1 y room 2.5.1 en las apps MP / ML, se realizara la actualización de la lib externa de datadog.
-- [Documento](https://docs.google.com/document/d/1dTdNFRRW6OAGSjBPEFFmZXorHFusEDLL5Y6Xd-6vupE/edit) de análisis.
-- [Comunicado](https://meli.workplace.com/notes/1410496432911912/?mode=edit&notif_id=1701444592182654&notif_t=work_knowledge_note_permission_grant&ref=notif) workPlace. 
No se hace la actualización de las lib en este mismo PR por que muchos equipos realizaran la actualización.  
- - #75101903

Bump Datadog

---

android-whitelist.json

Bumped ml qualtrics libs due to kotlin migration

---

android-whitelist.json

Se actualizan las version del marketplace-map de Checkout a la 15.+
- - #....

Update Checkout marketplace-map version

---

android-whitelist.json

Firebase perf expires date extend

---

android-whitelist.json

Se modificó nombre y versión ya que estaban mal cargadas
- - #....

[CHANGED] Portable Widget

---

android-whitelist.json

- Se extiende la fecha de expiración de los componentes de Navigation (AndroidX) para tener tiempo de deprecar su uso.
- - #....

[Update] Android Navigation Components expiration dates

---

android-whitelist.json

Update andes_integrations expire

---

android-whitelist.json

- Adicionando bibliotecas necessárias que eram utilizadas no smartPOS
- [SMART-5161]
[SMART-5161]: https://mercadolibre.atlassian.net/browse/SMART-5161?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[SMART-5161] - Adding new libraries for smartPOS

---

android-whitelist.json

Add expire in InAppUpdate because Kotlin migration
- - #....

Add expire In App Update

---

android-whitelist.json

Add expire user sections because kotlin migration
- - #....

Add expire user sections

---

ios-whitelist.json

Se retiran los breakingChange de las libs porque ya no son necesarios dichos cambios por parte de nuestra dependencia MLCardForm
- - #....

Update SplitPayment and Payments

---

android-whitelist.json

I would like to present a proposal for the inclusion of the AndroidX Tracing library in our whitelist. 
This library plays a role in Android application development, providing significant benefits in terms of performance, problem diagnosis, and code optimization.
AndroidX Tracing offers powerful tools for performance analysis, allowing you to identify and fix bottlenecks in your code. With the ability to chart the execution time of specific functions, we can efficiently optimize application performance, ensuring a smoother user experience.
- - [#105930](https://web.furycloud.io/help/tickets/105930)

Added androidx tracing for measure times

---

android-whitelist.json

There is a break change in Remote Config library.
- - #....

[SMART-5165] Include version 1.0.0 in remote config

---

android-whitelist.json

Se agrega la versión de comparator 9.+
- - #....

Add Comparator 9.+

---

android-whitelist.json

Flox 10 version added
- - #....

Flox 10 added

---

android-whitelist.json

Se aumenta la versión de Search a la 19 debido a la remoción de código legacy

bump search libs

---

android-whitelist.json

Se agrega versión de la lib [smart-helpers](https://github.com/melisource/fury_point-smart-helpers)
[SMARTI-1102](https://mercadolibre.atlassian.net/browse/SMARTI-1102)
[SMARTI-1102]: https://mercadolibre.atlassian.net/browse/SMARTI-1102?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[SMARTI-1102] Add smartHelpers version.

---

android-whitelist.json

add Maps to allowlist

---

android-whitelist.json

Bump attestation 10.x

---

android-whitelist.json

- Actualizamos fecha de expiración que se habia propuesto en https://github.com/mercadolibre/mobile-dependencies_whitelist/pull/1673/files#r1094513695
- - #....

Bugsnag Updated expiration date

---

android-whitelist.json
ios-whitelist.json

Webkit-Extensions library that provides tools to configure the Webkit Page and centralize configurations for MP and ML 
applications.
- - #....
- [] Mercado Libre
- [] Mercado Pago

Add webkit-extension 

---

android-whitelist.json

- [Documento](https://docs.google.com/document/d/1dTdNFRRW6OAGSjBPEFFmZXorHFusEDLL5Y6Xd-6vupE/edit) de análisis 
- ML  10.299.0 -> https://github.com/melisource/fury_mercadolibre-android/pull/13084
- MP  2.305.0 -> https://github.com/melisource/fury_mercadopago-android/pull/20212
- - #....

Bump work and room version

---

android-whitelist.json

Bump Restclient Crypto and LocalStorage for Kotlin migration
- - #....

Bump Restclient Crypto and LocalStorage

---

android-whitelist.json

Update version declaration to px.pmselector lib
- NO TICKET

Update pmselector declaration

---

ios-whitelist.json

[iOS] Bump IspSf to 3.0

---

ios-whitelist.json

Update allowlist iOS

---

ios-whitelist.json

...
- - #....
update expire MLUI

Update expire MLUI

---

android-whitelist.json

Since mPOS we have a new library which will works as an entrypoint to mPOS flow.
- - #....

[feature] Add new mPOS library to allowlist

---

android-whitelist.json

Fixed minor version to library androidx.tracing to latest stable version.
- - #108607

Fix bump version tracing

---

android-whitelist.json

Update ODR Android v12
- - #75105344

[bump] update odr version 12

---

android-whitelist.json

- Update libs for support kotlin 1.8
1. Dynamic Features 
2. Configuration Manager
3. Notifications
4. Rich Notifications
5. Notification Helpers
6. Place
7. Notification Center
8. Data Dispatcher
Task: https://mercadolibre.atlassian.net/browse/EVEREST-2212

Everest Update Libs Kotlin 1.8

---

ios-whitelist.json

Update AppMonitoring regex
- - #....

Update AppMonitoring regex

---

android-whitelist.json

Update libs for support kotlin 1.8
- - #....

Update Kotlin version devicessdk

---

android-whitelist.json

removed deprecated okhttp client methods
- - #....

bump tfs commons

---

.github/pull_request_template.md

Se actualiza el template de github, para validar que no se agreguen dependencias externas en nexus sin antes ser validadas por el team de platform updates
- - #....

Update template github

---

android-whitelist.json

Upgrade de la librería native-reauth-adapter-android a la versión 4.+
- - #....

Update Reauth-Adapter en android-whitelist.json

---

android-whitelist.json

Se agrega la lib qrCodeKotlin que reemplazará zxing para la generación de QRs
- - #75103220

add qrCodeKotlin

---

android-whitelist.json

Bumping Home Section Api
El motivo del bumping major és porque estamos disponibilizando una interface nueva para acceder a una nueva funcionalidade cuya interface funciona como callback
- - #....

Bumping home section api

---

ios-whitelist.json

MLEShops bump version
- - #....

MLEShops bump version

---

android-whitelist.json

feature :: Bumped isp bluetooth tools to correctly versions

---

ios-whitelist.json

Thales Manager SDK that provides tools for binding the app with Econ Token Platform. The Payment Experience's team need that to execute transaction using CTF validation program.
https://developer.dbp.thalescloud.io/docs/tsh-cof-token-gateway/1b03ab08dfb4c-ecom-token-platform
- - #....

Add Thales Manager SDK

---

android-whitelist.json

Ml-scanner-android 12.+ version expiration date changed, just to have some time left to fix some CameraX errors and MLKit18 integration tests
- - #....

Expiration date changed

---

android-whitelist.json
ios-whitelist.json

add CcapSDUI

---

android-whitelist.json

bump libdataprivacy

---

android-whitelist.json

Se actualiza a la versión 25.+ de la lib Authentication, en esta versión se migró a Kotlin 1.8.10.
...
- - #....
- [ x ] Interna: Libreria/modulo desarrollado in-house en base al ecosistema de Meli.

Bump authentication y AuthenticationEnrollment v25.+

---

README.md

Se modifica el readme explicando la nueva forma de testear la allowlist
- - #....

New way to test allowlist

---

android-whitelist.json

Agregando una nueava libraria. Esa libraria es un refactoring da libraria de cart-android y cart-android-manager. Nosotros poco a poco estamos eliminando  classes que no son utilizadas y migrando solo o que es util para un nuevo repositório.
- - #....

agregando nueva libraria cart-facade:proxy:1.1.0

---

android-whitelist.json

Se agrega la dependencia de la nueva lib wrapper  para generar códigos QR
- - #....

add new lib wrapper qr generator

---

android-whitelist.json

Due that this is a brand new library, its initial develop should start with 0.x.y
- - #....

Update lib version.

---

android-whitelist.json
ios-whitelist.json

Se agregan las dependencias para el módulo de Virtual Try On
- - #....

[Feature] Add Virtual Try On dependencies

---

ios-whitelist.json

Se desea eliminar MLCollaboratorsV2 de la whitelist ya que se va a remover de MP.
- - #....

Remove MLCollaboratorsV2

---

android-whitelist.json

Se bumpea la lib de recommendation-combo, los modulos de core y recommendations
- - #....

bump recos

---

ios-whitelist.json

Bump Protobuf to 3.25.2 due to CI issues
- - #....

Bump Protobuf to 3.25.2

---

android-whitelist.json

Allow Selling Framework dependencies version 3.+
- No ticket

Allow Selling Framework version 3.+

---

android-whitelist.json
ios-whitelist.json

Se realiza revert ya que la libreria no se termino de analizar el impacto que puede tener en ML porque incluye un .aar de una libreria externa.

Revert "Add Virtual Try On dependencies"

---

android-whitelist.json

Bump Restclient and Everest

---

ios-whitelist.json

[iOS] Bump IspSf to 4.0.0

---

ios-whitelist.json

cardForm - remove expiration date 
- - #....

Remove the expiration date from cardForm 

---

android-whitelist.json

Update Bitmovin version to 3.51.0
- - #75104772

Update Bitmovin version

---

ios-whitelist.json

Se agrega la librería external de Modiface para iOS.
- - #....

[Feature] Add modiface external lib

---

android-whitelist.json

Versión de bitmovin que evita colisión con exoplayer.
MPlay Bitmovin V 3.43.0 -> https://gradle.adminml.com/s/jxtcyvm27mwpe
MPlay Bitmovin V 3.43.1.+jason -> https://gradle.adminml.com/s/ji63z3wv2vqbs  
[#75108264](https://web.furycloud.io/help/tickets/111606?page=1&teams=false)

[MTV-8704] Updating Bitmovin version to 3.43.1+jason

---

android-whitelist.json

Se agrega version de Bitmovin, ya que el release de esta semana debe salir con la 3.43.0 y se le agrega fecha de expiración.
Esta es la misma version que estaba antes.
Actualmente se deben mantener la version 3.43.0 y la 3.43.1+jason
- - #....

Add Bitmovin version

---

android-whitelist.json

[mPOS][PaymentFlowFCu] Bump FCU to 12.+

---

ios-whitelist.json

Se sube numero de la versión de la librería y se deja por precaución un mes la anterior aunque no esta siendo utilizada por ninguna librería en producción
- - #....

MlCards deprecation date and upgraded version

---

ios-whitelist.json

Se agrega la dependencia para el módulo de Virtual Try On en iOS
- - #110182

[Feature] Add Virtual Try On in iOS

---

ios-whitelist.json

Revert FeedbackScreen changes on the whitelist

---

android-whitelist.json

se actualiza la version de lifecycle:proccess
- - #....

Update lifecycle proccess

---

android-whitelist.json

Update lib wishlist 1.+ and expire 0.+
- - #....

Update lib wishlist Android

---

android-whitelist.json

add adn v7

---

ios-whitelist.json

Se aumenta major de CPG por lo que se deprecan versiones anteriores.
- - #....

Update CPG Major

---

android-whitelist.json

Bump cart-manager version

---

ios-whitelist.json

* BreakingChange para librería AdvertisingADN.
- - #....

[Changed] - AdvertisingADN updated.

---

android-whitelist.json

Se actualiza el major de las libs de commons & data-dispatcher and Everest, debido al update de libs android x
- - #....

Update commons and data-dispatcher and everest

---

android-whitelist.json

Se sube recommendations-combo a la 5.+, y se agrega fecha de expiración para la anterior.
- - #....

bump recos 5.+

---

android-whitelist.json

add compose libs for odr 
- - #75110306

add compose libs for odr

---

android-whitelist.json

...Se realiza el update de la libs de commons, por el update de android x.
- - #....

Update expire commons

---

ios-whitelist.json

- Se agrega MeliphoneVoip a la whitelist, librería interna de CX para realizar llamadas VoIP utilizando el SDK de Twilio, previamente incorporado a la whitelist ([PR](https://github.com/mercadolibre/mobile-dependencies_whitelist/pull/2342)). 
- #75108248
- A cargo de Thayse Bianca Amaral De Carvalho

Add MeliphoneVoip lib

---

ios-whitelist.json

Se remove el SDK de TMGSDK
- - #....

Remove TMGSDK

---

android-whitelist.json

Se agrega la version nueva de commons.
- - #....

Add commons version

---

android-whitelist.json

New version of performance-tools-androis witth kotlin and Leak Canary bumped and added a silent-mode in analisis of memory leaks.
- Kotlin: 1.5 -> 1.8
- Leak Canary: 2.7 -> 2.13
- - #....

Bump version Performance Tools Android

---

android-whitelist.json

Update ptm-tools version to 3.+ (Okhttp migration)
- - #....

[No-TIcket] Update PTM-tools version

---

android-whitelist.json

Versión de bitmovin que evita colisión con exoplayer.
- - #....

[MTV-9209] Updating Bitmovin version to 3.43.1+jason

---

android-whitelist.json

-  Meliphone VoIP es una nueva lib en proceso de desarrollo del equipo de CX.
- Se modifica la versión en whitelist. 
-  # 75108113

Modified meliphone whitelist version

---

android-whitelist.json

Update expire `androidx.navigation:navigation-fragment-ktx`  Update expire androidx.navigation:navigation-ui-ktx
- - #....

Update expire navigation lib

---

android-whitelist.json

Se bumpea la lib de DAMI UI Components para deprecar el trackeo por Google Analytics
- - #....

Bump DAMI UI to 5

---

android-whitelist.json
ios-whitelist.json

Se agrega la librería de mobile actions. Para saber más acerca de esto, se puede leer el [RFC](https://docs.google.com/document/d/1ooNfU45KDtaH_73tN3TtdIoYRaETJ9LBkPdNvU1_XSE/edit?usp=sharing).

Mobile actions

---

android-whitelist.json

Actualizamos la versión de nav manager para soportar Tabbar en ML
- `com.mercadolibre.android.navigation_manager`

Navigation Manager Bump 6.0.0

---

android-whitelist.json

We pospose the expire date of previous ml-scanner-android version because of unresolved issues with a couple of features (MLKit18 and CameraX) of this version
- - #....

Ml scanner android expire change

---

android-whitelist.json

Se realiza downgrade de la libs de locations ya que se registro un issue en RC.

[Fix]downgrade gps locations

---

android-whitelist.json

Bump version - okHttp
_Smart tokenization version 4
CardForm version 6_
- - #....

bump smart-tokenization and card-form

---

ios-whitelist.json

Add AiAssistantClient to the iOS allow list
- - #....
- [ECOSRCHVIP-4409](https://mercadolibre.atlassian.net/browse/ECOSRCHVIP-4409)
[ECOSRCHVIP-4409]: https://mercadolibre.atlassian.net/browse/ECOSRCHVIP-4409?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Add AiAssistantClient to the iOS allow list

---

ios-whitelist.json

Thales Manager SDK that provides tools for binding the app with Econ Token Platform. The Payment Experience's team need that to execute transaction using CTF validation program.
https://developer.dbp.thalescloud.io/docs/tsh-cof-token-gateway/1b03ab08dfb4c-ecom-token-platform
- #75106929

Add TMGSDK

---

ios-whitelist.json

Se elimina deprecacion por temas de tiempos y dependencias de otros equipos.
- - #....

Downgrade CPG

---

android-whitelist.json

Se acaba de sacar un nuevo release de la Lib Authentication por lo tanto se agrega a la white list.
- - #....
- [ x ] Interna: Libreria/modulo desarrollado in-house en base al ecosistema de Meli.

se actualiza Authentication lib

---

android-whitelist.json

Adds support to v8.0.0 of SMART's pos-sdk library.

[SMART-5247] Add pos-sdk v8.0.0 on allowlist

---

android-whitelist.json

Se agrega el modulo variations al proyecto de rcm (Recomendations)
- - #....

added module variations [Recommendations]

---

android-whitelist.json
cross-kmp-allowlist.json

Esta librería es core de KMP y es necesaria para que corra el plugin.
- - #....

KMP stdlib common.

---

ios-whitelist.json

Update FBSDKCoreKit 17.0.0

---

ios-whitelist.json

Update Firebase/DinamicLinks 10.22.0

---

ios-whitelist.json

[iOS] Bump IspSf to 5.0.0

---

ios-whitelist.json

Add new Screenshots iOS lib to the iOS allowlist
- - #....

Add Screenshots iOS lib to allowlist

---

ios-whitelist.json

Prev: #2413 
Versions standardization till may 17th 2024 libs
IF source is tagged as private, it is a internal dependency, therefore it's allowed to have a regex in minor and no path - NO SECOND REGEX ALLOWED
{
"name": "EXAMPLE",
"source": "private",
"target": "production",
"version": "^~>\s?1.[0-9]*$"
}
ELSE source is tagged as public, it means we are dealing with an external lib and this should have specific major, minor and path - NO REGEX ALLOWED
{
"name": "EXAMPLE",
"source": "public",
"target": "production",
"version": "5.0.0"
}
- - #....

Versions standardization till may 17th 2024 libs

---

android-whitelist.json

Add new lib meli screenshots. Lib interna propia
- - #....

Add new lib Android meli screenshots

---

android-whitelist.json
ios-whitelist.json

[Closed-PR](https://github.com/mercadolibre/mobile-dependencies_whitelist/pull/2409)
- - #....

version checker

---

ios-whitelist.json

- The library was created to use CTF validation program in Checkout. Now, is possible to create binding and safe environment to transact more money.   
- We have use the Thales Manager SDK that provides tools for binding the app with Econ Token Platform. The Payment Experience's team need that to execute transaction using CTF validation program.
- [PXN-9505 ](https://mercadolibre.atlassian.net/browse/PXN-9505)- Tokenizacion Device con Visa & Master
- Related: https://github.com/mercadolibre/mobile-dependencies_whitelist/pull/2382

Add PxTokenization

---

android-whitelist.json

Add business_component

---

android-whitelist.json

Bump version - okHttp
_SecureInputs v3_
- - #....

bump secure-inputs 

---

android-whitelist.json

Kotlin 1.8
Android 13
- - #[114837](https://web.furycloud.io/help/tickets/114837)

Traceability version 9.0.0

---

android-whitelist.json

Se actualiza RestClient a la version 25. Además se agrega fecha de expiracion a los modulos que fueron eliminados 
- - #....

Update RestClient 25

---

android-whitelist.json

Add granular dependency to developer mode. modify date expires of lib Flipper.
- - #....

Add granular dependency to developer mode. modify date expires.

---

android-whitelist.json

new version at expires webkit

---

ios-whitelist.json

Update Firebase/core 10.22.0
- - #....

Update Firebase/core 10.22.0

---

android-whitelist.json

Se vuelve a rest client 24 para los dos modulos indicados
- - #....

Revert bump RestClient 25

---

android-whitelist.json

[Flox] New version in Engine: 11.0.0

---

android-whitelist.json

bumped qualtrics sdk

---

android-whitelist.json

Se agrega update version de remoteConfiguration y se deja un expires de la version anterior.

Bump version RemoteConfigurations

---

ios-whitelist.json

Bump Adjust SDK iOS version
- [] Interna: Libreria/modulo desarrollado in-house en base al ecosistema de Meli.

Adjust sdk bump for ios

---

android-whitelist.json

Bump Addresses v10 and XProdComp v2.
- - #....

Bump Addresses v10 and XProdComp v2.

---

android-whitelist.json

Update ccap-commons to 2.+ and put expiration the 1.+
- - #....

feat: bump ccap-commons to 2.+ and put expiration the 1.+

---

android-whitelist.json

...Se realiza revert debido a que no se publico la version todavia.
- - #....

Revert "Update commons to 36"

---

android-whitelist.json

Añado una libreria interna para MoneyOut
- - #....

add tranfer-checkout in whitelist

---

android-whitelist.json

Update mayor version of CPG and added expire old version.
- - #....

[Update] Update minimum version of cpg and added expire date old version

---

android-whitelist.json

Remove Restclient 21
- - #....

Remove Restclient 21

---

android-whitelist.json

- se habilita a tetris para utilizar el modulo de compose de ODR
- - #75113766

[feature] enable odr compose for tetris

---

ios-whitelist.json

Remove libs q no tienes uso

---

ios-whitelist.json

Add FeedbackScreen to the early adopter for Andes/SwiftUI
- - #....

Add FeedbackScreen to be an early Andes/SwiftUI adopter

---

ios-whitelist.json

Update granularidade Firebase y Facebook

---

android-whitelist.json

Bump NavigationCP v12, UINavigationCP v10 and XprodModules v2.
Upgrade por Android X.
- - #....

Bump NavigationCP v12, UINavigationCP v10 and XprodModules v2.

---

ios-whitelist.json

Update reglas Firebase

---

android-whitelist.json

Bump Everest

---

ios-whitelist.json

Deprecated RxSwift
We are adding exception use to the Instore team and blocking the use of others.
- - #....
- [x ] Mercado Pago
- [ x] Externa: Libreria desarrollada por un externo a Meli. (Google, Airbnb, otros).

add exception rxswift

---

android-whitelist.json

Allow developer settings library for Selling Framework version 3.+
No ticket
[PSF-2443]: https://mercadolibre.atlassian.net/browse/PSF-2443?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[PSF-2443] - Allow developer settings library 3.+

---

ios-whitelist.json

- Fix FirebaseCore granularity
- - #....

Fix FirebaseCore granularity

---

android-whitelist.json
ios-whitelist.json

Se suma la lib `ScreenshotsManager` a whitelist.
iOS: https://github.com/melisource/fury_screenshots-manager-ios
Android: https://github.com/melisource/fury_screenshots-manager-android
- - #....

Added screenshot manager lib

---

android-whitelist.json

-userbiometricsCore = "9.+"
-Preferences = "10.+"
-Ui = "9.+"
-Risk = "6.+" 
- - #....

Update SL libs

---

android-whitelist.json

Notification helpers v6

---

ios-whitelist.json

- Se actualizan las versiones de los subspecs de EverestLibs para que esten todas en una linea y mejorar la mantenibilidad.
- N/A

Refactor EverestLibs subspecs  to add all in one single line

---

ios-whitelist.json

Necesitamos actualizar la fecha de vencimiento para las versiones 2.x.x ya que por motivos de retrasos no podremos desplegar las versiones 3.x.x antes del 29/04/2024.
- #75114470

[iOS][AdvertisingADN] - Expired date updated.

---

ios-whitelist.json

Remove duplicated libs.
- - #....

[PX] Remove duplicated libs

---

android-whitelist.json

- Actualizamos la versión de Search a 20.+ que contiene los cambios para la integración de TabBar ML y los filtros nuevos
- Agregamos el expires a la versión 19.+ de Search
- - #....

Bump Search to 20.+

---

android-whitelist.json

[ANDROID] New Version ADN V8

---

ios-whitelist.json

Update granularid FBSDKCoreKit

---

android-whitelist.json

com.mercadolibre.android.restclient
com.mercadolibre.android.restclient-adapter-bus
com.mercadolibre.android.restclient-adapter-rx2
com.mercadolibre.android.restclient-extension-header
- - #....

Update expire restclient 23

---

android-whitelist.json

Se realiza bump de libs bajo ownership del equipo Proximity:
- Instore UI
- Discount Touchpoint
- Instore Home Sections
- MlBusiness Components 
- Instore Reviews

Update libs bajo ownership del equipo Proximity

---

ios-whitelist.json

[Changed] - Update OMSDK version to 1.4.13

---

ios-whitelist.json

Update granular list navigation

---

android-whitelist.json

New major for reauth native lib
- - #....

Add reauth native version 7

---

android-whitelist.json

Update Viewability version

---

ios-whitelist.json

Update MLBiometricSecurity and BiometricSecurityUI expires
- - #....

Update ios-whitelist.json MLBiometricSecurity and BiometricSecurityUI

---

android-whitelist.json

Add network with expire

---

android-whitelist.json

[mPOC] Bumped mpoc libraries to 1.+

---

android-whitelist.json

Add stripe bar library

---

ios-whitelist.json

- Se agrega la lib de Swinject for test.
- - #....

Swinject for tests

---

android-whitelist.json

Actualización de Librerias reviews3 y vpp
- - #....

Update reviews3 and vpp version

---

android-whitelist.json

Allow Selling Framework dependencies version 4.+ and 5.+
No Ticket

Bump selling framework version

---

ios-whitelist.json

New lib TransfersCheckout
`Para más información visitar [Wiki.](https://sites.google.com/mercadolibre.com/mobile/arquitectura/allowlist)`

New lib TransfersCheckout

---

android-whitelist.json

Se modifica el expires date de las libs de androidx, commons y data_dispatcher.

Fecha de expiracion de androidx y commons libs

---

android-whitelist.json

-  Meliphone VoIP es una nueva lib en proceso de desarrollo del equipo de CX.
- Se modifica la versión en whitelist de 0.+ a 1.+ para honrar las convenciones, ya que vamos a salir a producción.
-  # 75108113

Update meliphone lib

---

ios-whitelist.json

- Bump MeliphoneVoip version to 1.+
- Se modifica la versión en whitelist de 0.+ a 1.+ ya que vamos a salir a producción.
- - #75108248

[Bump] Bump MeliphoneVoip iOS to 1.+

---

android-whitelist.json

Upgrading of versions of PX libraries following the recommendation for Android x migration and to update other libraries that are expiring.
N/A

[Feature] Update PX Libraries

---

android-whitelist.json

Se separan los modulos de transfer chekcout
- - #....

Transfer checkout new modules

---

android-whitelist.json

Bump DAMI UI components 6

---

android-whitelist.json

`Update mayor version of ESHOPS and added expire old version.`
- - #....

[Bump] Bump ESHOPS mayor version to 4.+ and added expires date in the 3.+ version

---

ios-whitelist.json

Se actualiza regla de la librería Credits UI Components
- - #....

[Bump] Update Credits UI Components rule

---

android-whitelist.json

Se realiza el bump de la librería Credits Flux Client    
- - #....

Bump de librería Credits Flux Client

---

android-whitelist.json

Updates de versiones major de sdk del equipo de devices, por las dependencias transitivas de Android X
- - #....

Update devices android libs: devices-sdk and behavioral-sdk

---

android-whitelist.json

[Feature] Flox 12 version

---

android-whitelist.json

Se agrega la lib de sessions: Sessions Authorization (Iniciativa IFPE/SPEI) version `mercadopago-1.+` a la whitelist mobile.

Add sessions_authorization mercadopago-1.+ to whitelist

---

android-whitelist.json

Se actualiza la versión de Virtual Try On para el nuevo modulo commons.
- - #....

[BUMP] Virtual Try On Android version

---

android-whitelist.json

Se elimina la lib Credits Behaviour ya que esta ha sido eliminada de la app de Mercado Libre de manera definitiva porque su funcionalidad ya no es necesaria.
Fue removida de ML Config Provider en este [PR](https://github.com/melisource/fury_ml-config-provider-android/pull/846)
Y tambien fue removida en este [PR](https://github.com/melisource/fury_mercadolibre-android/pull/13828) de ML en el tren 10.319.0.

Remove Credits Behaviour

---

android-whitelist.json

Se agrega el SDK de TMG, la conversacion fue realizada por SLACK [temp-tmgsdk-integratiom](https://meli.slack.com/archives/C06PQ3LQ9K6) y [temp-tmgsdk-android-](https://meli.slack.com/archives/C06URLSP5BK)
- - 118084

Adding TMGSDK

---

ios-whitelist.json

Se actualiza la versión de Virtual Try On por la primera productiva
- - #....

[BUMP] Virtual Try On iOS version

---

android-whitelist.json

Se actualiza la versión de Virtual Try On para la primer versión productiva.
- - #....

[BUMP] Virtual Try On Android production version

---

android-whitelist.json

Se actualizan todas la libs de Checkout por breaking change de AndroidX
- - #....

[Bump] - Checkout ON All dependencies

---

android-whitelist.json

Por motivo de migracion de Android X se esta agregando las libs con sus respectivos bump del mayor    
- - #....

bump libs for android x

---

android-whitelist.json

Bump 9.0.0. Appcompat 1.3.1 to 1.5.1

Bump Andes 9.0.0

---

android-whitelist.json

Revert "[Fix]downgrade gps locations"

---

ios-whitelist.json

Se agregan las libs ShippingIosLogin y ShippingIosMyaccount
...
- - #....

Agregando libs de ShippingIosLogin y ShippingIosMyaccount

---

android-whitelist.json

- Add andes & compose early adoption for WMS

Add compose granularity for WMS modules

---

android-whitelist.json

Se agrega una nueva versión de Navigation Menu con la migración de rest client
- - #....

Update nav menu restClient Migration

---

android-whitelist.json

Added cardsnfcwallets in android white list
...
- - #....

Added cardsnfcwallets in android white list

---

android-whitelist.json

- Add activity-compose to auth-native-soo

Add activity compose to native sso

---

android-whitelist.json

Update libdataprivacy lib version

---

ios-whitelist.json

Se elimina la lib Credits Behaviour ya que esta ha sido eliminada de la app de Mercado Libre de manera definitiva porque su funcionalidad ya no es necesaria.
[PR](https://github.com/melisource/fury_mercadolibre-ios/pull/9922) de Eliminación del proyecto 
- [X ] Mercado Libre
- [X ] Interna: Libreria/modulo desarrollado in-house en base al ecosistema de Meli.

Remove MLCreditsBehaviours 

---

android-whitelist.json

This library is not in production and has no uses yet, we need  to go into production in version 1.+
- - #....

[CCAP-6409] Chore: change version 0.+ to 1.+

---

android-whitelist.json

Update android-whitelist.json everest version

---

ios-whitelist.json

agregando librería de pre-check-in

---

android-whitelist.json

Tras hacer [bump de Android X](https://github.com/melisource/fury_mobile-permissions-android/pull/65) en Permisos, subimos el major.

Update permissions lib

---

ios-whitelist.json

Add AmountScreen 1.0 to whitelist + deprecate 0.x

---

ios-whitelist.json

Update major version to wishlists lib
- - #....

Update major version to wishlists lib

---

android-whitelist.json

feat: add remedy challenge to catalog

---

cross-kmp-allowlist.json

Add the lib kotlinx-serialization-json only for rtc-mobile
- - #....

Add the lib kotlinx-serialization-json only for rtc-mobile

---

cross-kmp-allowlist.json
ios-whitelist.json

Add  expiration wishlists lib
- - #....

add wishlist expiration

---

android-whitelist.json

Change amount screen name versión to flavor
- - #....

[Feat]: Change amount screen name versión to flavor

---

.pre-commit-config.yaml
ios-whitelist.json

En este PR se habilita la nueva versión de MLThreeDS 6.6.129
- - #....

MLThreeDS iOS Version 6.6.129 

---

android-whitelist.json
ios-whitelist.json

- Kingfisher
Kingfisher es una biblioteca de Swift para la descarga y cacheo de imágenes en aplicaciones iOS. Permite la descarga asíncrona de imágenes, su almacenamiento en caché (memoria y disco), y ofrece soporte para animaciones y placeholders. También proporciona extensiones para UIImageView para facilitar la carga y visualización de imágenes. Ideal para mejorar el rendimiento y la experiencia de usuario en aplicaciones que manejan muchas imágenes.
- Coil
Coil es una librería nueva de kotlin que hace uso de Coroutines para brindar una mejor performance. Sus puntos fuertes son que es nueva, ligera, y fácil de usar. Es muy similar a Glide, pero te da menos control sobre el manejo de cache. Su documentación es clara, y pese a ser nueva tiene una comunidad en la que apoyarse.
RFC: …

[Everest Canvas] Add Kingfisher and coil libraries

---

android-whitelist.json

Bump de Andes Integrations a 4.+

Bump Andes Integrations 4.+

---

android-whitelist.json

Se agregan los bumps de las librerias de Everest

Android 14 - Everest

---

ios-whitelist.json

[Changed] - Update OMSDK version to 1.4.14

---

android-whitelist.json

…cion Android 14
Nuevas versiones de car-facade con migración de módulos para soportar Android 14
- - #....

Nuevas versiones de car-facade con migración de módulos para soportar Android 14

---

android-whitelist.json
ios-whitelist.json

Liberando el acceso de Declarative a MLVPP
- - #....

Liberando el acceso a MLVPP

---

android-whitelist.json

- Applying bump for 9.+ version of Andes compose. Replacing current 8.+

Apply compose 9+

---

android-whitelist.json

Add new version webkit

---

android-whitelist.json

Update lib wishlist 4.+ and expire 3.+
- - #....

update lib wishlists Android 4.0

---

android-whitelist.json

Upgrading Home Api lib
- - #....

[CHANGED] Update android-whitelist.json

---

android-whitelist.json

Add new version screenshots and InAppReport
- - #....

Add new version screenshots and InAppReport

---

android-whitelist.json

Actualización Android 14:
- dependencias otel.
[OTEL Android](https://gradle.adminml.com/c/edtkh72mmrfdc/zmvlmwqp5ppvi/dependencies?hideBuildA&hideBuildB)
[ML](https://gradle.adminml.com/c/uw74u5uleiofq/47rzsqyutxb5g/dependencies?hideBuildA&hideBuildB)
[MP](https://gradle.adminml.com/c/4hbdbr5xyeqiq/xd5bqw6cc62wm/dependencies?hideBuildA&hideBuildB)
- - #[75118345](https://web.furycloud.io/help/tickets/121691)

Bump otel v7 and dependencies.

---

android-whitelist.json

Add gif, svg and video

---

android-whitelist.json

Changes at ml-scanner-android lib:
- v14 added [MLKit18 version]
- Expire date for previous versions changed/added to 10-06-2024: 
- - #....

ScannerAndroid changes

---

android-whitelist.json

- Update feature delivery to 2.1.0 - Dynamic Features.

Update feature-delivery to 2.1.0

---

android-whitelist.json

Se agrega la nueva versiones de Search Android por la migración de Android 14
- - #....

[Android] Update Search 21.X.X

---

ios-whitelist.json

Se agregan expires para las libs legacy de registro, tanto para Android como para iOS, para poder borrar sus respectivos repos de manera segura.
- - #....

Add expires for registration

---

android-whitelist.json

En este PR se habilita la nueva versión de usdk 6.6.69
- - #....

[Android] usdk version 6.6.69

---

android-whitelist.json

Bump para soportar API 34
- - #....
https://maven.artifacts.furycloud.io/#browse/search=keyword%3Dcom.mercadolibre.android.dami_ui_components

Bump DAMI UI Components to 7.+

---

android-whitelist.json

Actualización de la libc2d, es una lib externa (.aar) del gobierno del Chile.
...
- - #....

chore: update the libc2d

---

android-whitelist.json

Add expire and version update.
-fury_instore-android
-fury_barcode-img-generator-android
-fury_meli-scan-barcode-ui-android
- - #....

add expire and new version instore libs

---

android-whitelist.json

Fix version Otel networking

---

android-whitelist.json

- Se agrega everest canvas a todas las libs de compose.

Add Everest Canvas to Compose

---

android-whitelist.json

Update uiComponent 18.+
- - #....

Bump uiComponents 18.+

---

android-whitelist.json

Este PR agrega el module migration de la lib interna app-monitoring.
- - #....

Add AppMonitoring Migration Module

---

ios-whitelist.json

- Add whitelist for Selling Framework v6
- https://mercadolibre.atlassian.net/browse/PSF-3059

Update Selling Framework iOS

---

.pre-commit-config.yaml
android-whitelist.json

- Adding Metrics v10
- Expiration date for Metrics v9
- - #....

Update Metrics V10

---

.pre-commit-config.yaml
android-whitelist.json

- Adding Metrics v10
- Expiration date for Metrics v9
- - #....

Update Traceability V10

---

android-whitelist.json

[CHANGED] Updated Merch repos major/expire dates

---

android-whitelist.json

This PR updates Home-section-api versions and expiration dates.
- - #....

[CHANGED] Update Home-section-api versions

---

ios-whitelist.json

Se agrega la libreria SessionsAuthorization
- - #....

Add: sessions authorization

---

android-whitelist.json

Se actualiza la version de Credits UIComponents
Es el update es por la migracion de Android 14 donde esta libreria core la implementa otra lib core que necesita se tambien ser migrada.
- - #....

Bump Credits UI Components v7.+

---

android-whitelist.json

- [appMonitoring build](https://gradle.adminml.com/c/xzr3eevwho644/g7im57htthn4s/dependencies)
- [ML build](https://gradle.adminml.com/c/dxavn7igcsfqi/spn3zujbr5fws/dependencies?hideBuildA)
- [MP build](https://gradle.adminml.com/c/ttpagjaub6tp4/j7x5kazbl22jo/dependencies)
- - #[75119154](https://web.furycloud.io/help/tickets/122500)

Upgrade datadog version for Android 14

---

android-whitelist.json

Se aumenta la versión de eshops a la 5 debido a la migración de Android 14
- - #....

Bump eshops version

---

android-whitelist.json

Se aumenta la versión de cpg a la 11 debido a la migración de Android 14
- - #....

Bump cpg version

---

android-whitelist.json

Bump Onboarding to version 4. Includes Android 14
- - #....

Bump Onboarding

---

android-whitelist.json

Upgrade data privacy library version to v5

Upgrade data privacy library version to v5

---

android-whitelist.json

Se realiza Bump de las libs del equipo Buyers Proximity para soportar Android Api 34
- - #....

Bump Proximity libs Android Api 34

---

android-whitelist.json

Actualización de las librarias para lograr la migracion para android 14

---

ios-whitelist.json

- Add KingfisherWebp - Everest Canvas

Add KingfisherWebp - Everest Canvas

---

android-whitelist.json

Se hace bump de comparator

---

android-whitelist.json

Update globe version to 2.3.1-114

---

android-whitelist.json

Bump Melidata to 22 for migration to Kotlin
- - #....

Bump Melidata 22

---

android-whitelist.json

update navigationMananager in home    
- - #....

update navigationMananager in home

---

android-whitelist.json

Bump Flox Client v5.0.0, Credits Toolkit v5.0.0, Meli Charts v7.0.0

---

android-whitelist.json

Se crea un nuevo bump de version 10 para la Credits Flux Client que incluye el soporte para Android 14
- - #....

Credits Flux Client v10

---

android-whitelist.json

Upgraded usersections and toolkit due to Android 14 migration
- - #....

Upgraded usersections and toolkit

---

android-whitelist.json

Bump Authentication V27.0.0 y Bump Login V21.0.0

---

android-whitelist.json

Update version to 3.+.
Set expire date to version 2.+
- - #....

Bump px-pm-selector

---

ios-whitelist.json

Upgrade new PxPmSelector iOS version
- - #....

Bump PxPmSelector 2.0.0 iOS

---

android-whitelist.json

Soporte android 14 para Viewability y ADN
- - #....

Bump Advertising libs- support api 34 

---

android-whitelist.json

[SX] Updated android 14 major versions

---

android-whitelist.json

We'll set a breaking change because of some migrations:
- ml-scanner-android v14's expire date setted to 25-07-24
- ml-scanner-android v15 added
- - #....

ml-scanner-android version added

---

ios-whitelist.json

New lib TransfersComponents iOS

Adding new lib iOS: TransfersComponents

---

ios-whitelist.json

Expire MLRxRestClient y remove RxSwift libs

---

android-whitelist.json

- Update commons 38 
- New version for everest 17

Update commons version to 38

---

android-whitelist.json

-- Se actualiza la fecha para hacer sync con el [deprecado](https://meli.workplace.com/notes/420146367465386) 
- - #....

Extend the expiration date of Firebase Performance

---

android-whitelist.json

[mPOS] Updated date limit zxing

---

ios-whitelist.json

Adiciona temporariamente a lib do Swinject para as libs "DependencyInjection" e "CrabDI"
- - #....

Swinject for CrabDI & DependencyInjection

---

android-whitelist.json

Add advertising analytics dependency

---

android-whitelist.json

Add transfer components v0.1.0
- - #....

[Add] Transfer Components Core v0.1.0

---

android-whitelist.json

Native Reauth 8
Reauth Adapter 5
- - #....

Native Reauth 8 and Reauth Adapter 5

---

ios-whitelist.json

- Set static version for kingfisher deps.

Set static version for kingfisher

---

android-whitelist.json

Se actualiza el major del section-api para el release 9.+
- - #....

Update section-api to major 9.+

---

android-whitelist.json

Se crea la version de Flox 13 con soporta para Android 14
- - #....

Bump Flox 13 with Android 14 support

---

android-whitelist.json

Se actualiza versión porque la anterior tiene un conflicto de clases con otro sdk externo.

Update globe version

---

ios-whitelist.json

Se subió el major de MLMap, por lo tanto te se agregó una fecha de expiración para la version 3 y se agregó a la whitelist la version 4.
- - #....

MLMap version updated

---

android-whitelist.json

Se realizan los cambios de este PR https://github.com/mercadolibre/mobile-dependencies_whitelist/pull/2684
- - #....

Fix nav manager 7.+

---

android-whitelist.json

Actualizar whitelist con versión de reviews
- - #
https://mercadolibre.atlassian.net/browse/DMIX-40

update reviews whitelist

---

android-whitelist.json
ios-whitelist.json

- Se agrega version 0 (test no productivo) verticals core iOS y Android.
- - #....

Add VerticalsCore to whitelist

---

android-whitelist.json

Fix allows-granular-project in the analytics lib.
- - #....

Fix allows-granular-projects in the Analytics lib

---

android-whitelist.json

SmartTokenization version 5.
- - #....

[CCAP-6890] Smart tokenization v5

---

android-whitelist.json

Bump lib versions
mpos: 9
fcu: 14
posreaders: 10
pointui: 7
mpoc: 2

[ISPMPOS-2646]Bump mpos libs

---

android-whitelist.json

- expire v1
- add v2
- allows granular projects
...
- - #....

Update request watcher lib

---

android-whitelist.json

Se añade el modulo de amount picker como dependencia en transfer checkout  
- - #....

Adding Amount picker in Transfer checkout module

---

android-whitelist.json

- Se agrega un nuevo módulo (`:metadata`) para la lib de `transfers_components`

Added new module for transfers_components lib.

---

android-whitelist.json

Se agrega Vpp y Search para poder usar la version 7.+ de navigation
- - #....

Add libs to granular projects

---

android-whitelist.json

[Feature] Bump usdk version

---

android-whitelist.json

Se actualiza la version de error handler a la versión 4.+ y se pone fecha de expiración a la versión 3.+
- - #75121532

[bump] Update Error Handler v4

---

android-whitelist.json

Globe version restored
- - #....

restore globe version

---

android-whitelist.json

Add libs of augmented reality with granularity for WMS

Add libs augmented reality granularity

---

android-whitelist.json

Se hace upgrade de la lib por que esta deprecada y no tiene soporte par android 14
https://gradle.adminml.com/c/z4rqr3egdpke2/g44gt74eqncca/dependencies
https://web.furycloud.io/help/tickets/121337

Bump interactivemedia to 3.34.0

---

android-whitelist.json

Hemos actualizado la versión de Traceability para eliminar la función de fricciones y hemos aumentado el mayor porque genera un breaking change.
- - #....

Update Traceability 11.+

---

ios-whitelist.json

Se agrega version 0 (test no productivo) demandCOre en iOS.
- - #....

DHV-4300-Add DemandCore to whitelist 

---

android-whitelist.json

- Okta BOM is necessary in the project yuca-authentication-android

[FEATURE] Added Okta bom dependency

---

android-whitelist.json

Update de UI a 11.0.0 debido a la subida de target a Android 14.

Updated UI & UI_legacy version to 11

---

android-whitelist.json

Fix de typos introducidos en https://github.com/mercadolibre/mobile-dependencies_whitelist/pull/2726
- - #....

Fix typos for DA Components granularity

---

android-whitelist.json

Quito los módulos de las dependencias granulares
- - #....

Remove test modules

---

android-whitelist.json

Bump de Da Components para la migración de Android 14
- - #....

Bump Da Components to 9

---

android-whitelist.json

New sdk globe implemented
- - #....

globe sdk update

---

android-whitelist.json

Se crea nueva version para modulo Instore UI perteneciente a equipo Proximity. Esto debido a que se agrega version por flavor.
- - #....

[Android] Update Instore UI

---

ios-whitelist.json

Crear la primera versión de ADNAnalytics.
- - #....

[Added] - Add AdvertisingAnalytics to ios-whitelist.json

---

android-whitelist.json

`Update lib wishlist 5.+
`
- - #....

update lib wishlists Android 5.0

---

README.md
android-whitelist.json

**WARNING** This PR depends that the PR with the module granularity check its merged and released in Allowlist CQ Quality   
- - #....
ALL

Feature DA components with granularity by  module

---

ios-whitelist.json

...
- - [Update bitmovin Analitics126462](https://web.furycloud.io/help/tickets/126462?page=1&teams=true) 

Update BitmovinPlayer ios-whitelist.json

---

ios-whitelist.json

Se realiza un downgrade de BitmovinPlayer.
- - #....

Downgrade BitmovinPlayer

---

android-whitelist.json

Update Braze SDK to -> 31.+.
-  # [127034](https://web.furycloud.io/help/tickets/127034)

Update sdk braze to -> 31.

---

android-whitelist.json

bump dev-mode lib

---

ios-whitelist.json

MpGadgets es una nueva lib responsable de Dynamic Quick Actions en iOS. Implica la implementación de acciones rápidas dinámicas, permitiendo la personalización de acciones rápidas.
- - #....

add MpGadgets in ios-whitelist.json

---

android-whitelist.json

Al realizar el update de diversas versions de MP que vencieron se  hizo el bump de nuestra lib 
- - #....

Bump Cash Versions

---

android-whitelist.json
ios-whitelist.json

Bump restclient 27

---

android-whitelist.json
ios-whitelist.json

Se agrega version de test para las nuevas libs de MLT More Like This, en android y iOS.
- - #....

Add MoreLikeThis libs to whitelist

---

android-whitelist.json

Se fixea la versión de play services vision

fix play-services-vision

---

android-whitelist.json
ios-whitelist.json

Se agregan las dependencias para una nueva librería de home & industries del equipo de verticales.
- - #....

Add home & industries lib Android and iOS

---

android-whitelist.json

Bump uiComponents 19.+ and maps 11.+
- - #....

Bump uiComponents 19.+ and maps 11.+

---

android-whitelist.json

Bump melidata to 23.+
- - #....

Bump melidata to 23.+

---

ios-whitelist.json

Add BitmovinAnalyticsCollector for Mplay

---

android-whitelist.json

Globe version update
- - #....

globe version update

---

android-whitelist.json

Se actualiza el mayor permitido de la librería Cards-Components-android para la 10.+
- - #....

Update cards-components-android allowed version

---

ios-whitelist.json

Update de version para libs de horizontal cards y gadgets

Update horizontal cards and gadgets version

---

android-whitelist.json
ios-whitelist.json

Se agrega la libreria nueva app-theme, la cual puede ser utilizada solo en mp-configurer y webkit
- - #....

Add library app-theme

---

android-whitelist.json

fix CashRails granular projects

---

android-whitelist.json

Este PR actualiza las versiones de la nueva librería de MoreLikeThis a 1.0.0 en Android por su primer release. Se agrega también la fecha de expiración en el módulo viejo en search.
- - #....

Update MLT to 1.0.0 in android

---

ios-whitelist.json

Update CcapSDUI to 1.X.X
- - # NO TICKET

[NO-TICKET] Update CcapSDUI to 1.X.X

---

ios-whitelist.json

Update major version and add expires to wishlists lib
- - #....

Update wishlists major version to 2.x.x

---

android-whitelist.json

Updated twilio voice sdk

---

android-whitelist.json

Add polycards Android version
...
- - #....

Add polycards Android version

---

ios-whitelist.json

Update reglas granularidad lib externas

---

cross-kmp-allowlist.json

Se agrega la libreria datetime de kotlin
- - #....

Add datetime KMP

---

android-whitelist.json
scripts/check_version_pattern.rb

Se agrega excepción a la lib de bitmovin ya que el plugin no permite detectar mediante sus regex como valida a la version 3.43.1+jason

[Fix] Added exclude

---

android-whitelist.json

* Se realiza bump version de las libs de Instore
https://mercadolibre.atlassian.net/browse/ISQRM-590

[ISQRM-590]Bump Instore libs

---

android-whitelist.json

Cambio la 6.6.70 por la 6.6.71 porque la 70 no se llegó a prender en prod por un problema, actualmente está la 6.6.69
- - #....

[Feature] Updates usdk to version 6.6.71

---

android-whitelist.json

[Selling Framework] Update SF library and add expires the old version.

---

android-whitelist.json

...
Se agregan los aumentos de version correspondientes a las libs de `tetris` y dentro de estas se hicieron cambios de 
estructura y se crearon nuevas libs

Major libs tetris version 2.+

---

android-whitelist.json

Se agrega la nueva lib para la utilizacion google sing in, que se va a estar utilizando en el Login.
https://mercadolibre.atlassian.net/browse/LGN-969
- - #....

Se agrega la Nueva librería Social Login Android

---

android-whitelist.json

Fix sobre este [PR](https://github.com/mercadolibre/mobile-dependencies_whitelist/pull/2814), estaban duplicados los modulos
- - #....

Replicated dependencies solved

---

android-whitelist.json

Added Search project to Coil Compose allowlist. It is necessary in order to load icons in the Actions section from a url.
- - #....

Added Search project to Coil Compose allowlist

---

ios-whitelist.json

Updated ios-whitelist.json for PxTokenization

---

ios-whitelist.json

Added PW to pure layout's list

Added PW to pure layout's list

---

.circleci/config.yml
cross-kmp-allowlist.json

Enable CI checks for KMP

---

android-whitelist.json

Update Internal Library AppMonitoring
- Add instrumentation module v5
- Expires v4
- - #....

Update AppMonitoring Modules

---

android-whitelist.json
ios-whitelist.json

Add Everest Canvas :D

---

android-whitelist.json

Necesitan agregar la lib nuevamente la CameraView temporalmente, para cumplir con una vulnerabilidad:
La idea que proponen es agregar el permiso temporal en la allowlist, publicar la lib y volver a eliminarla.
La lib cameraView esta agregada en las apps, asiq no es que nos cambia algo realmente
Estan trabajando en otra version donde tienen CameraX, donde ya van a eliminar definitivamente la dependencia. (ETA :fin de agosto)
podemos seguir esto con : Gonza Macedo
- - #....

Fix temp camera view

---

android-whitelist.json
ios-whitelist.json

Se agrega en la whitelist un nuevo repo del equipo de HomeWallet (Mercado Pago), Horizontal Cards.
- - #....

[ADDED] Horizontal Cards to whitelist

---

ios-whitelist.json

- Add MorelikeThis to iOS whitelist
- Se agrega expire a v 0.1 de test y a la del submodulo de Search, ya que esta nueva version reemplaza el subspec.
- - #....

Add MorelikeThis to iOS whitelist && More projects for VerticalsCore

---

android-whitelist.json

Bump up Devices SDK lib to v8
- - #....

Bump up Devices SDK v8

---

android-whitelist.json

Bump Cash Version

---

android-whitelist.json

Bump DAMI UI Components

---

android-whitelist.json

Se realiza un bump de InAppUpdates a 9.+ y mlInAppUpdates a 11.+
- - #....
- [x ] No

Bump inappupdates to 9 and mlinappupdates to 11.+

---

android-whitelist.json

Add Soloader warning
...
- - #....

Add Soloader warning

---

android-whitelist.json
ios-whitelist.json

Added new FeatureFlag SDK to whitelist iOS: https://github.com/melisource/fury_ff-sdk-ios
Added Melidata to use app-services libraries: https://github.com/melisource/fury_melidata-sdk-android/blob/master/melidata-sdk/build.gradle#L60-L61
- - #....

Added FFSDK to iOS whitelist and added Melidata to services

---

android-whitelist.json

Fix Melidata granular dependendy
- - #....

Fix melidata granular dependency

---

android-whitelist.json

Se agrega nuestro nuevo modulo el cual es una migracion del modulo remedies con arquitectura MVVW.
- - #....

Add person validation lib

---

android-whitelist.json

Se cambió el nombre del modulo por sugerencia, para separar iniciativas en el repo hi-android
- - #....

Update name module

---

android-whitelist.json

DAMI UI is a soon-to-be-deleted lib that's meant only for the lib moneyinv2-android, no other lib should use it and support will not be given. This change reinforces that.
- - #....

Granularity for DAMI UI

---

ios-whitelist.json

New libs Transfers
`Para más información visitar [Wiki.](https://sites.google.com/mercadolibre.com/mobile/arquitectura/allowlist)`
Add new libs Transfers [DATD-387](https://mercadolibre.atlassian.net/browse/DATD-387) 
[DATD-387]: https://mercadolibre.atlassian.net/browse/DATD-387?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[T. Definitions] [iOS] [DATD-387] Add new libs

---

ios-whitelist.json

Como parte del proceso de deprecado de MLCharts, se incluye CreditsUIComponents a las dependencias granulares de DGCharts.
- - #....

Add CreditsUIComponents to granular dependency of DGCharts

---

android-whitelist.json

Bump digital_account_components
Se cambia la version de da componets a la version de 10.+

Update android: digital_accounts_components

---

android-whitelist.json

This PR creates a new Multiwidget Android version. The Multiwidget is a small Design Driven UI, born in [HomeWallet](https://github.com/melisource/fury_home-wallet-android) but was migrated to a new repository to allow other repositories use it. It's gonna be used by homewallet, mp_search, home_banking and other future repos.
- - #....

[ADDED] Added Multiwidget android version

---

ios-whitelist.json

Because the first release of this library has not been done yet, we are going to have some versions until 1.0.0. This is why we are requesting a change from 1 to 0 for major.
MP Home team
- - #....

Change MPSearch major to 0

---

android-whitelist.json

CashRails version to 12
Cashin version to 21
Cashout version to 18
- - #....
- [ ✅ ] Mercado Pago

Bump Cash libraries

---

android-whitelist.json

This PR adds a new version to home api to include some major changes.
- - #....

[CHANGED] Adding new version to Home api

---

android-whitelist.json

Add granularity to external libs v005

---

ios-whitelist.json

En el equipo de Demanda Engagemente (Home, Recos, Listas, Cards) estamos creando una nueva librería con el fin de encapsular otras libs cross demanda que se han creado en el tiempo.
Inicialmente esta nueva lib sera usada desde MLHome para la iniciativa de Gamification.
- - #....

Add MLEngagementComponents library

---

android-whitelist.json

Se hace la actualización de la versión de Da Components, de 10.+ a 11.+

Updated da components version 10 to 11

---

android-whitelist.json

Se encontró un issue con transitividad y no es posible utilizar la librería en restclient, se quitará momentáneamente hasta que este resuelto desde controles de calidad.
- - #....

Remove transitive Dns

---

android-whitelist.json

Se encontró un issue con transitividad y no es posible utilizar la librería zxing, se quitará momentáneamente hasta que este resuelto desde controles de calidad.
- - #....

delete transsitive field to avoid ci error

---

ios-whitelist.json

Se agrega version 1 DemandCore en iOS y pasa a ser productiva.
- - #....

Change to production demand core

---

android-whitelist.json

Bump version Performance Tools

---

ios-whitelist.json

Add Polycards granular SwiftUI

---

android-whitelist.json

We need Lottie dependency for the new opening animations of the paid market app
- - #....

[MODS-4994]: Allows granular to Security UI

---

android-whitelist.json

We need Lottie dependency for the new opening animations of the paid market app
- - #....

[MODS-4994] Rename-package-allowed

---

android-whitelist.json

Posponemos la fecha de vencimineto para la version Legacy del repo ml-scanner-android. El Q que viene estaremos migrando a v15 a los integradores de esta version y podrá eliminarse
- - #....

ml_scanner v12 expire date changed

---

ios-whitelist.json

[Added] udpate omsdk 1.5.0

---

android-whitelist.json

Lib que será utilizada para inicializar la wallet de manera organizada.
- https://web.furycloud.io/help/tickets/18486.

Adding flow orchestrator - startup commons

---

android-whitelist.json

- Se granula version de Login para Google GMS recapchat
- - #....

Se granula version de Login para Google GMS recapchat

---

ios-whitelist.json

Add AndesIntegrations granular AppTheme for rebranding andes mp
- - #....

Add AndesIntegrations granular AppTheme

---

android-whitelist.json

- Add okio to 3.0.0
- Add caverock svg 1.4 (only for canvas - using for decode svg format)
- Add exifinterface 1.3.6 (only for canvas - using for compose feature)
- Add vectordrawable 1.1.0 (only for canvas - using for compose feature)
- Add accompanist-drawablepainter 0.30.1 (only for canvas - using for compose feature)
- - #....

Add new libs for Canvas Android

---

android-whitelist.json

Se actualiza la librería external de Modiface
- #131900

[VERTICALES-437] Upgrade version of Modiface dependency

---

android-whitelist.json

- Canvas is added to be able to use annotations.

Add canvas to annotations granulary

---

android-whitelist.json

- Add canvas to app-compat-resources granularity

Add canvas to appcompat-resources granulary

---

android-whitelist.json

add new library faceValidation:
```
{
"group": "com\\.mercadolibre\\.android\\.authfacevalidation",
"name": "facevalidation",
"version": "mercadolibre-1\\.\\+|mercadopago-1\\.\\+"
},
```
Se utiliza para la autentificación de rostro para lo que son los segundos factores, ahora de loguearse a la cuenta o intentar hacer algun cambio de seguridad. 
Login y reauthentication son los que consumen esta libreria.

Add new library FaceValidation

---

android-whitelist.json

Se necesita granular para el repositorio de login y de authentication el modulo de play-services-mlkit-text-recognitio. Ya que lo esta utilizando por transición en estos modulos.
```
ERROR: The following dependencies are not allowed:
- (Unauthorized) com.google.android.gms:play-services-mlkit-text-recognition:17.0.1 --> Unauthorized imports were made, on the following classes: LoginPlanner.java, GoogleApiProvider.kt, LoginManager.java, CredentialsResolver.java, LoginDeepLinkActivity.java, SMSBroadcastReceiverHandler.java, SMSBroadcastReceiverHandler.java, SMSBroadcastReceiverHandler.java, SMSBroadcastReceiverHandler.java, LoginRecaptchaClient.java, LoginRecaptchaClient.java, LoginRecaptchaClient.java, LoginRecaptchaClient.java, LoginRecaptchaClient.java, LoginRecaptchaClient.java, …
```

Login y Authentication granulado en play-services-mlkit-text-recognitio

---

android-whitelist.json

Se agrega namespace al bloqueo de transitividad de mlkit text recognition

Fix text recognition transitivity

---

android-whitelist.json

Eliminamos transitividad de MLKit hasta entender mejor el error reportado en el canal de slack

remove mlkit transitivity

---

ios-whitelist.json

[Added] udpate omsdk 1.5.1

---

android-whitelist.json

Se eliminan librerias que estaban como granularidad en mlkit que se agreagaron por error.

Fix granularity

---

android-whitelist.json

Add Transfers Components Offlinefirst module
Add expires to transfers_components
- - #....

[ADDED] Transfers Components Offlinefirst module

---

android-whitelist.json

Correct granular project to use security-crypto

---

android-whitelist.json

update name module qrcode kotlin granular block

---

android-whitelist.json

Se extiende la fecha de vencimiento para la lib Firebase perf.
- - #....

Update firebase perf expire

---

android-whitelist.json

New Jetpack Compose early adopter.

[Feature] Added money-out to Jetpack Compose granular dependencies

---

android-whitelist.json

Debido a una serie de errores al usar la dependencia de MLT dentro de VPP, se agrega en este PR una forma nueva de la dependencia como posible arreglo del error generado en el CI de vpp.
- - #....

Add new MLT dependency definition

---

ios-whitelist.json

Add StartupInitializerConfig lib in whitelist

Add StartupInitializerConfig lib

---

android-whitelist.json

Este PR postpone la fecha de expiración del módulo de MLT en search para evitar el bloqueo de VPP mientras se mergea el PR de la migración.
- - #....

Postpone MLT expiration to 28th of October

---

android-whitelist.json

Since release 2.1.4 from ConstraintLayout theres a fix need to allow animations in new Home Diagonal about new Banking Tabs
https://shield.adminml.com/requests/4539474

Bump constraint-layout minor version

---

android-whitelist.json

-Se hace update de la fecha de expiración de RxJava hasta Q1 R3
- - #....

Update expiration rx java libs

---

android-whitelist.json

Como parte de la [migración "Todos a V15"](https://docs.google.com/document/d/16Z6LXOAZ_ck-gBJhQM3NdYrnpjs5vKltkKbxy3gzd7E/edit#heading=h.ab7bim1runfn) sobre ml_scanner-android, procedemos a cambiar los flavors del repo para:
- Unificar los actuales mercadopago / mercadolibre [rebranding]
- Tener un nuevo flavor que utilice MLKit17 en lugar de MLKit18 como lo hace el de mercadopago.
Una vez finalizada, la version 12.+ del scanner ya no tendria efecto.
- - #....
Para más información sobre …

ml-scanner-android flavors changed

---

android-whitelist.json

- Se agrega el proyecto de PrepApp, a la estructura granular de room y preferences
- - #....

Prepapp Granular projects config

---

android-whitelist.json

- Se agrega el proyecto de PrepApp, a la estructura granular de room y preferences
- - #....

Prepapp Granular projects config - II

---

android-whitelist.json

Add Security Preferences in Cryptography granular projects
- - #....

Add Security Preferences in Cryptography granular projects

---

ios-whitelist.json

Se actualiza la librería external de Modiface

[VERTICALES-438] - Upgrade modiface dependency ios

---

ios-whitelist.json

Se agrega la lib de ml-engagement-component a la lista de granularidad de lottie.
El cintillo de Gamification en homes tendra una animación para la cual queremos usar lottie
https://github.com/user-attachments/assets/690a20c6-c592-4119-b826-76c67301a490
- - #....

Se agrega la lib engagement-component a la lista de granularidad de lottie IOS

---

android-whitelist.json

Se agrega Mercado Pago - Login para que pueda usar las commons de Startup.

Added mercadopago-login on startup commons

---

.github/pull_request_template.md

Este PR tiene el objetivo de modificar el Template de PR, para solicitar la creacion de Tickets y en el caso de Android solicitar la adicion de Builds Scan

Template Update

---

README.md

Se agregan tablas al Readme para mostrar la informacion de una forma mas amigable

Tables in Readme

---

.github/pull_request_template.md

Genero este PR para que eliminemos las URLs internas hasta que tengamos la Allowlist en Privado !

Url Update

---

ios-whitelist.json

Added `IspMpos` to iOS whitelist in order to have it as a dependency in `MPConfigProvider`

Added IspMpos to iOS whitelist

---

android-whitelist.json

Explicación de las librerías:
Prometheus: es el módulo que encierra la solución mpoc
Los aar que se subieron a Nexus requieren dos librerías más para la comunicación con los métodos que exponen:
slf4j: Se requiere esa versión específica por indicación del proveedor del kernel.
Neovisionaries: esta librería es para manejo de Currency según el país. Internamente nosotros la mapeamos a la que Meli tiene, pero la librería del kernel sólo recibe Neovisionaries.
Molten y Lava: son los dos AAR subidos a Nexus.
Build Scans:
Sin librerías
https://gradle.adminml.com/s/zizqne4rl4jjo
Con Librerías
https://gradle.adminml.com/s/6plz3cwnpilzi
[Se deja documento de seguimiento](https://docs.google.com/document/d/1hX7hiT9CqMOptKw9GRUP-COA9pw3Znx-fclCYQUVH_w/edit?tab=t.0#heading=h.2y3hcf2sb6yn)
Dependencia …

Library dependencies for Mpoc - contactless

---

android-whitelist.json

Add new version to Transfers Components modules
Add expires to transfers_components
Dependencia Externa con Artefacto en Nexus [ [Android](https://shield.adminml.com/c/4181) - [iOS](https://shield.adminml.com/c/4192) ]
Dependencia Externa [ [Android](https://shield.adminml.com/c/4588) - [iOS](https://shield.adminml.com/c/4589) ]
- # [Ticket Link]()
Para más información sobre el uso controlado mirar [Readme](https://github.com/mercadolibre/mobile-dependencies_whitelist/blob/feature/update- …

[ADDED] New version Transfers Components Modules

---

android-whitelist.json

Se agregan las dependencias relacionadas a **Bouncy Castle**
- "org.bouncycastle:bcprov-jdk15to18"
- "org.bouncycastle:bcpkix-jdk15to18"
- #[4557668]( https://shield.adminml.com/requests/4557668)
- #[4560435]( https://shield.adminml.com/requests/4560435)

Add bouncy castle dependency for mpoc in house

---

android-whitelist.json

- update remote config
- update ignite
- # [Ticket Link]()
Para más información sobre el uso controlado mirar [Readme](https://github.com/mercadolibre/mobile-dependencies_whitelist/blob/feature/update-readme-frontend-cross/README.md#support-for-granu …

[feature] update ff versions

---

android-whitelist.json

Se necesita añadir Cashin a la granularidad de la librería `Places` ya que anteriormente lo consumíamos a través de la librería DA-Components, librería que estamos deprecando de nuestros repositorios, por lo tanto ya no podemos utilizar Places.
Lo utilizamos ya que manejamos flujos de mapas en nuestro repo
- - #....
Para más información sobre el uso controlado mirar [Readme](https://github.com/mercadolibre/mobile-dependencies_whitelist/blob/feature/update-readme-frontend-cross/README.md#s …

added: cashin to places granular project

---

ios-whitelist.json

Se agrega el subspec Core
...
- # [Ticket Link]()
Para más información sobre el uso controlado mirar [Readme](https://github.com/mercadolibre/mobile-dependencies_whitelist/blob/feature/update-readme-frontend-cross/README.md#support-for-granular-depen …

Add EverestCanvas Core subspec iOS

---

android-whitelist.json
ios-whitelist.json

Se agrega canvas android solo para nuestro usuario early adopter, esta version ya se esta usando actualmente en ambas apps y vimos que no tuvo impacto negativo.
- - # https://mercadolibre.atlassian.net/browse/EVEREST-3886

Add canvas android

---

android-whitelist.json

Se agrega la nueva lib de checkout shipping "BuyingflowShipping", que forma parte del conjunto de nuevas librerías que nacen con la migración de MLCheckout v5 a v6.
- # [Ticket Link]()
Para más información sobre el uso controlado mirar …

Se agrega la lib de BuyingflowShipping a la whitelist de Android

---

cross-kmp-allowlist.json

Se actualiza la version de ktor
- https://shield.adminml.com/requests/4543838

Bump ktor - KMP

---

android-whitelist.json

Este PR introduce modificaciones al archivo `android-whitelist.json` para actualizar y ampliar la lista de excepciones para el NativeSdkIntegrations de smartpos. Los cambios realizados son los siguientes:
1. **Expiración del SDK miniapp-2:**
- Se agregó la propiedad `"expires": "2024-12-31"` para el grupo `com\\.mercadolibre\\.android\\.point_integration_sdk` y la versión `miniapp-2\\.+`. Esto establece una fecha de expiración para esta versión del SDK.
2. **Adición de soporte para miniapp-3:**
- Se agregó un nuevo registro para la versión `miniapp-3\\.+` bajo el mismo grupo `com\\.mercadolibre\\.android\\.point_integration_sdk`. Esto permite la inclusión y validación de versiones más recientes del SDK en futuras integraciones.
Estos cambios aseguran que la aplicación pueda seguir …

[SMARTI-1699] add support to version 3 to native Sdk Integrations

---

android-whitelist.json

Se actualiza la versión de Search a la `21.X` y Polycards a la `1.X` agregando una lista de permitidos para su uso
Para más información sobre el uso controlado mirar …

Update Search and Polycards versions

---

android-whitelist.json

- Se agrega el proyecto `"com.mercadolibre.android.transferscheckout"` a los módulos de `transfers_components`
Para más información sobre el uso controlado mirar [Readme](https://github.com/mercadolibre/mobile-dependencies_ …

[ADDED][DATX1-2061] Added transferscheckout project to granular projects for transfers_components modules

---

android-whitelist.json

...
Se agrega flux client como dependencia granular a la librería firebase-core
Para más información sobre el uso controlado mirar [Readme](https://github.com/mercadolibre/mobile-dependencies_whitelist/blob/feature/update-r …

Added flux client to firebase-core

---

android-whitelist.json

Eliminamos este bump, para evitar confusiones y hasta que se puedan hacer las pruebas correspondientes

Remove constraint-layout 2.1.x

---

ios-whitelist.json

El cambio agrega polycard 1.0.0 y además le coloca fecha de expiración a las versiones 0.x
[ ] Leí el contenido de este Pull Request y acepto que recibiré seguimiento del mismo una vez su contenido esté completo.

Update polycard 1.x iOS

---

android-whitelist.json

Se actualiza la versión de digital account components a la versión 13, la versión 12 se pone fecha de expiración el viernes primero de noviembre 
[ ] Leí el contenido de este Pull Request y acepto que recibiré seguimiento del mismo una vez su contenido esté completo.

Updated  digital accounts components version

---

android-whitelist.json

- Seteamos la `transitivity` para no exponer clases de Koin.
Para más información sobre el uso controlado mirar [Readme](https://github.com/mercadolibre/mobile-dependencies_whitelist/blob/feature/update-readme-frontend-cros …

Add "transitivity: false" to Koin dependencies

---

.github/pull_request_template.md

Se actualiza el Template del PR

---

android-whitelist.json

This reverts commit af9cbc0c74759fdb4a87ff056e4371fa963a4242.

Revert "Add "transitivity: false" to Koin dependencies (#3006)"

---

ios-whitelist.json

El cambio agrega MLSearch a las dependencias que contienen SwiftUI para que sean compatibles.
Para más información sobre el uso controlado mirar [Readme](https://github.com/mercadolibre/mobile-dependencies_whitelist/blob/fe …

Update MLSearch SwiftUI

---

android-whitelist.json

- Fix libraries modules used in the WMS Ar Measures project.
<table>
<thead>
<tr>
</tr>
</thead>
<tbody>
<tr>
</tr>
<tr>
</tr>
</tbody>
</table>
> <ul><li>- [ ] Leí el contenido de este Pull Request y acepto que recibiré seguimiento del mismo una vez su contenido y el de los Tickets solicitados esté completo. </li></ul> 
<details>
<table>
<thead>
<tr> …

Update Ar Measures libs modules

---

ios-whitelist.json

Con ese PR se pretende dar por deprecada la librería de livecommerce.
Deprecar la librería de livecommerce
<table>
<thead>
<tr>
</tr>
</thead>
<tbody>
<tr>
</tr>
<tr>
</tr>
</tbody>
</table>
> <ul><li>- [X] Leí el contenido de este Pull Request y acepto que recibiré seguimiento del mismo una vez su contenido y el de los Tickets solicitados esté completo. </li></ul> 
<details> …

Removed Livecommerce library.

---

android-whitelist.json
cross-kmp-allowlist.json
ios-whitelist.json

- Desde la iniciativa de Real Time, no vamos a utilizar finalmente Ktor ni KMP. Vamos a simplemente disponibilizar dos librerías nativas, que no precisan librerías externas.
[https://github.com/melisource/fury_rtc-android](https://github.com/melisource/fury_rtc-android)
[https://github.com/melisource/fury_rtc-ios](https://github.com/melisource/fury_rtc-ios)
<table>
<thead>
<tr>
<th><sub>Android</sub></th>
<th><sub>iOS</sub></th>
</tr>
</thead>
<tbody>
<tr>
<td><sub>Dependencia Externa con Artefacto en Nexus</sub></td>
<td><a href="#"><sub>Upload an artifact Android to Repository</sub></a></td>
<td><a href="#"><sub>Upload an artifact iOS to Repository</sub></a></td>
</tr>
<tr> …

Add realtime native libs and remove rtc-mobile with Ktor

---

android-whitelist.json

> Se suma la version major del repo mp_search
<table>
<thead>
<tr>
</tr>
</thead>
<tbody>
<tr>
</tr>
<tr>
</tr>
</tbody>
</table>
<details>
<table>
<thead>
<tr> …

Bump mp_search major to 2.+

---

android-whitelist.json

Se extiende la fecha de expiración de la librería `com.mercadolibre.android.isp_sf` versión 5.+.
<table>
<thead>
<tr>
</tr>
</thead>
<tbody>
<tr>
</tr>
<tr>
</tr>
</tbody>
</table>
<details> …

[Selling Framework] Allow SF library version 5.+

---

ios-whitelist.json

Necesitamos consumir el subspec StartupOrchestrator desde MPIntroScreen
<table>
<thead>
<tr>
</tr>
</thead>
<tbody>
<tr>
</tr>
<tr>
</tr>
</tbody>
</table>
<details>
<table>
<thead>
<tr> …

[FEATURE] Allow startup dependency from intro screen

---

android-whitelist.json

<table>
<thead>
<tr>
</tr>
</thead>
<tbody>
<tr>
</tr>
<tr>
</tr>
</tbody>
</table>
> <ul><li>- [X] Leí el contenido de este Pull Request y acepto que recibiré seguimiento del mismo una vez su contenido y el de los Tickets solicitados esté completo. </li></ul> 
<details>
<table>
<thead>
<tr> …

Scanner expire dates modified

---

android-whitelist.json

> La libreria de Moneyout requiere capturar los contactos de la agenda que la libreria de Contacts maneja, la libreria existia en el pasado en la whitelist, pero por alguna razón fue removida.
se agrega para continuar con el feature de input unificado
<table>
<thead>
<tr>
</tr>
</thead>
<tbody>
<tr>
</tr>
<tr>
</tr>
</tbody>
</table>
> <ul><li>- [X] Leí el contenido de este Pull Request y acepto que recibiré seguimiento del …

Added contacts lib into whitelist

---

android-whitelist.json

No podemos mergear cambios a canvas por no tener el propio repo en la granularidad.
Necesitamos meter un breaking change que debe entrar antes de que algun equipo comience a usar canvas 2.+, cosa que validamos ya que no se usa.
<table>
<thead>
<tr>
</tr>
</thead>
<tbody>
<tr>
</tr>
<tr>
</tr>
</tbody>
</table>
Hoy, ya.
> <ul><li>- [ ] Leí el contenido de este Pull Request y acepto que recibiré seguimiento del …

Update canvas to 3.+

---

android-whitelist.json

> To fix issue on CI. The old version of Constraint Layout was deprecated today en theres any other to replace it
<table>
<thead>
<tr>
</tr>
</thead>
<tbody>
<tr>
</tr>
<tr>
</tr>
</tbody>
</table>
<details> …

Bump constraintlayout from 2.0.4 to 2.1.4

---

android-whitelist.json

Cashin to 23.0.0
Cashout to 20.0.0
CashRails to 15.0.0
Hacemos bump de nuestras librerías, no poseen fecha de expiración ya que solo la consumen libs nuestras.
<table>
<thead>
<tr>
</tr>
</thead>
<tbody>
<tr>
</tr>
<tr>
</tr>
</tbody>
</table>
> <ul><li>- [ ] Leí el contenido de este Pull Request y acepto que recibiré seguimiento del mismo una vez su contenido y el de los Tickets solicitados esté completo. …

Bump cash_rails to 15

---

android-whitelist.json

Estamos añadiendo [esta](https://github.com/melisource/fury_location-android) nueva libreria a Everest-android
La idea de esta nueva libreria es generar una migracion masiva, vamos a migrar el modulo de Location Commons a esta nueva lib para todos los usuarios que anteriormente usaban  Location de Commons. Ya sean libs, fronts o apps
<table>
<thead>
<tr>
</tr>
</thead>
<tbody>
<tr>
</tr>
<tr>
</tr>
</tbody>
</table>
> …

Location lib added

---

android-whitelist.json

Se agrega el repositoruio de mpoc para poder hacer uso de la librería de dynamic feature, esto para ser utilizado en el poroto de tap to everything 
<table>
<thead>
<tr>
</tr>
</thead>
<tbody>
<tr>
</tr>
<tr>
</tr>
</tbody>
</table>
> <ul><li>- [ ] Leí el contenido de este Pull Request y acepto que recibiré seguimiento del mismo una vez su contenido y el de los Tickets solicitados esté completo. </li></ul> …

Agregar  mpoc a granular projects de la libreria dynamic_features 

---

android-whitelist.json

Se agrega un nuevo modulo llamado SecurityConfig
Hay libs que necesitan implementarla para adquirir solamente configuraciones o informacion que se encuentran y/o encontraran en este nuevo modulo
<table>
<thead>
<tr>
</tr>
</thead>
<tbody>
<tr>
</tr>
<tr>
</tr>
</tbody>
</table>
> <ul><li>- [x] Leí el contenido de este Pull Request y acepto que recibiré seguimiento del mismo una vez su contenido y el de los Tickets solicitados …

Add securityConfig module

---

ios-whitelist.json

Se agrega una nueva librería desde el equipo de Instore Payments para el manejo de la funcionalidad de Proximity Reader.
<table>
<thead>
<tr>
</tr>
</thead>
<tbody>
<tr>
</tr>
<tr>
</tr>
</tbody>
</table>
<details> …

Add new library IspTtp.

---

android-whitelist.json
ios-whitelist.json

> Se agrega el módulo para Android de una librería nueva que se está desarrollando llamada Rabbit Hole.
> **Sobre Rabbit Hole:** Para aumentar la interacción de los usuarios y reducir la dependencia de las búsquedas directas, estamos desarrollando un componente de recomendaciones infinitas. Partiendo del producto que el usuario está visualizando, también aprovecharemos su historial de navegación y comportamiento para mostrar contenido relevante más allá de la categoría actual.
Esto permitirá una experiencia de exploración fluida y personalizada, guiando a los usuarios a descubrir productos que podrían no haber considerado inicialmente, fomentando un ciclo continuo de descubrimiento que los mantenga inmersos dentro del ecosistema del marketplace.
<table>
<thead>
<tr> …

[VERTICALES-1381] add rabbit hole versions

---

android-whitelist.json

El nombre del paquete que usará las librerías de compose tenía un underscore (_) en lugar de un punto (.) y esto producía un error a la hora de validar si el paquete puede usar compose o no.
<table>
<thead>
<tr>
</tr>
</thead>
<tbody>
<tr>
</tr>
<tr>
</tr>
</tbody>
</table>
> <ul><li>- [ ] Leí el contenido de este Pull Request y acepto que recibiré seguimiento del mismo una vez su contenido y el de los Tickets …

[NO-TICKET] Fix package name for contactless - Mpos

---

android-whitelist.json

Se hicieron ajustes para que el bottomSheet del Calculator soporte la nueva navegación tab-bar.
El nuevo experimento de navegación afecto nuestra experiencia del calculator para bulkSale.
La firma para la integración con VPP cambio, por ese motivo se sube el mayor.
<table>
<thead>
<tr>
</tr>
</thead>
<tbody>
<tr>
</tr>
<tr>
</tr>
</tbody>
</table>
> <ul><li>- [x] Leí el contenido de este Pull Request y acepto …

New version home and industries

---

ios-whitelist.json

La lib AndesUIDraftModal expiro en agosto de 2023 ([PR](https://github.com/mercadolibre/mobile-dependencies_whitelist/pull/1974/files) en el que se realizo la expiración), antes de removerla en este PR se hicieron las siguientes validaciones:
Se valido que ya no tiene usos a través de [sourcegraph](https://mercadolibre.sourcegraph.com/search?q=%28%5Cbimport+AndesUIDraftModal%29++-repo:fury_ui-modal-ios&patternType=regexp&sm=0) (El repo [MLQuestions](https://github.com/melisource/fury_myml-questions-ios) esta deprecado y no se usa desde 2022)
Adicionalmente se validaron las dependencias en ML y MP, se encontró que se usaba en ML a través de una lib desactualizada, se ajusta la versión y dependencia en este [PR](https://github.com/melisource/fury_mercadolibre-ios/pull/10953/files)
Estos …

Remove AndesUIDraftModal

---

android-whitelist.json

> Debido a un freez que tuvimos en la migracion tenemos que ampliar la fecha de deprecado de EventBus
<table>
<thead>
<tr>
</tr>
</thead>
<tbody>
<tr>
</tr>
<tr>
</tr>
</tbody>
</table>
<details>
<summary>Sección obligatoria para Dependencias …

EventBus expiration date changed because of a freez

---

android-whitelist.json

Se bumpea la lib app theme. No hace falta mantener la version 0 ya que era una version de prueba. Solo se va a utilizar la 1.+.
<table>
<thead>
<tr>
</tr>
</thead>
<tbody>
<tr>
</tr>
<tr>
</tr>
</tbody>
</table>
<details>
<summary>Sección obligatoria …

Bump app theme

---

android-whitelist.json

Se agrega granularidad para smart pos previamente aprobado [aqui](https://github.com/mercadolibre/mobile-dependencies_whitelist/pull/3054)
<table>
<thead>
<tr>
</tr>
</thead>
<tbody>
<tr>
</tr>
<tr>
</tr>
</tbody>
</table>
> <ul><li>- [ ] Leí el contenido de este Pull Request y acepto que recibiré seguimiento del mismo una vez su contenido y el de los Tickets solicitados esté completo. </li></ul> 
<details>
<summary>Sección …

App theme granularity

---

android-whitelist.json

Actualización de las librerías VPP/QABD en la allowlist y agregar Granularidad.
<table>
<thead>
<tr>
</tr>
</thead>
<tbody>
<tr>
</tr>
<tr>
</tr>
</tbody>
</table>
<details>
<table> …

Update version VPP/QABD

---

ios-whitelist.json

Estamos en fase de _early adopters_ para la librería de CrabDI, y vamos a comenzar a usarla en la lib MLLocation (ambas libs pertenecen al equipo de Frontend Platform - Everest)
<table>
<thead>
<tr>
</tr>
</thead>
<tbody>
<tr>
</tr>
<tr>
</tr>
</tbody>
</table>
> <ul><li>- [ ] Leí el contenido de este Pull Request y acepto que recibiré seguimiento del mismo una vez su contenido y el de los Tickets solicitados esté completo. …

Add MLLocation to CrabDI's allowed granular projects

---

ios-whitelist.json

Se agrega una nueva librería desde el equipo de Instore Payments
<table>
<thead>
<tr>
</tr>
</thead>
<tbody>
<tr>
</tr>
<tr>
</tr>
</tbody>
</table>
<details>
<table>
<thead>
<tr> …

Add new library TTE.

---

android-whitelist.json
ios-whitelist.json

Deprecado de la librería de Google Analytics en Android y en iOS
<table>
<thead>
<tr>
</tr>
</thead>
<tbody>
<tr>
</tr>
<tr>
</tr>
</tbody>
</table>
> <ul><li>- [X] Leí el contenido de este Pull Request y acepto que recibiré seguimiento del mismo una vez su contenido y el de los Tickets solicitados esté completo. </li></ul> 
<details>
<table>
<thead>
<tr> …

Added exp date for analytics dependency on both iOS and Android.

---

ios-whitelist.json

La librería TensorFlowLiteSwift es usada en nuestro modulo viejo MLRemedies, el cual estamos migrando a PersonValidation, por eso necesitamos poder habilitar el uso de la lib en este nuevo Proyecto.
<table>
<thead>
<tr>
</tr>
</thead>
<tbody>
<tr>
</tr>
<tr>
</tr>
</tbody>
</table>
> <ul><li>- [ ] Leí el contenido de este Pull Request y acepto que recibiré seguimiento del mismo una vez su contenido y el de los Tickets …

Add PersonValidation to TensorFlowLiteSwift

---

android-whitelist.json

Estamos migrando la aplicación auth-remedies-mobile-android a la aplicación person-validation-android la cual ya esta utilizando CameraX. Estamos rollouteados para algunos sites, pero con una baja en la conversión en comparación a la vieja app. Ya que la migración además de un cambio de estructura de proyecto, tuvo un rediseño de experiencia de usuario, lo que queremos hacer de acá a fines de Q4, es probar la nueva estructura y rediseño con la cámara vieja, para poder determinar si la baja en conversión es dada por la experiencia nueva o por el cambio de componente de cámara. 
La idea es implementar CameraView en una versión y luego quitarla y poder obtener números de esta versión.
La aplicación remedies, se va a deprecar a fines de Q4, realizando la eliminación completa del proyecto en …

Add CameraView to person validation

---

android-whitelist.json

> This PR adds a new version to multiwidget to include some major changes. The Multiwidget is a small Design Driven UI, born in [HomeWallet](https://github.com/melisource/fury_home-wallet-android) but was migrated to a new repository to allow other repositories use it.
<table>
<thead>
<tr>
</tr>
</thead>
<tbody>
<tr>
</tr>
<tr>
</tr>
</tbody>
</table>
> <ul><li>- [x] Leí el contenido de este Pull Request y acepto que recibiré …

[CHANGED] Adding new version to multiwidget android

---

android-whitelist.json

[ISPMPOS-3261] change zdefend version from 1.+ to 1.0.1
Agregar la version productiva de la libreria, la cual tiene las mimas dependencias que la version 1.0.0 solo que tiene un patch productivo.
<table>
<thead>
<tr>
</tr>
</thead>
<tbody>
<tr>
</tr>
<tr>
</tr>
</tbody>
</table>
> <ul><li>- [x] Leí el contenido de este Pull Request y acepto que recibiré seguimiento del mismo una vez su contenido y el de los Tickets solicitados …

[ISPMPOS-3261] change zdefend version from 1.+ to 1.0.1

---

ios-whitelist.json

La nueva version de SecureInputs sube su min target a iOS 15. 
<table>
<thead>
<tr>
</tr>
</thead>
<tbody>
<tr>
</tr>
<tr>
</tr>
</tbody>
</table>
> <ul><li>- [ ] Leí el contenido de este Pull Request y acepto que recibiré seguimiento del mismo una vez su contenido y el de los Tickets solicitados esté completo. </li></ul> 
<details>
<table>
<thead>
<tr> …

add SecureInputs 2.0 and add expire date to version 1.0

---

ios-whitelist.json

Add HomeWallet granular AppTheme for rebranding MP
<table>
<thead>
<tr>
</tr>
</thead>
<tbody>
<tr>
</tr>
<tr>
</tr>
</tbody>
</table>
<details>
<table>
<thead>
<tr> …

Add HomeWallet granular AppTheme

---

android-whitelist.json

Rename package remedy-challenge in TTE granular project
Custom test:
<table>
<thead>
<tr>
</tr>
</thead>
<tbody>
<tr>
</tr>
<tr>
</tr>
</tbody>
</table>
<details>
<table>
<thead>
<tr> …

[CCAP] Feat: Rename package in TTE granular project

---

ios-whitelist.json

New version rule engine.
<table>
<thead>
<tr>
</tr>
</thead>
<tbody>
<tr>
</tr>
<tr>
</tr>
</tbody>
</table>
<details>
<table>
<thead>
<tr> …

[CHO] Feat: new version rule engine.

---

ios-whitelist.json

> Se agrega a la whitelist la dependencia de add-to-cart-ios parauso interno
<table>
<thead>
<tr>
</tr>
</thead>
<tbody>
<tr>
</tr>
<tr>
</tr>
</tbody>
</table>
> <ul><li>- [ ] Leí el contenido de este Pull Request y acepto que recibiré seguimiento del mismo una vez su contenido y el de los Tickets solicitados esté completo. </li></ul> 
<details>
<table>
<thead> …

Add to cart ios granular dependecy

---

.github/pull_request_template.md

Se elimina el formato de HTML del template y se cambia a estandares de MD para reducir el codigo. Aun no se resuelve el issue de los checkbox pero de esta forma es mas simple cambiarlos manualmente

Template Upgrade

---

android-whitelist.json

> Complete me!
<details>
| <sub>Dependencia Externa con Artefacto en Nexus</sub> | <a href="#"><sub>Upload an artifact Android to …

[FEATURE][WMSMOB-1215] Auth0 - Expiration date removal

---

ios-whitelist.json

Como parte de nuestra iniciativa de EverestCanvas, la idea es centralizar la carga de recursos locales a traves de ella, haciendo uso de la api de AppTheme para obtener el theme actual.
<details>
| …

added EverestCanvas to AppTheme granularity - iOS

---

ios-whitelist.json

Se quita la dependencia por no usarse en el repositorio de [IspMpos](https://github.com/melisource/fury_isp-mpos-ios) 
Fue removida de los podspec para la versión 2.360.0 de la wallet y 1.16.0 de IspMpos
<table>
<thead>
<tr>
</tr>
</thead>
<tbody>
<tr>
</tr>
<tr>
</tr>
</tbody>
</table>
> <ul><li>- [x] Leí el contenido de este Pull Request y acepto que recibiré seguimiento del mismo una vez su contenido y el de los Tickets …

[ALL][FIX][ISPMPOS-3409] - Remove UIImage-ResizeMagick due lack of use for IspMpos

---

android-whitelist.json

Actualmente se ha creado una versión del SDK, en la cual estamos buscando unificar el concepto de main apps y mini apps en un solo, denominado SmartApps.
<table>
<thead>
<tr>
</tr>
</thead>
<tbody>
<tr>
</tr>
<tr>
</tr>
</tbody>
</table>
<details> …

Added v4.+ in the whitelist to integration SDK

---

android-whitelist.json
ios-whitelist.json

>Necesitamos agregar una fecha de expiración a la libreria android:ui que se encuentra deprecada.
<details>
| <sub>Dependencia Externa con …

Add expire date to ML UI - Android

---

android-whitelist.json

Se agrega fecha de expiración y ultima version de OMSDK
[Ticket de shield](https://shield.adminml.com/requests/4479241)
| <ul><li>- [x] <sub>Externa</sub></li></ul> | <sub>Libreria desarrollada por un externo a Meli. (Google, Airbnb, otros). Requiere Ticket de Shield.</sub> |
<details>
| …

Added expire date to OMSDK

---

ios-whitelist.json

> Complete me!
> <ul><li>- [X] Leí el contenido de este Pull Request y acepto que recibiré seguimiento del mismo una vez su contenido y el de los Tickets solicitados esté completo.</li></ul>
<details>
| <sub>Dependencia Externa con Artefacto en Nexus</sub> | <a href="#"><sub>Upload an artifact Android to …

Add AccountRelationships granular dependency

---

android-whitelist.json

Como parte de nuestra iniciativa de EverestCanvas, la idea es centralizar la carga de recursos locales a traves de ella, haciendo uso de la api de AppTheme para obtener el theme actual.
<details>
| …

Added EverestCanvas to AppTheme granularity - Android

---

ios-whitelist.json

Se habilita el de AndesUI/SwiftUI y MLNavigation/SwiftUI para AdvancedDebuggerTech.
Uso de swiftUI.
> Complete me!
<details>
| …

Enabled AdvancedDebugger for SwiftUI

---

android-whitelist.json

Se agrega Advanced Debugger a la white list de compose en Android.
Poder usar declarativo en Advanced Debugger Android.
> Complete me!
<details> …

Enable declarative for Advanced Debugger on Android.

---

android-whitelist.json

This PR include IPC connection library. With this library any project is able to connect with any HAL (Hardware Android Layer) or Platform services.
<details> …

[SMART-8209] Include IPC connection library

---

ios-whitelist.json

Add TransfersComponents to granular SwiftUI
> Complete me!
<details> …

Add TransfersComponents to granular SwiftUI

---

android-whitelist.json

Se hace bump de la lib de cashin a `25.+`
<details>
| <sub>Dependencia Externa con Artefacto en Nexus</sub> | <a href="#"><sub>Upload an …

Bump cashin to 25.+

---

android-whitelist.json

https://shield.adminml.com/requests/4849142
Esta versión incluye cambios en API y corrección de fixes.
<table>
<thead>
<tr>
</tr>
</thead>
<tbody>
<tr>
</tr>
<tr>
</tr>
</tbody>
</table>
<details>
<summary>Sección obligatoria para Dependencias …

Update twilio voice

---

android-whitelist.json

Se agregan dependencias que faltaban. 
[PR](https://github.com/mercadolibre/mobile-dependencies_whitelist/pull/3095) anterior.
Poder usar declarativo en Advanced Debugger Android.
> Complete me!
<details>
| …

Added dependencies for Advanced Debugger.

---

android-whitelist.json
ios-whitelist.json

Vamos a deprecar el uso de PINRemote en iOS, del lado de Android vamos a deprecar Picasso y Fresco impulsando el uso de Everest Canvas
[Fury docs de Everest Canvas](https://furydocs.io/everest-canvas-ios/latest/guide/#/)
<details> …

Added deprecated date and description for Fresco, Picasso and PINRemote - Android/iOS

---

android-whitelist.json

Queremos agregar la lib de livedata-runtime compose para que los equipos que hoy dia ya usan Livedata puedan transformar esos objetos a estado con facilidad.
| <ul><li>- [x] <sub>Externa</sub></li></ul> | <sub>Libreria desarrollada por un externo a Meli. (Google, Airbnb, otros). Requiere Ticket de Shield.</sub> |
<details>
| Descripción | Android | …

Added livedata-runtime compose

---

android-whitelist.json

Subir la version disponible de Cashout a 22.+
<details>
| <sub>Dependencia Externa con Artefacto en Nexus</sub> | <a href="#"><sub>Upload an …

[Cashout] Bump Cashout to 22.+

---

android-whitelist.json

> Complete me!
> <ul><li>- [X] Leí el contenido de este Pull Request y acepto que recibiré seguimiento del mismo una vez su contenido y el de los Tickets solicitados esté completo.</li></ul>
<details>
| <sub>Dependencia Externa con Artefacto en Nexus</sub> | <a href="#"><sub>Upload an artifact Android to …

Feature: add account relationships android to cryptography

---

android-whitelist.json

New Andesui core added to whitelist
We have incorporated a new module in andes called core that allows to centralize common code for imperative and declarative. This core module will be used in the Integrations Repository to allow the configuration of currencies. …

Feature Andesui core added to whitelist

---

android-whitelist.json

> Was added "com.mercadolibre.android.mercadopago_login" into allow list from Theme granullarity
<details>
| <sub>Dependencia Externa con …

Added mercadopagologin into Theme granullarity

---

android-whitelist.json

Se agrega Vpp para permitir granularidad en canvas-compose.
<details> …

Added vpp to granular project for canvas-compose

---

android-whitelist.json

Add Flavor to card form and remedy
Keep names from previous versions plus the flavors
> Complete me!
<details>
| <sub>Dependencia Externa con …

[CCAP] Feat: Add Flavor to card form and remedy

---

ios-whitelist.json

Se agrega cart manager iOS para alinearnos con Android.
Agregar Cart Manager para manejar el servicio de carrito.
> Complete me!
<details>
| …

Add Cart Manager

---

android-whitelist.json

Para usar el cash smartpos nos pide tener esta librería en allow
<details> …

[CASH] Added smartpos lib as allow

---

.pre-commit-config.yaml
ios-whitelist.json

Se crea un nuevo módulo de la dependencia de Add To Cart iOS para darle soporte en Polycard
Responsables:
@kealonso_meli
@carlomunoz_meli
> Complete me!
> <ul><li>- [X] Leí el contenido de este Pull Request y acepto que recibiré seguimiento del mismo una vez su contenido y el de los Tickets solicitados esté completo.</li></ul>
<details> …

AddToCard project

---

ios-whitelist.json

> Se necesita actualizar el OMSDK a su última versión.
<details> …

[Changed] - OMSDK 1.5.2.

---

android-whitelist.json

- Add release/8.0 version for Selling Framework permission.
- Set expiration for release/7.0 for SellingFramework.
- Remove expiration for release/5.0 for SellingFramework.
<details>
| Descripción | Android …

Update android-whitelist.json for SellingFramework to release/8.0

---

android-whitelist.json

add timber
> Complete me!
<details>
| <sub>Dependencia Externa con Artefacto en Nexus</sub> | <a href="#"><sub>Upload an artifact Android to …

Add timber temporally for mpos team

---

android-whitelist.json

Debemos liberar un cambio para terminar de soportar el rebranding en nuestro proyecto auth-remedies-mobile-android,
dado que el mismo es una lib que migramos a person-validation-android, sigue contando con el uso de CameraView (la nueva lib usa CameraX), por lo que no podemos sacar nuevos releases si no esta whitelisteada la lib de CameraView. Por esto es que nuevamente se pide extender la lib de CameraView para poder sacar el release con el cambio de soporte de rebranding.
Hoy en día la migración esta prendida para MLC y MLU al 100% y estamos en etapa de rollout para MLA. La idea es matar CameraView lo antes posible en este Q.
| <ul><li>- [x] <sub>Interna</sub></li></ul> | <sub>Libreria/modulo desarrollado in-house en base al ecosistema de …

Extend CameraView lib for ReBranding

---

.github/pull_request_template.md

> La adición de una dependencia requiere de varios análisis con el objetivo de que ninguna librería impacte de forma negativa al Stack Tecnológico de Meli. Tener en cuenta que el proceso realizado por Platform Updates puede ofrecer los siguientes plazos:
Librerías internas: 1 - 2 días  
Librerías externas: 1 - 2 semanas / más en casos excepcionales  
> Este plazo comienza una vez la solicitud está completa y sus comentarios sean resueltos.
> Complete me! …

Template Update - ETA

---

android-whitelist.json

És necesario agregar la biblioteca interna Crabdi al proyecto mp-gadgets
<details>
| <sub>Dependencia Externa con Artefacto en Nexus</sub> | …

Add crabdi dependency to mp-gadgets project

---

android-whitelist.json

add mp-gadgets in the crab-di-android group

---

android-whitelist.json

Para usar el cash smartpos nos pide tener esta librería en allow.
**NOTA:** Previamente se habia hecho merge del PR donde se agregaba esta lib pero se hizo con el path:
`com.mercadopago.android.cash_smartpos` pero el correcto es `com.mercadolibre.android.cash_smartpos`
| <ul><li>- [X] <sub>Interna</sub></li></ul> …

[CASH] Added smartpos lib as allow in cashin

---

ios-whitelist.json

SpGlobeWrapper update
| <ul><li>- [x ] <sub>Interna</sub></li></ul> | <sub>Libreria/modulo desarrollado in-house en base al ecosistema de Meli.</sub>                    | …

SpGlobeWrapper update to 2.0.0

---

ios-whitelist.json

Bump IspSf Version to 8.0.0

---

android-whitelist.json

> Se incrementa la version major de la biblioteca mp_search
| <ul><li>- [ ] <sub>Externa</sub></li></ul> | <sub>Libreria desarrollada por un externo a Meli. (Google, …

Bump mp_search major to 3.+

---

android-whitelist.json

Feature/Add Melidata SDK to granular project

---

android-whitelist.json

> Bumpeamos el major de nuestra lib
<details>
| <sub>Dependencia Externa con Artefacto en Nexus</sub> | <a href="#"><sub>Upload an artifact …

[HomeWallet] Bumped toolkit major and added expire date

---

android-whitelist.json

Debido a los cambios de rebranding, se decidió subir el major de las librerías debido a que estos pueden ser breaking changes 
> Complete me!
| <ul><li>- [ ] …

Update android mpos instore payments majors versions 

---

android-whitelist.json

> Agregar Yoshi como dependencia de nuestra lib meliphone voip
<details> …

added yoshi to whitelist

---

android-whitelist.json

Se agrega security_preferences como proyecto granular para que pueda implementar AppTheme
| <ul><li>- [ ] <sub>Externa</sub></li></ul> | <sub>Libreria desarrollada por …

Se agrega security_preferences como proyecto granular

---

android-whitelist.json

En nuestra iniciativa necesitamos hacer uso de AppThemeManager de la libreria com.mercadolibre.android.app_theme para poder obtener el theme actual
> Complete me!
| …

added nfc payments to app_theme

---

ios-whitelist.json

Se remueve la dependencia PPMagnesWrapper ya que fue eliminada.
| <ul><li>- [ ] <sub>Externa</sub></li></ul> | <sub>Libreria desarrollada por un externo a Meli. …

Remove PPMagnesWrapper dependency

---

ios-whitelist.json

Necesitamos que la librería de CcapSDUI pueda agregar AndesUI/SwiftUI como dependency para que no falle el linter de la CI
> Complete me!
| <ul><li>- [ ] …

Adding CcapSDUI as early adopter of Andes/SwiftUI subspec
