ios-whitelist.json
Se agrega CHTCollectionViewWaterfallLayout con un tag de expire que dice la fecha en la que ve a expirar, no está implementado el expire pero por ahora está bueno para tener saberlo nostoros, idealmente deberia autoexpirarse (borrarse del json) el expire está en el formato YYYY-MM-DD (ISO 8601)
=> se agrego CHTCollectionViewWaterfallLayout

ios-whitelist.json
Se agrega la dependencia a MLShippingComponents con vencimiento en diciembre
MLReturns esta dependiendo de MLShippingComponents por unas constantes.
Se planea mover las constantes al SDK y así remover la dependencia
=> Add MLShippingComponents Dependency

android-whitelist.json
Downgradeamos la versión de Rx2 a Rx1 porque MercadoPago usa Rx1 y la idea es incluir en Q3 nuestro módulo en MercadoPago. El costo de desarrollo que implica migrar MercadoPago a Rx2 es mucho mayor, por lo tanto optamos por un downgrade en nuestro módulo.
=> Downgrade from Rx2 to Rx1

android-whitelist.json
Agregamos la lib de kotlin después de una prueba de concepto para ver como impactaba la lib y el 
Agregamos la lib y desarrollamos una sección de la nueva home nativa completamente en kotlin (desarrollo + tests), y luego comparamos el size de una versión release con el código actual contra el código actual + experimento de homes con este cambio.
El aumento en size es de aprox ~150kb y hay que tener en cuenta que este aumento no solo es por el feature hecho en kotlin, sino por la nueva home nativa, por lo que el size final es mucho menor.
before | after
-- | --
=> Add Kotlin lib to whitelist

ios-whitelist.json
Se actualiza la dependencia de lottie-ios a la version 2.5.0.
Este cambio es necesario porque las versiones anteriores tenían un issue en las animaciones: https://github.com/airbnb/lottie-ios/issues/429
Tal y como menciona la issue nos afecta en el siguiente caso:
Desde la pantalla de start del shake, si el usuario se dirige a "términos y condiciones" y luego vuelve, la animación se queda freezada.
=> Update Lottie to 2.5.0

ios-whitelist.json
Se agrega el carácter `$` en las regex de las versiones, para evitar falsos positivos.
Por ejemplo, para MLCart, `~>2.6.7` matcheaba, cuando solo debería matchear con el formato `~>2.x`
=> Se corrigen las regexs de versiones

ios-whitelist.json
De ahora en mas va a ser la 2.* asi no obligamos a los fends a fijar una version. Es el unico en ese caso.
=> Se saca el fix de version de lottie

android-whitelist.json
Se agrega la libreria de picasso temporalmente a la whitelist hasta que se encuentre disponible la nueva libreria de mapas.
=> Add picasso temporarly

android-whitelist.json
Se añade kotlin-android-extensions-runtime a la whitelist de Android
=> Se añade kotlin-android-extensions-runtime a la whitelist de Android

ios-whitelist.json
With the latest [PureLayout 3.1.2](https://github.com/PureLayout/PureLayout/releases/tag/v3.1.2), they have support for building Safe Areas constraints.
=> Updating PureLayout to 3.1.2

ios-whitelist.json
Se agrega MLCard, componente del header de alta de tarjeta (crédito/débito).
Será utilizado en conjunto con cho y px con el fin unificar la experiencia de los usuarios y reducir el mantenimiento de código.
=> Add MLCard

ios-whitelist.json
Se agregan las dependencias necesarias para los fends de MP.
- MPSDK
- SDWebImage
- RazzleDazzle
- MPDynamicSkeleton
- ISO8601DateFormatter
- FSQCollectionViewAlignedLayout
- FBSDKCoreKit
- FBSDKLoginKit
- RSKImageCropper
- MPSignUpLibs
- Realm
*** Realm es una de las libs que deberían tener fecha de expiración, pero por el momento no tenemos definido cuando.
=> Whitelist mp

android-whitelist.json
- Se agregan las dependencias de MP
- Se saca la version fija  de "android-image-cropper", por que en MP estamos usando una mas nueva. Quedamos en que por el momento liberamos hasta que analizemos con los fends de meli que tieenen una version vieja una fecha estimada para que se migren, asi le seteamos un expire.
=> Whitelist mp android

ios-whitelist.json
MLNetworking and MLMelidata regular expressions are fixed. 
MLNetworking last version is [0.14.1](https://github.com/mercadolibre/mobile-ios_networking/releases/tag/0.14.1)
MLMelidata last version is [0.3.10](https://github.com/mercadolibre/melidata-sdk_ios/releases/tag/0.3.10)
=> Fixing melidata and networking dependencies

android-whitelist.json, ios-whitelist.json
Agrego la dependencia para las libs del CP Navegación:
fury_navigationcp-android/ios: Lib que contiene al behaviour opcional
fury_ui-navigationcp-android/ios: Lib que contiene al HUB de direcciones que se dispara al clickear el CP navegación.
=> Android/iOS - CP Navegación

android-whitelist.json
En MP necesitaríamos consumir el modulo Header de la Wallet de Meli
=> Agrego el Header de MlWallet a la whitelist de Android

android-whitelist.json
Se actualiza el nombre del módulo "locationData" a "shipping-address", ya que la lib fue renombrada para mejorar la legibilidad.
=> Actualización nombre de módulo de CP Navegación

ios-whitelist.json
Se revierte el major de MLMapComponent porque no era necesario el breaking change y se borro la version 3.0.0.
=> Update Map version on whitelist.

android-whitelist.json
Those dependencies are required for the module https://github.com/mercadolibre/fury_mobile-android-dagger.
=> Whitelist Dagger dependencies for Android

android-whitelist.json
This a miss from previous PR: https://github.com/mercadolibre/mobile-dependencies_whitelist/pull/122
=> Added dagger-android-support

android-whitelist.json
Agregando a la whiteList la dependencia de SafetyNet Attestation para Site Security. Para la integración de esta nueva API a ATR.
=> safetynet dependencie

android-whitelist.json
Agrego a la whitelist el converter de gson de retrofit.
En principio lo vamos a wrappear en flox dado que necesitamos tener un control muy especifico sobre la serializacion de objetos.
=> Whitelisted retrofit's gson-converter

ios-whitelist.json
Se realiza el cambio de la version de la lib MPSDK de iOS a 10.0
=> Cambio de la version de la lib MPSDK iOS

android-whitelist.json
- Se agrega 'com.mercadolibre.android.classifieds.listing' al whitelisting de dependencias.
- Se elimina la versión en la entrada de DynamicFlow, para soportar futuras major.
=> Added Android 'com.mercadolibre.android.classifieds.listing'

android-whitelist.json
Se agregar la lib [fotoapparat](https://github.com/RedApparat/Fotoapparat) para el manejo de cámaras custom. En particular a ser usado por el equipo de Remedies (IV)
=> add fotoapparat

android-whitelist.json, ios-whitelist.json
En esta librería estamos extrayendo lógica que usamos en checkout para interpretar reglas de decisión que mandamos del BE al cliente. Esto nos sirve para definir flujos a seguir.
Esta lib representa el primer paso en un plan de componetización general de checkout apps. Ya que los futuros componentes harán uso de este primero.
Esto incluso podría ser utilizado por otras librerías en Meli.
=> Agrega la lib de Rule Engine

android-whitelist.json
Actualizo versión de observable recycler view en las dependencias.
En search-android se utiliza la 1.6.0, y en sdk la 1.5.1, lo que hace que falle el circle en search-android
=> Update observable recycler view whitelist version

android-whitelist.json
Se actualiza la versión de lottie para evitar errores en algunas animaciones de Point en la aplicación de Mercado Pago. Se habló con los equipos afectados para avisar de este cambio.
=> Subir la versión de lottie para evitar errores en Point

ios-whitelist.json
- Se agrega `RxSwift` 4.4.1 como dependencia permitida de iOS
=> RxSwift added to iOS dependencies whitelist

android-whitelist.json
GridLayout v7 includes several improvements that were backported from the latest versions of Android.
=> Add GridLayout Support Lib

android-whitelist.json
Necesitamos agregar a la whitelist el modulo shortlist de activities.
Este modulo es un listado reducido de pocas actividades, que en principio sera importado desde el modulo que se esta creando para la nueva home de MP.
Shortlist se integrará en la home de manera similar a como se integra el skeleton, con un include en el xml y la correspondiente instancia de la clase (no es una android activity).
=> add shortlist activities

android-whitelist.json
Este modulo es un storage de activities. Permite almacenar activities obtenidas con un apiCall o realtime activities.
Al recibir, las guarda y avisa mediante el eventbus portable a quien se suscriba (listado corto y largo de activities).
El modulo facilita el guardado de realtime activities y la creación de un listado único. Será importado por el modulo de Point, ya que ellos son (al momento) los que insertan realtime activities.
=> add activities storage module

android-whitelist.json
En mobile-android estamos forzando a 27.1.0, así que tiene sentido actualizar aquí la versión de las deps para todos.
=> Updated Support Libs Versions

android-whitelist.json
Whitelisteamos la 27.1.0 sin dejar de aceptar la 27.0.2 para evitar romper los builds de los distintos fends.
=> Added Support Lib 27.1.0 without replacing the previous one

android-whitelist.json
Agrega a la whitelist el módulo de API de Secciones de la nueva Home de MercadoPago. El módulo incluye las interfaces que se deben implementar para poder integrarse en la Home.
=> Add Wallet Home API module

ios-whitelist.json
Se agrega a la whitelist de iOS la API de Secciones de la nueva Home de MP en donde se incluyen las interfaces que cada sección debe implementar para incorporarse a la nueva Home.
Se agregan también tres de las secciones que van a ser parte de la nueva Home: 
- Activities: `OperationDetail/Commons` y `OperationDetail/RealtimeActivities`
- Mapa QR: `InStoreHomeSections`
- Cross Selling: `MPMerchEngine`
=> Add Wallet Home API and Home Sections

ios-whitelist.json
Se modifica en la whitelist de iOS las versiones de las dependencias necesarias para la nueva Home Wallet de MP.
=> Changed to null version on new home wallet dependencies

ios-whitelist.json
RxBlocking nos permite detenernos y esperar a que se cumpla una condición determinada. En mi caso lo utilizo para testeo de RxSwift ya que se trabaja con observables y podemos esperar a que se emita el primer elemento y así compararlo con un resultado esperado. El peso aproximado de la lib es de 400 KB.
=> Added RxBlocking to iOS dependencies

android-whitelist.json
Se fixea un punto faltante en mercadolibre/mobile-dependencies_whitelist#195
=> Fix de "Update Whitelist including LibSodium-JNI"

android-whitelist.json, ios-whitelist.json
Se agrega dependencia de las nuevas librerías MLCharts para iOS y Android.
Estas libs las desarrollamos desde el team Tools For Sellers San Luis + Santa Fe, para que los demas equipos puedan utilizar graficos con estilo meli.
Adjunto algunas capturas de la lib funcionando en el nuevo modulo de Dashboards nativo.
| <img width="302" alt="Screen Shot 2019-05-09 at 11 55 08" src="https://user-images.githubusercontent.com/5194168/57463570-6ab9f500-7251-11e9-8572-ecf235b36956.png"> | <img width="289" alt="Screen Shot 2019-05-09 at 11 55 37" src="https://user-images.githubusercontent.com/5194168/57463571-6c83b880-7251-11e9-9b11-950a800fe1ce.png"> |
|-|-|
=> Add MLCharts dependencies

android-whitelist.json
Se agrega la dependencia de la nueva lib de charts. Que va a reemplazar mlcharts. Se hizo un refactor muy grande, y prácticamente se construyó nuevamente la lib para soportar casos de tablets.
También se agrega librería de calendarios, para utilizar en el flujo de dashboard Tablets.
=> Added charts dependency

android-whitelist.json
Se elimina (nuevamente) la Support Library vieja de la whitelist
=> Remove SL 27.X

ios-whitelist.json
No estaba la dependencia a `MercadoPagoSDKV4` (PX en iOS).
Esta dependencia se usa en varios fends (InStore, SinglePlayer, etc).
=> Se agrega dependencia a PX (MercadoPagoSDKV4)

android-whitelist.json
Este PR es para whitelistear la lib de adjust, la cuál va a ser agregada en un principio en la app de mp.
=> Add lib adjust to whitelist

ios-whitelist.json
Agrego MLHistory como dependencia en MLVPP, pero no estaba en la whitelist
https://circleci.com/gh/mercadolibre/fury_vpp-ios/2128
=> Add MLHistory to whitelist

ios-whitelist.json
Quitamos RxBlocking ya que según las recomendaciones de RxSwift, esta lib solo debe ser usada en ambientes de tests.
=> Removing rxblocking

android-whitelist.json, ios-whitelist.json
Agregamos librería de comparador de productos a la whitelist, la misma se importa desde vpp
=> Add Comparator lib to whitelist

android-whitelist.json
La version 2 de flox tiene un pequeño breaking change que ya fue corregido por los teams y nos coordinamos para entrar en este tren 9.60.
Faltó haber hecho este paso.
=> Whitelisted flox v2

android-whitelist.json
La traemos transitivamente (esta misma version para no generar problemas) por okhttp. La empiezo a traer manualmente porque la vamos a usar explicitamente (no via okhttp) en localstorage
=> Add okio to whitelist

android-whitelist.json
rollback bugsnag because the 4.18 uses androidx
=> rollback bugsnag version to 4.17.2

ios-whitelist.json
Vamos a pasar de major por la migración del MeliSDK.
=> Actualiza version de UINavigationCP iOS

android-whitelist.json
Agrego la nueva version de commons, permitiendo todavia la version anterior, por si hay algun configurer que falte actualizarse con esta version, pueda seguir funcionando.
=> add commons 14.+ and still allow the old version

ios-whitelist.json
### Descripción
- Se contempla `MLNotificationsHelpers` dentro de la whitelist
=> MLNotificationsHelpers

android-whitelist.json
Se agregan a la whitelist los módulos de Loyalty:
- Commons
- Webview
- Drawer 
Y la lib de datamanager
=> + Loyalty libs

ios-whitelist.json
- "MPThreeDS"
- "PXAddon"
_MPThreeDS esta pesando 295kb y depende de NdsThreeDS.framework que pesa 8,3 MB  y de ThreeDSCore.framework que pesa 2,4 MB. PXAddon esta pesando 90kb_
_Si, Mastercard esta impulsando el SDK de seguridad de 3-D Secure._
_Se esta cerrando el desarollo de la nueva version_
_Si, 3-D Secure es mantenida por Mastercard_
_17 de septiembre de 2019_
_NdsThreeDS y ThreeDSCore van a ser utilizadas por MPThreeDS y para el resto de los devs debería ser transparente los cambios que haya en futuros releases. El ownership va a ser el [equipo de PX](mailto:px_nativo@mercadolibre.com)_
_NA_
_No_
_No especifica ninguna_
_No especifica en la doc. Segun los plist, iOS 10_
_Principalmente en Brasil va a ser requerido el uso de esta libreria para poder hacer pagos con tarjetas_
- [*] …
=> Add 3DS and PXAddon to iOS whitelist

ios-whitelist.json
- FBSDKCoreKit `5.3.0`
- FBSDKLoginKit `5.3.0`
Esta lib con esta versión ya se está usando en `mobile-ios` donde no corre el lint de dependencias. 
Ahora necesito agregar la dependencia a la nueva lib de navegación y está fallando el lint, por lo que actualizo la whitelist. 
No se las razones por la que se utiliza la `5.3.0`, pero se está realizando una migración a la `v5.8.0` por una restricción de Apple. Este PR sería para poder utilizar la misma versión que está en la app hasta que se realice la migración.
=> Update FBSDK version to 5.3.0

ios-whitelist.json
- Se elimina MeliSDK
- Se quita dependencia duplicada (SmiSdk)
- Se quita MLShippingComponents (se debe utilizar por deeplink)
=> Se limpian dependencias duplicadas y deprecadas

android-whitelist.json
Se modificaron las whitelist de Analytics e UiComponents:
**Analytics:**
- Se agrega una caché de custom dimensions. Esta cache tiene como finalidad transformar un mapa de custom dimensions con key el nombre de la custom dimension a un mapa de custom dimensions con el id de la misma como key, teniendo en cuenta la plataforma (ml, mp) a la que pertenece la custom dimension. El listado de custom dimensions se puede encontrar en https://api.mercadolibre.com/ga/dimensions Para poder utilizar la caché es necesario incorporar el plugin com.mercadolibre.android.analytics.transform Se puede encontrar mas información acerca de como incorporarlo en el siguiente link.
**UI-Components**
**Nuevo:**
- Se depreca ActionBarComponent.Action. El mismo al ser un enum hace que no podamos guardar estado del …
=> Se modifica la whitelist para Analytics e UI Components [Android]

ios-whitelist.json
Se agregan las siguientes librerias:
- "MPBalance"
- "UIImage-ResizeMagick"
Las mismas están siendo utilizadas actualmente por el pod MPSDK, solo que no estaban whitelisteadas.
=> Added missing dependencies used by MPSDK

android-whitelist.json
- "com.google.android.play:core:1.6.4"
- El aar pesa 99kb 
- Mantenido por Google
- 24 de octubre de 2019
- El wrap se hace desde un behaviour en fury_in-app-updates-android
- Ninguna para este tipo de feature nativo
- No esta atado al startup
- Tiene Min API level 21. Para Min 21 se va a utilizar un alert nativo.
- Cuando hay una actualizacion opcional o mandatoria hoy en dia se muestra un alert nativo. La idea es mostrar un flow de google para medir si esto mejora la conversion.
- fury_in-app-updates-android
=> [Android] Se agrega com.google.android.play:core:1.6.4

README.md, android-whitelist.json
- "com.mercadolibre.android.navigationcp:navigationcp:3+"
- "com.mercadolibre.android.navigationcp:shipping-address:3+"
- "com.mercadolibre.android.uinavigationcp:addresshub:3+"
Se migran las imágenes a webp y se sube el minApiLevel
- Home, vip, cpg-supermarket, search
Van a ser notificados de la necesidad de updatear el major, mientras tanto se mantiene la versión actual.
=> Actualización versión navegaciónCP

ios-whitelist.json
Update del sdk de facebook a la 5.8.0
Apple está rechazando apps que contengan versiones del SDK de Facebook donde se utiliza UIWebView APIs y tenemos que updatearnos a la version 5.8.0 para que no nos rebote apple.
N/A
N/A
N/A
N/A
N/A
N/A
N/A
N/A
N/A
N/A
N/A
N/A
N/A
=> Facebook sdk 5.8.0

ios-whitelist.json
Se mantiene también la version anterior de firebase hasta que MP no se migre
=> Add firebase for mp fends not updated yet

ios-whitelist.json
Es una lib interna, que actualmente ya está en uso. Tiene lo referido a la unidad de negocio Cards. Cómo se usará como dependencia en otra lib, es que se requiere agregar a la whitelist.
=> MeliCards whitelist

android-whitelist.json
-"com.mercadolibre.android.inappupdates"
La lib pesa 104kb. 65kb son de codigo (pre-proguard), 35kb son del R de commons.
N/A
N/A
N/A
N/A
Nosotros somos los owners
N/A
Se va a agregar un nuevo Configurator para inicializar la variante en cada BE
N/A
N/A
Remplaza al bump actual para manejar updates de versiones inactivas.
Y maneja los updates opcionales usando la API de Google In App Updates o el bump actual para API<21.
Esta lib es cross app. La idea es que con una configuracion externa cualquier app pueda elegir las politicas de updates y luego setear los behaviours correspondientes en los lugares clave.
N/A
N/A
=> Fix en parseo de inappupdates

android-whitelist.json
Se agrega la versión 2.+ de carddrawer. La misma cambia su MinSdk a 19. 
Se agrega expiración para la versión 1.+ en caso de que necesiten los Fends sacar hotfixes de las versiones que actualmente estén en rollout. 
Ninguno. Salvo el cambio del minor solo trae modificaciones en layouts.
Mercado libre
Ayer
No
Usada por el equipo de Checkout y PX. Ambos trabajamos en conjunto para el release de esta lib. 
- [Checkout](https://github.com/mercadolibre/buyingflow-mobile_android)
- [PX](https://github.com/mercadopago/px-android)
=> Se actualiza la versión de la lib de card drawer

ios-whitelist.json
Actualicé la regex de MLDynamicModal para que soporte incluir el patch. 
Necesitamos esto para depender de una versión previa a la **0.3.0** de la lib, donde pasó a ser static. Si comenzamos a depender de esa versión, tenemos que migrar el pod (MPPoint) también a static y no forma parte del scope de la tarea que estamos intentando cerrar de dejar de depender del MPSDK.
=> Update MLDynamicModal regex

android-whitelist.json
- "com.mercadolibre.android.security:security_ui:mercadopago-2.+"
- Mercadopago
- 18/12/2019
- Tiene Min API level 19
- PX y MonetOut
- www.github.com/mercadolibre/mpmobile-android_wallet
En que apps impacta mi dependencia
=> Add version 2 security ui in whitelist

ios-whitelist.json
Creamos la nueva librería de modales que acompaña la iniciativa de Andes y necesitamos agregarla a la whitelist
https://github.com/mercadolibre/fury_ui-modal-ios
- "AndesUIDraftModal"
02/01/2020
No
_iOS 10 - iOS 13_
Actualmente estamos utilizando la lib para prender modales a los usuarios desde la librería de merchengine
=> adding MPUIModal iOS lib to whitelist

.github/pull_request_template.md
Modificamos el template del PR para empezar a forzar la completitud de la wiki de Mobile.
Hoy tenemos un montón de libs utilitarias, tanto internas como externas, y solo nosotros tenemos visibilidad de cuáles son.
Se suman devs y equipos nuevos todo el tiempo con lo cuál necesitamos tener la wiki lo más completa posible.
=> Agregamos al template del PR una pregunta para hacer explícito que haya documentación sobre la lib en la wiki de Mobile

android-whitelist.json
Reverts mercadolibre/mobile-dependencies_whitelist#386
porque hay equipos donde les esta fallando por no haber subido.
Tendríamos que revisar el impacto nuevamente y recién ahí actualizar.
=> Revert "Update journeyapps from 3.5 to 3.6"

android-whitelist.json
- "com.mercadolibre.android:apprater-mp:10.+"
En principio no debería afectar en el peso de la app ya que se encuentra actualmente en Mercado Pago y no estaba agregada en la whitelist. 
Requerimos agregar esta lib para poder incorporarla en el repo de instore.
Estas modificaciones afectan a que luego de un pago exitoso se envíe un evento a la lib de appRater y al pasar 7 días el usuario pueda puntuar la app. Esto aplica únicamente a MercadoPago pero como instore afecta a ambas apps necesitamos que se encuentre cargada en whitelist. 
Actualmente estamos teniendo un rating de 3.8 en Play Store desde el lado de Android, por ende buscamos agregar esta funcionalidad lo antes posible para subsanar esta situación. En primera instancia afecta a instore. A la brevedad esto será removido de instore …
=> add apprater mp for mp

ios-whitelist.json
Hola! Agrego la dependencia de jrswizzle, que ya la teniamos en MLUI, solo que no estaba sobre fury por lo que no tenia la whitelist. Ahora que está sobre fury y queremos hacer el release está fallando por que falta esta dependencia.
De todas maneras voy a:
- Revisar los casos que están usando esta lib si es realmente necesaria, para tratar de eliminarla
- Revisar si estos componentes no deberían estar en andes.
- "JRSwizzle"
https://github.com/rentzsch/jrswizzle
La lib ya está incluida en wallet pero era un modulo viejo MLUI
Nosotros.
No aplica, ya la tenemos
No aplica, ya la tenemos
No aplica, ya la tenemos
No aplica, ya la tenemos
No aplica, ya la tenemos
No aplica, ya la tenemos
No aplica, ya la tenemos
No aplica, ya la tenemos
No aplica, ya la tenemos
No aplica, ya la tenemos …
=> add jrswizzle

android-whitelist.json
- "com.mercadolibre.android.fluxclient:flux-client:3.+"
Imperceptible, se añade una nueva feature la cual incrementa el major de la lib.
Librería interna
Librería interna con 2 major previos y alrededor de un año de uso
Si, la librería es mantenida por el equipo de Credits
20/02/2020
Creemos que no es necesario un wrapper de la lib.
No.
No, no tiene código con NDK.
Ya estamos en API 19 en este repo y los repos que lo importan también.
Los casos de uso los comentamos en este [PR](https://github.com/mercadolibre/mobile-dependencies_whitelist/pull/343), dejo la referencia para no repetirlos.
=> Se agrega el nuevo major 3.+ de flux_client a la white list

android-whitelist.json
- Se agrega "com.mercadolibre.android.classifieds.credits" al whitelist de dependencias.
=> Classifieds Credits already added to white list

ios-whitelist.json
El modulo ya esta en uso. Ahora lo metimos en el configurer y lo sacamos del SDK y por ello no pasa CI xq necesita estar en la whitelist.
=> se agrega el modulo apprater

ios-whitelist.json
Se corrige la version de 3 (inexistente) a 0 que es la correcta.
=> fix version mpapprater

android-whitelist.json
- "com.google.android.material:material:1.0.0"
- "androidx.appcompat:appcompat:1.0.0"
Se corrige la version de Material y AppCompat para la migración a Android X. Según la documentación de Material, la version estable que reemplaza support es la [1.0.0](https://github.com/material-components/material-components-android/releases/tag/1.0.0), no la [1.1.0](https://github.com/material-components/material-components-android/releases/tag/1.1.0).
Relacionado con este thread de slack: https://meli.slack.com/archives/CSKLKAGC8/p1590090396002500?thread_ts=1589910342.446000&cid=CSKLKAGC8
No
No
Tiene Min API level 14
Si, es actualmente usada por Google.
Bastante madura
Si, es mantenida por una comunidad extensa e incluso es propiedad de Google
03/02/2020
Necesaria para la migración a Android X
- …
=> Fix Material & AppCompat Version

android-whitelist.json
- "androix.core:core-ktx:1.2.0"
La dependencia ya estaba agregada, pero estaba mal el JSON. Con este PR se soluciona.
=> Fixing ktx core version

ios-whitelist.json
Hacemos un rollback de ignite debido a que lo hicimos un dia de cierre y hay equipos sin migrar.
=> rollback ignite

android-whitelist.json
- "androidx.percentlayout:percentlayout:1.0.0"
("androidx.percentlayout:widget:1.0.0" no existe y por lo tanto tampoco se usa en ML ni en MP)
Se fixea el name de la dependencia de percentLayout para AndroidX, la cual se introdujo en el siguiente Pr: https://github.com/mercadolibre/mobile-dependencies_whitelist/pull/431
=> Fixing percentLayout name

android-whitelist.json
Actualizamos major de Recomendations por update a Gradle 5 y soporte a AndroidX.
26/05/2020
- https://github.com/mercadolibre/recommendations-android
=> add recommendations v7+ to whitelist

android-whitelist.json
Sube el major por la migracion a Android X en las libs de modales y merchengine.
**17/06/2020**
=> Bump Growth Tooling - Android X

context_whitelist.json
El repo de mydata tiene el ownership un equipo de shipping, pero el módulo de profile picture en Android lo tenemos nosotros.
Ya esta agregada la rule de automation.
Falta revisar la key de iOS a ver si se puede hacer algo o no.
=> Agregamos el contexto profile_picture que va a servir para Android

context_whitelist.json
Se agrega la key de iOS faltante en el contexto vacía
=> Fix: Profile Picture Context

android-whitelist.json
- "androidx.viewpager2:viewpager2:1.0.0"
[ViewPager2](https://developer.android.com/jetpack/androidx/releases/viewpager2)
No
No
_8 B_
_Si, viewpager2 es actualmente usada por una amplia comunidad de desarrolladores android._
_Sí, viewpager2 es mantenida por AndroidX_
_1 de abril de 2020_
_Proponemos agregar esta dependencia ya que es de uso general y en nuestro caso lo necesitamos para nuestra librería próxima a salir (Librería de chequeo de hardware para ventas de Seguros de Robo y Daño - Insurtech)._
[Trivial - Release Process Migration](https://github.com/mercadolibre/fury_insurance-check-mobile-android/pull/40)
- [insurance-check-mobile-android](https://github.com/mercadolibre/fury_insurance-check-mobile-android)
=> Dependency add: androidx.viewpager2:viewpager2: 1.0.0

android-whitelist.json, context_whitelist.json
- "com.mercadopago.android.da_components:da_components:1+"
No, son componentes visuales retutilizables que se reusan en varios modulos de digital accounts.
No
Nada en particular
Es un modulo reutilizable, en principio agrega 119 Kb. 
Conforme se comience a usar esta libreria, los proyectos que la usan reducirán su tamaño.
=> add da_components to whitelist

android-whitelist.json
Se actualiza la version de melidata-sdk. Estamos por la 6.12 y la whitelist tenia la 4.+. Esto funcionaba debido a un bug en el plugin de gradle ML
=> Melidata sdk update

android-whitelist.json
- "com.squareup.retrofit2:adapter-rxjava2:2.6.4"
- "com.squareup.retrofit2:converter-gson:2.6.4"
Se agregan estas dependencias que faltaban en la whitelist, debido a la migración de los proyectos a Androidx: https://sites.google.com/mercadolibre.com/mobile/gu%C3%ADas-y-problemas/gu%C3%ADas-de-migraci%C3%B3n/migraci%C3%B3n-android-x
=> Add retrofit version 2.6.4 for adapter-rxjava2 and converter-gson

android-whitelist.json
hago un downgrade de la version porque 15.+ es pre androidx, y a partir de la 16.x no compila el configurer hasta q se haga la migracion correspondiente.
=> Update mp sdk

android-whitelist.json
- Se agregan nuevas versiones de navigation-cp, address-hub y bookmarks
- Se actualiza dependencia de history. Actualmente se usa en home, vip, pdp y variations, las cuales ya usan o usarán la version 3.0 de history, para el tren de esta semana (v10.50)
=> Update history, bookmark and navigation-cp

android-whitelist.json
Se hace bump de la versión de Authentication de 13 a 14. Porque había quedado obsoleta
=> bump Authentication to 14

ios-whitelist.json
La regex ahora acepta un minor. Esto se hace porque MLCheckout no soporta todavía la versión 1.5.0 de CardDrawer, y necesitamos fijarla en 1.4.9.
=> Actualiza regex version CardDrawer

android-whitelist.json
Agregamos esta dependencia que deberiamos tener desde antes en el whitelist.
- "com.bugsnag:bugsnag-android-core:4.17.2"
- "com.bugsnag:bugsnag-android-core:4.22.3"
- [LeakCanary Configurator](https://github.com/mercadolibre/fury_ml-config-provider-android/pull/469)
=> Added bugsnag-android-core

android-whitelist.json
Dependencia que deberiamos tener:
*Dependencia actual de MP*: `com.mercadolibre.android:notificationcenter:mercadopago-5.2.1`
*Dependencia actual de ML*: `com.mercadolibre.android:notificationcenter:mercadolibre-5.0.0`
=> Added nofificationcenter 5.+ to whitelist

android-whitelist.json
- "com.mercadolibre.android:notificationcenter:mercadolibre-4.+"
- "com.mercadolibre.android:notificationcenter:mercadopago-4.+"
Necesitamos agregar la version 4.+ dado que es la ultima pre androidx y notificationcenter esta siendo utilizada en ml-config-providers que es un repo que no tiene androidx generando un conflicto. Esto queda así hasta sacar la dependencia de notificationcenter de los config-providers
=> Added 4.+ for pre androidx

android-whitelist.json
Dependencia que deberíamos tener:
Dependencia actual de MP: com.mercadolibre.android.instore:instore:mercadopago-7.+
Dependencia actual de ML: com.mercadolibre.android.instore:instore:mercadolibre-7.+
Necesitamos agregar esta dependencia para poder utilizar Local Storage (es necesario para poder agregar nuestro catalogo a config_providers)
=> adding In-Store repo to whitelist

android-whitelist.json
Se saca de la lista de dependencias la librería de Hint-Picker y SMS-Verification ambas son parte de https://github.com/mercadolibre/fury_auth-android-phone-validation y quedaron en desuso.
=> Remove Hint-Picker & SMS-Verification libs

android-whitelist.json, ios-whitelist.json
- Update de versión de `MLLoyalUIComponents` iOS hasta 2.9
- Update Android hasta v3.9
En la versión 2.0.0 incluimos cambios que rompen compatibilidad con nuestro componente de cross-selling y sus modelos.
=> Update MLLoyalUIComponents versions

android-whitelist.json, ios-whitelist.json
Se fixea whitelist para los módulos de checkout-sdk
El proyecto cuenta con los siguientes módulos, para que se tomen correctamente tuvimos que agregar cada uno a la whitelist
Todos los módulos parten del path
`com.mercadolibre.android.buyingflow.checkout` es por esto que no modificamos el archivo context
=> [Fix] cho-sdk dependencies for android

android-whitelist.json
Por el momento dejamos la 2.x y 3.x soportadas,
este cambio lo necesitamos para la migración a flox 5, luego de la migración enviaremos otro PR eliminando la versión 2.x
No
No
Mismo impacto que la version 2.x
Ya esta configurado desde antes
Ya esta configurado desde antes
Ya esta configurado desde antes
Es una librería compartida entre el checkout y mis compras
- [Migracion a flox 5](https://github.com/mercadolibre/fury_buyingflow-mobile-android/pull/4767)
- [example fend](https://github.com/mercadolibre/fury_buyingflow-mobile-android)
- [ X] Mercado Libre
- [X ] Ya existe, no tengo que agregar ni modificar nada.
=> Sumamos la version 3 de la librería de componentes

android-whitelist.json
- com.mercadolibre.android.uicomponents:10.0.0
- com.mercadolibre.android.configuration.provider: 14.0.0
- com.mercadolibre.android.navigation:5.0.0
Necesitamos subir los major porque se migro a AndroidX y Flox5.
=> Bump uicomponents, config-provider, navigation-menu

android-whitelist.json
Debido a que los releases hace rato están saliendo con la versión 1.3.0 de Coroutines se propone asumir esto y permitir el uso de la versión 1.3.0.
Mirando la resolución de las dependencias de las apps:
**En paralelo, se propone que las apps de ML y MP traigan la dependencia y fuercen la versión de las Coroutines.**
=> Updated Coroutines Version to 1.3.0

android-whitelist.json
Se realizó la migración de Android X en Andes, por lo que se aumento el major.
=> Bump version Andes

context_whitelist.json
Este PR agrega las siguientes dependencias a la context whitelist:
- `com.mercadolibre.android.nfcpayments.core`
- `com.mercadolibre.android.nfcpayments.flows`
- `com.mercadolibre.android.nfcpayments.cardwidget`
- `com.mercadolibre.android.nfcpayments.hce-sdk`
=> NFC Payments Context Keys

android-whitelist.json
- "androidx.appcompat.appcompat:1.2.0"
Agrego a whitelist esta version de appCompat que ya estamos utilizando en Wallet, pero me rompe el PR cuando actualizamos repo de AndesUI.
=> Whitelist appCompat version 1.2.0

android-whitelist.json
- "com.google.zxing:core:3.3.2"
_No, Zxing:core no requiere inicialización en el `Application`_
Sem bump 47,1 MB com lo bump 47,2 MB
=> bump version zxing 3.3.2

ios-whitelist.json
Se actualiza la version de JRSwizzle. La version 1.1.0 actualmente en la whitelist no existe en el repositorio de CocoaPods. Solo esta publicada la version 1.0, [ver repositorio de CocoaPods](https://github.com/CocoaPods/Specs/tree/master/Specs/7/b/3/JRSwizzle)
Al mismo tiempo, al revisar las apps se esta usando la version 1.0 a pesar de no ser valido por la whitelist.
- MLUI
- MPTracking
=> Fix JRSwizzle version

android-whitelist.json
- `com.mercadolibre.android.nfcpayments.core`: this is the library providing support for NFC Payments. It's intended to be used by other modules to, for example, check the availability to make NFC Payments. This library also wraps de HCE SDK API, so consumers don't get coupled to SDK-specific classes.
- `com.mercadolibre.android.nfcpayments.flows`: this is the module containing the functional flows of the NFC Payments feature. It declares the activities and layouts and uses a MVP architecture. It is intended to be accessed via deep linking from other parts of the App.
- `com.mercadolibre.android.nfcpayments.card-widget`: this library provides the UI component to display a card-like item in the Banking section of the Home screen. It's used by the team implementing the Home of the App.
- …
=> NFC Payments dependencies

.github/pull_request_template.md
La cuenta de bugsnag no tiene sentido desde que todos tenemos cuenta con SSO y los contextos por app quedó deprecado con la nueva whitelist de contextos (de hecho ese check nuevo está justo debajo).
Estos 2 checks ya no tenían sentido.
=> Remuevo sección "Configuración de Bugsnag" deprecada del template de PR

android-whitelist.json
Agrego Modals Engine a whitelist ya que la necesitamos para poder agregar el ModalsEngineBehaviour a Config-Provider.
- "com.mercadolibre.android.modalsengine:modals-engine:3.+"
No
No
Hace 1 mes
(https://sites.google.com/mercadolibre.com/growthtooling-wiki/modals-engine)(https://github.com/mercadolibre/fury_modals-engine-android)
=> Se agrega Modals Engine a la Whitelist

android-whitelist.json
- "com.mercadolibre.android.pms:pms:11.+"
No. La lib de PMS solo es utilizada por un par de libs aledañas a la hora de generar una orden de compra o una registración.
No, PMS no tiene código con NDK.
Min API level 19
Max API level 29
N/A
El proyecto en Jira en el que se van a crear los crashes que ocurran es: [AT](https://mercadolibre.atlassian.net/jira/software/c/projects/AT/issues/)
Es una lib que va a morir en el corto plazo. La mayor parte de sus features (todo lo que tiene que ver con el funcionamiento core de la app) fueron migradas a fury_matt-android. Nos queda la dependencia en un par de libs aledañas (como checkout y registrations). En esas libs se utiliza para …
=> Updated PMS' available versions to include 11.+, which contains Android X and Gradle migrations

android-whitelist.json
- `com.mercadolibre.android.tfs_commons:imageutils:0.+ `
_No
_No
_No
=> Se agrega nuevo módulo a la lib "tfs-commons-android" a la whitelist

android-whitelist.json
"com.mercadolibre.android.cart:manager"
Se actualiza la versión de cartManager, y se deja la versión anterior con un expires en 3 meses (mayo del 2021)
_Es una lib usada actualmente en ML_
_No_
_Las mismas que ML_
=> CartManager version updated

android-whitelist.json
- "com.mercadolibre.android.cardscomponents:cards-home-section:3.+"
_No.
_No.
_No
Es una seccion que ya existe en el repo Home. Se mueve a repo cards para transferir owner.
Es una seccion que ya existe en el repo Home. Se mueve a repo cards para transferir owner.
- [PR](https://github.com/mercadolibre/fury_home-wallet-android/pull/760)
- [fend](https://github.com/mercadolibre/fury_cards-components-android)
=> Add cardlist home section

android-whitelist.json
Se actualizan las versiones de libs core para soportar solamente android X, comparto un link [https://docs.google.com/spreadsheets/d/1gSD6HoFv3epLjPg4O_E-JNENDD-AEzLiuiVRQMNkzTA/edit?usp=sharing] donde estan todas las libs que se modifican y los bumpVersion.
_Si, …
=> Update libs core para soportar solamente android x

android-whitelist.json, ios-whitelist.json
Android
- `"com.mercadolibre.android.fees_installments:mlfees:1.+|2.+"`
- `"com.mercadolibre.android.fees_installments:mlfees-legacy:2.+"`
iOS:
- `MLFeesAndInstallments` -> `2.+`
_**Nota:** en el caso de Android, se mantienen dos dependencias, una con el código actual (mlfees-legacy) y la otra con el código nuevo (mlfees), que es consumido por PricingUI. mlfees-legacy va a deprecarse posteriormente._
_No_
_No_
_-_
=> Se modifican las versiones de MLFees

ios-whitelist.json
- Se agregan todas las dependencias externas utilizadas actualmente que hoy no estaban en la whitelist
- Se agrega el campo `source` que determina de que source debería obtenerse la dependencia
- Se agrega el campo `target` que indica si la dependencia es de targets de tests o productivos
Debido a vulnerabilidad expuesta en el [post](https://medium.com/@alex.birsan/dependency-confusion-4a5d60fec610) debemos revisar si nuestro pods privados vienen efectivamente de nuestra source privada.
Para ello, vamos a revisar desde el [plugin de la whitelist ](https://github.com/mercadolibre/mobile-cocoapods_whitelist/pull/7) que cada dependencia venga de una source conocida.
A su vez, como el analisis se va a realizar sobre TODAS las dependencias, debimos agregar las de test y por eso agregamos el …
=> Feature: Dependency Confusion

ios-whitelist.json
iOS:
* MPMoneyTransfer ~> 2.0
* MPContacts ~> 3.0
***Nota:*** El contexto para estos pods ya estaba definido, pero ninguno de los dos se había agregado a la whitelist; como antes de la versión 0.1.0 del plugin no se hacían verificaciones, no había saltado el error 
_No_ .Ya se estaban utilizando
Las mismas de la app de Mercado Pago
Ya se estaban utilizando 
***Nota:*** El contexto para estos pods ya estaba definido
=> Se agregan  MPContacts (~> 3.0) y MPMoneyTransfer  (~> 2.0)  a la whitelist

ios-whitelist.json
[BAGEL](https://github.com/yagiz/Bagel): is a little native iOS network debugger. It's not a proxy debugger so you don't have to mess around with certificates, proxy settings etc. As long as your iOS devices and your Mac are in the same network, you can view the network traffic of your apps seperated by the devices or simulators.
_No, solo se utilizaría para Test Apps_
- [PR Ejemplo Utilización](https://github.com/mercadolibre/fury_buyingflow-mobile-ios/pull/3185)
- [Wiki de utilización](https://github.com/mercadolibre/fury_buyingflow-mobile-ios/wiki/Bagel-Network-debugger)
=> Bagel - iOS network debugger for TestApps

ios-whitelist.json
=> Bump libs firebases

android-whitelist.json
Solo se borran de la whitelist android versiones de nuestras libs ya expiradas.
=> Eliminación de libs de screenlock ya expiradas

android-whitelist.json
"com.mercadolibre.android.recommendations:rcm:9.+"
No, es solo un update de la versión
[Buying Flow] (https://github.com/mercadolibre/fury_buyingflow-mobile-android)
[VPP] (https://github.com/mercadolibre/fury_vpp-android)
[Reviews] (https://github.com/mercadolibre/fury_reviews-mobile-android)
=> Recos major change and expires

android-whitelist.json
Se actualiza la versión de JNA para permitir `5.5.0` además de `5.1.0` de cara a una futura actualización.
Esta dependencia  solo es usada por el módulo de NFC Payments debido a un requerimiento del SDK para HCE.
=> Added version 5.5.0 for JNA dependency

ios-whitelist.json
- Se actualiza la version de adjust a 4.28.0 por mail de adjust indicando que apple esta rechazando versiones anteriores.
No
N/A
N/A
No cambia el peso de la lib que ya esta en prod.
=> Bump adjust to 4.28.0

android-whitelist.json, context_whitelist.json, ios-whitelist.json
Android
- "com.auth0.android:auth0:1.+"
- "com.auth0.android:jwtdecode:1.+"
iOS
Auth0, 1.+
_No, es una librería que se usa para hacer login y solo se levanta en el momento que se llama.
_ Si, Si
Android API version 21 or newer is required.
- Se creó un proyecto sin la dependencia a Auth0 el cual su apk obtuvo un peso de 3.953.835 bytes o 4MB aproximadamente, a ese mismo proyecto se le agregan las dependencias de auth0 y su apk resulta pesando 4.363.646 o 4.4MB aproximadamente, arrojando una diferencia de 409.811 o 0.4MB aproximadamente que correspondería al peso de la lib.
Android
- …
=> Add auth0 dependencies.

android-whitelist.json
- "com.google.android.libraries.places:places:2.4.0"
No.
No
Tiene minSDKVersion 16
No hay cambios significativos ya que se reemplaza una lib deprecada por su versión actual.
- Solamente se agrega la librería de Places. No se elimina aun la vieja librería ya que no estoy seguro que no se utilice por otros modulos.
Se agrega la nueva librería de Places en su versión 2.4.0: com.google.android.libraries.places:places:2.4.0
No estoy seguro, pero imagino que muchas empresas la utilizan, Google por ejemplo en su aplicación Google Maps.
Muy madura, tiene muchas actualizaciones y documentación.
Sí, es una lib mantenida por Google. 
https://developers.google.com/maps/documentation/places/android-sdk/releases …
=> Agregado de librería de places 2.4.0 para Android

context_whitelist.json
Se crea el contexto para las nuevas libs android y iOS que a futuro sera la que se encargaran de la reauthenticacion nativa
El proyecto en Jira en el que se van a crear los crashes que ocurran es: ASEC
Se utulizara esta lib interna para poder reauthenticar al usuario con un second factor en algun flujo de la app que lo solicite
- https://github.com/mercadolibre/fury_native-reauth-ios
- https://github.com/mercadolibre/fury_native-reauth-android
=> Se agrega el contexto de la lib interna de reauth nativa, android y iOS

context_whitelist.json, ios-whitelist.json
Estas librerías van ser utilizadas por el nuevo flujo de Registro V3. Parte de la iniciativa seguridad 360.
Se agregan al JSON de Context y a la whitelist de iOS las nuevas librerías nativas de Auth Challenges, Auth Commons y hub.
Las tres Libs son soportadas a partir de  IOS 10+
El proyecto en Jira en el que se van a crear los crashes que ocurran es: **_RRYL_**
- [Hub](https://github.com/mercadolibre/fury_auth-hub-ios)
- [AuthChallenges](https://github.com/mercadolibre/fury_auth-challenges-ios)
- [AuthCommons](https://github.com/mercadolibre/fury_auth-commons-ios)
=> ADD Auth Challenges, Auth Commons & Hub context

android-whitelist.json
Por pedido de uno de los equipos que depende de la vieja lib de places, se extiende el periodo de vencimiento al 31-05-2021
=> extension de tiempo de expiración en vieja lib de places

android-whitelist.json
Hacemos rollback de material a la 1.0.0 porque hubo algunos flujos que comenzaron a tener problemas de theme al estilear sus componentes:
```
error: resource style/Widget.AppCompat.TextView (aka com.mercadolibre.android.discounts.payers.testapp:style/Widget.AppCompat.TextView) not found.
```
=> [Rollback] material 1.3.0 -> 1.0.0

android-whitelist.json
- "com.mercadopago.android.multiplayer:commons:5.+"
_No, este módulo ya lo usa **moneytransfer** pero lo estamos exponiendo para ser usado por otra lib nueva_
_No_
_Este módulo ya lo usa **moneytransfer** pero lo estamos exponiendo para ser usado por otra lib nueva. No tiene impacto en el peso de descarga e instalación de la app_
_Estamos creando una nueva lib **funds-movements** y necesita acceder al módulo de commons de **moneytransfer** para reutilizar varios componentes._
- [Add Multiplayer commons dependency](https://github.com/mercadolibre/fury_funds-movemen …
=> Add moneytransfer commons module to the Android whitelist

ios-whitelist.json
Estamos teniendo problemas con la validación lint de los PRs hechos en MLConfigurationProvider. El problema viene relacionado con la whitelist de dependencias y su última actualización a la versión 2.0. MLConfigurationProvider sigue necesitando trabajar con la 1.0 por lo que de momento añadiremos soporte para ambas versiones usando la forma: `^~>\\s?[1-2].[0-9]+$` a nivel del whitelist StartUPInitializer.
ND
https://github.com/mercadolibre/fury_ml-config-provider-ios
=> Dual version support (StartUPInitializer)

android-whitelist.json
Bump: 
"com.mercadolibre.android.navigationcp:navigationcp:5.+"
"com.mercadolibre.android.navigationcp:shipping-address:5+"
Repositorios afectados
Home, vip, cpg-supermarket, search
Van a ser notificados de la necesidad de updatear el major, mientras tanto se mantiene la versión actual.
=> Update NavigationCP version

android-whitelist.json
Update de dependencia de viewbinding , esto es debido a poder dar soporte a la 3.x y 4.x ya que pueden haber proyectos con 3.x aun.
Las dependencias se terminan resolviendo según la version de agp que tengamos en los proyectos, por eso tenemos el 4.+
=> Update viewbinding version

android-whitelist.json
Se agrega un `expires` a todos los módulos de Webkit que están dentro de UI-Components porque hemos migrado Webkit a un [repositorio independiente](https://github.com/mercadolibre/fury_webkit-android) y pronto vamos a eliminar esos módulos de UI-Components. …
=> An expiration date is added to the Webkit modules that are inside the UI-Components

android-whitelist.json
Actualmente tenemos libs que todavia usan esta lib, pero en las apps se lo estamos pisando hace mucho tiempo con la 2.2.0 y 2.1.0, por lo que mantener esta version puede ser producto de errores.
=> Expire fresco 1.13.0

android-whitelist.json
- "com.mercadolibre.android.wallet.home:home:mercadopago-1.+"
- "com.mercadolibre.android.wallet.home:sections:mercadopago-1.+"
Se agrega _mercadopago-_ ya que es parte de la versión que tenemos implementada en la app de Point Smart
_No_
_No_
_Hace 2 semanas_
_En nuestra librería de MoreOptions en Point Smart tenemos una serie de secciones configurables basadas en los componentes de la Home de la Wallet._
- [More Options](https://github.com/mercadolibre/fury_point-more-options-android)
fury_home-wallet-android
=> Se agrega mercadopago-1 a la version de home y section

android-whitelist.json
- "com.mercadolibre.android.cardscomponents:cards-components:4.+"
_No, cards-components no requiere inicialización en MercadoPago
_No
Min api 21
Se migra a min api 21 la lib de componentes de cards
- [Cards Acquisition](https://github.com/mercadolibre/fury_cards-acquisition-android)
- [Cards …
=> Bump major cards acquisition

android-whitelist.json
- com.mercadolibre.android.cardsbanking:card-widget:1.0.0 
- com.mercadolibre.android.cardsbanking:cards-home-section:1.0.0
- No
- No
- Example module está pesando 14kb y okhttp para la versión 4.2.0 ~4 terabytes. Para descarga pesaría aproximadamente Xkb menos porque example app tiene Ykb de recursos que se splittean para cada densidad_
- Cards Home Section ya tiene varios años, es un modulo de la Home Wallet que fue cedido.
- Card Widget es otro modulo que esta presente en NFC desde hace 6 meses que es migrado
- No
- Hace menos de un día  
- No
- En el …
=> Android Card Banking Dependecies Added

ios-whitelist.json
- Se hace bump de major de MLHistory en iOS a [2xx](https://github.com/mercadolibre/fury_history-ios/releases/tag/2.0.0)
...
=> Bump iOS major in whitelist for MLHistory

android-whitelist.json
Se sube el mayor de Login y Authentication por la migración de MIN SDK a 21 en ambas libs ademas que en Authentication se borra lógica legacy.
Login 
Authentication
No afecta el start-up
son libs nativas
github.com/mercadolibre/fury_auth-android-authentication
github.com/mercadolibre/fury_auth-android-login
=> Change mayor Login & Authentication

android-whitelist.json
- Se aumentan versiones para módulos de la librería `com.mercadolibre.android.tfs_commons`(de uso interno de SX/TFS). 
- Modulo **`tracking`**: `mercadopago-1.+` y `mercadolibre-1.+`
- Modulo **`imageutils`**: `1.+`
- Modulo **`ktx`**: `1.+`
- Modulo **`mvp`**: `1.+`
- Se aumenta la versión de `com.mercadolibre.android.charts:melicharts`, de `0.+` a `1.+`
Aclaración: se sacan las versiones `0.+` ya que no quedan repos que consuman la versión `0` y que realmente lo necesiten.
_No_
_No_
_No tiene un impacto significativo, ya que son muy pocos archivos en cada módulo._
El proyecto en Jira en el que se van a crear los crashes que ocurran es: [Tools For Sellers](https://mercadolibre.atlassian.net/secure/RapidBoard.jspa?rapidView=1090&projectKey=TFS)
=> TFS Commons: cambio de versión major en los módulos de 0 a 1

android-whitelist.json
- "androidx.concurrent:concurrent-futures:1.1.0"
- "androidx.concurrent:concurrent-futures-ktx:1.1.0"
- _No_
-  _No_
-  _NA_
-  _No tiene impacto en el peso de descarga_
_Migración API 30: Remplazo de FirebaseJobDispatcher por WorkManager para carga de agenda de contactos del dispositivo.
Actualmente es posible usar el WorkManager pero requerimos usar el CallbackToFutureAdapter el cual requiere la libreria que se quiere añadir._
- [MLTP-1326: Migration to WorkManager](https://github.com/mercadolibre/fury_moneytransfer-android/pull/777)
- [MoneyTransfer - Android](https://github.com/mercadolibre/fury_moneytransfer-android)
Libs …
=> feat: Add concurrent-futures to the Android whitelist

android-whitelist.json
- "androidx.work:work-runtime:2.1.0"
- _No_
- _No_
- _NA_
- _No tiene impacto en el peso de descarga_
_Migración API 30: Remplazo de FirebaseJobDispatcher por WorkManager para carga de agenda de contactos del dispositivo.
Actualmente es posible usar el WorkManager a nivel local, en integración con la app de MercadoPago genera problemas binarios de versión de librerías que ya se habían detectado en otros proyectos y se había hecho bump a la versión 2.1.0 pero solamente en kotlin, como la implementación está en Java se realiza el bump a la versión 2.1.0 de la librería._
- [MLTP-1326: Migration to …
=> Bump work-runtime version to 2.1.0

android-whitelist.json
- "com.mercadolibre.android.security_two_fa:totp:2.+"
- "com.mercadolibre.android.security_two_fa:totpinapp:2.+"
- [Wallet](https://github.com/mercadolibre/mpmobile-android_wallet/pull/14402)
- [Wallet](https://github.com/mercadolibre/mpmobile-android_wallet)
- [Login](https://github.com/mercadolibre/fury_auth-android-login)
- [Security Options](https://github.com/mercadolibre/fury_security-options-android)
=> Bump version 2.+, totpinapp and totp

android-whitelist.json
-  `com.mercadolibre.android.search:11.+`
Este cambio es para poder hacer la migración de api 21
=> Bump version search to v11

android-whitelist.json
Agrego expires para estas libs pre androidX
que ya se estan reemplazando en las apps por sus versiones correspondientes
=> Expires for libs pre androidx: Android.Arch.Lifecyle

android-whitelist.json
Se corrigen las regex de las dependencias
" com.mercadolibre.android.payment_flow_fcu:entities_fcu:version"
" com.mercadolibre.android.payment_flow_fcu:pointsmartpos_fcu:version"
De momento estas dependencias no tienen impacto actual sobre dichas apps ya que se encuentran en proceso de desarrollo.
[PR](https://github.com/mercadolibre/mobile-dependencies_whitelist/pull/829) en las que se incluyeron dichas dependencias
No
No 
- N/A
- [PaymentFlowFCU](https://github.com/mercadolibre/fury_payment-flow-fcu-android)
=> Corregir regex de las versiones para FCU

android-whitelist.json
Se agrega la dependencia del modulo de [mpos](https://github.com/mercadolibre/fury_payment-flow-fcu-android/tree/feature/mpos-module/mpos) la cual se va a agregar al repo de [paymentflow](https://github.com/eferrin/fury_payment-flow-android)
Se cambian las regex de las dependencias de  posreaders y fcu  (usadas por [paymentflow](https://github.com/eferrin/fury_payment-flow-android))  para permitir versiones fijas 
_**(ex: posreaders 4.27.0,  fcu 1.14.1)**_
-  "com.mercadolibre.android.payment_flow_fcu.mpos:1.x.x"
-  "com.mercadolibre.android.payment_flow_fcu.paymentflowfcu:1.x.x"
-  "com.mercadolibre.android.payment_flow_fcu.posreaders:4.x.x"
- No
- No
- No afecta el peso,  dos dependencias ya existen y la dependencia que se agrega es còdigo que se mueve desde …
=> Dependencia mpos y major fijos para las dependencias de paymentflow

android-whitelist.json
Este update nos permite poder soportar la libs en kotlin.
- update libs androidx.transition:transition:1.3.0 a 1.4.1
- androidx.transition:transition-ktx:1.4.1
=> Se actualiza libs de transitions para soportar kotlin

android-whitelist.json
Se agrega expire de la libs de trello debido a que no tiene uso en las apps
...
=> Expire libs trello

android-whitelist.json
Se agrega `expires` a librerías de Insurtech con fecha previa al deadline de migración a android 11. 
Se agregan las versiones con cambio en el mayor, de la librerías con la migración a android 11 realizada. 
=> Expires for lib Insurtech and bump version with migration android 11

android-whitelist.json
Se agrega expire para las libs que utilizan rxjava1.
=> Se agrega expire de la libs de rxjava

ios-whitelist.json
Ya la lib estaba aprobada en el https://github.com/mercadolibre/mobile-dependencies_whitelist/pull/877
Había un typo en el nombre y seguía arrojando el warning de librería no permitida en el whitelist.
=> Fix typo in Google Places iOS dependency

ios-whitelist.json
- Eliminando libs deprecadas : CustomBadge, MTBBarcodeScanner e DZNPhotoPickerController.
=> Cleaning deprecated libs

android-whitelist.json
- -  "com.mercadolibre.android.security:security_ui:mercadopago-4.+"
- -  "com.mercadolibre.android.security:security_ui:mercadolibre-4.+"
- [ x] _Tiene Min API level 21
- [example PR](https://github.com/mercadolibre/fury_security-ui-android/pull/112)
- [example fend](https://github.com/mercadolibre/fury_security-ui-android)
- [ x] Ya existe, no tengo que agregar ni modificar nada.
=> Security UI update - cambio de major por min api 21

android-whitelist.json
Se eliminan las entradas de libs de Insurtech con fecha de expiración próxima. 
- _No, mis Libs no requieren inicialización en el `Application`_
=> Delete Insurtech expired libs

android-whitelist.json
En pos de seguir actualizando el stack de libs cross que usamos en meli, encontramos que la dependencia androidx.legacy:legacy-support-v4 está DEPRECADA. 
¿Qué tengo que hacer? 
Si tenes la dependencia androidx.legacy:legacy-support-v4:
Podes eliminarla ya que:
This artifact and its classes are deprecated. [Starting with Android 8, background check restrictions make this class no longer useful.](https://developer.android.com/jetpack/androidx/releases/legacy)
**Si tenes que migrar alguna funcionalidad pre-androidx mira este link.
Que vamos a hacer?
Vamos a setear un expire para la lib androidx.legacy:legacy-support-v4 el 15/10/2021. 
Ante cualquier duda pueden escribirme.
=> remove deprecated legacy pre-androidx lib

android-whitelist.json
Se nos retraso el ingreso de la lib security ui a los trenes, y mando unos dias de extension de la fecha de expiración, para evitar que tire errores al buildear hasta que entremos a las monoliticas.
=> Extender la fecha de la lib security ui

android-whitelist.json
Arreglo un path que cambiamos en el PR: 
https://github.com/mercadolibre/mobile-dependencies_whitelist/pull/957
- - "com.mercadolibre.android.loyalty:webview:mercadolibre-11.5.0"
- - "com.mercadolibre.android.loyalty:webview:mercadopago-11.5.0"
=> loyalty webview fix in package

android-whitelist.json
- Extender TTL de Libreria RxJava v1hasta el 2021-11-05
=> Aumenta tiempo de expiracion para Rx v1

android-whitelist.json
- Add expires a zxing y cia
- Add version of kotlin that we are using
- delete datami and aspecjt. We dont use them anymore.
- fix "expire" to "expires"
- remove me.dm7.barcodescanner O_O
- remove old version of playstore core
=> Expires Zxing and other minor changes/fixes

android-whitelist.json
- "com.google.android.material:material:1.0.0"
Agregamos el expire a la version 1.0.0 de acuerdo al post de [workplace](https://meli.workplace.com/notes/430416041798862)
=> Material 1.0.0: expire date added

android-whitelist.json
Se cambian las regex de las dependencias de [point-ui](https://github.com/mercadolibre/fury_point-ui-android) para permitir versiones fijas en [paymentflow-fcu](https://github.com/mercadolibre/fury_payment-flow-fcu-android/blob/master/gradle.properties#L114)
(ex: point-ui 1.18.0)
com.mercadopago.android.point_ui:components:1.18.0
com.mercadopago.android.point_ui:components:1.+
- No
- No
- No afecta el peso, dos dependencias ya existen y la dependencia que se agrega es còdigo que se mueve desde com.mercadolibre.android.payment_flow_fcu.paymentflowfcu
- [point-ui](https://github.com/mercadolibre/fury_point-ui-android)
- [paymentflowfcu](https://github.com/mercadolibre/fury_payment-flow-fcu-android)
-
Libs [internas](https://sites.google.com/mercadolibre.com/mobile/ar …
=> Dependencia point-ui usar versiones fijas para las dependencias de paymentflow-fcu

android-whitelist.json
- add expire to lottie 2.x: since in the apps its being replaced by v3.3.1 and this could lead to weird and potential errors
=> add expire to lottie 2.x

android-whitelist.json
- Please refer to this [PR](https://github.com/mercadolibre/mobile-dependencies_whitelist/pull/981/files) for further information
- Adjusted already expired dates wrongly set to 2021 instead of 2022.
=> [FIX] OTEL & NR PoC Expired Dates

android-whitelist.json
- - "com.mercadolibre.android.security_two_fa:totpinapp:3.+"
- - "com.mercadolibre.android.security_two_fa:totp:3.+"
...
- [Login PR](https://github.com/mercadolibre/fury_auth-android-login/pull/199)
- [Login](https://github.com/mercadolibre/fury_auth-android-login)
- [Security Options](https://github.com/mercadolibre/fury_security-options-android)
=> bump version 3.+ security-two-fa

ios-whitelist.json
Actualización de la versión de Bugsnag a 6.14.3 para admitir el [Plugin Network Breadcrumbs](https://docs.bugsnag.com/platforms/ios/customizing-breadcrumbs/#capturing-network-requests)
No
¿Utiliza libs nativas? ¿Tiene soporte para las diferentes arquitecturas de devices?
[Bugsnag Network Breadcrumbs](https://docs.bugsnag.com/platforms/ios/customizing-breadcrumbs/#capturing-network-requests)
- Sin variación 
- [MLCommons](https://github.com/mercadolibre/fury_mobile-commons-ios)
=> Adding new version 6.14.3 of Bugsnag and BugsnagNetworkRequestPlugin

android-whitelist.json
Bump de la lib android de Andes Modal a la versión 6.+ (se sube a API 21)
Se agrega expire a la versión 5.+
- - "com.mercadolibre.android.draftandesui:draft-modal:6.+"
=> Bump draft-modal lib version to 6.+ (API 21 major)

android-whitelist.json
-"com.google.android.material:material:1.3.0"
Desde AndesUI necesitamos subir la lib de material dado que tenemos algunos componentes cuya contribución depende de la actualización de la lib dado que en las siguientes versiones se agregaron.
- Slider (Single & Range)
Algo que vemos positivo además de tener la lib "al día" es que en la 1.3.0 se migra constraintLayout de 1.1.3 a 2.0.1 y nosotros actualmente solo soportamos 2.0.4 lo cual podría generar problemas en el uso de la lib en si misma.
A día de hoy algunas apps que no son las principales ya están usando la versión 1.3.0 por fuera de la whitelist.
[Post de migracion](https://meli.workplace.com/notes/430416041798862)
- No
- Tiene Min API level 14
- El modulo sube 500 Kb de peso en la app (ML/MP).
=> Material 1.3.0

android-whitelist.json
- "com.mercadolibre.android.maps:core:6.+"
- "com.mercadolibre.android.maps:core:5.+" --> Expiración para el 1 de Enero de 2022
- [Agregado de hiperlinks en MapsCore](https://github.com/mercadolibre/fury_mobile-maps-android/pull/171)
-[ Maps Core](https://github.com/mercadolibre/fury_mobile-maps-android)
=> Versión de Maps Core y se pone fecha de expiración a la versión anterior

android-whitelist.json
Se agrega expire a las versiones de kotlin & coroutine, y se elimina la version de kotlin 1.3.40 debido a que ya no se esta utilizando.
kotlin-android-extensions-runtime.
kotlin-reflect.
kotlin-stdlib. 
kotlin-stdlib-common.
Kotlin-stdlib-jdk7.
kotlinx-coroutine-android
kotlinx-coroutine-core.
Libs [internas](https://sites.google.com/mercadolibre.com/mobile/arquitectura/libs-utilitarias/libs-internas) o [externas](https://sites.google.com/mercadolibre.com/mobile/arquitectura/libs-utilitarias/libs-e …
=> Se agrega expire a la libs de kotlin

android-whitelist.json
Se agrega expire a la libs de cameraview debido a que necesitamos deprecarla para soportar kotlin 1.5, en Q1 vamos agregar la nueva version que soporta kotlin 1.5, por el momento la version va estar solo en las apps de MP y ML 
...
=> se agrega expire cameraview

android-whitelist.json
- - "com.mercadolibre.android.flox:6.+"
Es una lib utilizada por varios equipos incluidos arquitectura mobile. Hace un tiempo atrás generamos la versión 6 con la migración de API 21 pero nos olvidamos de whitelistearla, nos dimos cuenta cuando quisimos agregar la dependencia en la lib de Sell. Actualmente en mobile-android ya se está utilizando la versión 6.0.0 de Flox, pero necesitamos esto para que no fallen los prs de las libs y podamos tener todo actualizado
- [ PR donde se necesita ](https://github.com/mercadolibre/fury_sell-mobile-android/pull/1896)
- [Sell mobile …
=> Updating Flox whitelisted version

android-whitelist.json
- - "io.reactivex:rxjava:1.3.6"
- - "io.reactivex:rxandroid:1.2.1"
Es necesario agregar estas dependencias dado que RxBle necesita de estas dependencias para poder correr y el deadline está para finales de Q1.
=> Add rxjava and rxandroid in android whitelist

android-whitelist.json
- "org.jetbrains.kotlin:kotlin-stdlib-jdk8:1.3.71"
- No
=> Add kotlin sdt-jdk8 to whitelist

android-whitelist.json
- - "com\\.mercadolibre\\.android\\.wallet\\.home"
Es necesario prolongar el tiempo de expiracion de la version 1.49.0 de home y home sections para no romper compatibilidad con el codigo actual en el repositorio de Smartpos. Se esta trabajando en un feature que va a adaptar a las nuevas versiones que tiene deadline para finales de Abril de 2022.
Contacto: Lideres tecnicos David Ortegon, Leandro Maguna. 
PL Mateo Pedemonte
- [PR](https://github.com/mercadolibre/fury_mpmobile-smartpos/pull/1593)
- [smartpos](www.github.com/mercadolibre/fury_mpmobile-smartpos)
Libs …
=> Prolongar tiempo de expiración librerias home y home section para el repo de Smartpos

android-whitelist.json
- - "com\.mercadolibre\.android\.wallet\.home"
...
Fix en la referencia de la libreria de home, sobre el PR https://github.com/mercadolibre/mobile-dependencies_whitelist/pull/1034 recientemente mergeado
=> Fix en la version de home y home sections

android-whitelist.json
Se actualiza la fecha de expiracion de Firebase-ads ya que se utiliza en la home de mercado libre para las publicidades.
=> Firebase-ads: change expires date

android-whitelist.json
Actualizamos las versiones del SDK de notifications.
Seteamos la version minima a 16.+ con fecha de expiración en Q2 para dar tiempo a la migración.
Eliminamos una version vieja del sdk tambiém.
- _Si pero ya de antes, no se agrega nada nuevo.
=> Update notifications versions

android-whitelist.json
Se agrega la dependencia de point credits al whitelist para versiones 1.+ 
- "com.mercadolibre.android.point_credits:credits:1.y.z"
=> Add point credits to android whitelist

android-whitelist.json
- - com.mercadolibre.android.point_smart_helpers:hardware_buttons:1.+
Es necesario agregar esta lib para que pueda ser utilizada en el repo de recargas de SmartPost y de esta forma realizar un comportamiento personalizado para los botones físicos del dispositivo, esto para el feature de Semovi
- [232](https://github.com/mercadolibre/fury_point-recharge-android/pull/232)
- [fury_point-recharge-android](https://github.com/mercadolibre/fury_point-recharge-android) …
=> Add module hardware_buttons in Point Smart Helpers

ios-whitelist.json
- 
- _No, Valkiria es una librería utilitaria que de momento expone solo 2 funcionalidades, showInteractionScreen y showErrorScreen ambas deben ser llamadas por otras libs para mostrar pantallas de restricciones en sus flujos, no se carga al inicio de la app por sí misma
- Sí
- iOS 12
=> Fix reg exp Valkiria iOS Dependency

android-whitelist.json
vipcommons 4.+
Se subio el major de vipcommons porque migramos a kotlin 1.5
=> bump vipcommons

android-whitelist.json
- "com.mercadolibre.android.search:input:13.0.0"
- "com.mercadolibre.android.search:search:13.0.0"
- [Cart](https://github.com/mercadolibre/fury_buyingflow-cart-android)
- [Home](https://github.com/mercadolibre/fury_homes-android)
- [VPP](https://github.com/mercadolibre/fury_vpp-android/)
=> Bump search version to 13

android-whitelist.json
- Adicionar la dependencia de la nueva libdataprivacy para android
Sí, nuestra libreria impacta, porque guardamos las preferencia de ubicación en un Catalog LocalStorage y necesitamos borrar el caché cada vez que los usuarios inician la aplicación MP o ML
Sí, utiliza la libreria LocalStorage para guardas las preferencia de ubicación de los usuarios
No tiene
Example module está pesando 14kb y xxLib para la versión 1.0 ~4 terabytes.
[example PR](https://github.com/mercadolibre/mobile-dependencies_whitelist/pull/www.github.com/mercadolibre)
Repositorios afectados
[example fend](https://github.com/mercadolibre/mobile-dependencies_whitelist/pull/www.gi …
=> adicionar en la Whitelist android nueva lib de data privacy

android-whitelist.json
- Valkiria
- _No, Valkiria es una librería utilitaria que de momento expone solo 2 funcionalidades, `showIfNeeded` y `showErrorScreen` ambas deben ser llamadas por otras libs para mostrar pantallas de restricciones en sus flujos, no se carga al inicio de la app por sí misma._
- [example PR]([www.github.com/mercadolibre](http://www.github.com/mercadolibre))
- [example fend]([www.github.com/mercadolibre](http://www.github.com/mercadolibre))
Libs [internas](https://sites.google.com/mercadolibre.com/mobile/arquitectura/libs-utilitarias/libs-internas) o [externas](https://sites.google.com/mercadolibre.com/mobile/arquitectura/libs-utilitarias/libs-exter …
=> PXN-3636: [Feat] Valkiria Version Bump

android-whitelist.json
Se cambia la fecha del expire de la v12 porque les da error a los equipos que no migraron a api23.
- "com.mercadolibre.android.search:input:13.0.0"
- "com.mercadolibre.android.search:search:13.0.0"
- [Cart](https://github.com/mercadolibre/fury_buyingflow-cart-android)
- [Home](https://github.com/mercadolibre/fury_homes-android)
- [VPP](https://github.com/mercadolibre/fury_vpp-android/) …
=> Change expire date lib 12

ios-whitelist.json
Luego que nos llegó el PR automático de iOS 13, el mismo tenía el cambio de estas dos librerías a 2.0.0, lo cual rompe con las versiones permitidas en la whitelist.
...
=> Adding to whitelist DaManagement and Cashout

ios-whitelist.json
- CardsEngagement 2.0
- MeliCards 2.0
=> Adding CardsEngagement and MeliCards 2x to iOS allowlist

android-whitelist.json
upgrades matt-android dependency version to 8.+ and sets the expiration date of version 5.+ to 2022/05/15
- - "com.mercadolibre.android.matt:8.+"
- No, mi Lib no requiere inicialización en el `Application`
- N/A
- [Matt-Android PR #84](https://github.com/mercadolibre/fury_matt-android/pull/84)
- [Matt-Android PR #85](https://github.com/mercadolibre/fury_matt-android/pull/85)
- 
=> Adding matt version 8.+ to android whitelist

ios-whitelist.json
- Debido a los cambios de minimo de iOS, se sube la version del major para MLVPP en iOS a 2, por lo cual debemos soportar un major 2.0 en los podspec
- No
=> Bump MLVPP major available

ios-whitelist.json
=> Adding CardsComponents 2x to iOS allowlist

android-whitelist.json
En esta version incrementamos el Min Api Level a 23
- - "com.mercadolibre.android.purchases:experimentals:2.0.0"
- - "com.mercadolibre.android.purchases:purchases:2.0.0"
=> Updating Purchases dependencies

ios-whitelist.json
- Se actualizan las versiones de libs core de Checkout.
- Dos de ellas llevan un expire por las dudas.
iOS 13
https://github.com/mercadolibre/fury_bf-flox-components-ios
https://github.com/mercadolibre/fury_rule-engine-ios
https://github.com/mercadolibre/fury_marketplace-ios-map
=> Update Checkout Core libs

ios-whitelist.json
=> Changed version support for StartupInitializer-ios

android-whitelist.json
- **com.mercadolibre.android.credits.ui_components:3.0.0**
Subio la lib a 3.0 a raiz de los bumps de min api level 23 y de kotlin + gradle, sin embargo como queda tiempo del deadline pueden existir modulos que aun no hayan actualizado probado su funcion en la 3.0 (las cuales son en esta semana)
Libs [internas](https://sites.google.com/mercadolibre.com/mobile/arquitectura/libs-utilitarias/libs-internas) o [externas](https://sites.google.com/mercadolibre.com/mobile/arquitectura/libs-utilitarias/libs- …
=> Bump CUIC 3.0 & maintain 2.0

android-whitelist.json, ios-whitelist.json
update allowlist: cleaning expired libs manually because we lost the integration with our cleaning bot. fixed in #1230
=> update allowlist: cleaning expired libs

ios-whitelist.json
Hola! estamos agregando el SDK de opentelemetry y sus dependencias para iOS.
La idea es que pueda reemplazar el sdk de New Relic y mismo firebaseperformance como libreria de tracing/log/metrics.
Con esta implementación estaríamos igualando la implementación en Android y Backend.
Las dependencias se podrían "dividir" en
**Core**:
Ofrece la api para poder hacer un trace
- - "OpenTelemetryApi"
- - "OpenTelemetrySdk"
**Dependencias de modulo Core**:
Son 2 dependencias utilizadas en la implementación del modulo core. 
Son dependencias hechas por apple, que son originalmente solo para SPM, pero fueron adaptadas a Cocoapods mediente un podspec en nuestro repo privado
- - "SwiftAtomics"
- - "SwiftAtomicsShims"
**Exporter**:
Su responsabilidad es recolectar y enviar mediante un protocolo …
=> Opentelemetry for iOS

ios-whitelist.json
- Hola! Estamos agregando la libreria wrapper de Opentelemetry en iOS y una dependencia que faltó en el último PR: https://github.com/mercadolibre/mobile-dependencies_whitelist/pull/1214
**Opentelemetry**:
- Módulo para permitir el uso de conceptos de OpenTelemetry o la construcción de capas de abstracción encima. También permite configurar la implementación de MP y ML en iOS.
"Opentelemetry"
**Exporter**:
- Estamos agregando una dependencia que faltó en el PR:  https://github.com/mercadolibre/mobile-dependencies_whitelist/pull/1214
"SwiftNIO"
- _Si, el análisis está en el PR https://github.com/mercadolibre/mobile-dependencies_whitelist/pull/1214 …
=> Add Opentelemetry lib and missing SwiftNIO dependency

android-whitelist.json
Se corrige el regex para el versionado de la librería spirtech que impedían que las nuevas versiones sean tomadas validas
=> [Fix] spirtech version regex

ios-whitelist.json
Por Inconvenientes con las actualizaciones de las lib a iOS 13 , se pospone la expiración de la version previa de esta lib 
- - #....
=> new expire date creditscore

android-whitelist.json
"com.google.zxing.core:3.3.2"
"com.journeyapps:zxing-android-embedded:3.6.0|4.0.2"
Estimado, necesitamos extender la fecha de vencimiento de estas librerías debido a que el ML kit todavía tiene errores:
https://issuetracker.google.com/u/0/issues/207732702?pli=1
https://mercadolibre.atlassian.net/browse/SPPG-1902
=> fix zxing-android lib

ios-whitelist.json
En InStore Mobile iOS, nos encontramos en la migración al nuevo Scanner propuesto por arquitectura.
Para migrar InStore al nuevo Scanner(https://github.com/mercadolibre/fury_ml-scanner-ios), debemos convivir un tiempo con el que está hoy vigente MLScanner(https://github.com/mercadolibre/fury_scanner-ios).
Estas dos librerías, debido a su gran parecido, entran en conflicto.
Para hacer convivir estas dos librería, a la librería de MLScanner, tocó cambiarle el nombre y firma a algunas clases. Esto generó la versión 3.0.0.
En este repositorio de white-list, solo se cambió para que esta nueva versión MLScanner 3.0.0 sea utilizada por todos los equipos que como InStore, deben tener las dos librerías conviviendo mientras se hace un rollout exitoso.
- - #....
Para más información visitar …
=> Actualizar versiones para la MLScanner a las versiones V.3.0.0

android-whitelist.json
https://github.com/mercadolibre/fury_buyingflow-cho-sdk-android
```
implementation "com.mercadolibre.android.buyingflow.checkout:flow:$flowVersion"
```
Si requiere inicialización en el Application, pero ya se está haciendo dado que el módulo estaba ya integrado a meli
_No
Las mismas de todo meli
No suma peso dado que ya se estaba incluyendo en la app de meli
El proyecto en Jira en el que se van a crear los crashes que ocurran es: el de checkout_on
Estamos creando un módulo para centralizar las apps que utilizamos con flox. Pertenece al sdk y por ende inicia con la versión que se maneja actualmente.
https://github.com/mercadolibre/fury_buyingflow-cho-sdk-android
=> Add flow library that belongs to a module in the checkout sdk

android-whitelist.json
extend expire date firebase-ads
se actualiza fecha de expiración de fire base-ads para utilización en componentes de ads en la home de ML
=> extend expire date firebase-ads

android-whitelist.json
"com.bugsnag:bugsnag-plugin-android-okhttp:5.22.4" (Se actualizó de la 5.13.0 a la 5.22.4)
Se actualiza la version de Bugsnag Plugin Android Okhttp de la 5.13.0 a la version 5.22.4 
- - #....
=> Updated Version Bugsnag Plugin Android Okhttp

android-whitelist.json
Se añade la librería de Advertising ADN que permite agregar publicidad para probar funcionalidades como
- Renderización de ads
- Envío de eventos de prints
- Envío de evento para medir clicks
- Redirecciones desde los ads
=> adding advertising_adn_lib

android-whitelist.json
Se actualiza el nombre de la librería 
advertising_adn_lib:component --> advertising:adn
=> rename Advertising ADN lib

ios-whitelist.json
Debido ya existir un pod externo con este nombre, podemos tener conflictos al descargar nuestra lib como dependencia.
El nuevo nombre elegido es InAppUpdateFlow.
Agregamos un expire en la lib con nombre actual.
- - #....
=> Change InAppUpdates name

android-whitelist.json
Se quitaron los flavors de ML y MP en la lib de [Notifications](https://github.com/mercadolibre/fury_mobile-notifications-android/pull/355), por ende se agrega un nuevo registro en la whitelist para contemplarlo
=> Add notif version

ios-whitelist.json
This commit reverts changes from [4b32fba](https://github.com/mercadolibre/mobile-dependencies_whitelist/commit/4b32fbad67af9da768825492124da188daea1ef1) and [b5c98b5](https://github.com/mercadolibre/mobile-dependencies_whitelist/commit/b5c98b542342f47d23478e0498ae2675b7bafbe0), PR #[1355](https://github.com/mercadolibre/mobile-dependencies_whitelist/pull/1355) since the bump to version 4 was aborted.
- [MSF-1773](https://mercadolibre.atlassian.net/browse/MSF-1773)
=> Revert MLNotifications version upgrade to v4

android-whitelist.json
Added expires for Android 12 migration
- expire : 2022-09-16
- libraries: 
- androidx.work:work-runtime
- com.google.android.gms:play-services-analytics
- androidx.core:core
- android.core:core-ktx
- androidx.browser:browser
=> Added expires for Android 12 migration

ios-whitelist.json
- NetworkStatus es una dependencia de OpenTelemetry necesaria para agregar información de networking requests a nuestros tracks/spans. Es un Swift package mantenido por la comunidad open source de Opentelemetry.
- - #7545910
=> Add NetworkStatus (Opentelemetry dependency) to allowlist

android-whitelist.json
Se actualiza la versión del SDK de Braze para [Android 21.0.0](https://github.com/Appboy/appboy-android-sdk/releases/tag/v21.0.0).
- - #7544758 -> Actualizar Lib braze-sdk Android WhiteList
=> Update Braze SDK version Android to 21.0.0

android-whitelist.json
- Add
- -- [io.opentelemetry.instrumentation:opentelemetry-okhttp-3.0](https://github.com/open-telemetry/opentelemetry-java-instrumentation/tree/main/instrumentation/okhttp/okhttp-3.0/library) this lib included version because version is different to io.openTelemetry: 
- -- io.opentelemetry:opentelemetry-extension-trace-propagators for B3 context propagators 
- - #7546018
=> Add dependencies for instrumentation restClient in openTelemetry

ios-whitelist.json
Agregando una nueva biblioteca de iOS para facturación de terceros en el flujo de checkout, nuestro repositorio es: https://github.com/mercadolibre/fury_si-billing-info-ios
- #7546376
=> Add MLSIBillingInfo library in ios whitelist

android-whitelist.json
Se actualiza la version del SDK de braze (appboy) para android. [23.1.2](https://github.com/Appboy/appboy-android-sdk/releases/tag/v23.1.2)
- - #7546764 -> Actualizar version de libreria appboy-android-sdk (braze) - whitelist
=> Upgrade braze's sdk version

android-whitelist.json
-added expire date advertising adn v1.+ 
-added new version advertising ADN v2.+
este cambio incluye los cambios automáticos para soportar api 32 y gradle 14.+
- #7546923
=> bump and expire date Advertising ADN 

android-whitelist.json
The bump is performed due to the migration of Android 12.
* added expires date `ml_esc_manager` v4.+
* added new version `ml_esc_manager` v5.+
- - [PXN-5058](https://mercadolibre.atlassian.net/browse/PXN-5058?atlOrigin=eyJpIjoiMDc3YjE2ZjY5YjlhNDEwY2IxZWEzZTBhZGE2Y2ViNjUiLCJwIjoiaiJ9)
=> [PXN-5058] Bump version to 5.+ and expires version 4.+ - ESC

android-whitelist.json
- Se habilita una versión previa de uso en el SDK de braze (appboy) para android. [18.0.1](https://github.com/Appboy/appboy-android-sdk/releases/tag/v18.0.1)
- #7547145 - Actualizar version de libreria appboy-android-sdk (braze) - whitelist
=> Se habilita el uso de una version anterior de braze (appboy)

android-whitelist.json
The bump is performed due to the migration of Android 12.
added expires date cardform v2.+
added new version cardform v3.+
#7547210 
=> [PXN-5080] Bump version to 3.+ and expires version 2.+ - CardForm

android-whitelist.json
Se extiende la fecha de expiracion de las librerias afectadas por la migración a Android 12
Se añade nuevas versiones
=> Added libraries for support Android 12

android-whitelist.json
- Updated Insurance QPage version to 8 and created expiration date for version 7
- Updated Insurance FloxComponent version to 7 and created expiration date for version 6
=> [Insurance] QPage and FloxComponent Update and Expiration Date

android-whitelist.json
Se extiende el expire de las librerías hasta el 30/09
=> Extended expire libraries

android-whitelist.json
Se actualiza la dependencia de cards components paral a migración a min api 32, y se le agrega un expiration date a la versión anterior
- - #....
=> update cards components whitelist (Migration Max Api 32)

android-whitelist.json
Update in andes components and coachmark modules
`com.mercadolibre.android.andesui:coachmark:6.+`
`com.mercadolibre.android.andesui:components:6.+`
Both updates due the migration to support Android 12
=> Andes 6.+ added (API 32 migration)

android-whitelist.json
Update modal versions to 8.+
Modal module migrated to minApi 23 and meli gradle plugin 15.+ (Android 12)
`com.mercadolibre.android.draftandesui:draft-modal:8.+`
=> Bump draft-modal lib version to 8.+ (Migration API 32)

android-whitelist.json
Se agrega la libreria androidx.swiperefreshlayout:swiperefreshlayout que facilita la acción pull to refresh, se agrega ya que es uno de los eventos que soportamos como equipo de webkit.
Nota: Esta librería estaba implícita en androidx.browser pero al actualizarse de 1.0.0 a 1.4.0, en la nueva versión fue removida.
- - #7548377
=> Added swiperefreshlayout implementation

android-whitelist.json
Agregamos robolectric 4.5.1 : Soporte a java 11 para robolectric 
Necesitamos el cambio porque ci o local no va a poder correr robolectric con java 11 sin este bump
=> [BUMP] Robolectric 4.5.1 and delete old version (4.0.1)

android-whitelist.json
**Se actualiza la versión de Search a `14.+`**
- "com.mercadolibre.android.search:compats:14.0.0"
- "com.mercadolibre.android.search:input:14.0.0"
- "com.mercadolibre.android.search:search:14.0.0"
**Se agrega fecha de expiración para la versión de Search `13.+`**
- #7547859
=> Bump search version to 14

ios-whitelist.json
Se agrega versión 6 para StartupInitializer. La versión 5 queda con fecha de vencimiento hasta diciembre 2022. 
Ticket: #7547872
=> StartupInitializer version 6 is added.

android-whitelist.json
La libreria de reviews tuvo un nuevo release a 2.1.0 dejando la version de whitelist 1.2.1 desactualizada 
- - #....
=> Update library version reviews from 1.2.1 to 2.1.0

ios-whitelist.json
Se sube la version a 2.0.0 debido a refactor de Opentelemetry en 2 subspecs (Core y Setup).
- - #7549111
=> Update Opentelemetry version

android-whitelist.json
Se elimina fecha de expiración para la versión de Search `13.+`
Se eliminan las versiones de Search a `14.+` porque no se llegó a generar por problemas de API 32:
- "com.mercadolibre.android.search:compats:14.0.0"
- "com.mercadolibre.android.search:input:14.0.0"
- "com.mercadolibre.android.search:search:14.0.0"
- - #....
=> Revert Search to version 13

android-whitelist.json
[Native Reauth](https://github.com/mercadolibre/fury_native-reauth-android/releases/tag/4.0.0)
[Native Reauth Adapter](https://github.com/mercadolibre/fury_reauth-native-adapter-android/releases/tag/3.0.0) 
=> Bump up reauth native. (API 32 Migration)

android-whitelist.json
Se solicita la ampliación de expiración de la librería Pos readers  por apertura de dead line para migración a android 12, esto debido a que bloquea PRs que no tienen relación con dicha migración# Ticket ID
- - #....
=> [No-ticket] Update expiration date for Pos Readers 

android-whitelist.json
Se agrega la dependencia `AsyncLayoutInflater` que antes venía en `browser:1.0.0`.
[browser:1.0.0](https://mvnrepository.com/artifact/androidx.browser/browser/1.0.0)
[browser:1.4.0](https://mvnrepository.com/artifact/androidx.browser/browser/1.4.0)
- - #....
=> Add AsyncLayoutInflater dependency

android-whitelist.json
Downgrade hardware_buttons module to 1.0, because migration android 32.
=> Downgrade hardware_buttons module to 1.0.

android-whitelist.json
Se realiza bump de las librerias de NfcPayments y Gamification como parte de la migración a Android 12
- - #7547902
=> bump nfc libs

android-whitelist.json
Solicitamos se extienda el plazo de deprecación de la librería de webkit debido a que el plazo para la migración de Android 12 está para el 13/10 y nuestro equipo añun no soporta android 12 por lo que no podemos hacer uso de la versión 4.0
=> [No-Ticket] Update deprecate date

android-whitelist.json
- Migración a API32 de Touchpoint por un lado. 
- Corrección sobre la version de MLBusiness, ya que no se va a subir el major (Se había  hecho en este [PR](https://github.com/mercadolibre/mobile-dependencies_whitelist/pull/1493) ) de esta Lib debido a que la usan otros equipos y no se vio la necesidad de eso. Sin embargo, la migración a API32 ya se encuentra hecha para versiones con el major 3.+, por lo que, repito no hacia falta el cambio. 
- - #....
=> Api32 migration bumping

android-whitelist.json
Se añade SDK de NFCPushProvisioningService
- - #7546598
=> Added Nfc Push Provisioning SDK to whitelist

android-whitelist.json
- Se actualiza Congrats a API 32 (Android 12)
=> Bump Congrats lib to v 7.+

android-whitelist.json
Se actualiza fecha de expire de las librerías insurance, debido a que no fue posible subir al tren, por problemas con otras librerías.
- - #....
=> Update expires Insurance Qpage and FloxComponent

android-whitelist.json
- Update fcn libs expire dates
=> Update FCN libs expire dates

android-whitelist.json
Agregar una nueva regla para que puedan usar la versión [6.+](https://github.com/mercadolibre/fury_cpg-android/releases/tag/6.0.0) de la biblioteca cpg-ui-components.
- - #....
=> nova regra utilizar a lib cpg-header v4 e v6

ios-whitelist.json
We remove this version since the migration to IOS 13 does not apply to Melidata yet.
- - #....
=> Removed melidata bump to 1.0

android-whitelist.json
Actualizamos las ultimas dependencias de Loyalty migradas a API 32.
- - #....
=> loyalty bump API 32 migration

android-whitelist.json
... Se arregla el group de la dependencia de cash_rails y cashut.
=> Fix group cash_rails and cashout

android-whitelist.json
PEUI es una lib que sirvio de precursor al onboarding unificado, hoy en día ya no tiene propósito de existir pero hasta hace no mucho tiempo algunas de sus pantallas tenían trafico para cubrir casos borde. Esta lib se esta deprecando desde hace un tiempo y estuvimos trabajando con los equipos que la utilizaban a lo largo del año. 
Hoy en día ya no tiene uso en la wallet pero podría haber quedado la referencia en algún `build.gradle` de módulo. Actualizamos la whitelist para que el ci empiece a avisarles de borrarla.
A fin de Q4 estaríamos borrando el repositorio y eliminando la dependencia completamente de la whitelist
- - #....
=> Expiring PEUI

android-whitelist.json
Se actualiza play-services-auth a la version 19.2.0 a causa de un issue encontrado con Android 12.
=> Bump play-services-auth

ios-whitelist.json
Adding new Lib Cross CreditsToolkit.
The purpose of the library is to contain functionalities that are common to the different modules in iOS.
- - #7556557
=> add credits-toolkit whitelist ios

ios-whitelist.json
Se agrega un nuevo repo privado llamado CashRails para MoneyRails solamente IOS por el momento
ver [MICI-710](https://mercadolibre.atlassian.net/browse/MICI-710) 
=> [CHG] adds cashrails libraty to ios only

android-whitelist.json
We first attempted to add the library at [Mobile Testing - Android](https://github.com/mercadolibre/fury_mobile-testing-android/pull/140/files,) expecting we would have just to bump this repository. 
The [linter](https://rp-ci-android.furycloud.io/blue/organizations/jenkins/mobile-testing-android/detail/mobile-testing-android/38/pipeline/) though does not allow it 'cause these libraries should be added to the allow-list. If we add the library here, it doesn't make sense to implement these libraries through core-testing. We could access them directly in the app.
In resume, it's sort of a deadlock situation.
The first sentence is true. The second is not. I.e.:
* [Junit](https://github.com/mercadolibre/mobile-dependencies_whitelist/blob/126b1b0060c9aaeeff02b823d88464ba6ca6777e/android-whiteli …
=> Add test libraries

android-whitelist.json
Modulos de cash rails, para compartir logica de negocio y visual entre cashin y cashout
=> Adding cash-rails modules

android-whitelist.json
Desde el equipo Android de Money In, en conjunto con Andes, estamos llevando a cabo el deprecado de la librería congrats-wallet-android, la cual hoy en día contiene diferentes builders para poder crear una congrat desde un cliente nativo Android.
El motivo del deprecado es la aparición del componente AndesFeedbackScreen, el cual va a suplir dichas congrats ajustándose a los guidelines de diseño que propone Andes como equipo.
La fecha estipulada para dicha acción es el día 31 de marzo de 2023, es decir, el último día hábil de Q1.
Les dejamos a continuación la documentación oficial de Andes para que puedan implementar las Feedback Screen en los casos que aplique y les solicitamos que cualquier duda que presenten con dicha dependencia se pongan en contacto conmigo o cualquiera de los …
=> Added expiration date for congrats wallet android

android-whitelist.json
Add Flipper library to use into developer mode. Developer Mode ofrece herramientas de debug que facilitan la tarea del desarrollador. Flipper solo sera usada en developer mode para aumentar el numero de herramientas disponibles. Flipper trae herramientas como deeplink dispatcher, análisis de peticiones rest, mock de respuestas rest, analizador y editor de componentes de layout, acceso a las bases de datos locales del dispositivo (siempre que se tengan permisos). Ya que Developer Mode solo se usa en Modo Debug (Nunca en release) la librería de Flipper solo estará disponible cuando compilemos en debug.
- #7557949
=> add Flipper library to use in developer mode

ios-whitelist.json
Se agrega la dependencia `CxSupportDaisy` a la whitelist de iOS. La misma provee un nuevo feature de un componente de ayuda nativo. Se adjunta su [documentación](https://furydocs.io/cx-support-daisy-ios/0.2.0).
- - #7559539
=> Add CxSupportYoshi to Whitelist iOS

android-whitelist.json
This lib is used for Mplay.
Mercado Play es un servicio de streaming basado en publicidad que entrega entretenimiento gratuito a personas en Latam con acceso a smartphone / computador. Con el sello de Mercado Libre ofrece una experiencia simple y rápida, donde podrán descubrir una amplia biblioteca de contenido en series y películas, con cortes publicitarios relevantes para cada usuario.
A diferencia de redes sociales, TV abierta o servicios de Live TV, nuestro producto entrega una mejor oferta en series y películas, de forma gratuita, segura, con una cantidad aceptable de publicidad, y una mejor experiencia de navegación.
=> New MPlay Lib

android-whitelist.json, ios-whitelist.json
Se agrega a los archivos de whitelist tanto para Android y iOS las libs de shorts-android y shorts-ios respectivamente. Estas libs pertencen a la iniciativa de Shorts y son libs de webviews donde se usa Webkit2 para mostrar diferentes webs que se tienen en la iniciativa.
Shorts es una iniciativa donde nuestro foco es que a travéz de contenido de Videos cortos el usuario permanezca en la app de MELI, generamos contenido para ello, anteriormente Shorts era Livecommerce, sin embargo, con un enfoque y características diferentes.
=> Shorts webview libraries are added to the whitelist files

android-whitelist.json, ios-whitelist.json
Se agrega a  whitelist  las libs de fury_clips-android y fury_clips-ios.
Estas libs extrae el componente de Shorts  donde el  foco es que a través de contenido de Videos cortos el usuario permanezca en la app de MELI.
#7561670
=> Clips dependency

android-whitelist.json
Por problemas de dependencias en okhttp3 es necesario usar la version 0.45.0 de flipper networking ya que la version que se maneja actualmente en meli (0.90.2) trae por transitividad una version de okhttp3 no compatible con la usada en meli. asi mismo se desea mantener la version de flipper networking 0.90.2 ya que otros equipos la usan.
- #7562084
=> add version 0.45.0 flipper networking

android-whitelist.json
- Se actualiza la versión de Digital Accounts Components a la 5.+ y se depreca la versión 4.+ con fecha de expiración para el 13/01/2023.
- - #7562615
=> [Update] Digital Accounts Components 5.+ and expired 4.+

android-whitelist.json
Moved business logic that was inside the configurators (mp-config-provider-andriod & ml-config-provider-andriod) to the matt-android lib.
=> Matt-android bump

android-whitelist.json
Se actualiza la librería de Places de 2.4.0 a 2.5.0, añadiendo a la antigua versión fecha de expiración para los dispositivos Android. 
Evidencias del uso de la librería de places 2.5.0 en dispositivo Android:
https://user-images.githubusercontent.com/80784177/217015648-335d408e-a1f7-4399-8ee6-63739579f55a.mp4
Evidencias del uso de la librería de places 2.5.0 en Android Studio:
https://user-images.githubusercontent.com/80784177/217021840-8ef75bcf-ab76-43ca-90e9-66ec549c99d7.mov
Documentación: [Link](https://docs.google.com/document/d/1UsX4A-Povv0LUJzzSpoSkgN_Rk939sJPoB3928HlXhY/edit#)
"com.google.android.libraries.places:places:2.5.0"
- ¿Afecta al start-up time de alguna forma?: **No**
- ¿Utiliza libs nativas? ¿Tiene soporte para las diferentes arquitecturas de devices?: **No**
- Impacto …
=> upgrade library version for places 

android-whitelist.json
Con el update del Android Gradle Plugin para 7.2.2, hicimos un bump major el las libs y depreciamos la anterior
- com.mercadolibre.android.home.toolkit
- com.mercadolibre.android.wallet.home
=> Bump libraries by AGP update version (7.2.2)

android-whitelist.json
Addresses version 7.+ se depreca
Addresses version 8.+ se habilita con la migración de java 11 y AGP 7.2.2 + resclient + bug fix de SLA
- - #....
=> addresses version 7 was deprecated and 8 is enabled now

android-whitelist.json
- Se genera el split de navigation manager entre los modulos core y tabbar. Debido a que el equipo de home MP necesita interactuar con la dependencia de tabbar
- - #7567707
=> Split Navigation Manager

android-whitelist.json
[SMARTY-7569](https://mercadolibre.atlassian.net/browse/SMARTY-7569)
Se agrega librería Courier y dependencias necesarias para implementar notificaciones push usando el protocolo mqtt dentro de la app de Smartpos.
Acá se puede consultar información relacionada al poroto [Google Site MQTT](https://sites.google.com/mercadolibre.com.co/instore-mqtt/inicio)
- - #7567655
[SMARTY-7569]: https://mercadolibre.atlassian.net/browse/SMARTY-7569?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [SMARTY-7569] Add Courier library

android-whitelist.json
Con el update del Android Gradle Plugin para 7.2.2, hicimos un bump major el las libs y depreciamos la anterior
com.mercadolibre.android.merchengine
com.mercadolibre.android.merch_realestates
=> Bump libraries by AGP update version (7.2.2) - Home

android-whitelist.json
"com.google.zxing.core:3.3.2"
"com.journeyapps:zxing-android-embedded:3.6.0|4.0.2"
Se solicita extender la fecha, dado que aún no tenemos una directiva por parte de arquitectura para el uso de una lib compatible con Point Smart
7570177
=> Update zxing expiration date

android-whitelist.json
Se actualizan las versiones de cashin y cashout
- - #7571218
=> bump cashin and cashout dependencies

android-whitelist.json
Bump api module from [home-section-api](https://github.com/mercadolibre/fury_home-section-api-android) because [automatic PR bump of AGP 7.2.2](https://github.com/mercadolibre/fury_home-section-api-android/pull/163).
- - #....
=> Bump home-api to 4.+

android-whitelist.json
- Se actualiza la versión de Search a 16.+ y se agrega expires_date a la versión 15.+.
- El cambio de versión en Search se da debido al nuevo comportamiento de Compats, en la que se empieza a aceptar el uso de múltiple dominios. Hasta el momento solo teníamos el dominio de autopartes y en esta nueva versión se acepta el de Neumáticos. Esto generó un cambio en el modelo y en la manera en que se trataban las selecciones de un user, por eso la versión 15 será deprecada en breve.
- - #7571523
=> Update Search dependency

android-whitelist.json
- SPMPOS-71  (https://mercadolibre.atlassian.net/browse/SPMPOS-71)
Hicimos pruebas exhaustivas desde la testapp de cameraX con MLKit, obteniendo como resultado que barcodes que con la librería de terceros de cámara actualmente usada, no eran posibles de resolver.. con cameraX sí lo fueron.
Además, al tratarse de una librería nativa (que al no ser de terceros) tendrá mayor compatibilidad que la utilizada actualmente 
CameraX es compatible con dispositivos que ejecutan [Android 5.0 (nivel de API 21)](https://developer.android.com/about/versions/lollipop?hl=es-419) y versiones posteriores. Esta cifra representa más del 98% de los dispositivos Android existentes ([fuente](https://developer.android.com/training/camerax/camera1-to-camerax?hl=es-419))
sin librería (63.2MB)
con librería (64.3MB) …
=> [SPMPOS-71] update library camerax to 1.1.0

android-whitelist.json
Se realizan bump de cashRails a 2.+ y se agregan los expires correspondientes
- - #....
- [] Mercado Libre
=> Bump cash_rails library's to 2.+

android-whitelist.json
It was already used but directly in MP and ML.
- N/A
=> [Feature] Adds pxUsdk to the whitelist

android-whitelist.json
`com.mercadolibre.android.uicomponents`
- Migration to Android 13
- Permission Read_External_Storage removed
- Migration to AGP 7.2.2. and Java 11
- Bump Versión meliPluginGradleVersion=16.+
- Bump Versión robolectric = "4.5.1"
- Added future migration notice for ErrorHandler
- [permissions] Adding EventBus unregister when permission event is executed.
- - #....
=> Bump UiComponents 16.0.0 Android 13

android-whitelist.json
Bump version SecureInputs
obs: Lib is not in production yet and no project is using it yet, so we did not put the deprecated field in the old version.
- - #....
=> [TRIVIAL] Bump version SecureInputs 1.+

android-whitelist.json
Crashlytics library name fixed to **core**.
**Internal library** - [Crashlytics](https://github.com/mercadolibre/fury_fbm-wms-crashlytics-android)
=> [FIX] Crashlytics library name fixed

android-whitelist.json
Se añade nueva lib de [NfcPushProvisioning](https://github.com/mercadolibre/fury_nfc-push-provisioning-android)
- #7550904 without lib size
- #7579639 with lib size (906KB)
=> Added NfcPushProvisioning to whitelist

android-whitelist.json
Se realiza el update de las libs de kotlin 1.8.10 & room 2.4.3que son necesarias para la migracion de kotlin . 
Se adjunta [analisis](https://docs.google.com/document/d/1htpvmhXiVTdgiY-oGwlosHccxc2CsVXI8Ah3_YmKENI/edit#heading=h.jbfac7s0vyhp) de la migración, que es necesario para agregar un cambio a la allowlist.
- - #....
=> Update bump kotlin and room

android-whitelist.json
Necesitamos cambiar la fecha de expiracion de la libreria ml-scanner 10.xx para que todas las equipos que tienes la dependencia puedan pruebar la version 11.x.
- - #....
=> extend deprecation ml-scanner 10.x

android-whitelist.json, ios-whitelist.json
Actualizar la fecha de expiración de Andes Draft Modal, hasta el 30 junio 2023
=> Update expiration date AndesUIDraftModal

ios-whitelist.json
Fix MLNetworking version specification. It was accepting the patch number, which is wrong.
The way it was, a lib using MLNetworking could specify version '~> 0.39.0' which is not compatible with '0.40.0', blocking future updates of the lib in the apps.
- 
=> Fix MLNetworking version specification

android-whitelist.json
Se extiende el periodo de expiración, debido a que se esta trabajando en la migración desde firebase-ads a nuestra librería in-house de ADN, puntualmente para el site de MLV aun se utiliza firebase-ads para traer publicidad desde googleAdManager.
- - #....
=> Update expire date firebase-ads

ios-whitelist.json
Se adicionan las etiquetas de description y expires para la propiedad SecurityOptions, debido a que se removera esta librería el 30 de Junio del 2023
- - #2447
Para más información visitar [Jira.](https://mercadolibre.atlassian.net/browse/SE-2447)
=> [SE-2447]: Rev eliminación de security-options IOS

ios-whitelist.json
Reverts mercadolibre/mobile-dependencies_whitelist#1883
Hacemos este revert porque nos encontramos con problemas al intentar actualizar los pods del repositorio [fury_bf-purchases-ios-legacy](https://github.com/mercadolibre/fury_bf-purchases-ios-legacy), entonces optamos por no cambiar el mayor de la versión que queremos sacar de [**MLPurchases**](https://github.com/mercadolibre/fury_bf-purchases-mobile-ios) para evitarnos estos problemas y poder seguir con el release.
=> Revert "Update MLPurchases/Integration version to 3.X.X"

android-whitelist.json
PTM lib to schedule alarms that trigger job executions.
- - SMART-3447
=> [SMART-3447] Adding PTM's qualified alarm lib to whitelist.json

ios-whitelist.json
Necesito cambiar el número de subversión del paquete "SmiSdk-swift" de "4.2.1" a "4.1.2", porque había trocado el número de subversiones que vamos a usar en production. 
- - #....
=> Bump Smisdk to vrsion 4.1.2

android-whitelist.json
Due to Recharge library's Kotlin migration to 1.8.10, it's necessary to update the version major number because even thought it won't cause a breaking change on our app (since smartpos  is already migrated), it can cause a crash if this library were used in previous releases of the app. 
- - #....
=> Update library version: recharge 7.+ -> 8.+

android-whitelist.json
Due to Recharge library's Kotlin migration to 1.8.10, it's necessary to update the version major number because even thought it won't cause a breaking change on our app (since smartpos  is already migrated), it can cause a crash if this library were used in previous releases of the app. 
- - #....
=> Update version: helpers 3.+ -> 4.+

android-whitelist.json
Due to the library's Kotlin migration to 1.8.10, it's necessary to update the version major number because even thought it won't cause a breaking change on our app (since smartpos  is already migrated), it can cause a crash if this library were used in previous releases of the app. 
- - #....
=> Updatte virtualization 3.+

android-whitelist.json
Due to Recharge library's Kotlin migration to 1.8.10, it's necessary to update the version major number because even thought it won't cause a breaking change on our app (since smartpos is already migrated), it can cause a crash if this library were used in previous releases of the app.
- - #....
=> point-credits 3.+ -> 4.+

android-whitelist.json
Buenas!, actualmente tenemos el [repo de geofencing](https://github.com/mercadolibre/fury_instore-experiments) muy desactualizado; no tenemos como probar esta lib ya que la api que creaba las audiencias murió y no hay algún desarrollador que nos pueda dar soporte, además hemos intentado encontrar interesados en que esta funcionalidad siga viviendo en meli pero hasta ahora no ha sido posible. Vemos un muy bajo tráfico en producción por lo que se observa en tracks(Ya habíamos apagado un ff con anterioridad que controlaba esta funcionalidad). Dado que se requiere dar soporte a Android 13 y nos comentaron que el repo requiere implementar una lib de [data privacy](https://furydocs.io/dp-product-it-documentation/v1.4.0/guide/#/dp-suite/data-privacy-helper/index) se decidió eliminar esta lib. …
=> Deprecate instore geofencing

ios-whitelist.json
Bump DatadogSDK version to 1.21.0 to fix a bug.
- - #7587043
=> Bump Datadog SDK version to 1.21.0

android-whitelist.json
- Create flan dsl module with major bump version.
- The RP of Mercury is a little bit more complex than ML/MP. We have a larger TTM. The larger expires there are settled because major 2 is productive, 3 didn't even start the rollout and we already have the 4 major. Lots of tech debts being paid.
=> Major bump flan with core n dsl modules

android-whitelist.json
Se requiere deprecar la versión 8.+.+ por lo tanto se agrega la nueva version 9 y se agrega un expire en la versión 8.
- - #....
=> Attestation Lib: Add version 9 and set expire version 8

android-whitelist.json, ios-whitelist.json
Andes Draft Modal expira el 3 de agosto de 2023
- - #....
=> Expiration Andes Draft Modal

android-whitelist.json
- - #....
Como se discutió en el canal war-room-mobile, necesitaremos lanzar un hotfix que depende de las versiones que ya han salido de la allowlist, por lo que necesitamos estas versiones por un tiempo más.
[war-room-link](https://meli.slack.com/archives/C04LY39HG6A/p1691013455869829)
- - #....
=> Soporte para hotfix mplay en la 10.272 de ML Android 

android-whitelist.json
Actualización de la version de datadog para cambio de la versión de Kotlin 1.8.10
- - # 7576055
=> Bump datadog version

android-whitelist.json
Since we at mPOS will have more libraries to update with MPP we decided to make the MPP version more efficient to avoid update every time it's necessary.
Also I created three new libraries which will be maintained by the mPOS team.
- mPOC :: The base library which will communicate with mPOS module
- MyPinPad: :: Library which contains a logic to use MPP library.
- InHouse :: In future we will replace MPP library to an Inhouse solution.
- - #....
=> [ISPMPOS-744] Updated MPP version and created whitelist to mPOC libraries

android-whitelist.json
Se aumenta la versión de Search a la 18 debido a la migración a Kotlin 1.8.10
- - #....
=> [Search] Bump version to 18

ios-whitelist.json
- Debido a que el equipo encargado de la librería de MoneyOut no ha podido realizar el cambio de la dependencia de MPContacts se cambia la fecha de expiración de la librería de Realm y MPContacts para el 08-09-2023
- N/A
=> [Update] change the expiration date for MPContacts

android-whitelist.json
ESC Manager Bump version to 6.+ and expires version 5.+
- - #....
=> [Feat]: ESC Manager bump to 6.+ and expires 5.+

ios-whitelist.json
Bump Datadog SDK to 1.23.0 to fix issue APM not connecting to RUM
- - #7591704
=> Bump DatadogSDK to 1.23.0

android-whitelist.json
We are removing the expiration date from the MQTT dependency because there isn't a defined expiration date for generating the first major version, 1.0.
- [SMART-4197](https://mercadolibre.atlassian.net/browse/SMART-4197)
[SMART-4197]: https://mercadolibre.atlassian.net/browse/SMART-4197?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [SMART-4197] Update the expiration date of the MQTT dependency

ios-whitelist.json
Debido a que se han presentado algunos inconvenientes con los PR para el cambio en el manejo de las dependencias de MPContacts de la librería MLMoneyOut se cambia la fecha de expiración de la librería de Realm y MPContacts para el 30-09-2023 para tener el tiempo suficiente para hacer la transición correspondiente.
- N/A
=> [Update] change the expiration date MPContacts

ios-whitelist.json
En este PR se fija versión de MLThreeDS a 2.0.6. 
=> MLThreeDS Version 2.0.6

android-whitelist.json
Se genera un rollback para la librería de Globe dado que no se logró avanzar con la integración de la version 2.2.5-55 en la wallet
- - #....
=> [Feature] Rollback Globe lib from 2.2.5-55 to 2.2.1-52

android-whitelist.json
Se agrega expire a la libs de rxjava en post de comenzar a avisar a los equipos que no es recomendable utilizar esta libs, en 2024 se estara trabajando en remover esta libs.
- - #....
=> update expire rxjava 2

android-whitelist.json
Como parte de la migración a OkHttp 4, debemos subir el major de Everest para evitar romper libs que se traen por transitiva OkHttp desde Restclient y hacen uso de la misma. 
Relacionado a este [PR](https://github.com/mercadolibre/mobile-dependencies_whitelist/pull/1949)
- - #....
=> Bump Everest

ios-whitelist.json
Bump version of CardForm on iOS
- - #....
=> [iOS] bump CardForm v5 & adding expires date to older version

android-whitelist.json, ios-whitelist.json
This PR is required to be merged, before than [pr validate expire day](https://github.com/mercadolibre/mobile-dependencies_whitelist/pull/2044)
According to a new validation, libs cannot expire wednesday or thursday so, the expires date that don't achieve this validation, are modified 
- - #....
=> Expires day are modified in order to the new validation

android-whitelist.json
Se modifica la fecha de expiración de ml_cards para ingresar en el siguiente tren 10.282 con la versión 3.0.
Esta librería era utilizada únicamente por `[advertising-android ](https://github.com/melisource/fury_advertising-adn-lib-android/)` hasta su versión 5.6.*, y el día de hoy hicieron el `[bump](https://github.com/melisource/fury_mercadolibre-android/pull/12581/files)` a la versión dónde ya no hacen uso de la lib. 
Según nuestros registros era la única librería que la utilizaba, se corroboró también generando el árbol de dependencias. 
- - #....
=> Expire ml-cards

android-whitelist.json
This PR is required to be merged, before than [pr validate expire day](https://github.com/mercadolibre/mobile-dependencies_whitelist/pull/2044)
According to a new validation, libs cannot expire wednesday or thursday so, the expires date that don't achieve this validation, are modified
- - #....
=> Libs that expires wednesday or thursday are modified in order to the new validation

android-whitelist.json
- Se agrega everest 2.+ para que todas las versiones que tengan kotlin 1.8 puedan utilizarla sin problema de retrocompatibilidad con la version 1.+
=> Add everest 2.+

android-whitelist.json, ios-whitelist.json
This PR is required to be merged, before than https://github.com/mercadolibre/mobile-dependencies_whitelist/pull/2079
According to a new validation, libs cannot expire wednesday or thursday so, the expires date that don't achieve this validation, are modified
- - #....
=> Libs that expires wednesday or thursday are modified in order to expire validation

android-whitelist.json
- com.mercadolibre.android.errorhandler.v2:core version set to the latest one (v2.+), which includes the migration to Android 13
- v1+ expiration date set to two weeks from today.
- - #....
=> Error handler v2 added and v1 marked as deprecated

android-whitelist.json
Se esta trabajando en mejoras para el nuevo dispositivo N950 y se actualiza el Major debido que provoca un breaking change en la libreria de pointsmart-sdk. Se deja el expire en al 31/12/23 por para versiones recientes.
- - #....
=> Update json pointsmart sdk

scripts/checkdate.rb
Se realiza fix de [validacion de fecha de expire](https://github.com/mercadolibre/mobile-dependencies_whitelist/pull/2044). No se realizaba manejo de rama `else` por lo que no realizaba la validacion correspondiente.
Antes de mergear este PR, [se debe mergear este primero](https://github.com/mercadolibre/mobile-dependencies_whitelist/pull/2087), que modifica las fechas de libs que expiran miercoles o jueves. Caso contrario, fallara el CI.
Se muestra que ahora si realiza la validacion cuando hay un expire que cae miercoles o jueves:
- - #....
=> [Fix] validation date fixing

android-whitelist.json
Se quita la version 6.0.0 ya que esta lib pertenece a ML Config provider y aun no se han realizado todas las migraciones de Kotlin 1.8, lo cual esta ocasionando problemas.
=> Remove credits behaviour 6.0.0

ios-whitelist.json
-     Update app-monitoring-ios major version to 2
- app-monitoring-ios Internal Lib
- O tempo de expiração de 3 meses foi escohido por causa do tempo em que o rollout demora e que ainda esteja disponível em caso de rollback .
=> Add app-monitoring-ios 2.0

android-whitelist.json
Se agregan las versiones con mayor subido, correspondiente al breaking change de la [migración kotlin 1.8.10](https://github.com/melisource/fury_ml-scanner-android/pull/110). También se fija un expire para las versiones previas.
- - #....
=> ML scanner breaking change

android-whitelist.json
Allows version 1 of behavioral SDK. Sets expire date to 31-12-2023.
- - #....
=> Allow major 1 of behavioral sdk

android-whitelist.json
Due to Kotlin 1.8 migration, the version 5.0 of cardform dependency has changed your proposal and must follow the migration guidelines, with expiration date to `2023-10-31`.
A new version of this dependency (cardform v6) will be released soon with new features and the accorded expiration date to `2023-12-31`.
- - #....
=> Card Form: Update Expire Date

android-whitelist.json
Se corre la fecha de vencimiento de ML-scanner del 30-10 al 13-11 solo para mercadolibre, ya que algunos integradores no se han migrado a Kotlin 1.8.10 por estar fuera del scope (apps != ML / MP)
apps por fuera:
- preparation-app 
- [fury_shipping-crowd-android](https://github.com/melisource/fury_shipping-crowd-android)
- [fury_shipping-logistics-android](https://github.com/melisource/fury_shipping-logistics-android)
- [fury_shipping-flex-android](https://github.com/melisource/fury_shipping-flex-android)
- - #....
=> Expiration time extended for ML-scanner lib version

android-whitelist.json
Bump de Melidata a 18.+ debido a migración de clases públicas de Java a Kotlin
- - #....
=> Bump Melidata to 18.+

ios-whitelist.json
Actualmente, appmonitoring-ios utiliza Datadog SDK 1.0+ como el principal proveedor de observabilidad (RUM, Logs y ErrorTracking) que brindamos a nuestros clientes.
Sin embargo, en nuestro trabajo continuo con Datadog en los últimos Qs, identificamos la necesidad de features específicas que Datadog no ofrece actualmente.
Datadog se compromete a introducir estas nuevas features en su version SDK 2.0+, asi que solicito este update en la allowlist.
La version SDK 2.0 es la modularizacion de todo el SDK 1.0 en Productos
Se realizaron pruebas integradas con MDS. Evidencias en el [[RFC] Datadog SDK 2.0](https://docs.google.com/document/d/1iWk3WvreEBelH7qdZkcSl3dLKJV2zxsm_sv6HIuxeME/edit):
- Incremento de peso: **0,1MB**
- Incremento startup time: **0,7 ms** 
validados con el equipo Performance …
=> Add DatadogSDK 2.0 and expire to 1.x versions

android-whitelist.json
- Se actualiza la versión de Digital Accounts Components a la 6.+ y se agrega fecha de expiración para la versión 5.+ para el 12/01/2024.
=> [Update] Digital Accounts Components 6.+ and added expiration date to version 5.+

android-whitelist.json
`Se actualiza la version de la librería NFC a 6`
No agregué fecha de expiración para la version 4 porque desde la version 2.302 de wallet que no se utiliza la versión 4 👀 
No sabemos por qué no saltó antes el warning de allowlist. Vamos a agregar el whitelisteo a nuestras documentaciones internas de generación de version. (Hoy vimos que figurabamos en la lista en el siguiente thread: https://meli.slack.com/archives/CSKLKAGC8/p1702564150055939)
- - #....
=> Update nfc-payments lib version

android-whitelist.json
xprod_flox_components version 0 was deprecated and 1 is enabled now. Module zipcode was deprecated from addresses.
- addresses version 8.+ se depreca
- addresses version 9.+ se habilita con la migración de Kotlin 1.8
- xprod_flox_components version 0.+ se depreca
- xprod_flox_components version 1.+ se habilita con la migración de Kotlin 1.8
- Modulo zipcode de addresses se depreca
=> addresses version 8 was deprecated and 9 is enabled now.

android-whitelist.json
Las librerías que se actualizaron son:
- mercado coin: 5.+ a 6.+
- navigation-manager: 4.+ a 5.+
- crossAppLinks: 7.+ a 8.+
- navigation-menu: 9.+ a 10.+
- - #....
=> Update navigation libs version

android-whitelist.json
El mismo tema de este [PR](https://github.com/mercadolibre/mobile-dependencies_whitelist/pull/2208) anterior. Pero faltaron los sub-modules de la lib. Es la misma version. Las mismas usadas en las pruebas.
Build Scan
Mercado Pago  https://gradle.adminml.com/s/kkzh2mpzvob6y
Mercado Libre https://gradle.adminml.com/s/wcj7duyerzxgo
Con la inclusión de las versiones de work-runtime 2.8.1 y room 2.5.1 en las apps MP / ML, se realizara la actualización de la lib externa de datadog.
-- [Documento](https://docs.google.com/document/d/1dTdNFRRW6OAGSjBPEFFmZXorHFusEDLL5Y6Xd-6vupE/edit) de análisis.
-- [Comunicado](https://meli.workplace.com/notes/1410496432911912/?mode=edit&notif_id=1701444592182654&notif_t=work_knowledge_note_permission_grant&ref=notif) workPlace.
No se hace la actualización de las …
=> Update Datadog libs

android-whitelist.json
Se actualiza la librería WebKit version 7.+ a 8.+ debido a la migración de Kotlin 1.8.10 de la lib.
=> Updated the allowed version of Webkit.

android-whitelist.json
Bump Andes 8.+ . This breaking change includes kotlin 1.8.10
=> Andes Bump 8.+

android-whitelist.json
Esta nueva version para MLKit-text-recognition es necesaria para emparejar a v18.x.x con MLKit-barcode. El que no esten ambas versiones emparejadas trae un crash al usar OCR
- - #....
=> MLKit text-recognition bumped to v18

ios-whitelist.json
Esta librería se crea para dividir el funcionamiento de la librería de MLCart en 2. Y en un futuro reemplazar a MLCart en la app de MercadoLibre
=> ADD CartFacade in iOS whitelist

android-whitelist.json
Se agrega modulo de exoplayer para solucionar errores en el touchpoint de home (clips) que utiliza exoplayer
[Link](https://web.furycloud.io/help/tickets/107196?page=1&teams=false) a la solicitud
PR a la integrada para excluir el modulo: https://github.com/melisource/fury_mercadolibre-android/pull/13166/files
PR en homes para importar ese modulo: https://github.com/melisource/fury_homes-android/pull/1300
#75103855
=> exoplayer module added

android-whitelist.json
- Se actualiza la versión de Digital Accounts Components a la 7.+ y se agrega fecha de expiración para la versión 6.+ para el 31/03/2024 coincidente con la de OkHttp3.
- Se aguarda a que se destrabe este [PR](https://github.com/melisource/fury_da-components-android/pull/327) para pasarlo a _Ready for review_
=> [Update] DaComp to version 7.+ and added expiration date to version 6.+

scripts/checkkeynames.rb
Se actualiza el step de checkkeynames del pipeline de validación del json de xyz-whitelist.json para inclui el nuevo feature de "allow granular project".
Referencia al error en CI:  https://app.circleci.com/pipelines/github/mercadolibre/mobile-dependencies_whitelist/6838/workflows/26c74218-c5e9-4fa4-a6b3-b1522a864dc2/jobs/16021
Referencia a la nueva key: https://github.com/mercadolibre/mobile-dependencies_whitelist?tab=readme-ov-file#android-platform
=> [Feature] allows_granular_projects key added to pipeline checks

android-whitelist.json
Agregamos las dependencias que ya se encuentran en [ML](https://github.com/melisource/fury_mercadolibre-android/blob/594433ec2f3cbe0641e44f31ec2876dfdb465ca4/gradle/libs.versions.toml#L602) y [MP](https://github.com/melisource/fury_mercadopago-android/blob/82e1f563b1e065d3594111e332eb5f2711c483bf/gradle/libs.versions.toml#L736) para jetpack compose. Pero con la granularidad de que solo andes pueda utilizarla de momento.
**IMPORTANTE**: si llegan PRs agregando proyectos a la granularidad por favor no los mergeen, que se contacten con alguien del equipo de declarativo. Henrique Mota, Nicolas Suarez, Alejandro Funes o yo.
=> [Feature] Add declarative dependencies for allowed projects only

android-whitelist.json
- Remove CardForm v6 from Android Whitelist
- This version no longer exists and was removed from android artifacts
- Fury Ticket: #75108406
=> Remove CardForm v6 from Android Whitelist

android-whitelist.json
Adds new lib to allow list. This library is used in SMART projects, and it manages the card reader process developed by the SF team.
=> [SMART-5603] Add Reader Manager SF lib to the allow list

android-whitelist.json
Se realiza el update de las librerias de android x para empatar las librerias en todo meli. (este update ya fue realizado en Q4 en las apps principales)
<meta charset="utf-8"><b style="font-weight:normal;" id="docs-internal-guid-fb5c58b3-7fff-ca2d-8e0f-f920bd8428ea"><p dir="ltr" style="line-height:1.2;text-align: justify;background-color:#ffffff;margin-top:0pt;margin-bottom:0pt;"></p><div dir="ltr" style="margin-left:0pt;" align="left">
Libreria | Versión | Se actualiza a
-- | -- | --
appcompat | 1.3.1 | 1.5.1
lifecycle | 2.3.1 | 2.6.1
fragment | 1.3.6 | 1.4.1
activity | 1.2.4 | 1.7.2
core | 1.6.0 | 1.9.0
</div><p dir="ltr" style="line-height:1.2;margin-left: 36pt;text-align: justify;background-color:#ffffff;margin-top:0pt;margin-bottom:0pt;"><br /></p></b><br …
=> Update libs android x + expire

android-whitelist.json, ios-whitelist.json
`Se agrega la dependencia para el módulo de Virtual Try On en Android`
- - #....
=> [Feature] Add Virtual Try On in Android

android-whitelist.json
- Se habilita ODR para utilizar las dependencias de Jetpack Compose.
-  #75109588
=> [feature] add odr for compose

android-whitelist.json
Necesitamos Bajar la versión de Bitmovin por un problema de compatibilidad con el equipo de Clips que afecta también a homes, pero este downgrade nos va a volver a afectar con el problema de conflictos que teniamos con el equipo de VPP. Así que por ahora dejo ambas versiones para poder actuar dependiendo de las decisiones que se tomen, en conjunto con la solución que nos de bitmovin. 
Por lo menos por ahora, es importante poder bajar la version de Bitmovin.
- - #113819
=> Bitmovin Downgrade

ios-whitelist.json
Se agrega OneExperience a la whitelist, librería interna que contiene capability para una sola experiencia.
=> Add One Experience library

android-whitelist.json
Se realiza el bump firebase bom y de las libs de play services unicamente habilitada para las librerias que suben en conjunto con la app el 14/3
[Versiones que se actualizan
](https://sites.google.com/mercadolibre.com/mobile/gu%C3%ADas-y-problemas/migraci%C3%B3n-firebase-google-play-services)
=> Bump Firebase&Gps

android-whitelist.json
Agregamos el proyecto de integrationes de andes (inyeccion de temas y fuentes) a la allowlist granular
=> Add andes-integrations to allows_granular_projects in declarative

ios-whitelist.json
Se corrigen los nombres de las libs de Everest, figuraban como `Everest` pero debe ser `EverestLibs`
Actualmente el plugin que verifica las dependencias no es exhaustivo, solo valida contra el comienzo del nombre de la lib y como se va a [corregir](https://github.com/melisource/mobile-cocoapods_whitelist/pull/23) este comportamiento es necesario corregir los nombres en la allowlist.
- - N/A
=> Fix Everest name

android-whitelist.json
Habilitamos el modulo de components-compose para usar en andes-integration
=> Allow Andes compose-components for andes-integrations module

android-whitelist.json
Se quita del allowlist la version 33, la cual incluía una version de gps locations con issues.
Se agrega commons a granular de shadowapi ya que necesitan hacer un implement.
=> refactor commons version

android-whitelist.json
Add in allow granular of compose the tetris project that uses this dependencies
- - #....
=> Add tetris in allow granular for compose

android-whitelist.json
Se rollbackea versión de authentication 26, se deja como versión actual la 25.
- - #....
- [ x ] Interna: Libreria/modulo desarrollado in-house en base al ecosistema de Meli.
- [ x ] No
=> rollback de authentication version 26

android-whitelist.json
- Version 8 of the SecurityTwoFa library is still available so we decided to extend its expiration date.
- - #....
=> stf extend v8

android-whitelist.json
Se extiende la fecha de firebase perf, aun hay equipos que utilizan la dependencia, desde nuestro equipo, retiraremos la logica que esta en la lib de metrics y eliminar la dependencia que tenemos con firebase perf.
- - #....
=> Firebase perf expires date

android-whitelist.json
Se agregan dependencias que son necesarias para nuestra nueva herramienta de testing de accesibilidad ([MAI](https://github.com/melisource/fury_a11y-testing-framework-android))
- #75112749
Nota: estas dependencias se usarán en un módulo interno que sólo será incluido en la demoapp de Andes Android.
=> Add MAI dependencies with granularity

android-whitelist.json
Agregamos la lib de bottomsheet en demand core. Va a ser usada por Vpp como por search como una lib interna
- - #....
=> add allowlist to bottomsheet module of demand core

android-whitelist.json
- Update commons to 36.+
- Problem error: https://meli.slack.com/archives/CSKLKAGC8/p1712671803197229 (Transitive deps)
- It is not wanted to adopt version 35.+
=> Update commons to 36

android-whitelist.json
Se extende la fecha de expiración de libs para que se permita seguir con los PR de intent-fix al release de MP 2.322 y MP 2.323 
https://github.com/melisource/fury_home-wallet-android/pull/1775
https://github.com/melisource/fury_home-wallet-android/pull/1776
- - #....
=> Extended advertising, melidata and restclient expire date

android-whitelist.json
Se extende la fecha de expiracion de la lib `restclient-adapter-rx2:23.+` para permitir seguir con el PR de un intent-fix: 
https://github.com/melisource/fury_home-wallet-android/pull/1775
- - #....
=> Extend expire date for restclient-adapter-rx2:23

android-whitelist.json
Se suma la lib `restclient-adapter-rx2:24` para permitir seguir con el intent-fix al release 2.323: 
https://github.com/melisource/fury_home-wallet-android/pull/1776
- - #....
=> Extend restclient-adapter-rx2:24 for intent-fix purpose

ios-whitelist.json
Debido a un tema de conflictos con el CDN de Cocoapods referente al nombre Screenshots al querer instalar la librería como dependencia se generaba un error donde trataba de instalar la librería Screenshots que viene de ios-specs y también la de Cocoapods. Seguimos las intrucciones según la documentación para definir la prioridad de los source pero no nos funcionó así que se decidió a que la mejor solución es cambiar el nombre de la lib de nosotros de Screenshots a MLScreenshots.
Este cambio lo podemos hacer sin problema ya que aun no se está usando esta lib.
- - #....
=> Change Screenshots name to MLScreenshots

android-whitelist.json
Bump Restclient 24 temporarily because this version was fixed and it now doesn't include AndroidX migration any more, so teams can use it until AndroidX migration's deadline
- - #....
=> Bump Restclient 24

android-whitelist.json
Se cambiaron las fechas de expiración de los siguientes módulos de security_two_fa:
- Totpinapp
- Faceauth
- Core
- Totp
Se agrega detalle acerca de la eliminación del módulo TOTP de manera permanente. 
- - #....
=> Change expiration date of security_two_fa libraries

android-whitelist.json
- Update Bugsnag lib to 6.4.0
- Update expire Bugsnag lib 5.29.0
- MP: https://gradle.adminml.com/c/wm7zciaaallfs/pt5iaqvzrc5pk/dependencies
- ML: https://gradle.adminml.com/c/j2of2vhkotwao/22qtlvkxcax7i/dependencies
- https://web.furycloud.io/help/tickets/118273
=> Bump Bugsnag Lib to 6.4 and Update Expires for 5.29

cross-kmp-allowlist.json
Se añade Coroutines y KTor.
Tamaño de cada dependencia:
Coroutines -> se mantiene la misma de Android
ktor-client-core -> 91kb
ktor-client-content-negotiation -> 3kb
ktor-serialization-kotlinx-json -> 5kb
Por ahora estas libs solo estan disponibles para el proyecto de Realtime Communication (RTC). 
El uso de KTOR se decidio porque es posible comunicar a servidores SSE . Las librerias de Meli de Networking (ios) y resclient (Android) tambien son usadas en este proyecto para obtener los headers y obtener una comunicación efectiva hacia APIs dentro de Meli.
master -> [link](https://gradle.adminml.com/s/6uxq55hwihcw6)
rtc. mobile -> [link](https://gradle.adminml.com/s/tpyszfzkm4q4e)
**COMPARACIÓN DE MASTER CON RTC MOBILE (APP ML)**
[Link de diferencia de …
=> Coroutines and ktor for KMP

android-whitelist.json
The expiration date for SDK from Visa was updated
https://github.com/mercadolibre/mobile-dependencies_whitelist/pull/2297
=> Update expiration date for visa kernel library

android-whitelist.json
Se actualiza el expire de las libs de firebase & gps ya que se actualizo el roadmap de la migración a causa de un incidente.
=> Update expire firebase&GPS

ios-whitelist.json
Add Stripe Bar in allow list. This lib don't have dependencies external
https://github.com/melisource/fury_stripe-bar-ios
- - #....
=> add stripe bar to allow list

android-whitelist.json
Due the update versions of appcompat/commons tuvimos que subir la version de fcu para 13.+.
Let the version until end of the year because the Smart team is behind of usage and have more time to align correctly.
- - #....
=> Updated fcu versions to 13+

README.md, scripts/checkkeynames.rb
Agregamos la documentacion para  soportar transitividad . 
Depende del merge de [este PR](https://github.com/melisource/fury_qcs-build-pu-android/pull/23) y el deploy de controles de calidad 
Depende del merge de [este PR](https://github.com/melisource/fury_qcs-build-information/pull/69) de QCS Information
=> Add transitivity doc

ios-whitelist.json
- Update Bugsnag version to 6.28.1
- Since we're migrating our issue tracker from commons to AppMonitoring, we are updating the Bugsnag SDK with it. 
- - #75118946
=> Update Bugsnag version to 6.28.1

android-whitelist.json
We upgraded Andes to Android 14, so we created the new major for our library and expired Android 13 support implementations.
=> Bump Andes 10.+ and expire 9.+

android-whitelist.json
Bump Cashin 17.+ by android 14 migration and expire 16.+
=> Bump Cashin 17.+ and expire 16.+ 

android-whitelist.json
Bump Cashout 14.+ by android 14 migration and expire 13.+
=> Bump Cashout 14.+ and expire 13.+

android-whitelist.json, ios-whitelist.json
Se agrega MPSearch, feature de busqueda desde la home de Mercado Pago.
El uso de SwiftUI del lado iOS se encuentra aprobado, por lo que también se agregan los permisos.
- - #....
=> Add mpsearch to whitelist

android-whitelist.json
PR con update de la versión de appMonitoring 2.+/3.+ a la versión 4.+ que contiene la migración del modulo de commons crahstrack a la lib hub appMonitoring. 
- version 2.+ debe quedar por que la usan las app mercury / smartPos "ya ellos saben de la migración"
- versión 3.+ versión actual y creada para el [update de libs Android X](https://meli.workplace.com/notes/1148014866540731?saml_reauth=1718111795&request_id=hmbgofipnbmgadihnlkochaoalcnimfbokagnlmc&login_type=1).
- versión 4.+ migración mudulo crahstracking de commons. 
- - #....
=> Update AppMonitoring v3 to v4

android-whitelist.json
We add the `integrations-compose` module (part of the andes_integrations project). We are migrating certain parts from the `components-compose` module (part of the andesui project) so we must authorize the same projects that already have access to the `components-compose` module:
=> [Feature] Add integrations-compose module and declare granular projects

.pre-commit-config.yaml, android-whitelist.json
Esta dependencia es necesaria para poder ejecutar pruebas de snapshot en Jetpack Compose cuando hay animaciones presentes. Si bien para snapshot test usamos Paparazzi, la versión mínima que funciona con animaciones en Compose es la 1.3.0 que requiere Java 17 y Gradle 8. Para hacer mocks de estas animaciones y usar pruebas de snapshot con Paparazzi 1.2.0 agregamos el plugin de mockposable el cual usa en su entorno de test la libreria de jetbrains.compose runtime.
https://mvnrepository.com/artifact/org.jetbrains.compose.runtime/runtime
=> Added jetbrains runtime for mockposable implementation

android-whitelist.json
Andes-integrations: delete 3.+, add expire to 4.+ and add stable 5.+
El cambio de mayor viene por la migración a Android 14
=> [Feature] Andes-integrations: delete 3.+, add expire to 4.+ and add stable 5.+

android-whitelist.json
Bump:
- NavigationCP v13
- UINavigationCP v13
- Addresses v11
- XprodFE Component v3 
- XprodFE Modules v3
Upgrade por Android X.
- - #....
=> Bump Android 14 - NavCP UINavCP Addr Mod Comp

android-whitelist.json
Se agrega la versión de navigationManager 7.+ para el repo de home, es necesario para continuar con tabbar en home
- - #....
=> Add navigation Manager version to home

android-whitelist.json
Add new version of Webkit with the number 11.+ and added an expire date into Webkit 10.+ with the date "2024-08-01"
=> [Update] Webkit to 11 and expire webkit 10

android-whitelist.json
Se extiende el deadline de firebase & gps dado que aun no se impactaron las migraciones en las apps principales
=> Extend expire firebase&gps

android-whitelist.json
-Se realiza un cambio en el major version debido a la migración a Android 14
-Debido a que no se mergeó el cambio de nombre del package de la librería, se retrotrae ese cambio
-Se descarta de manera momentánea la eliminación del módulo totp de la whitelist. 
- - #....
=> Edit security two fa in whitelist

android-whitelist.json
Se actualiza el major de screenshot_manager por el bump que tuvo de la migracion a android 14
- - #....
=> Update android-whitelist.json for screenshot_manager major bump to 2.+

android-whitelist.json
Se actualiza las siguientes librerías por breaking change:
buyingflow-cho-sdk-android ---> 15.+
marketplace-android-map --> 16.+
rule-engine-android ---> 13.+
bf-flox-components-android ---> 13.+
smart-coupons-android ---> 7.+
buyingflow-android ---> 5.+
payment-android ---> 5.+
core-flox	---> 3.+
Se colocan la fecha de expiración el 28/09/2024
=> Update all Checkout libraries

android-whitelist.json
Both teams, OneExperience and Identity validation require please to extend CameraView's expire date. 
**NEXT, HOW WE ARE?:**
- **_[ml-scanner-android](https://github.com/melisource/fury_ml-scanner-android) [OneExperience]_** -> CameraView usage was totally replaced by CameraX (controlled by FeatureFlag). So,  in the meanwhile we are monitoring CameraX performance, its desirable to preserve CameraView.
- **_[auth-remedies-mobile-android](https://github.com/melisource/fury_auth-remedies-mobile-android) [Identity Validation]_** -> They'll finish to implement CameraX at beggining of Q3. Then, they'll take it to production and rollout it.
- - #....
=> CameraView expire date extension requirement

android-whitelist.json, ios-whitelist.json
Review V6 dependency added to whitelist.
- https://github.com/melisource/fury_buyingflow-review-android
- `implementation "com.mercadolibre.android.buyingflow_review:review:{version}"`
- https://github.com/melisource/fury_buyingflow-review-ios
- `dependency 'BuyingflowReview', '~> {version}'`
=> Review V6 dependency added to whitelist

android-whitelist.json
Bump Screenlock libs:
- Risk Management 7.+
- Userbiometrics 10.+
- Security_preferences 11.+
- Security_ui 10.+
- - #....
=> Bump up  Screenlock libs - Android 14

android-whitelist.json
- Se agrega multiplayer a la lista de projectos con la dependencia de transfers_components
- - #....
=> Add multiplayer to granular projects of transfers_components dependency

android-whitelist.json
Este PR es para poder empezar a usar la version 21.0.1 del service de location para la nueva lib de [location](https://github.com/melisource/fury_location-android)
- - #....
=> Location lib added to use play-services-location 21.0.1 version

android-whitelist.json
Scanners 14 version expire date changed
Posponemos el vencimiento de v14 del Scanner, debido a problemas que hubo con la migracion a la nueva lib de Permissions
- - #....
=> Scanners 14 version expire date changed

android-whitelist.json
Se agregan dependencias granulares usadas en módulos del proyecto da-components-android que son usados en otros proyectos de distintos equipos de Digital Accounts para testing
- - #....
=> Added granularities for da components

ios-whitelist.json
HorizontalCards es una dependencia que tienen cards y otras views que compartilha de home y search , es para nuevo proyecto llama Home Diagonal 
- - #....
=> Added HorizontalCards in ios-whitelist.json

android-whitelist.json
Se extiende la fecha de expiración, ya que depende de la migración de android 14
Cuando se haga la migracion, ya no usaremos la version   "version": "3\\.29\\.0" de interactivemedia
- - #....
=> Extend expiration date to interactivemedia

ios-whitelist.json
Agregamos el subspec donde vamos a utilizar la librería de AppTheme, ya que no funcionaba el granular sin especificar el subspec.
- - #....
=> Change the subspec to fix the granular

android-whitelist.json, ios-whitelist.json, scripts/check_version_pattern.rb, scripts/checks.sh
Se agrega script para chequear que si una lib es externa debe tener una versión fija.
En caso de que se intente ingresar con una lib externa que contenga un versionado dinamico mostrara el siguiente error:
Ej. iOS
Ej. Android
=> Added check version pattern script

android-whitelist.json
Incorporar com.mercadoenvios.android.authentication_enrollment y com.mercadoenvios.android.authentication_enrollment a allow_granular
Para poder completar con la migración realizada por arquitectura en [ESTE PR](https://github.com/melisource/fury_auth-android-authentication/pull/286) es necesario resolver el siguiente error:
`- (Granular dependency not allowed for this project) com.google.android.gms:play-services-auth:20.7.0`
Este error sucede al correr el CI de la rama en cuestión.
Este cambio se realiza agregando las libs de authentication a granularity, solucion propuesta [AQUI](https://meli.slack.com/archives/C06KS2448JK/p1723215626403179)
=> Add authentication and authentication_enrollemnet to allow_granular

ios-whitelist.json
- Add Selling Framework as granular dependency for MPDynamicSkeleton
Selling Framework CI fail, because Selling Framework (IspSf) was not listed as a granular dependency of MPDynamicSkeleton: https://rp-ci-ios.furycloud.io/blue/organizations/jenkins/isp-sf-ios/detail/isp-sf-ios/3340/pipeline
--
=> Add Selling Framework as granular dependency for MPDynamicSkeleton

cross-kmp-allowlist.json
Removemos los `expires` para las libs que utliza `rtc-mobile`, ya que estamos en una etapa próxima a salir a producción y vemos como finales estas dependencias.
=> Remove rtc-mobile expires in cross-kmp-allowlist.json

android-whitelist.json
Necesitamos la extenision del vencimiento de ml-scanner-android (solo para este proyecto) con motivo de un rollback necesario como hotfix en la 2.344 MP
- - #....
=> v14 scanner added just for grwth

android-whitelist.json
Se actualiza whitelist para versiones del checkout:
Core-flox 4.0
Payments 6.0
SDK 16.0
SmartCoupons 8.0
=> Update Checkout Versions

android-whitelist.json
libs: conjunto fresco y MPAndroidChart
N/A
TODO
=> Add granularity to external libs v002 (fresco)

android-whitelist.json
libs: bugsnag, applinks, fb-android-sdk
elimino: rx-preferences que no se encontraron usos.
N/A
TODO
=> Add granularity to external libs v001 (bugsnag, applinks, fb-android-sdk)

android-whitelist.json
Este PR agrega la dependencia para la versión 2.+ de la librería de MoreLikeThis. Además, elimina una dependencia experimental de la misma que no es necesaria.
- - #....
=> Add MoreLikeThis 2.0 version

android-whitelist.json
libs: libsodium, play-services varias, integrity
N/A
TODO
=> Add granularity to external libs v003 (libsodium, play-services Varias, integrity)

ios-whitelist.json
Se agrega en la whitelist un nuevo repo del equipo de HomeWallet (Mercado Pago), Multiwidget.
- - #....
=> [Added] Add Multiwidget library to iOS whitelist

android-whitelist.json
Se agrega la lib de shorts al granular project de navigation manager ya que es necesario para el flujo de clips con la Tabbar
- - #....
=> Add shorts to granular projects for nav manager

android-whitelist.json
Se agrega expire a libs de stetho debido a que esta versión se encuentra deprecada de 2022 y ya no se esta utilizando, ademas esta versión no es compatible con libs androidX, en pos de apagar jetifier es necesario que se remueva.
- - #....
=> Expire libs stetho

android-whitelist.json
Se agrega nueva versión de facebook soloader y se deja un expire para la versión anterior. Por otro lado se agrega las dependencias que lo utilizan mediante la configuración "implementation" a un esquema de granularidad.
=> new facebook soloader version

ios-whitelist.json
Agrego a la dependencia granular de MoreLikeThis Search/Core iOS en vez de "Search"
- - #....
=> Change MLT granular dependency for SearchCore subspec

android-whitelist.json
Bump OkHttp Dns.
Es un módulo necesario para sobreescribir los dns de los request con la finalidad de minimizar errores de UHE de nuestras apps.
[Traffic Mobile](https://app.datadoghq.com/notebook/6770083/no-response-traffic-mobile-apps) acá se puede observar la cantidad de UnknownHostException y el impacto que podríamos generar al recuperar un porcentaje de los mismos.
- - #....
=> Bump OkHttp Dns

android-whitelist.json, cross-kmp-allowlist.json
Se agrega granularidad y transitividad a la dependencia `modiface`, para q solo se pueda implementar dentro del proyecto de `virtual_try_on` y evitar que se propague transitivamente a otros repos.
- - #....
=> [Update] Modiface - add granularity and transitivity

android-whitelist.json
=> Add granularity to external libs v004

android-whitelist.json
=> Add granularity to external libs v005

android-whitelist.json
Por un error reportado del equipo de User Accounts se decide revertir estos cambios:
"Se agregó hace 1 hora el `allows_granular_projects` solo a 3 packages para que puedan usar view binding https://github.com/mercadolibre/mobile-dependencies_whitelist/pull/2866/files . Y ahora no nos permite utilizarlas en nuestros proyectos"
- - #....
=> Revert "Add granularity to external libs v005"

android-whitelist.json
Transitivity a libs externas
La idea es tener una visibilidad de las libs externas y quienes las consumen
Dividir este PR en partes para bajar la cantidad de soportes/consultas
=> Granularity to external libs

android-whitelist.json
Desde el equipo de switch de cuentas de colaboradores nos solicitaron un cambio en la lib auth-remedies-mobile-android para poder soportar colaboradores en nuestro flujo, ya que de no hacerlo se les muestra una pantalla de bloqueo a los usuarios.
Dado que auth-remedies-mobile-android es una lib que migramos a person-validation-android, sigue contando con el uso de CameraView (la nueva lib usa CameraX), por lo que no podemos sacar nuevos releases si no esta whitelisteada la lib de CameraView. Por esto es que nuevamente se pide extender la lib de CameraView para poder sacar el release con el cambio de soporte de colaboradores.
Por más información del cambio, esta el siguiente [RFC](https://docs.google.com/document/d/1zXN7oob3K1Y1Zy-Fm4YmQEtdf_S9bH6hFjfsUGGYAxo/edit?pli=1#heading=h.34kpp25js4 …
=> Extend cameraview for collaborators

android-whitelist.json
Este PR pasa la fecha de expiración del módulo de MLT dentro de search android para el 13 de Octubre. Esto se hace para proveer más tiempo a quienes lo necesitan de migrar a la nueva librería y evitar errores en creación de versiones y PRs dónde no se ha realizado.
- - #....
=> Postpone MLT expiration date to 13th of October 2024

android-whitelist.json
Actualizacion de dependencia granular para Moneyout
Se permite mlkit-text-recognition como dependencia granular del proyecto moneyout.
Actualmente moneyout utiliza esta librería para la funcionalidad de escanner de tarjetas de crédito y débito para MLM. Se 
pretende migrar este desarrollo a la libreria scanner_ml, aún no se tiene fecha de cuando se va a realizar esta migración, 
pero se tiene en el radar.
- [Conversacion slack al respecto](https://meli.slack.com/archives/CSKLKAGC8/p1726242815151929?thread_ts=1726090584.469769&cid=CSKLKAGC8)
=> add granular dependency to moneyout

android-whitelist.json
Remoción de librería que no es más requerida para proyecto de ar measures de WMS
=> Remove lib of zxing

android-whitelist.json
Se necesita habilidar demandcore para usar flexbox por un componente nuevo de price
- - #....
=> add flexbox allow for demandcore

android-whitelist.json
Added `Android-tetris` project to use the coil library
...
- - #....
=> Added tetris-android in allows_granular_projects coil compose

android-whitelist.json
=> Add granularity to external libs lote 008

ios-whitelist.json
Agregamos la dependencia de CrabDI, por ahora limitado solo a ser usado dentro de CcapCommons.
Esta nueva dependencia expone el codigo que antes se encontraba en uno de los subspecs de CcapCommons.
- - #....
=> add CrabDI to whitelist

ios-whitelist.json
Expiration date added for MpGadgets because it is a frontend library and does not need to be on the whitelist.
- - #....
=> added expire date to MpGadgets

android-whitelist.json
- Se realiza cambio de granulación con login. Login se invoca de otra manera desde las dependencias de la monolitica.
`meli-login = { module = "com.mercadolibre.android:login", version.ref = "login" }`
Por este motivo la forma correcto que se debe granular es   `"com.mercadolibre.android:login"
Granulandolo de esta manera el error se arregla.
```
ERROR: The following dependencies are not allowed:
- (Granular dependency not allowed for this project) com.google.android.gms:play-services-recaptcha:16.0.0
```
=> Corrección en la granulación de Login

android-whitelist.json
En Q4 vamos a estar migrando a los actuales consumidores de la version 12 (Legacy, deprecada) a la version 15 de ml_scanner-android ([Migracion](https://docs.google.com/document/d/16Z6LXOAZ_ck-gBJhQM3NdYrnpjs5vKltkKbxy3gzd7E/edit)). Debido a que el integrador Point_smartpos-android es incompatible con MLKit18 (Debido a la ausencia de GooglePlayServices en dispositivos Point) que usa el scanner v15 actual, proveeremos (por medio de Flavors) una v15 con MLKit17 (no dependiente de GooglePlayServices).
- - #....
=> MLKit17 expire dates removed

android-whitelist.json
Se agrega `Search` a la lista de dependencias que pueden usar Jetpack Compose para implementar [Polycard](https://github.com/melisource/fury_polycards-android)    
- - #....
=> [Feature] Add Search to Compose dependencies

android-whitelist.json
New description to some jetpack compose dependencies that are only allowed to be used by WMS team. Also removed teams that were using these dependencies
=> Removed teams from granular dependencies

android-whitelist.json
We're adding the :widgets module from mp_search to the whitelist, to use it in home-wallet
- - #....
=> [HomeWallet] Added widgets module from mp_search

android-whitelist.json
Se agrega la libreria AI Assistant Client a la lista de libs permitidas para usar Room.
- - #....
=> Add IA Assistant to room granular dep allowed 

ios-whitelist.json
Se downgradea la version de MLMap para no bloquear releases de otros equipos
=> Downgrade MLMap version

ios-whitelist.json
Se agrega la lib de FujiDI y se agrega al control granular de CrabDI
- - #....
=> Add FujiDi to supported project using CrabDI

ios-whitelist.json
The lib expires today (15/10/24). This PR removes MpGadgets from the allowlist.
- - #....
=> Remove MpGadgets

android-whitelist.json
Se agrega la lib de engagement-component a la lista de granularidad de lottie
El cintillo de Gamification en homes tendra una animación para la cual queremos usar lottie
https://github.com/user-attachments/assets/d26962aa-486a-4707-bb13-f0eb6f7f7f13
- - #....
=> Engagement-component lib with lottie

android-whitelist.json
[ISPMPOS-3050] added lib zdfend to whitelist
I added new zdefend lib used to make local attestations.
This is a certified library with PCI norma.
- - # [4480016](https://shield.adminml.com/requests/4480016)
[ISPMPOS-3050]: https://mercadolibre.atlassian.net/browse/ISPMPOS-3050?atlOri …
=> [ISPMPOS-3050] added lib zdfend to whitelist

ios-whitelist.json
Se pide agregar la nueva lib de checkout shipping "BuyingflowShipping", que forma parte del conjunto de nuevas librerias que nacen con la migracion de MLCheckout v5 a v6.
- - #....
=> Se agrega la lib de BuyingflowShipping a la whitelist de iOS

android-whitelist.json
- Changing libraries used in the WMS Ar Measures project.
We are replacing the com.gorisse.thomas.sceneform:sceneform:1.23.0 library with the native Google libraries ([com.google.ar](http://com.google.ar/).sceneform.ux, [com.google.ar](http://com.google.ar/).sceneform, and com.google.ar.core) to ensure you have access to the latest ARCore updates and native library support. The com.gorisse.thomas.sceneform library has been discontinued.
The use of augmented reality on Mercury WMS relates to the need to measure large packages, which could not be done by any other systemic tools.
- - #....
- https://web.furycloud.io/help/tickets/22371
=> Change used libs list in arMeasures project

ios-whitelist.json
Se agrega como dependencia granular la lib de HomeIndustries para que pueda consumir VerticalsCore
[ ] Leí el contenido de este Pull Request y acepto que recibiré seguimiento del mismo una vez su contenido esté completo.
=> Add HomeIndustries to VerticalsCore granular dependency

android-whitelist.json
- Luego de agregar Koin en [este PR](https://github.com/mercadolibre/mobile-dependencies_whitelist/pull/2964/files), eliminamos de momento la `transitivity: false`
- Por otro lado, sumamos Crab-DI, la lib que funcionará como wrapper de Koin, con granularidad para 3 repos
<table>
<thead>
<tr>
</tr>
</thead>
<tbody>
<tr>
</tr>
<tr>
</tr>
</tbody>
</table>
> <ul><li>- [X] Leí el contenido de este Pull Request y acepto que …
=> Add Crab DI (Koin wrapper)

android-whitelist.json
Estoy realizando el cambio porque el [CI](https://rp-ci-android.furycloud.io/blue/organizations/jenkins/security-preferences-android/detail/security-preferences-android/1518/pipeline/273/) me está fallando, por eso estoy ajustando y cambiando a `com.mercadolibre.android.security:security_preferences`.
Adjunto error:
> ERROR: The following dependencies are not …
=> Change security_preferences for add apptheme
