mercadolibre/mobile-dependencies_whitelist

- ios-whitelist.json
La libreria es necesaria para Mensajeria y para Notifications. Es la "pastilla azul" que indica que hay nuevos mensajes.
> [Feature] iOS add: MPTopFloatingView.

- android-whitelist.json
desde checkout dependemos de la lib de recommendations
> Add Recommendations to android whitelist

- android-whitelist.json
Se agrega el módulo de shipping components a la whitelist
> Add shipping components to whitelist

- ios-whitelist.json
Para evitar que nos falle [travis](https://github.com/mercadolibre/buyingflow-mobile_ios/pull/2333)
> Se agrega Firebase para evitar warnings en MLCheckout

- ios-whitelist.json
Creo MLSearch/Suggestion con la version 3.*.* y indento bien firebase que estaba feo indentado
> Added MLSearch/Suggestion

- README.md
- android-whitelist.json
JSON now is conformed per:
```
{
whitelist: [
{
group: "regex",
name: "regex",
version: "regex",
expires: "yyyy-MM-dd"
}
]
}
```
Squash, since it was branched from a testing branch
> Refactor of dependencies JSON

- android-whitelist.json
- ios-whitelist.json
Responsables de los módulos:
* **Android:** Nicolas Fortunato
* **iOS:** Demian Tejo
* **PL:** Matias Liwsky
> Se agregan las dependecias de PX

- android-whitelist.json
Agregamos las dependencias de RxAndroid y RxJava para Android.
> [Android] Added Rx dependencies

- android-whitelist.json
- ios-whitelist.json
Se agregan los componentes de ProgressCircle y MultiImageView tanto para iOS como para Android.
> Adding components

- ios-whitelist.json
En myml estamos creando un lib de commons, para reautilizar código entre los diferentes proyectos.
> Agrega dependencia para proyectos de myml

- android-whitelist.json
En MyML estamos creando un lib de commons, para reutilizar código entre los diferentes proyectos.
El repo desde donde usaremos esta commons lib es:
https://github.com/mercadolibre/myml-android_subscriptions
> Agregar dependencia para proyectos de myml Android

- ios-whitelist.json
Se agrega la dependencia de DynamicLinks para prender apertura contextualizada para la iniciativa Viral Loop de descuentos
> Update Firebase dependencies

- android-whitelist.json
We are adding kotlin stdlib to the master whitelist
> Impact Kotlin to master

- android-whitelist.json
- ios-whitelist.json
Se agregan las libs de mapas a la whitelist para que puedan ser utilizadas desde SYI.
> Whitelist maps

- android-whitelist.json
- ios-whitelist.json
* added lottie deppendency in android
* added dependency in iOS
> Lottie (#43)

- android-whitelist.json
> Agrego las dependencias del SDK

- android-whitelist.json
Elimino filtro de version asi es posible actualizar la dependencia de constraint layout
> Allowing different versions of constraint layout

- android-whitelist.json
This is needed ASAP in order to be able to release module integrations
> Add new Variations Module to the Whitelist

- ios-whitelist.json
Se llevan los cambio de dev a master
> Dev -> Master

- android-whitelist.json
En el PR #69 se rompe la syntax.
> Fixed syntax

- android-whitelist.json
add `com.mercadopago.android.px:checkout`  to the whitelist
> Add PX lib to whitelist

- android-whitelist.json
Se agregan dependencias para la nueva arquitectura
> Add dependencies for new architecture

- android-whitelist.json
Agrego la dependencia para la nueva lib de mapa
> Android - MapLib

- android-whitelist.json
- ios-whitelist.json
Initialli, it will be used only by Instore
> Adding Discovery module for Android and iOS

- ios-whitelist.json
Se agrega la dependencia del sdk de MP a la whitelist
> add MPSDK to whitelist

- android-whitelist.json
Porque me esta fallando el módulo font-configurator de los providers de ML: https://circleci.com/gh/mercadolibre/fury_ml-config-provider-android/2584
> Agrego Calligraphy v2.1.0

- android-whitelist.json
- ios-whitelist.json
Llevo los cambios de develop a master
> Develop -> Master

- android-whitelist.json
Se agregan media-compat y v4 support libs
> Adding some support libs

- android-whitelist.json
Se removió la versión anterior(que contenía guiones bajos) y se agregó la nueva(que contiene puntos).
> Updating On Demand Resources from whitelist

- android-whitelist.json
Agregamos deps de los nuevos profile-data y profile-picutre
> Add profile data/picture deps

- android-whitelist.json
Agrego la dependencia para la nueva lib de card-header que será usada por checkout
> Android - Card header

- android-whitelist.json
Se arregla la versiones porque quedaron mal :D
> Firebase versions fix

- android-whitelist.json
Se downgredean las versiones porque no era las que usamos actualmente.
> Downgrade Firebase versions to the one we use

- android-whitelist.json
Se agrega CPG Library como nueva entry.
Author: @leandrotemperoni
> Added CPG Library

- android-whitelist.json
Subimos las dependencias de GPS y Firebase para dar soporte a nuevos features en las apps de ML y MP
> Actualizamos las dependencias de Firebase y GPS 

- android-whitelist.json
Fixeamos el update que quedo mal
> Fix dependencias de firebase y gps

- android-whitelist.json
Reverts mercadolibre/mobile-dependencies_whitelist#124
> Revert "Added dagger-android-support"

- android-whitelist.json
Reverts mercadolibre/mobile-dependencies_whitelist#122
> Revert "Whitelist Dagger dependencies for Android"

- ios-whitelist.json
Para que pueda incluirse en los Fends de iOS
> Se agrega el SDK de Biometrics para iOS

- ios-whitelist.json
Add `MLClassifiedsDynamicFlow`:
https://github.com/mercadolibre/fury_classifieds-dynamic-flow-ios
This lib adds functionality of creating dynamic flows:
| | | | 
|---|---|---|
| ![](https://user-images.githubusercontent.com/1062240/48778657-97368080-ecb4-11e8-9188-139033400672.gif) | ![](https://user-images.githubusercontent.com/1062240/49037406-e5f28780-f198-11e8-9eac-1458cb5a37e2.gif) | ![](https://user-images.githubusercontent.com/1062240/48950839-4a081800-ef1b-11e8-876b-4a6657962489.gif) |
En equipo Classificados estamos cerca de primer release de Dynamic Flow - la librería que estamos haciendo para `Pedir Presupuesto` - Servicios.
Esta lib será utilizada para construir flujos dinámicos - parecidos a SYI.
En wiki tenemos un par de ejemplos: …
> 💪 Add `MLClassifiedsDynamicFlow`

- ios-whitelist.json
Se agrega librería que permite ingresar montos con el formato correcto tipo currency
> Added AmountLabel lib

- android-whitelist.json
Dynamic Flow Library already added to Whitelist
> Dynamic Flow

- ios-whitelist.json
Se agrega la dependencia del nuevo módulo de colaboradores. Que contiene todo lo referido a controles de permisos para los usuarios operadores
> Se agrega dependencia MLCollaborators

- android-whitelist.json
Agrego la dependencia a draw bridge: https://github.com/mercadolibre/fury_buyingflow-bridge-android
> Agrego dependencia a DrawBridge

- ios-whitelist.json
La agrego ahora que hicimos la release 0.1.0 de Flox.
> Se agrega Flox

- android-whitelist.json
Se agrega la librería de attestation que contiene el feature de Safetynet.
> Add attestation lib

- android-whitelist.json
- ios-whitelist.json
**Descripcion**
Estamos con un track que consite en la construccion de una nueva seccion de dashboard en donde mostraremos, entre otras cosas, graficos de ventas, etc.
**Objetivo**
Estamos generando una libreria generica para generar widgets que contendran charts (que por detras usará las librerias que cargo en esta whitelist).
Si bien el objetivo inicial es usarla para crear la seccion de dashbord, la idea es que escale a otros teams y pueden utilizar.
La misma lib tendrá la documentacion correspondiente y deberia ser super simple agregar un "widget" a su flujo.
Las librerias que estamos generando seran:
- https://github.com/mercadolibre/fury_mobile-charts-android
- https://github.com/mercadolibre/fury_mobile-charts-ios
Dichas libs, nos permitiran crear un widget que podran contendrán …
> Chart libs

- ios-whitelist.json
Se agrega MLVIPLinkScanner a la whitelist ya que empieza a ser dependencia de Questions
> Add MLVIP/URLScanner

- android-whitelist.json
Se habilita la dependencia de `biometrics_ui`
> Se incluye biometrics_ui

- android-whitelist.json
- Re ordeno alfabéticamente el JSON de Android
- Agrego Bookmarks y History
> Re-sorting Android JSON file + adding History and Bookmarks libraries

- android-whitelist.json
Reverts mercadolibre/mobile-dependencies_whitelist#160
> Revert "Updated Support Libs Versions"

- android-whitelist.json
Agrego la libreria de login a la white list para usar el modulo en MercadoPago
> add login lib

- android-whitelist.json
Se agrega dependencia de libreria de congrats generica.
La idea es impulsar el uso de esta libreria para que los fends que tengan que realizar una congrats se les haga mas facil.
> Add Congrats Dependency

- android-whitelist.json
Whitelisted Support Library v28.0.0
> Whitelisted Support Library 28

- ios-whitelist.json
Esta lib la utilizamos para descargar y cachear imágenes. 
https://cocoapods.org/pods/PINRemoteImage
> add pinRemote 2.1.4

- android-whitelist.json
repo: https://github.com/mercadolibre/buyingflow-mobile_android/
> Added commons dependencies needed for Checkout

- ios-whitelist.json
Agrego a la whitelist de ios el repo [milestone tracker](https://github.com/mercadolibre/fury_milestone-tracker-ios)
> Agrego milestone tracker a la whitelist de ios

- android-whitelist.json
> Update Whitelist including LibSodium-JNI

- android-whitelist.json
Se remueve la version de la dependencia de activities para Android.
> Activities version removed

- android-whitelist.json
Adding adjust sdk and installreferrer to android whitelist
> add adjust to whitelist and installreferrer

- android-whitelist.json
> Sort JSON alphabetically and adding Commons libraries

- android-whitelist.json
- Se suben las versiones a utilizar para los modulos que consume la Home de MP a la version 1.+
> [Home-Dependecies] - Updating carrousel, banner and discount benefits v1.+

- android-whitelist.json
> Add matt lib

- android-whitelist.json
Se agrega la lib de fontela a la whitelist
> add fontela

- android-whitelist.json
Se corrige el nombre del módulo
> Correct Name Timesquare

- ios-whitelist.json
Reverts mercadolibre/mobile-dependencies_whitelist#216
@LFuryk hacelo de nuevo porfa pero con la versión fija.
> Revert "Bugsnag Version"

- ios-whitelist.json
Reverts mercadolibre/mobile-dependencies_whitelist#217
> Revert "Revert "Bugsnag Version""

- android-whitelist.json
dejo habilito  la version 2.+ del rule engine
> Change rule engine fixed version

- android-whitelist.json
> Temporal whitelist of API 27

- android-whitelist.json
- Agrego el SDK de Datami para navegacion gratuita.
> SDK Datami

- android-whitelist.json
> Add registration android lib

- android-whitelist.json
Se agrega a la whitelist la librería de soporte de "customtabs"
> Add support custom tabs

- android-whitelist.json
Signed-off-by: Gabriel Cerceau <gabriel.cerceau@mercadolibre.com>
> Add zxing core library

- ios-whitelist.json
Subo la versión mínima de Flox a 2.0.0
> Bump flox to version 2

- android-whitelist.json
Agrego a la whitelist la nueva lib pública de Card drawer. Va a ser usada por Checkout y PX
> Android - Card drawer

- android-whitelist.json
- ios-whitelist.json
Se fijan los mayors para todas las versiones de la whitelist. En caso de externos, se fija la versión completa. 
No se debe mergear antes de realizar la comunicación
> Fix all mayor versions

- android-whitelist.json
Add flexbox to dependencies list
> Se agrega flexbox 0.3.0

- android-whitelist.json
Se crea una lib con componentes comunes para home, vip, pdp y variations (nuestroos repos), esto nos va a permitir tener todo en un lugar y poder bajar un poco el tamaño de la app por cosas duplicadas
> Add vip commons

- android-whitelist.json
> Fix vip commons package

- android-whitelist.json
Se va a utilizar en Notifications para reemplazar al JobsScheduler.
> Se agrega la librería de WorkManager

- ios-whitelist.json
Ambas son libs creadas inhouse
> Adding MLRxRestClient and MLCommonUIComponents

- ios-whitelist.json
Se creó librería para manejo de Flux por parte de los clientes:
https://github.com/mercadolibre/fury_flux-client-ios
> MLFluxClient added to WhiteList

- android-whitelist.json
Se prepara la whitelist para cuando este merged ODR5
> Prepare for ODR5

- android-whitelist.json
Reverts mercadolibre/mobile-dependencies_whitelist#252, hasta que tengamos las libs publicadas y ahi enforzamos
> Revert "Prepare for ODR5"

- android-whitelist.json
La version 2.8.0 que es la ultima trae androidx.
> Added image-cropper version 2.7.0

- android-whitelist.json
We added flavors to "merchengine:carrousel"
> Adding new regular expressions for merchengine

- android-whitelist.json
Se actualiza la whitelist para incluir el nuevo módulo de addons de PX
> Updated android-whitelist

- ios-whitelist.json
Es la lib que creamos para seguridad en pagos.
> Add MLBiometricSecurity.

- ios-whitelist.json
Se agrega nueva lib de components de negocio de UI
Más info en:
https://github.com/mercadolibre/mlbusiness-components-ios
> Add iOS MLBusinessComponents Lib

- android-whitelist.json
- "com.mercadolibre.android:user_configuration:develop-1+"
- "com.mercadolibre.android:user_configuration:production-1+"
_Si, OkHttp es mantenida por una comunidad extensa e incluso es propiedad de SquareUp_
_Creemos que no es necesario un wrapper de la lib. La vamos a usar desde otra lib utilitaria (el REST Client) y para el resto de los devs debería ser transparente los cambios que haya en futuros releases …
> User configuration lib

- android-whitelist.json
> solved conflicts with rule

- android-whitelist.json
- "com.google.firebase:firebase-ml-vision:17.0.+"
Genera una diferencia de 0,2 MB en el peso de la app.
No encontré
Poco madura, lib en beta.
Si, el mantenimiento esta a cargo de google.
Tenemos el problema que esta versión fue generada hace un año, y que la tenemos "topeada" porque en la siguiente versión empieza a soportar AndriodX
El ownership va a ser el [equipo de Identity](mailto:identity@mercadolibre.com)
Hay varias, el Q pasado estuvimos analizando algunas pero ninguna nos convenció por motivos de usabilidad y resultados obtenidos.
No, si requiere un start-up la primera vez que se invoca al modulo, ya que descarga algunos modelos- 
No encontre info
Robustecer la experiencia de pedido de selife en el frontend de validación de identidad.
- [Pr proof of …
> Nueva lib de firebase para detección de caras

- ios-whitelist.json
- MLNavigation 
El impacto es positivo a futuro ya que se va a remover mucho código de `mobile-ios`
Es interna 
Primera versión 
Es interna
Hoy
Es lib interna del equipo de Mobile Arquitectura. 
No existe, resuelve una necesidad concreta para nuestra arquitectura. 
No directamente, pero nos da herramientas para impactarlo positivamente en un futuro.
No.
iOS 10.0
Para el manejo de deeplinks externos en la app. La lib es agnóstica al negocio de ML por lo que puede ser usada por otras apps de MercadoLibre.
- mobile-ios branch ->[ **feature/routing-ios**](https://github.com/mercadolibre/mobile-ios/tree/feature/routing-ios)
- mobile-ios
- fury_ml-config-provider-ios
> New lib core: MLNavigation

- android-whitelist.json
Actualizamos major de search input y recommendations por update del min api level en ambas libs. Dejamos además vieja entrada con el major-1 para no romper a las libs que todavia no se actualizaron.
> Add recos and search entry for new versions

- ios-whitelist.json
- MLQADB
Compilando la testapp de VPP con y sin QADB, el peso aumenta 0,4MB
Es interna
Primer version
Es interna
Hoy
No, es interna. El owner es el equipo de Search
Ninguna, responde a un nuevo caso de uso para el flujo de preguntas/respuestas.
No, se utiliza en Vips y PDPs
No
IOS 10
Queremos evitar la necesidad de que los usuarios pregunten antes de comprar, mediante un buscador de preguntas con contenido curado.
- https://github.com/mercadolibre/fury_vpp-ios/pull/377
- VIP https://github.com/mercadolibre/vip-ios
- VPP https://github.com/mercadolibre/fury_vpp-ios
> Add QADB to whitelist

- android-whitelist.json
Se agregan las lib al whitelist. Estas librerías van a ser usando en los nuevos flujos de Registro y Login por teléfono.
> Feature add hint picker and sms verification lib 

- android-whitelist.json
- "com.mercadolibre.android.vpp:vip_commons:1.+"
Ninguno, ya que este modulo se encuentra en el [repo de PDP](https://github.com/mercadolibre/fury_vpp-android), y ya esta productivo.
Es un lib con funcionalidad común al equipo que maneja VIP/Homes/PDP. Lo que hicimos durante el desarrollo de PDP, fue ir identificando código duplicado entre estos 3 fends, y colocarlo en un módulo separado, para que pueda ser importado desde los otros 2 fends.
Es manejado por nosotros mismos, es interno.
El 6/11/2019, el día de ayer. Con cada release de PDP se genera una nueva versión.
No, no afecta.
No, no tiene codigo con NDK.
Ya estamos en API 19 en este repo y el repo a importarlo también.
Es un lib con funcionalidad común al equipo que maneja VIP/Homes/PDP. Lo que hicimos durante el desarrollo de PDP, …
> Add vip commons entry

- android-whitelist.json
Actualización a la minApiLevel 19 en las siguientes libs
- "com.mercadolibre.android.buyingflow.bridge:4.+"
- "com.mercadolibre.android.marketplace.map:6.+"
- "com.mercadolibre.android.rule.engine:3.+"
> Actualización de dependencias

- ios-whitelist.json
Sodium
-
-
_Bastante madura. 
_Si, siempre están haciendo updates en la lib.
_Hace 11 dias
_Creemos que no es necesario un wrapper de la lib. 
_No, Sodium no requiere inicializacion en el `Application`_
Foundation. Si, tienes soporte.
XCode 10.2. Swift 5 y Swift 4.2 source compatible
Estamos creando nuevas features con la equipo de Cards y es necesario hacer criptografia de varias informaciones de las tarjetas.
-
mpmobile-ios_wallet (vamos agregar nuestra libreria cards-engagement-ios en wallet. Todavia no hicimos esto)
- [x ] Mercado Pago
> changed ios whitelist json - adding Sodium

- android-whitelist.json
La dependencia ya la tenemos actualmente, simplemente que el lint gradle no estaba activado en la lib
- "org.aspectj:aspectjrt:1.9.2"
122512 bytes (122 kb?)
Bastantes, es una lib bastante conocida y utilizada para muchisimas APIs (p.ej. Hugo)
Muy madura. Es iterada bastante seguido y tiene un codebase enorme
Esta en desarrollo activo
Mayo 2019
Esta wrappeada via Metrics
Se pueden usar otros elementos que funcionen a base de AOP, pero es la mas conocida en el mercado (junto a ser estable, mantenida, etc)
No, no se inicializa ya que el weaving lo hace en compile time
No
No aplica. No es android.
A traves de Metrics, va a permitirnos crear metricas totalmente transparente sobre un codebase al cual no tenemos acceso
- https://github.com/mercadolibre/fury_metrics-android/pull/10
- …
> AspectJ 1.9.2

- ios-whitelist.json
### PR que dependen de este cambio:
https://github.com/mercadolibre/mpmobile-ios_wallet/pull/4727
https://github.com/mercadolibre/mobile-ios/pull/4271
Hace 1 semana
> bump version Remedy

- ios-whitelist.json
Ninguna, solo un incremento en version en dependencia a firebase.
Es un bump de una versión, no se agrega nada nuevo
Meli ya esta usando la dependencia
Re madura
La mantiene google de forma activa
Hace 8 días
No se va a wrappear, el owner es el equipo de mobile-arquitectura
N/A
Puede ser, al igual que la version que ya usamos
Esta diseñada para apple que tiene menos diversidad devices que mi abuela por parte de padre
N/A
Tracking, etc. Los mismos que ya estamos usando actualmente
También en Metrics
N/A
Los que usan Firebase, https://docs.google.com/spreadsheets/d/1soaM7UnGAeg7CexkcXT5o_UrbVC57K-qms5yZacCK3Q/edit#gid=0
> support next version firebase

- ios-whitelist.json
- MLMetrics 1.*
- MLFirebase 1.*
- MLNavigation 1.*
El mismo hasta ahora, los cambios implican solo reorganización interna de código
Meli
Son libs internas, las usamos en ml y mp
Son libs internas
1 día
* https://github.com/mercadolibre/fury_billpayments-ios
* https://github.com/mercadolibre/fury_instore-ios
* https://github.com/mercadolibre/fury_meli-cards-ios
* https://github.com/mercadolibre/mpmobile-ios_mlrecharge/tree/development
* https://github.com/mercadolibre/traffic-registration_mobile_ios/tree/master
* https://github.com/mercadolibre/fury_mp-config-provider-ios
* https://github.com/mercadolibre/mpmobile-ios_moneytransfer
* https://github.com/mercadolibre/ios_point
* https://github.com/mercadolibre/mpmobile-singleplayer_ios/tree/master
* …
> Se sube version de MLMetrics, MLFirebase, y MLNAvigation

- android-whitelist.json
- "com.mercadolibre.android.traceability:traceability:1.+"
El Aar esta pesando 32kb
No deberia, si se inicializar una clase con el context y callback
No
para poder tracear los flujos del usuario
> add traceability lib

- ios-whitelist.json
Se agrega otra dependencia a firebase, basicamente no agrega nada nuevo
> Add whitelist for firebase/analytics

- CODEOWNERS
- android-whitelist.json
bump del sdk de MP
+actualizo los codeowners, con Lucas y yo
> sdk mp bump

- ios-whitelist.json
[MLScanner](https://github.com/mercadolibre/fury_scanner-ios)
Calculé la diferencia de peso entre un proyecto que tiene la lib y uno que no y me da aproximadamente 100kb.
Lib interna
Lib interna
Si
26/11/2019
Esta lib tiene como objetivo desacoplar el scanner de qr de InStore de manera de que pueda ser utilizado por otros fronts con lo que: Reutilizamos código y Unificamos la experiencia de scan en apps MELI y MP.
Utilizar el scanner nativo con implementación de cada front.
No, se instancia en donde se va a utilizar.
Si, internamente utiliza mecanismos nativos para escanear qr.
iOS 10+
Actualmente lo está utilizando el equipo de CardsAcquisition. Está planificado empezar a utilizarlo en InStore y Cashout.
- [Feature/scan qr](https://github.com/mercadolibre/fury_cards-acquisition-ios/pull/6 …
> Added MLScanner

- ios-whitelist.json
- MLNotifications 3.0.0
- Se agrega expiración para la versión 2.+ en caso de que necesiten los Fends sacar hotfixes de las versiones que actualmente esten en rollout.
Ninguno, es un update por un breaking change en la interfaz que utilizan las apps.
_Hago release de la 3.0.0 hoy_
_No_
- [mobile-ios](https://github.com/mercadolibre/mobile-ios)
- [mpmobile-ios_wallet](https://github.com/mercadolibre/mpmobile-ios_wallet)
- [loyal-ios](https://github.com/mercadolibre/loyal-ios)
- [myml-ios_messages](https://github.com/mercadolibre/myml-ios_messages)
- [auth-ios-login](https://github.com/mercadolibre/fury_auth-ios-login)
> Update Notifications iOS

- ios-whitelist.json
**Firebase/MLVision**
**Firebase/MLVisionFaceModel**
| Antes | Después |
| ------ | ------ |
| ![image](https://user-images.githubusercontent.com/23457769/69639662-ac6a8b80-103b-11ea-867b-6a1341b77d69.png) | ![image](https://user-images.githubusercontent.com/23457769/69643550-3f0e2900-1042-11ea-929b-668540c39914.png) |
No encontré
Poco madura, lib en beta.
Sí, el mantenimiento está a cargo de google.
22 de Octubre de 2019 salió la [versión 6.11.0](https://github.com/firebase/firebase-ios-sdk/releases/tag/6.11.0), pero como en ML usamos Firebase/Core 6.9.0, tenemos que usar la versión 0.18
El ownership va a ser el [equipo de Identity](mailto:identity@mercadolibre.com)
Hay varias, el Q pasado estuvimos analizando algunas pero ninguna nos convenció por motivos de usabilidad y resultados …
> Nueva lib de firebase para detección de caras para iOS

- android-whitelist.json
-"com.mercadolibre.android.inappupdates"
La lib pesa 104kb. 65kb son de codigo (pre-proguard), 35kb son del R de commons.
N/A
N/A
N/A
N/A
Nosotros somos los owners
N/A
Se va a agregar un nuevo Configurator para inicializar la variante en cada BE
N/A
N/A
Remplaza al bump actual para manejar updates de versiones inactivas.
Y maneja los updates opcionales usando la API de Google In App Updates o el bump actual para API<21.
Esta lib es cross app. La idea es que con una configuracion externa cualquier app pueda elegir las politicas de updates y luego setear los behaviours correspondientes en los lugares clave.
N/A
N/A
> Se agrega libreria de in-app-updates

- android-whitelist.json
- "com.mercadolibre.android.scanner:scanner:mercadopago-0.1.0"
Lib interna
Lib interna madures inicial
Si
28/11/2019
Si, él owner es https://github.com/journeyapps/zxing-android-embedded lib que actualmente se utiliza en Instore y Flex.
_Si, existe Vision. Preferimos esta porque:
https://drive.google.com/open?id=1ObMr13tSAwp0jtfCmFpD3Zg4n9ezWgY0BufGtJPpjiA
_No, Scanner no requiere inicializacion en el `Application`_
_No, Scanner no tiene codigo con NDK_
Esta lib tiene como objetivo desacoplar el scanner de qr de InStore de manera de que pueda ser utilizado por …
> scanner added to whitelist

- android-whitelist.json
- "com.mercadolibre.android.security:security_preferences:mercadolibre-2.+"
- "com.mercadolibre.android.security:security_preferences:mercadopago-2.+"
_664 KB_
_No, es una lib interna_
_Tiene aproximadamente 3 meses de uso en mercadopago_
_No, lib interna_
_Hace 1 día_
_Creemos que no es necesario un wrapper de la lib. El ownership va a ser el [equipo de session security](sessions_security@mercadolibre.com)_
_Si, security preferences requiere  inicialización en el MercadoPago_
_No, Security Preferences no tiene código con NDK_
_En flujo de PX, Money out y Security Settings_
- [PR Security UI](https://github.com/mercadolibre/fury_security-ui-android/pull/10)
- [mpmobile-android_wallet](https://github.com/mercadolibre/mpmobile-android_wallet)
- …
> Security Preferences Version 2.+

- android-whitelist.json
- "com.mercadolibre.android.search:(cualquier módulo):9.+"
Nulo. Es un major de una librería actual donde se elimina una clase pública
No aplica
No aplica
Interna. No aplica
Interna. No aplica
No aplica
No aplica
No, es solo un breaking change
No aplica
Min API 19
Es interna, no aplica
No aplica
No aplica
> Adding major version v9 of Search

- android-whitelist.json
Agregamos remote config a la whitelist
https://github.com/mercadolibre/fury_remote-configuration-android
- "com.mercadolibre.android.remote.configuration.keeponite:X.X.X"
Tiene solo dos clases y no tiene recursos
Se utilizará desde los configuration providers tanto de ML como de MP.
Es una lib nueva, interna.
- No aplica.
Hace una semana
_No se va a wrappear, el owner somos nosotros.
- No aplica
No
No aplica
Min 16 Max 28
Para los configuradores de ML y MP donde vamos a proveer el uso del Checker para evitar los flavors en los fends cross.
> Agregamos Remote configurations a la whitelist

- ios-whitelist.json
Agregamos remote config a la whitelist
https://github.com/mercadolibre/fury_remote-configuration-ios
- "MLRemoteConfiguration"
Tiene solo dos clases y no tiene recursos
Se utilizará desde los configuration providers tanto de ML como de MP.
Es una lib nueva, interna.
- No aplica.
02/01/2020
_No se va a wrappear, el owner somos nosotros.
- No aplica
No
No aplica
Swift 5..
Para los configuradores de ML y MP donde vamos a proveer el uso del Checker para evitar los flavors en los fends cross.
> Agregamos Remote Config a la whitelist

- android-whitelist.json
Creamos la nueva librería de modales que acompaña la iniciativa de Andes y necesitamos agregarla a la whitelist
https://github.com/mercadolibre/fury_ui-modal-android
- "com.mercadolibre.android.andesui:draft-modal:1.+"
Hace 1 semana
No
Actualmente estamos utilizando la lib para prender modales a los usuarios desde la librería de merchengine
> Adding AndesUI Draft Modal Library

- ios-whitelist.json
- "MLCardForm"
Inicialmente se usara dentro de PX, reemplazando el alta de tarjeta actual sin impactar en el peso. La idea es que otros equipos que tengan alta de tarjeta usen este componente, reduciendo el peso final de las apps.
Va a ser el primer release y va a ser prendido gradualmente
_Si, MLCardForm va a ser mantenida por el equipo de PX_
> Add MLCardForm to iOS whitelist

- android-whitelist.json
- "com.mercadolibre.android.cardform:1.+"
_Por ahora, solo va a ser usada internamente.
_Va a ser el primer release y va a ser prendido gradualmente
_Si, va a ser mantenida por el equipo de PX
_N/A
_Creemos que no es necesario un wrapper de la lib. 
_No
_No
_No, CardForm no tiene código con NDK_
_Estamos creando una nueva biblioteca llamada cardForm que se encargará de dar de alta nuevas tarjetas. Es un módulo independiente que busca agilizar y aumentar la cantidad de usuarios con tarjetas asociadas.
- [px-android](https://github.com/mercadopago/px-android)
> add lib cardform

- android-whitelist.json
- [Flux Client](https://github.com/mercadolibre/fury_flux-client-android): "com.mercadolibre.android.fluxclient:flux-client:2.+"
Imperceptible, se añade una nueva feature la cual incrementa el major de la lib.
Es un desarrollo interno.
Está en una etapa temprana de desarrollo, vamos incorporando features a medida que necesitamos cubrir nuevas features respecto al procesamiento de flux.
Si, es mantenida por nosotros mismos, es un desarrollo interno.
08/01/20. Versión [v2.0.0](https://github.com/mercadolibre/fury_flux-client-android/releases/tag/2.0.0)
No, no afecta.
No, no tiene código con NDK.
Ya estamos en API 19 en este repo y los repos que lo importan también.
Los casos de uso los comentamos en este [PR](https://github.com/mercadolibre/mobile-dependencies_whitelist/pull/343), dejo la …
> Add major version v2 of flux-client-android.

- ios-whitelist.json
Se agrega a la whitelist la lib de `AndesUI`
> andesui dependency

- android-whitelist.json
- "com.mercadolibre.android.garex:core:1.+"
_El módulo de garex está pesando 104.8KB_
_Libreria interna_ 
_Lib interna madures inicial_
_Si, la librería es mantenida por el equipo de Garantías Extendidas 
garex-dev@mercadolibre.com_
_14/01/2020_
_Creemos que no es necesario un wrapper de la lib. La vamos a usar desde buyingflow-mobile_android _
_No_
_No, Garex no tiene codigo con NDK_
_Tiene Min API level 16_
_Estamos creando la integración con CHO, para empezar a ofrecer garantías extendidas en el proceso de compra de un item único, para los sites MLA, MLM y MLB_
- [Garex](https://github.com/mercadolibre/fury_garex-mobile-android)
- [CHO](https://github.com/mercadolibre/buyingflow-mobile_android/)
> Add garex library to whitelist

- android-whitelist.json
Andes UI library is added to the Android whitelist.
- "com.mercadolibre.android.andesui:components:1.+"
_22 de enero de 2020_
_El ownership va a ser de todo Meli_
_No_
_No_
_La librería de Andes UI es la nueva opción para que los fends muestren los distintos componentes oficiales de nuestro lenguaje de diseño._
- [PR a Configurators ML](https://github.com/mercadolibre/fury_ml-config-provider-android/pull/319)
> Added Andes UI Library

- android-whitelist.json
- "com.mercadolibre.android.scanner:scanner:1.+"
N/A
Uso interno
Es la segunda version releseada.
Si
27/01/2020
No
N/A
No
Si, la support por medio de la arquitectura de meli.
Instore - CardAdquisition
N/A
(https://github.com/mercadolibre/fury_instore-android)
> Bump to 1.+ of Scanner lib

- android-whitelist.json
- "com.journeyapps.zxing-android-embedded:3.6"
N/A
N/A
N/A
No
Hace 10 dias
Si, el equipo de Instore desarrollo una Scanner lib.
El ownership va a ser Instore (mailto:instore_mobile_core@mercadolibre.com)
N/A
No
N/A
N/A
N/A
N/A
N/A
> Update journeyapps from 3.5 to 3.6

- android-whitelist.json
- "com.otaliastudios:cameraview:1.6.1" (https://github.com/natario1/CameraView)
La idea es remplazar la lib de camara fotoapparat. Hicimos el cálculo del peso de la app sacando la lib de fotoappart y agregando la de cameraView, y la app de ML pesa 115 KB menos. 
N/A
N/A
Si, CameraView es mantenida por una comunidad
Hace 19 días.
N/A
Si, existe CameraX y CameraKit. Preferimos esta porque:
- CameraKit no la están actualizando.
- CameraX tiene min api lvl 21
No, CameraView no requiere inicialización en el 'Application'
No, CameraView no tiene codigo con NDK
Tiene Min API level 15
N/A
- https://github.com/mercadolibre/fury_auth-remedies-mobile-android/pull/45
- https://github.com/mercadolibre/mobile-android
- https://github.com/mercadolibre/mpmobile-android_wallet
- [ x] …
> add camera view lib

- android-whitelist.json
- "org.jetbrains.kotlinx:kotlinx-coroutines-core:1.2.2"
- "org.jetbrains.kotlinx:kotlinx-coroutines-android:1.2.2"
_https://github.com/Kotlin/kotlinx.coroutines_
_Si, google ya utiliza para algunas APIs, Nubank, empresas que utilizan kotlin estan a mirar coroutines._
_Bastante madura, Ex. retrofit ya da suporte para coroutines, algunas APIs de google ya utilizan coroutines._
_Si, mantenida por una comunidad extensa e incluso es propiedad de JetBrains_
_25 Sep 2019_
_Creemos que no es necesario un wrapper de la lib._
_No_
_No_
_No_
_No_
_Hacer processos en background, Main Tread Safe, eficiencia en work leak_
- https://github.com/mercadolibre/fury_cards-engagement-android/blob/9c415c3d774eb3d811a52327758c67f8b6230b08/core/src/main/kotlin/com/mercadolibre/android/cardsengagement/core/OnDeman …
> Kotlin Coroutines 1.2.2

- android-whitelist.json
Descripción del la lib : (https://github.com/mercadolibre/mobile-dependencies_whitelist/pull/395)
> Fix touchpoint version

- ios-whitelist.json
Update sobre [MLScanner](https://github.com/mercadolibre/fury_scanner-ios)
Ya se utiliza actualmente.
Lib interna
Lib interna
Si
05/02/2020
Esta lib tiene como objetivo desacoplar el scanner de qr de InStore de manera de que pueda ser utilizado por otros fronts con lo que: Reutilizamos código y Unificamos la experiencia de scan en apps MELI y MP. 
El owner de la lib es InStore.
Utilizar el scanner nativo con implementación de cada front.
No, se instancia en donde se va a utilizar.
Si, internamente utiliza mecanismos nativos para escanear qr.
iOS 10+
- Ya se está utilizando en CardsAcquisition para el flujo de asociación de tarjetas que ya actualizó a la versión 1.x
- También estamos migrando el scanner de InStore para que utilice esta lib. El cambio lo vamos a liberar en las próximas …
> Bump MLScanner to 1.+

- android-whitelist.json
Por naming clash hubo que cambiar el package de la lib de Draft Modal y releasear un nuevo major. Este PR se encarga de eso.
> Updated AndesUI Draft Lib

- android-whitelist.json
- ios-whitelist.json
- "com.mercadolibre.android.buyingflow.flox.components:core:1.+"
- pod ‘MLBFFloxComponent’, ‘~> 1.0’
El peso de descarga es 56 KB
No
No
minApiLevel=19
Esta librería es compartida entre checkout y mis compras y se usa para contener widgets de ui comunes entre ambos fends.
- https://github.com/mercadolibre/buyingflow-mobile_android/pull/4326
- https://github.com/mercadolibre/fury_bf-flox-components-android
- https://github.com/mercadolibre/fury_bf-purchases-mobile-android
- https://github.com/mercadolibre/buyingflow-mobile_android
- https://github.com/mercadolibre/fury_bf-flox-components-ios
- https://github.com/mercadolibre/fury_bf-purchases-mobile-ios
- https://github.com/mercadolibre/buyingflow-mobile_ios
- [ X] Hay que agregar lo que pongo a continuación... 👇
Buying flow flox components …
> Agregamos una nueva libraria de buyingflow

- android-whitelist.json
Se corrige la version de variations, la cual ya esta [releseada](https://github.com/mercadolibre/fury_variations-android/releases/tag/3.0.0) desde octubre del 2019, pero los fends no se encuentran actualizados.
En mobile-android ya esta la version 3.0.0 (https://github.com/mercadolibre/mobile-android/pull/6473/files) tambien actualizada desde octubre.
Una vez actualizada la whitelist, se mandaran los prs a los fends correspondientes
-  "com.mercadolibre.android.variations:variations:3.1.0",
N/A
N/A
N/A
N/A
11/02
N/A
N/A
No
N/A
19 / 28
Ya la usa Vip, Carrito y Recos
- https://github.com/mercadolibre/cart-android
- https://github.com/mercadolibre/vip-android
- https://github.com/mercadolibre/recommendations-android
> Bump Variations 3.x

- android-whitelist.json
- "com.mercadolibre.android.credits:ui_components:0.+"
N/A
N/A
N/A
N/A
Hace 1 día
Es una libreria interna con componentes de UI en android para el equipo de credits. El ownership va a ser credits-front-it (mailto:credits-front-it@mercadolibre.com)
N/A
No, no requiere inicialización en el `Application`
No, no tiene código con NDK
Estamos creando un nuevo frontend para tarjeta de crédito y decidimos crear una libreria de componentes de UI para poder reutilizarlos en los diferentes módulos.
- [https://github.com/mercadolibre/fury_credit-card-statements-android/pull/5](https://github.com/mercadolibre/fury_credit-card-statements-android/pull/5)
- [credit-card-statements](https://github.com/mercadolibre/fury_credit-card-statements-android)
> Added credits ui_components library dependency for 0.+ versions

- ios-whitelist.json
No aplica solo se actualizo la dependencia de MPTracking . Se actualiza la libs debido a que del equipo de arquitectura mobile estamos removiendo appsFlyer, debido a los cambios realizados es el porque debemos actualizar el major de la libs.
Estas modificaciones afectan a las siguientes librerias:  MPMiniapps, MPSDK, MPPoint, Single-player (mlrecharge y paybiils),  MPMoneyTransfer, MPSignUp
_Creemos que no es necesario un wrapper de la lib. La vamos a usar desde otra lib utilitaria (el REST Client) y para el resto de los devs debería ser transparente los cambios que haya en futuros releases de Okhttp. El ownership va a ser el [equipo de X](mailto:x-team@mercadolibre.com)_
_No, OkHttp no requiere inicializacion en el `Application`_
_No, OkHttp no tiene codigo con NDK_ …
> Update version libs MPTracking

- ios-whitelist.json
- _"MLLoyalDM:0.+"_
_La librería pesa 7 KB._
_Es una librería interna._
_Librería interna con madurez inicial._
_Sí, la librería es mantenida por el equipo Loyalty._
_Hace 2 semanas._
_Creemos que no es necesario un wrapper de la lib._
_No, MLLoyal no requiere inicializacion en el `Application`_
_Sí, actualmente las siguientes también internas:_
- MLCommons
- MLAnalytics
- MLNetworking
- MLUI
_De Apple:_
- Foundation
- ExternalAccesory
_El Loyalty Data Manager será el encargado de almacenar y modificar la información de Loyalty para que sea consistente en todos los componentes que decidan utilizarla. En principio va a ser utilizada para sincronizar componentes de Mercado Pago y potencialmente replicar esto en Mercado Libre._
- …
> Agregar Loyalty Data Manager

- android-whitelist.json
- "com.facebook.android:facebook-applinks:5.13.3"
- "com.mercadolibre.android.cross_app_links:core:0.+"
Facebook AppLinks pesa aproximadamente **67Kb.** Hoy en día ya se estan agregando en la app, a través del SDK (ya agregado en la whitelist). No podemos sacar el SDK, ya que registration depende del mismo todavía. El día que no exista esa mas dependencia, solo va a quedar esta dependencia, disminuyendo el peso.
Es de Facebook, es necesaria para la utilización de Facebook AppLinks
Bastante madura, el SDK de FB tiene ya una larga trayectoria, muchos releases
Sí, por Facebook
Hace 5 días
Estamos wrappeando el uso de la lib en una librería nueva: [CrossAppLinks](https://github.com/mercadolibre/fury_cross-app-links-android)
No, es la misma inicialización de Facebook
No, FB SDK no tiene codigo …
> Adding Facebook AppLinks dependency

- android-whitelist.json
- "com.mercadolibre.android.traceability:traceability:2.+"
Sin diferencia de peso con version anterior 
Librería interna.
Es la segunda version que se lanza. 
27/02/2020
No debería, si se inicializar una clase con el context y callback
No
para poder tracear los flujos del usuario
> bump version traceability v2.0.0

- ios-whitelist.json
AndesUI iOS soporte para v2
https://github.com/mercadolibre/fury_andesui-ios/tree/develop/LibraryComponents
> Update AndesUI 2.0 ios

- android-whitelist.json
AndesUI Android soporte para v2
- https://github.com/mercadolibre/fury_andesui-android/
> andes ui android version update

- .github/pull_request_template.md
_No, OkHttp no requiere inicializacion en el `Application`_
_No, OkHttp no tiene codigo con NDK_
[¿Qué es el SLA de Crashes?]([https://sites.google.com/mercadolibre.com/mobile/release-process/seguimiento-de-errores](https://sites.google.com/mercadolibre.com/mobile/release-process/seguimiento-de-errores))
_Example module …
> Mejoramos el template para los PRs (ver justamente este PR como demo)

- android-whitelist.json
- ios-whitelist.json
- _"MLLoyalUIComponents:1.+"_
_La librería pesa 96 KB._
_Es una librería interna._
_Librería interna con madurez inicial._
_Sí, la librería es mantenida por el equipo Loyalty._
_Hoy._
_Creemos que no es necesario un wrapper de la lib._
_No, MLLoyalUIComponents no requiere inicializacion en el `Application`_
_Sí, tiene las siguientes dependencias internas:_
- _MLCommons_
- _MLUI_
_MLLoyalUIComponents contiene elementos de UI correspondientes a las features de Loyalty (Mercado Puntos)._
- [https://github.com/mercadolibre/fury_navigation-sections-ios/pull/19](url)
- [https://github.com/mercadolibre/fury_navigation-sections-ios](url)
- [https://github.com/mercadolibre/mobile-ios](url)
Nota: Si tu equipo no tiene acceso, entonces debes completar el …
> Agregar Loyalty UI Components

- android-whitelist.json
Se cambia el name de una lib de Loyalty
> Update Whitelist with Loyalty Fix

- android-whitelist.json
Es update de libs
- "com.mercadolibre.android.cross_app_links:" 0.+ => 1.+
Bump de la lib
- [Config ML PR](https://github.com/mercadolibre/fury_ml-config-provider-android/pull/359)
- [Config MP PR](https://github.com/mercadolibre/fury_mp-config-provider-android/pull/346)
> Bumping CAL version

- .github/pull_request_template.md
Fix markdown format for **Pull Request template**
> 🛠 Fix markdown format

- ios-whitelist.json
- MLCreditsCore 1.x
No 
Libreria Interna
Primera Version
No
18/03/2020
Creamos esta lib para centralizar funcionalidad Core de los repos de Credits Consumer con el fin de reutilizar codigo y dejar plasmado el proceso de Flux como cliente.
- [Consumer Credits Personal Loans](https://github.com/mercadolibre/fury_credits-consumer-pl-ios)
- [Consumer Credits Admin] (https://github.com/mercadolibre/fury_credits-consumer-admin-ios)
> MLCreditsCore library added

- ios-whitelist.json
- `MLClassiCredits`
No
No
N/A
N/A
- [[Trivial] Configure tracking for `MLClassiCredits` #4632](https://github.com/mercadolibre/mobile-ios/pull/4632)
El proyecto en Jira en el que se van a crear los crashes que ocurran es: **[MOB-557](https://mercadolibre.atlassian.net/browse/MOB-557)**
En equipo Clasificados estamos terminando desarrollo de un módulo nuevo: `MLClassiCredits`
- https://github.com/mercadolibre/mobile-ios/pull/4632
- [fury_classi-credits-ios](https://github.com/mercadolibre/fury_classi-credits-ios)
> 🤑 Add `MLClassiCredits`

- ios-whitelist.json
_- "MPSPPrepaid:0.+"_
_La librería pesa 1.3MB._
_Librería interna._
_Librería interna con madurez inicial._
_Sí, la librería es mantenida por el equipo de Single Player_
_15/01/2020_
_Creemos que no es necesario un wrapper de la lib._
_No._
_No._
_La librería está destinada a reemplazar el módulo de Paybills (MercadoPago) y Cellphone Recharge (MercadoPago y MercadoLibre), unificando todos los flujos prepagos en una sola librería donde desde backend se defina la navegación permitiendo mayor flexibilidad a la hora de realizar A/B testing, e incorporar nuevos proveedores y/o negocios._
- [Mercado Pago](https://github.com/mercadolibre/mpmobile-ios_wallet)
> Add MPSPPrepaid to iOS whitelist

- android-whitelist.json
- ios-whitelist.json
Cambios de dependencia para la migración  AndroidX
https://docs.google.com/spreadsheets/d/1LeKz3LbXhWxiVkqHthlGhxXnW3JDb9nAYkcNhczN_XI/edit#gid=0
https://docs.google.com/spreadsheets/d/1hfkUpbk-r0B1PNiGo_rcnAo-7bSk_EEfAKB9oQviO8Y/edit#gid=0
No hubo ganancias significativas
Bastante madura
_Si, Google siempre trae noticias de AndroidX
_Sí, Con la  actualización OkHttp y Retrofit que ganamos en el start-up time
https://github.com/mercadolibre/mpmobile-android_wallet/pull/10714
_AndroidX es una mejora significativa respecto de la biblioteca de compatibilidad de Android original, que ya no se actualiza. Los paquetes de androidx reemplazan por completo la biblioteca de compatibilidad, ya que proporcionan paridad de funciones y bibliotecas nuevas.
- [androidX …
> Android x migration

- ios-whitelist.json
- MLCrossAppLinks v1.0.0 
_No, si bien la lib es para poder hacer fetch de links al iniciar por primera vez, esto se hace de forma async_
_No_
_Mismas que mobile-ios (iOS 10.0+)_
_No afecta al peso, solo agrega código y muy poco_
El proyecto en Jira en el que se van a crear los crashes que ocurran es: **_${MNA}_**
> Adding MLCrossAppLinks whitelist

- android-whitelist.json
Estamos trabajando para poder deprecar el SDK de MP, y para esto estamos migrando ciertas funcionalidades, entre ellos hoy el SDK provee la tool timber q varias librerias y fronts.
Por esto queremos sacarlo del SDK la dependencia y encaminar su deprecado y eliminación. El usar timber o log de ML es un step más grande porque no solo depende de SDK, por eso por ahora solo lo sacamos para ir encaminando los cambios
- "com.jakewharton.timber:timber:4.5.1"
https://github.com/JakeWharton/timber
_No_
_No_
_No_
_No, ya utilizamos pero esta me saltando erro de whitelist cuando tengo agregar fuera de la SDK, estamos borrando la SDK de MP y migrando las dependencias que los modulos necesitan. Timber es uno_
Nota: Si tu equipo no tiene acceso, entonces debes completar el siguiente form de [acceso a …
> Added timber dependency

- .github/.stale.yml
Configuramos esta integración para que pushee automáticamente para que nos movamos por PRs que están mucho tiempo abiertos.
> Setup GitHub's Stale integration: https://github.com/apps/stale

- ios-whitelist.json
- CardsEngagement/Feedback
_No, CardsEngagement/Feedback no requiere inicializacion en el `Application`_
_No, CardsEngagement/Feedback no tiene codigo con NDK_
Xcode 11 / Swift 5 (develop branch)
iOS >= 10.0 
- [ x] Ya tenemos usuario en Bugsnag, es: **_${cards-mobile@mercadolibre.com}_**
- [ x] Ya esta configurado el contexto del módulo en las apps: **ML** [Android](https://github.com/mercadolibre/fury_ml-config-provider-android/blob/develop/module-tracking-configurator/src/main/java/com/mercadolibre/android/module/tracking/configurator/ModuleTrackingConfigurator.java), [iOS](https://github.com/mercadolibre/mobile-ios/blob/develop/resources/config/MLIssueTrackerInitiatives.plist) y **MP** [Android](https://github.com/mercadolibre/fury_mp-config-provider-android/blob/develop/moduletracking …
> Add Engagement Feedback

- android-whitelist.json
Se añade la posibilidad de que Listing de presupuestos pueda ser no solo `0.+` sino tambien `1.+`
> 🚀 Listing de Classi actualizado a 0.+ y 1.+

- android-whitelist.json
Se agrega un nuevo modulo de una lib ya agregada
- "com.mercadolibre.android.loyalty_ui_components:home-mp-components:1.+"
No
Pesa 59 kB
- [ x] Ya tenemos usuario en Bugsnag, es: **_${blah@mercadolibre.com}_**
- [x ] Ya esta configurado el contexto del módulo en las apps: **ML** [Android](https://github.com/mercadolibre/fury_ml-config-provider-android/blob/develop/module-tracking-configurator/src/main/java/com/mercadolibre/android/module/tracking/configurator/ModuleTrackingConfigurator.java), [iOS](https://github.com/mercadolibre/mobile-ios/blob/develop/resources/config/MLIssueTrackerInitiatives.plist) y **MP** [Android](https://github.com/mercadolibre/fury_mp-config-provider-android/blob/develop/moduletracking-configurer/src/main/java/com/mercadolibre/moduletracki …
> loyalty-ui-components new module added

- android-whitelist.json
La dependencia ya fue agregada y aceptada en #392 
Se separo código en modulos diferentes para poder utilizar en el futuro los componentes de ui aunque no se utilice Flox. (Todos este código iba a estar presente en el único modulo que ya se agregó a esta whitelist)
- "com.mercadolibre.android.credits.ui_components:components:0.+"
- "com.mercadolibre.android.credits.ui_components:flox:0.+"
No, ninguno de los dos modulos de Credit UIComponents requiere inicializacion en el `Application`
No
Aunque el peso de los componentes de Flox no es significativo, al haberse separado en dos módulos se permitiría, incluir la lib de componentes sin las clases de Flox.
Nota: Si tu equipo no tiene acceso, entonces debes completar el siguiente form de [acceso a …
> Updated Credits UIComponents library id and modules

- android-whitelist.json
Se agrega migración de gradle a 5 de credits `2.0.0`
Fecha de expiración de credits `1.+`  primero de Junio
> 🚀 Migracion a gradle 5 de classi credits

- android-whitelist.json
- "com.mercadolibre.android.instore:geofencing:1.+"
_No, Geofencing no requiere inicializacion en el `Application`_
_No, Geofencing no tiene código con NDK_
_Soporta los SDK incluidos en MP actualmente, cuando el target SDK suba a Android 10, se requerirán cambios para soportar background location_
El módulo no incluye dependencias nuevas ni recursos, por lo que no debería contribuir significativamente al peso de la app
[¿Qué es …
> Add Geofencing dependency

- android-whitelist.json
Se agrega migración de gradle a 5 de dynamic flow `1.0.0`
Fecha de expiración de credits `0.+`  primero de Junio
> 🚀 dynamic flow Gradle migration

- android-whitelist.json
Modificar la definición de la librería 
{
“group”: “androidx\\.browser”,
“name”: “customtabs”,
“version”: “1\\.0\\.0"
}
cambiar por:
{
“group”: “androidx\\.browser”,
“name”: “browser”,
“version”: “1\\.0\\.0"
}
Esto se debe a que cuando se migra las librerías hacia AndroidX la librería
` implementation "com.android.support:customtabs:$supportLibraryVersion"`
pasa a ser
`  implementation "androidx.browser:browser:$supportLibraryVersion"`
que es rechazada como correcta por la whitelist de dependencias, pero sin embargo está bien definida.
> La migración de librería fue realizada con la herramienta de conversión automática de Android Studio
_No
_No
Nota: Si tu equipo no tiene acceso, entonces debes completar el siguiente form de [acceso a …
> fixed androidx browser name definition

- android-whitelist.json
- "androidx.core:core-ktx:1.2.0"
_No
_Si, es propiedad de Google
_Tiene Min API level 14 y Max 29
_No, generando dos APK(ambas xhdpi-Armeabi-v7a-debug) en modo debug y comparandolas en _Android Studio_ muestra que para el caso de **smartPos** la apk con la lib core-ktx pesa 19.3 MB mientras que sin ella pesa 19.2 MB mostrando una diferencia de 1.5 KB
Para el caso de la **wallet** el apk en debug con la lib core-ktx pesa 58MB mientas que sin ella 57.9MB mostrando una diferencia de 75.8Kb
_Si, Google y cualquiera que actualmente enfrente el desarrollo de Kotlin en Android
_Bastante madura, core-ktx es parte primordial del desarrollo de Kotlin en Android
_Si, core-ktx es mantenida por Google
_De la 1.2.0 (estable) fue el 05/02/2020. Ademas tienen la 1.3.rc01 al 15/04/2020
_No
_Estamos …
> Add androidx lib: core-ktx

- android-whitelist.json
Se sube el major de la lib de "lifecycle-extensions". 
La versión que se tiene (1.+)es pre migración androidx, que corresponde a la lib que se usa pre migración la cual es "android.arch.lifecycle:extensions".
https://developer.android.com/jetpack/androidx/releases/lifecycle
- "androidx.lifecycle:lifecycle-extension:2.0.0"
No
No, no contiene código con NDK.
Si, OkHttp es actualmente usada por X, Y, Z, etc empresas._
Bastante madura
Si, Google siempre trae noticias de AndroidX
04/03/2020
Creemos que no es necesario wrappear esta lib, es una lib directa de android y es de uso común entre libs.
Se usa para crear componentes optimizados para ciclos de vida y realizan acciones en respuesta a un cambio en el estado del ciclo de vida de otro componente.
En VPP se usa para hacer fetch de los …
> lifecycle extension major

- android-whitelist.json
- ios-whitelist.json
- Android "com.mercadolibre.android.cards-components:1.+"
- iOS "CardsComponents" 1.+
No, no requiere inicialización, ya que son componentes compartidos entre las librerías de cards, para no repetir código
_No, OkHttp no tiene codigo con NDK_
No debería tener impacto, ya que es código que está productivo, y que en el caso de no meter esta lib, tendríamos que duplicar código
El proyecto en Jira en el que se van a crear los crashes que ocurran es: CARDS …
> Whitelist cards components library

- android-whitelist.json
Bumpeamos version de traceability
> Feature/traceability 3+

- android-whitelist.json
- Lib para poder interceptar url's relacionadas al contexto de TOTP
- Enviar a playstore y descargar el authenticator .
- Enviar a authenticator para configurar una nueva clave.
- "com.mercadolibre.android.security_two_fa:totp:1.0.0"
- 4 KB
_No, totp no requiere inicialización en el `Application`_
_No, totp no tiene código con NDK_
El proyecto en Jira en el que se van a crear los crashes que ocurran es: **_${ASEC}_**
- [] Necesito que me ayuden a configurarlo. …
> Lib totp in WebView

- android-whitelist.json
com.mercadolibre.android.loyalty_ui_components:cho-congrats-components:X.X"
Tenemos en cuenta ahora el major [2.+ para loyalty_ui_components](https://github.com/mercadolibre/fury_loyalty-ui-components-android/releases/tag/2.0.0)
_No
- flox
- andes
- mlbusinessComponents
El proyecto en Jira …
> New loyalty module

- android-whitelist.json
Diferencia con el PR que se realizo el Revert: 
`"version": "1 \\.\\+|2\\.\\+"` **ahora ->** `"version": "1\\.+|2\\.+"`
Testeado pegandole al fork desde donde sale este PR y funcionando :) 
com.mercadolibre.android.loyalty_ui_components:cho-congrats-components:X.X"
Tenemos en cuenta ahora el major [2.+ para loyalty_ui_components](https://github.com/mercadolibre/fury_loyalty-ui-components-android/releases/tag/2.0.0)
_No
- flox
- andes
- mlbusinessComponents
Nota: Si tu equipo no tiene acceso, entonces debes completar el siguiente form de [acceso a …
> New loyalty module 

- ios-whitelist.json
- Charts actualización de 3.2.2 a 3.4.0
_No, Charts no requiere inicializacion en el `Application`_
Xcode 11 / Swift 5 (master branch)
iOS >= 8.0 (Use as an Embedded Framework)
tvOS >= 9.0
macOS >= 10.11
Charts
No se
_Bastante madura, existe desde Apr 7, 2015 y se sigue manteniendo._
_Si_
_Oct 9, 2019_
_Se implementó un wrapper *MeliChart* que se va a estar utilizando en la próxima versión de MLDashboard._
_Si, existe PNChart. Preferimos esta porque:_
- Se sigue manteniendo.
- Hay una contraparte en android con la misma arquitectura de datos.
_MLDashboard_
> Update Charts iOS

- ios-whitelist.json
N/A
NO
SI
iOS 10
N/A
El proyecto en Jira en el que se van a crear los crashes que ocurran es: **DIDIV**
> Version 2.0.0 Remedies

- android-whitelist.json
- ios-whitelist.json
- user-blocker
_Si, en casos excepcionales puede alargar el tiempo de start up mientras valida el estado del usuario
Es una lib interna de ML y no tiene dependencias externas nuevas
No aplica
No aplica
las clases de user blocker se reportan al equipo de kyc
El proyecto en Jira en el que se van a crear los crashes que ocurran es: **AMF** (igual que lib de kyc)
> user blocker added

- ios-whitelist.json
- MLIgnite
No, solo estamos eliminando el código no utilizado
Si
iOS 10
No lo medimos pero seguro que se hizo más pequeño.
Hace 5 dias
> bump ignite to version 1

- ios-whitelist.json
Se agrega la versión de Lottie con operador optimista (~>2.0). Esto es necesario para las libs cross apps, ya que tenemos distintas versiones en MP y ML.
N/A
N/A
N/A
N/A
N/A
[MLRemedies](https://github.com/mercadolibre/fury_auth-remedies-mobile-ios)
- [MLRemedies](https://github.com/mercadolibre/fury_auth-remedies-mobile-ios/pull/62)
[MLRemedies](https://github.com/mercadolibre/fury_auth-remedies-mobile-ios)
> Lottie: Se agrega versión de Lottie con operador optimista para flavours

- ios-whitelist.json
- Charts de 3.2.2 a 3.4.0
_No_
_No_
Xcode 11 / Swift 5 (master branch)
iOS >= 8.0 (Use as an Embedded Framework)
tvOS >= 9.0
macOS >= 10.11
_No hay información en el repo, pero es la contraparte de MPAndroidChart en iOS y es la más utilizada para mobile._
_Bastante madura, es muy estable y se viene manteniendo desde el 2015_
_Si, se viene haciendo mantenimiento desde el 2015._
_abril 15 de 2020_
_Tiene un wrapper tanto para android como para iOS el cual es MeliCharts que se va a sumar a la whitelist después de este update. El ownership es de [Tools For …
> update charts version to 3.4.0

- android-whitelist.json
Actualizamos major de marketplace.map por update a Gradle y migración de AndroidX.
- "com.mercadolibre.android.marketplace.map"
El proyecto en Jira en el que se van a crear los crashes que ocurran es: **checkout_on**
**17/06/2020**
- [VPP](https://github.com/mercadolibre/fury_vpp-android/blob/develop/dependencies.gradle#L40)
> Version Marketplace Map

- android-whitelist.json
- "androidx.activity:activity:1.0.0"
No
--
Apk sample sin la dependencia: 13,8MB
Apk sample **con** la dependencia: 13,8MB
App instalada, version sin dependencia: 14,61MB
App instalada, version **con** dependencia: 14,64MB
_Si, OkHttp es mantenida por una comunidad extensa e incluso es propiedad de SquareUp_
_Creemos que no es necesario un wrapper de la lib. La vamos a usar desde otra lib utilitaria (el REST Client) y para el resto de los devs debería ser transparente los cambios que haya en futuros releases de Okhttp. El ownership va a ser el [equipo de …
> Agrego androidx.activity a whitelist

- .github/pull_request_template.md
Fixed many typos in the PR template
> Fixed typos in the PR template

- android-whitelist.json
Actualizamos major de cart manager por update a Gradle 5 y migración de Android X.
- "com.mercadolibre.android.cart:manager:7.0.0"
El proyecto en Jira en el que se van a crear los crashes que ocurran es: **_cart_**
- [cart-android](www.github.com/mercadolibre)
> Cart Manager a 7.+ por migración a Android X

- ios-whitelist.json
- MLTFSCommons
_No_
_No_
iOS >= 8.0
_Después de compilarlo como framework el peso es de 324kb_
**No se si es necesario agregarlo acá? porque veo muchos de nuestros pod que no están en este archivo. Si pueden darme más info sobre esto se lo agredezco.**
_Tenemos varios repos en donde siempre tenemos que agregar el …
> add tfs commons to the whitelist

- android-whitelist.json
Importamos y utilizamos la libreria [ReLinker](https://github.com/KeepSafe/ReLinker) que nos sugirió el equipo de Soporte de Bugsnag para evitar [estos](https://app.bugsnag.com/mercadolibre/mercado-libre-android/errors/5e989b0147d4420017190e19?filters%5Bevent.since%5D%5B%5D=7d&filters%5Berror.status%5D%5B%5D%5Btype%5D=eq&filters%5Berror.status%5D%5B%5D%5Bvalue%5D=open&filters%5Bapp.release_stage%5D%5B%5D%5Bvalue%5D=production&filters%5Bapp.release_stage%5D%5B%5D%5Btype%5D=eq&filters%5Bevent.unhandled%5D%5B%5D%5Btype%5D=eq&filters%5Bevent.unhandled%5D%5B%5D%5Bvalue%5D=true&event_id=5ef60c3b005b72d849610000) y [estos](https://app.bugsnag.com/mercadolibre/mercado-libre-android/errors/5e989b0147d4420017190e19?filters%5Bevent.since%5D%5B%5D=7d&filters%5Berror.status%5D%5B%5D%5Btype%5D=eq&filter …
> Adding ReLinker library

- README.md
- context-whitelist.json
Sacamos del context-whitelist.json la referencia a los repos, por pedido de websec.
> Se elimina el repo del context-whitelist.json

- android-whitelist.json
Actualizamos major de variations y vpp:vip_commons
- "com.mercadolibre.android.variations:variations:4.+"
- "com.mercadolibre.android.vpp:vip_commons:2.+"
- [Variations](https://github.com/mercadolibre/fury_variations-android)
Usado en 
- [Vip](https://github.com/mercadolibre/vip-android)
- [Cart](https://github.com/mercadolibre/cart-android/)
- [Recommendations](https://github.com/mercadolibre/recommendations-android)
- [Vpp](https://github.com/mercadolibre/fury_vpp-android)
> Actualización de Vpp a 2.+ y Variations a 4.+ por Android X

- android-whitelist.json
> Update search version

- context_whitelist.json
Se agregan 2 front-ends de Tools For Sellers (CollaboratorsUI y FeesAndInstallments), en los contextos para Mobile Issues
_No se agregan dependencias nuevas_
No.
Si.
_Min API 19_
No hay cambios
> Added TFS (Tools For Sellers) apps contexts

- context_whitelist.json
- "GarexGpage:0.+"
_No_
_No_
_GarexGpage está pesando 86kb._
_Estamos creando un nuevo frontend GarexGpage para presentar una vista con opciones de garantía extendida durante el flujo de checkout para el caso en que el producto lo acepte._
- …
> Add Garex Gpage context

- ios-whitelist.json
- ninguna
no
nada nuevo, update de la lib interna de kyc de 2.X a 3.X
nada
no afecta
solo nosotros, lib interna
funciona
la mantenemos nosotros, el equipo de kyc
hoy
no, es interna, @nievesjesus y @Federico0812 somos owners
no hay nada igual en el mercado
recopilamos datos personales de los usuarios y los …
> kyc lib version upgraded to 3.0

- ios-whitelist.json
- "GarexGpage:0.+"
_No_
_No_
_GarexGpage está pesando 86kb_
_Estamos creando un nuevo frontend GarexGpage para presentar una vista con opciones de garantía extendida durante el flujo de checkout para el caso en que el producto lo acepte._
- …
> Add GarexGpage to iOS whitelist

- context_whitelist.json
Se eliminan contextos inválidos de Collaborators
_No se agregan dependencias nuevas_
No.
Si.
_Min API 19_
No hay cambios
> Fixed "tools_for_sellers" contexts

- android-whitelist.json
- context_whitelist.json
- ios-whitelist.json
- MLDashboardComponent
- MeliChart
- Se depreca mlchart android
- Se corrige y actualiza context-whitelist para todos los proyectos que pertenecen al equipo TFS
_No._
_Si._
_iOS >= 8.0_
_Melichart: 2.7MB_
_MLDashboardComponent: 4.7MB_
- [MLDashboard](https://github.com/mercadolibre/fury_tfs-dashboard-ios)
> update TFS whitelists and context_whitelist

- android-whitelist.json
- context_whitelist.json
- ios-whitelist.json
- "com.mercadolibre.android.static_resources:1.+"
Se usa un behaviour en ios para registrar configuraciones
Si
Android Min API level 21
iOS 10
iOS: 64kb
Android: 100kb
El proyecto en Jira en el que se van a crear los crashes que ocurran es: **DAMIO**
- [example PR](https://github.com/mercadolibre/fury_cashout-ios/pull/3)
- [example fend](https://github.com/mercadolibre/fury_cashout-ios)
> adding static resources to whitelists

- context_whitelist.json
- ios-whitelist.json
- PointFlowEngine
- PointUI
No
Si
iOS >= 10
PointFlowEngine: 650 KB
PointUI: 57 KB
El proyecto en Jira en el que se van a crear los crashes que ocurran es: **_${POINT}_**
Flujo de cobro unificado.
- Estas libs no están productivas aun.
https://github.com/mercadolibre/fury_point-flow-engine-ios
https://github.com/mercadolibre/fury_point-ui-ios
> Agregado de libs PointFlowEngine y PointUI iOS

- android-whitelist.json
- context_whitelist.json
- "com.mercadolibre.android.instore:reviews"
_No
_No
Los mismos que MP
_El módulo no tiene imágenes_
> Add reviews to the whitelist

- .github/stale.yml
Mejoramos la config para que no queden tanto tiempo los PRs abiertos
> Cambiamos stale para que ponga el label en 7 días

- ios-whitelist.json
- "InsurtechFloxComponents:0.+"
_No_
_No_
_InsurtechFloxComponents está pesando 89kb_
_Creamos esta lib para desarrollar los componentes de Flox necesarios para las iniciativas de Insurtech._
- [garex-gpage-ios](https://github.com/mercadolibre/fury_garex-gpage-ios)
> Add Insurtech Flox Components to whitelist

- context_whitelist.json
- "InsurtechFloxComponents:0.+"
_No_
_No_
_InsurtechFloxComponents está pesando 89kb_
_Creamos esta lib para desarrollar los componentes de Flox necesarios para las iniciativas de Insurtech._
- [garex-gpage-ios](https://github.com/mercadolibre/fury_garex-gpage-ios)
> Add InsurtechFloxComponents context

- context_whitelist.json
- "InStoreUIComponents:1.+"
- "com.mercadolibre.android.instore_ui_components:core:1.+"
_ No, es un componente de UI que no requiere inicialización desde el mainApplication.
_ No
_ Las mismas que MP y ML …
> Adding new instore-ui-components context

- android-whitelist.json
Se actualiza la version de commons. estamos por la version 15.11
> update commons version

- android-whitelist.json
- ios-whitelist.json
> Bump flox components version

- android-whitelist.json
Agregamos dependencias que se usan en config-providers y no estan en la whitelist
> Dependencies for providers missing

- android-whitelist.json
Las dependencias ya fueron agregadas y aceptadas en #392 y actualizadas en #442 
Se agrega la version 1.+ para dar soporte al futuro release formal de la lib que vamos a hacer y poder soportar correctamente el versionado de nuevas features asi como resguardar a quienes nos usen de posibles breaking changes utilizando el mayor.
- "com.mercadolibre.android.credits.ui_components:components:0.+|1.+"
- "com.mercadolibre.android.credits.ui_components:flox:0.+|1.+"
No, ninguno de los dos modulos de Credit UIComponents requiere inicializacion en el `Application`
No
Aunque el peso de los componentes de Flox no es significativo, al haberse separado en dos módulos se permitiría, incluir la lib de componentes sin las clases de Flox.
Nota: Si tu equipo no tiene acceso, entonces …
> Update Credits UIComponents available version to future 1.+ release [CFM-5312]

- ios-whitelist.json
Firebase/Core
Firebase/DynamicLinks
Firebase/Analytics
Firebase/MLVision
Firebase/MLVisionFaceModel
Con versiones 631.1 ó 6.9.0
No
Si
> Update Firebase versions

- android-whitelist.json
Se agregan algunas dependencias faltantes
> Fix: dependencies missing

- android-whitelist.json
libs que ya teniamos y hacemos el bump para que esten actualizadas, de alguna manera este valor no se estaba verificando
> fix sdk whitelist

- android-whitelist.json
Agregamos dependencias que estaban whitelisteadas y faltaban agregar a la whitelist
> Fix: missing dependencies

- android-whitelist.json
bump de la lib de fresco para matchear la que usamos
> fix dependencies

- android-whitelist.json
"com.mercadolibre.android.instore_ui_components:core:1.+"
_ No, es un componente de UI que no requiere inicialización desde el mainApplication.
_ No
_ Las mismas que MP y ML …
> Whitelist instore ui components lib

- context_whitelist.json
- ios-whitelist.json
"PPMagnesWrapper:0.+"
No
No
Las misma que ML
Para analizar el peso de la app se generaron 2 builds en MDS, uno con Magnes y uno sin, y miramos el download size. Pasa de 125.4 mb a 125.5 mb asumimos que es aproximadamente 100kb la diferencia, se podrían hacer más tests para obtener un número preciso pero ya se concluye que el peso no es un problema.
Paypal
Bastante madura
Si, libPPRiskMagnesOC.a es necesaria en el funcionamiento del checkout  de Paypal
22 días
https://github.com/braintree/braintree_ios
Si, se wrappea la lib libPPRiskMagnesOC.a de Paypal
_Si, existe volley. Preferimos esta porque:_
- Razon X
- Razon Y
- Razon Z
Desde Checkout ON al elegir Paypal como medio de pago debemos utilizar esta lib
https://github.com/mercadolibre/buyingflow-mobile_ios/pull/3859/files …
> Add PPMagnesWrapper iOS to the whitelist

- android-whitelist.json
> add milestone tracker v3

- android-whitelist.json
- "com.mercadolibre.android.userbiometrics:core:2.+"
- "com.mercadolibre.android.security:security_preferences:mercadopago-2.+"(Version actual, se agrego expiracion)
- "com.mercadolibre.android.security:security_preferences:mercadolibre-2.+"
- "com.mercadolibre.android.security:security_preferences:mercadopago-3.+" (Version Android X, se esta por generar release de la lib)
- "com.mercadolibre.android.security:security_preferences:mercadolibre-3.+"
- "com.mercadolibre.android.security:security_ui:mercadopago-2.+"(Solo se usa en la home y se va a expirar)
- "com.mercadolibre.android.security:security_ui:mercadolibre-2.+"
- "com.mercadolibre.android.security:security_ui:mercadopago-3.+" (Android X, version actual)
- "com.mercadolibre.android.security:security_ui:mercadolibre-3.+"
Son …
> Actualizar nuestras libs de mobile devices security en whitelist android

- ios-whitelist.json
"InstoreReviews:0.+"
No
No
Los mismos que MP
El módulo no tiene imágenes
> Add instore ios reviews to the whitelist

- android-whitelist.json
- "com.mercadolibre.android. multiimageview:3.+"
- "com.mercadolibre.android.progress-circle:3.+"
_No_
_Son libs internas de Meli_
_Tiene Min API level 21, máx api level 29_
-
> Update whitelist-version of progress-circle & multiimageview

- android-whitelist.json
- com.mercadolibre.android.qadb:core:3.+
- com.mercadolibre.android.comparator:comparator:3.+
- com.mercadolibre.android.uinavigationcp:addresshub:4.+
Hago bump de estas 3 por el check fallido en [este PR](https://github.com/mercadolibre/fury_vpp-android/pull/901).
_Si, OkHttp es actualmente usada por X, Y, Z, etc …
> Bump qadb comparator and addresshub

- android-whitelist.json
> +dep for configurer

- ios-whitelist.json
- InStoreUIComponents:1.+
_ No, es un componente de UI que no requiere inicialización desde el mainApplication.
_ No
_ Las mismas que MP y ML
PR: https://github.com/mercadolibre/mobile-dependencies_whitelist/pull/518
[¿Qué es el …
> InStoreUIComponents whitelist

- android-whitelist.json
> more fixes 

- android-whitelist.json
> Fix cardform import

- android-whitelist.json
- "name": "melidata-sdk",
"version": "4\\.\\+|5\\.\\+|6\\.\\+" …
> Merge melidata versions

- android-whitelist.json
- "com.squareup.leakcanary:leakcanary-android:2.2"
- "com.squareup.leakcanary:leakcanary-android:1.6.3"
_No
_Si
_ No tiene impacto ya que la libreria solo se usará para los BuildTypes Debug y Mds.
_Sí, LeakCanary es mantenida por una comunidad extensa e incluso es propiedad de SquareUp_
11 de Junio de 2020
_ La usamos para detectar memory leaks en diferentes apps
- [Configurator usando la libreria](https://github.com/mercadolibre/fury_ml-config-provider-android/pull/469)
- [Android Configurator](https://github.com/mercadolibre/fury_ml-config-provider-android)
> Added LeakCanary version

- android-whitelist.json
- "com.squareup.okhttp3:logging-interceptor:3.11.0"
- "com.squareup.okhttp3:logging-interceptor:3.12.10"
_No, ya estamos utilizando esta dependencia en MP y necesitamos agregar aca por causa del
depecrecated de SDK_
_No
_No_
_Case todos las empresas que utilizan Okhttp utilizan esta dependencia para hacer los loggs de las requests_
_Estamos creando un nuevo frontend 'example' y necesita hacer API calls con un websocket custom porque vamos a permitir llamados en real time (vamos a utilizar OkHttp para el mismo). Creamos una API example-module que nos wrappea la …
> logging-interceptor dependency

- context_whitelist.json
Se agrega al contexto las librerias de Cashout y Disbursements.
- Se crea libreria de Cashout que abarca todas las experiencias de extraer dinero en efectivo en distitnos sites.
- Se crea libreria de Disbursements que contiene las experiencias para la recepcion de remesas de dinero.
- mercadolibre/fury_cashout-android
- mercadolibre/fury_cashout-ios
- mercadolibre/fury_disbursments-android
- mercadolibre/fury_disbursments-ios
> Cashout and Disbursements context

- android-whitelist.json
> Fixing multidex version

- android-whitelist.json
- context_whitelist.json
- "com.mercadolibre.android.insu_flox_components:floxcomponents:0.+"
_No_
_No_
_Este modulo está recién iniciado, su peso va a estar determinado por la cantidad de componentes que se alojen (no va a ser demasiado)_
El proyecto en Jira en el que se van a crear los crashes que ocurran es: **INSUG**
_Creamos esta lib para desarrollar los componentes de …
> Add Insurtech Flox Components to android whitelist and context

- android-whitelist.json
- "androidx.biometric:biometric:1.0.1"
The Biometric library is a static library that you can add to your Android application. It invokes BiometricPrompt on devices running P and greater, and on older devices will show a compat dialog. Compatible on devices running API 14 or later.
El aar de la lib pesa 38 KB, la diferencia del apk release de la monolitica con la nueva dependencia en comparacion sin esta crece 50 KB
- [x ] Ya agregué y/o actualicé el contexto en la …
> Android X - lib biometric

- android-whitelist.json
- "com.mercadolibre.android.ignite:core:2.+"
No
No
Min: 19 - Max: 29
No cambió el tamaño del módulo.
> Bump ignite Lib

- android-whitelist.json
- context_whitelist.json
- "com.mercadolibre.android.devices_sdk:devices:1.+"
_Si, tiene un configurator que se ejecuta en el startup de la app pero toda la ejecución es en un thread en background._
_No, no tiene código con NDK_
_No debería impectar ya que implica deprecar un módulo por otro, pero mientras se espera a que todos los que usan el módulo desde security se migren al de esta lib si. El peso que sumaría es _
El proyecto en Jira en el que se van a crear los crashes que ocurran es: …
> Added devices_sdk module migrated from security lib

- android-whitelist.json
- "com.mercadolibre.android.adjust:core:3.+"
No hay cambios frente a la versión anterior.
Nop.
Min API 29
No hubieron cambios en el peso de la lib.
El proyecto en Jira en el que se van a crear los crashes que ocurran es: **_${AT}_**
> Updated Adjust version to latest.

- android-whitelist.json
- "com.mercadolibre.android.matt:core:3.+"
No hubieron cambios frente a la versión anterior.
No.
Min API 29
No cambió el tamaño del módulo.
El proyecto en Jira en el que se van a crear los crashes que ocurran es: **_${AT}_**
> Updated matt lib to latest.

- android-whitelist.json
"com.mercadolibre.android.security:attestation:3.+"
_No hubieron cambios frente a la versión anterior._
_No_
_Tiene Max API level 28_
_No cambió el tamaño del módulo_
El proyecto en Jira en el que se van a crear los crashes que ocurran es: **_${SITESEC}_**
> Updated security lib to latest

- android-whitelist.json
Se sube la versión de Login que había quedado outdated.
> Bump Login version

- android-whitelist.json
-com.mercadolibre.android.userbiometrics:3.+
Pasa la version de la lib 2 a 3.
No
No
19
user biometrics
Es una lib propia que le actualizamos el primer numero de la version
> Actualizacion la lib propia user biometrics

- android-whitelist.json
"androidx.lifecycle:lifecycle-viewmodel-ktx:2.2.0"
_No, es una extension que solo se usa con ViewModels en Kotlin
No
No, solo necesita kotlin y la libreria androidx.lifecycle:lifecycle-viewmodel.
Estas extensiones de viewmodel solo agregan 5Kb en jar, que ofuscado seguramente se reduce.
No tiene dependencias, ya que son extensiones kotlin para mejorar la experiencia de la libreria ifecycle-viewmodel que ya estamos importando en nuestros proyectos.
Es una libreria que es parte del suite androidx.lifecycle. Es parte del framework de android.
Muy
Mantenida por google como parte del  suite lifecycle-viewmodel
19 de agosto de 2020
No
Ninguna
En todos lados donde comencemos a usar el patron MVVM recomendado por las architecture patterns de android.
Ninguno todavia. 
Por el momento se usara en : …
> Adding lifecycle-viewmodel-ktx to whitelist

- context_whitelist.json
- ios-whitelist.json
- MLCollaboratorsV2
No
Si
ios=>10
0.5 MB
- MLCollaborators
> Add MLCollaboratorsV2 to context and ios whitelist

- android-whitelist.json
Se agrega v13 de Configuration Providers y se elimina la v11.
> Actualizacion de lib config

- android-whitelist.json
Se agregaron las dependencias de purchases, que no estaban, pero que se están usando hace un tiempo.
- com.mercadolibre.android.purchases:purchases
- com.mercadolibre.android.purchases:experimentals
Nota: Si tu equipo no tiene acceso, entonces debes completar el siguiente form de [acceso a herramientas]([https://sites.google.com/mercadolibre.com/mobile/arquitectura/acceso-a-herramientas](https://sites.google.com/mercadolibre.com/mobile/arquitectura/acceso-a-herramienta …
> Agregando purchases a la whitelist

- android-whitelist.json
Sube el major por API 29 en la lib de Draft Andes.
**08/10/2020**
> Bump Draft Andes

- context_whitelist.json
- "InsuranceCheckMobile"
- "com.mercadolibre.android.insurance_check_mobile"
No
No
Android
MinApiLevel = 19
MaxApiLevel = 29
iOS
Min = iOS 10
Max = iOS 14
El proyecto en Jira en el que se van a crear los crashes que ocurran es: INSUG
[¿Qué es el SLA de Crashes?](https://sites.google.com/mercadolibre.com/mobile/rele …
> add insurance-check-mobile context

- android-whitelist.json
- "com.mercadolibre.android.biometrics:sdk:4.+"
_No
_No, Biometrics no tiene código con NDK_
_No tiene cambios que impacten en el peso del módulo_
El proyecto en Jira en el que se van a crear los crashes que ocurran es: **_${DVCS}_**
> Bump biometrics version to 4.0

- android-whitelist.json
- context_whitelist.json
Estas librerías van ser utilizadas por el nuevo flujo de Registro V3 y Login. Parte de la iniciativa seguridad 360
Se agregan a al JSON de Context y a la whiteList. Por pedido de arquitectura la nuevas librerías nativas Android. De Auth Challenges y hub.
En qué apps impacta mi dependencia
> Add Auth Challenges & Hub context

- context_whitelist.json
- ios-whitelist.json
_No
_No
_ Minima 10.0 Maxima 13.2
_ SecurityOptions - Mercado Libre -> 1.5Mb con bundle
_ SecurityOptions - Mercado Pago -> 1.7Mb con bundle
El proyecto en Jira en el que se van a crear los crashes que ocurran es: **_sitesecurity_**
_ Pantalla de seguridad para ambas aplicaciones
> MODS-351-Nueva-Lib-Security-Options - Nueva libreria Security Options

- android-whitelist.json
Las dependencias ya fueron agregadas y aceptadas en https://github.com/mercadolibre/mobile-dependencies_whitelist/pull/500 junto con la version 1.+
Se extiende la fecha de expiración para alinear junto a iOS el release de 1.0.0
- "com.mercadolibre.android.credits.ui_components:components:0.+|1.+"
No, ninguno de los dos modulos de Credit UIComponents requiere inicializacion en el `Application`
No
Aunque el peso de los componentes de Flox no es significativo, al haberse separado en dos módulos se permitiría, incluir la lib de componentes sin las clases de Flox.
Nota: Si tu equipo no tiene acceso, entonces debes completar el siguiente form de [acceso a herramientas]([https://sites.google.com/mercadolibre.com/mobile/arquitectura/acceso-a-herramientas](https://sites.googl …
> Credits ui_components library dependency for 0.+ versions

- ios-whitelist.json
N/A
NO
SI
iOS 10
N/A
El proyecto en Jira en el que se van a crear los crashes que ocurran es: **DIDIV**
> Version 3.0.0 Remedies

- android-whitelist.json
- context_whitelist.json
- ios-whitelist.json
- **context_whitelist.json**: se agrega un contexto para dos nuevas librerías mobile (iOS y Android), para un nuevo frontend de una nueva sección de configuración de pricing en MercadoPago. _Ambas están con su desarrollo recién comenzado._
- Android: `com.mercadolibre.android.pricing_ui:pricing-ui`
- iOS: `PricingUI`
- **[android/ios]-whitelist.json**: se agrega a la whitelist dos librerías para Android y iOS. Actualmente, posee el challenge de **configuración de Tasas y plazos**, y un componente base que va a ser consumido por PricingUI en ambas plataformas.
- Android: `com.mercadolibre.android.fees_installments:mlfees`
- iOS: `MLFeesAndInstallments`
No
`-`
_Tienen Min API level 19_
- Para PricingUI, no tenemos peso ya que se está comenzando a desarrollar
- MLFees (Android): **404,8 KB** …
> Added context for the new Pricing frontend mobile library

- android-whitelist.json
> Update Lib Congrats

- context_whitelist.json
[¿Qué es el SLA de Crashes?](https://sites.google.com/mercadolibre.com/mobile/release-process/seguimiento-d …
> rename security to MobileDevicesSecurity

- android-whitelist.json
- com.mercadolibre.android.cardscomponents:cards-components:2.+
_No
_Si
Update de compatibilidad. No se agrego nada nuevo
- Cards Engagement y Cards Acquisition (Todo el mismo equipo)
> Update Cards Components

- context_whitelist.json
- iOS: BusinessConfigUi
- Android: com.mercadolibre.android.business_config_ui
No
Android:
Min Api 19
iOS:
Min iOS 10
Es una librería nueva ("Tu negocio"), y recién comienza el desarrollo, por lo que todavía no tenemos información sobre el peso.
Por el momento, solo agregamos al contexto y antes de salir lo haremos en la whitelist.
El proyecto en Jira en el que se van a crear los crashes que ocurran es: TFS
[¿Qué es el SLA de Crashes?](https://sites.google.com/mercadolibre.com/mobile/release-process/seguimiento-de-e …
> Add business config ui to context.

- android-whitelist.json
- context_whitelist.json
- "com.mercadolibre.android.insu_qpage_on:qpage_on:1.+"
No
No
- Min API level 19
- Max API level 29
Este modulo está recién iniciado y va a ser construido a través de la tecnologia flox.
En el largo plazo, la idea es que reemplace al modulo de garantia extendida, el cual hoy en dia esta pesando aprox 120 kb
- [WIP] Ya está configurado el contexto del módulo en las apps: **ML** [Android](https://github.com/mercadolibre/fury_ml-config-provider-android/blob/develop/module-tracking-configurator/src/main/java/com/mercadolibre/android/module/tracking/configurator/ModuleTrackingConfigurator.java), [iOS](https://github.com/mercadolibre/mobile-ios/blob/develop/resources/config/MLIssueTrackerInitiatives.plist) y **MP** [Android](https://github.com/mercadolibre/fury_mp-config-provider-android/blob/de …
> Add Insurtech libs to context and android whitelist

- android-whitelist.json
Esta libreria ya existia pero era usada en el mismo
proyecto, ahora la vamos a usar desde otro proyecto,
razón por la cual la necesitamos exportar.
- "com.mercadolibre.android.checkout:congrats:11.+"
Si requiere inicialización en el Application, pero ya se está haciendo dado que el módulo estaba ya integrado a meli
_No
Las mismas de todo meli
No suma peso dado que ya se estaba incluyendo en la app de meli
- [ X] Ya está configurado el contexto del módulo en las apps: el contexto es checkout_on
- [X ] Ya agregué y/o actualicé el contexto en la [context-whitelist](https://github.com/mercadolibre/mobile-dependencies_whitelist/blob/master/context-whitelist.json)
El proyecto en Jira en el que se van a crear los crashes que ocurran es: el de checkout_on …
> Agregamos el componente de congrats de checkout on

- android-whitelist.json
- context_whitelist.json
- ios-whitelist.json
- "MLCheckoutSDK: 0.+"
No
No
Las mismas que ML
Esta modulo está recién iniciado y va a ser construido a través de la tecnologia flox.
Si, utiliza:
- MLBFFloxComponent (mantenida por Checkout)
Esta nueva libreria va a soportar nuevas features tales como OneTap (compra rapida con opciones precargadas) y  SplitPayment (pagar con dos medios). Tambien algunos subflujos como BillingInfo.
> Add MLCheckoutSDK lib

- android-whitelist.json
Modificación de dependencia **com.mercadolibre.android.insu_flox_components:floxcomponents:0.+** para que la misma admita los flavor  **mercadolibre** y **mercadopago**
- "com.mercadolibre.android.insu_flox_components:floxcomponents:mercadolibre-1.+"
- "com.mercadolibre.android.insu_flox_components:floxcomponents:mercadopago-1.+"
_No
_No
El proyecto en Jira en el que se van a crear los crashes que ocurran es: **INSUG** …
> Added flavor to insu_flox_components dependency

- context_whitelist.json
- ios-whitelist.json
- **context_whitelist.json**: se agrega un contexto para una nueva librería mobile (iOS por el momento), para manejar situaciones de Seguridad Mobile tanto en MercadoPago como MercadoLibre. _Se encuentra en su desarrollo recién comenzado._
- iOS: `MobileDevicesSecurity`
- **ios-whitelist.json**: se agrega a la whitelist una librería para iOS.
- iOS: `MobileDevicesSecurity `
_No
_No
__ Minima 10.0 Maxima 13.2_
Nota: Si tu equipo no tiene acceso, entonces debes completar el siguiente form de [acceso a herramientas]([https://sites.google.com/mercadolibre.com/mobile/arquitectura/acceso-a-herr …
> added MobileDevicesSecurity

- android-whitelist.json
- "com.mercadolibre.android.garex:core:4.+"
_No_
_No, Garex no tiene código con NDK_
_Min API level 19_
_Max API level 29_
Update de compatibilidad. No se agregó nada nuevo.
> Update Garex version

- android-whitelist.json
Cambio de major por migración a flox 5 de la lib cards components
> Update cards components version

- android-whitelist.json
Se agrega expiracion de modulos y bump cards engagement major para flox 5
> Added Expires cards dependecies

- android-whitelist.json
- context_whitelist.json
- "com.mercadolibre.android.startup_initializer:core:1.+"
- "com.mercadolibre.android.startup_initializer:test:1.+"
_No
> Add Startup Initialializer

- context_whitelist.json
- "com.mercadolibre.android.insu_webview"
- "InsuWebview"
No
No
Android
MinApiLevel = 19
MaxApiLevel = 29
iOS
Min = iOS 10
Max = iOS 14
App size Android: 20KB
Librería que renderiza webView para simular flujos nativos.
> add Insurance webView

- android-whitelist.json
- "org.jetbrains.kotlin:kotlin-stdlib-jdk7"
_No
_No
_ MP 36.2 variant release
_Si
_Bastante madura, no es la última versión_
_Sí
_Nov 2019_
_Creemos que no es necesario un wrapper de la lib. La vamos a usar desde otra lib utilitaria (el REST Client) y para el resto de los devs debería ser …
> Actualizar versión de la librería  kotlin-stdlib-jdk7 a 1.3.50

- android-whitelist.json
com.mercadolibre.android.inappupdates
_No
_Si, …
> Major libs in-app-updates MP

- android-whitelist.json
Bump de max API version de melidata a 7 con migracion a androidX
> Melidata Major

- android-whitelist.json
Agrego version 2.0.4 de ConstraintLayout
- "androidx.constraintlayout:constraintlayout:2.0.4"
- "android.support.constraint:constraint-layout:2.0.4"
_No, Mejora tiempo de renderizado de UI, alrededor de un 5%, 10 % mas rapido que su anterior version._
_Si tiene soporte para diferentes arch._
_Tiene Min API level 9_
_Si, ConstraintLayout 2.0 es actualmente usada por Glovo, Rappi, Airbnb, Trello, Slack._
_Bastante madura, estuve probando mucho sus nuevos componentes, y ConstraintLayout (el componente que hoy usamos …
> Update  ConstraintLayout version 2.0.4

- android-whitelist.json
Se actualizan las libs core que fueron migradas a AndroidX
> Bump version libs core

- android-whitelist.json
Agrego version 2.0.4 de ConstraintLayout
- "androidx.constraintlayout:constraintlayout:2.0.4"
- "android.support.constraint:constraint-layout:2.0.4"
_No, Mejora tiempo de renderizado de UI, alrededor de un 5%, 10 % mas rapido que su anterior version._
_Si tiene soporte para diferentes arch._
_Tiene Min API level 9_
_Si, ConstraintLayout 2.0 es actualmente usada por Glovo, Rappi, Airbnb, Trello, Slack._
_Bastante madura, estuve probando mucho sus nuevos componentes, y ConstraintLayout (el componente que hoy usamos …
> Resolve ConstraintLayout

- android-whitelist.json
- "com.google.android.play:core:1.7.2 "
- Para soluciona una [vulnerabilidad de la libreria](https://developer.android.com/reference/com/google/android/play/core/release-notes#1-7-2)
> Updated play:core version to 1.7.2

- android-whitelist.json
Added support for the old version of the play:core library
> Supporting old version for now

- android-whitelist.json
Se sube la versión de la librería de Authentication tras la migración de AndroidX.
> Bump authentication version

- android-whitelist.json
Se actualiza las libs core de maps y keepnite para soportar migracion de android x
> Update bumpVersion libs maps y remoteConfigurations

- android-whitelist.json
Agregamos version 2.+ a la lista de permitidos en la libreria static resources.
Agregamos la version 2.+ como valida en la lista, esta libreria la estamos actualizando a una nueva version, compatible con la anterior pero con casos de uso nuevos.
No afecta a lo que ya se esta usando
No 
[static resources android](https://github.com/mercadolibre/fury_static-resources-android)
> Add static_resources 2.+

- android-whitelist.json
- "androidx.appcompat:appcompat:1.0.2"
Actualizamos version de AppCompat.
_De todas formas no estamos obligando al update, sino manteniendo ambas por las dudas, si tenemos identificado a alguien de vip que este al tanto del problema que tenian esta bueno que les avisemos para que puedan hacer alguna prueba, pero mientras podemos ir mergeando esta adaptación para poder avanzar del lado de Andes_
> Added version appcompat 1.0.2

- android-whitelist.json
"com.mercadolibre.android.instore_ui_components:core:2.+"
No, es un componente de UI que no requiere inicialización desde el mainApplication.
_No.
_Las mismas que MP y ML. …
> Bump Instore-UI 2.0

- android-whitelist.json
BumpVersion libs core debido a migracion android X
> Update whitelist libs core[WIP] [DO NOT MERGE]

- android-whitelist.json
BumpVersion libs local storage debido a que migramos a android X
> Update Version Local Storage

- android-whitelist.json
- "com.mercadolibre.android.addresses:core:4.+"
- "com.mercadolibre.android.addresses:zipcode:4.+"
_No, es solo un update de la versión_
_Se usa en el checkout y se empezará a usar en MyML_
- https://github.com/mercadolibre/fury_myml-mydata-android
> Updating addresses to v4

- context_whitelist.json
Added modules to context file:
* Credit Card Disable
* Credit Card Payment
* Credit Card Statements
* Credit Card Upgrade
* Credits UIComponents
No
N/A
N/A
N/A
El proyecto en Jira en el que se van a crear los crashes que ocurran es: https://mercadolibre.atlassian.net/jira/software/projects/SCRED
> Added modules to context whitelist

- android-whitelist.json
- "com.mercadolibre.android.recommendations:rcm:8.+"
No, es solo un update de la versión
- [Buying Flow] (https://github.com/mercadolibre/fury_buyingflow-mobile-android)
- [VPP] (https://github.com/mercadolibre/fury_vpp-android)
- [Reviews] …
> [Recommendations] - Bump version

- android-whitelist.json
- context_whitelist.json
- "com.mercadolibre.android.startupinitializer:splash:1.+"
_Sí, es parte de la iniciativa de Startup Flow_
_No_
_Es un módulo muy chico que incluye clases base para los splashes de Android ML y MP_
N/A
Release inicial
_Sí_
_Splashes de ML y de MP_
- [Mobile …
> Added context for Startup Initializer and added Splash module

- android-whitelist.json
- androidx.databinding:viewbinding
_No, no requiere inicialización en el `Application` y genera las clases de binding en tiempo de compilación
_Si
No tiene problema, soporta min API level 19
_Es la forma recomendada de google para hacer view binding.
_ Madura, con soporte oficial de google
_Sí, forma parte de jetpack
_Principalmente findViewById pero es menos safe y conlleva mas boilerplate code.
_Queremos usarlo en variations y empezar a usarlo en vpp, que actualmente usa kotlin syntethic, que quedó deprecado.
https://github.com/mercadolibre/fury_vpp-android/pull/1010
- [vpp](https://github.com/mercadolibre/fury_vpp-android) (Se quiere migrar de a poquito)
- [variations](https://https://github.com/mercadolibre/fury_variations-android)
- …
> Add View Binding Dependency

- android-whitelist.json
Borrado version proximamente deprecada:
"com.mercadolibre.android.instore_ui_components:core:1.+"
No, es un componente de UI que no requiere inicialización desde el mainApplication.
No.
Las mismas que MP y ML. …
> Delete version deprecated 1.0 Instore Ui Components

- android-whitelist.json
* Se incrementa la versión del rule engine a 4.+
* Se depreca la versión 3
> Add version 4 of rule-engine

- android-whitelist.json
- "com.mercadolibre.android.liveness_detection:facetec:sdk-9.0.4@aar"
No, FaceTec SDK no requiere inicialización en el 'Application'
_
Aumenta 5.04 MB en la descarga de la app.
_
Bastante madura, FaceTec SDK tiene ya una larga trayectoria.
_
11 de noviembre del 2020
No es necesario.
_ …
> Add liveness detection FaceTec SDK

- android-whitelist.json
- context_whitelist.json
Se agrega una lib interna para uso del team (su contraparte en iOS ya existe)
- `com.mercadolibre.android.tfs_commons:tracking:mercadopago-0.+`
- `com.mercadolibre.android.tfs_commons:tracking:mercadolibre-0.+`
- `com.mercadolibre.android.tfs_commons:tracking:mercadopago-1.+`
- `com.mercadolibre.android.tfs_commons:tracking:mercadolibre-1.+`
_No_
_No_
_No_ …
> Se agrega nueva lib "tfs-commons-android" a la whitelist y contexto

- android-whitelist.json
Estas son dependencias que actualmente se utilizan en la lib de contacts y es necesario incorporarlas a la whitelist para que el modulo pase la CI
- com.firebase:firebase-jobdispatcher:0.8.5
- com.squareup.sqlbrite:sqlbrite:1.1.2
No, ninguna de las libs requiere inicializacion
N/A
N/A
No afecta al peso de la app ya que las librerias se utilizan hace mucho
N/A
N/A
N/A
N/A
N/A
N/A
N/A
Ambas se utilizan para el manejo de los contactos en el device
> Add Contacts dependencies

- android-whitelist.json
Fijamos versiones de libs que no estaban pero que ya estamos usando, y bumpeamos las que ya estamos usando pero quedaron desactualizadas en la whitelist
> MP=ML=Whitelist

- android-whitelist.json
Se incorpora la lib de [CartAndroid](https://github.com/mercadolibre/fury_cart-android) (utilizada actualmente en ML), se incorpora la versión del último release y se deja un expire de 3 meses a la versión anterior
- "com.mercadolibre.android.cart:cart:mercadolibre-8.+"
- "com.mercadolibre.android.cart:cart:mercadopago-8.+"
_Es una lib usada actualmente en ML_
_Es una lib interna_
_Las mismas que ML_
> Add CartAndroid 

- android-whitelist.json
- "com.mercadolibre.android.andesui:coachmark:3.+"
_No.
_No.
_Tiene Min API level 19.
_Creemos que no es necesario un …
> add andes coachmark

- android-whitelist.json
- "androidx.webkit:webkit:1.4.0"
No, Webkit no requiere inicialización en el `Application`
No.
Tiene Min API level 14
[Documentación oficial](https://developer.android.com/reference/androidx/webkit/package-summary?hl=es)
~8 Kb
Es una libreria que es parte del suite androidx.webkit. Es parte deJetpack.
Madura
Mantenida por google
16 de diciembre de 2020
No.
Ninguna.
Necesitamos esta lib para utilizar la clase `WebViewAssetLoader` la cual es una clase auxiliar para la carga de archivos locales y recursos estáticos dentro de una webview. Se utilizará concretamente para renderizar un archivo PDF.
Por el momento ninguno.
https://github.com/mercadolibre/fury_ui-components-android/tree/master/pdf-viewer
> Add webkit dependency

- android-whitelist.json
> Se modifica el expire que quedo mal la fecha

- android-whitelist.json
Se actualiza fecha de expiración de la versión 7 Cart
> Update Cart Expire date

- android-whitelist.json
- context_whitelist.json
- "com.mercadolibre.android.security_two_fa:totpinapp:1.+"
_No, TotpInApp no requiere inicialización en el `Application`_
_No, TotpInApp no tiene código con NDK_
_TotpInApp module está pesando 25kb._
_25/02/2021_
_El ownership va a ser el [SAFE](safe@mercadolibre.com)_
_Estamos creando una lib para crear códigos que estarán siendo validados en backend_
- [auth-android-login #136](https://github.com/mercadolibre/fury_auth-android-login/pull/136)
- [Android Login](https://github.com/mercadolibre/fury_auth-android-login/)
- …
> Feature/Add TotpInApp Lib

- android-whitelist.json
- ios-whitelist.json
Android
- "io.jsonwebtoken:jjwt-api:0.11.2"
- "io.jsonwebtoken:jjwt-impl:0.11.2"
- "io.jsonwebtoken:jjwt-gson:0.11.2"
iOS
- "JWT" -> "2.2.0"
_No, no requieren ninguna inicializacion y su uso ocurre en el thread async que mantiene melidata para el envio de tracks
_No, usa libs nativas.
45k es la diferencia de apks buildeadas en release
_Bastante madura, tienen soporte en mas de 10 stacks de tecnologias diferentes y el jsonwebtoken es algo que gana mas y mas fuerza con el tiempo desde 2015_
Si esta en desarrollo activo y tiene releases estables.
_11 Junio 2020_
No hace falta. El ownership va a ser [melidata](mailto:melidata_dev@mercadolibre.com)
_Estamos en una iniciativa core de securizacion en melidata, encriptacion, PII y firmado. Estas libs corresponden a la parte de firmado de los …
> Melidata signature libs required

- android-whitelist.json
- context_whitelist.json
- ios-whitelist.json
- "com.mercadolibre.android.livecommerce:1.+"
- "Livecommerce"
_No
_No
_Creemos que no es …
> Add livecommerce lib dependency

- README.md
- ios-whitelist.json
Se incluyen las dependencias que faltaron en el [PR](https://github.com/mercadolibre/mobile-dependencies_whitelist/pull/677)
> Fix: Uncaught Dependencies

- ios-whitelist.json
se agregan dependencias de tests faltantes por el issue de dependency confusion
> Test dependencies

- ios-whitelist.json
- StartUPInitializer
Si, los configurator tanto de MP como de ML, se configuran en esta librería 
Se soporte swift y Objc
iOS 10
840 KB 
- [mp-config-provider](https://github.com/mercadolibre/fury_mp-config-provider-ios/pull/307)
- [mp-config-provider](https://github.com/mercadolibre/fury_mp-config-provider-ios)
- [ml-config-provider-ios](https://github.com/mercadolibre/fury_ml-config-provider-ios)
-
> Adding StartUPInitializer ~> 1.0

- ios-whitelist.json
> adding MPMerchengine ~> 2.0.0

- context_whitelist.json
Borrado de contextos de librerías que no existen más - Insurance 
- "com.mercadolibre.android.roda_qpage"
- "com.mercadolibre.android.insurance_protections"
_No, eran librerías internas las cuales levantaban webviews
_No
_No_
- "com.mercadolibre.android.roda_qpage" _v1.0.5 26 Nov 2020_
- "com.mercadolibre.android.insurance_protections" _v1.0.5 12 Nov 2020_
_Creemos que no es necesario un wrapper de la lib. La vamos a usar desde otra lib utilitaria (el REST Client) y para el resto de los devs debería ser transparente los cambios que haya en futuros releases de …
> Removed from deleted Insurtech library contexts

- android-whitelist.json
La lib de recaptcha nativa de google, es necesaria para la nueva implementacion de recaptcha enterprise:
com.google.android.gms:play-services-recaptcha:16.0.0
No, no requiere inicializacion
No
Minimo
Bastante madura, es una lib de Google
Si
No
No
Para mejorar la seguridad del login y disminuir los casos de falsos positivos de la implementacion actual.
- [ReCaptcha Enterprise](https://github.com/mercadolibre/fury_auth-android-login/pull/144)
- [Login](https://github.com/mercadolibre/fury_auth-android-login)
> Add recaptcha dependency

- android-whitelist.json
Se agrega nuevo Major de checkout
> Bump Cho Version

- android-whitelist.json
- "com.mercadolibre.android.uicomponents:*:11.+"
_No, no requiere inicialización en el `Application`_
No hay impacto
> Bump UIComponents Android

- android-whitelist.json
- ios-whitelist.json
- Se actualiza la version del sdk de cho en Android.
- Se actualiza la version del sdk de cho en iOS.
> Update cho sdk version in Android and iOS

- context_whitelist.json
- "com.mercadolibre.android.mlwebkit.webkit
- "com.mercadolibre.android.mlwebkit"
- "com.mercadolibre.android.mlwebkit.webkitcomponent"
_No, no requiere inicialización en el `Application`_
_No
No hay impacto
> Agrega los contextos de la libreria de Webkit

- android-whitelist.json
> Upgrade vpp major

- context_whitelist.json
- ios-whitelist.json
- DeveloperMode ~> 0.2
No
Si y si
iOS 10
Nada, no debería llegar a prod
En desarrollo para poder cambiar configuración dentro de la App
- [Mobile-iOS](www.github.com/mercadolibre/mobile-ios)
- [Wallet Mp](www.github.com/mercadolibre/mpmobile-ios)
> Add DeveloperMode

- ios-whitelist.json
Fix regex for Adjust to allow 4.28.0 not just 4.28.1+
> Fix adjust regex to allow 4.28.0

- android-whitelist.json
- ios-whitelist.json
- "com.mercadolibre.android.mlwebkit:1.+"
_No, estamos haciendo una migración de repositório_
_No_
_No, es un replace de la lib de webkit de UI-Components_
> Add dependences de MlWebkit

- context_whitelist.json
- "InsuQpageOn:0.+"
_No_
_No_
_Tiene Max iOS 14_
_InsuQpageOn está pesando 89kb_
_Creamos esta lib para desarrollar los componentes de Flox necesarios para las iniciativas de Insurtech._
- [garex-gpage-ios](https://github.com/mercadolibre/fury_garex-gpage-ios)
> Add InsuQpageOn to context

- android-whitelist.json
- "com.mercadolibre.android.insu_proxy.insu_proxy:1.+"
Current version: **1.0.0**
**Aclaración:** Librería de uso interno(Insurtech) y en modo `debug`.
_No, insu_proxy no requiere inicialización en el `Application`_
_El peso de la lib es de 20kb aproximadamente, es una librería de uso interno y en modo debug, y es considerablemente pequeña_
- No es necesario agregar el contexto ya que no va a operar en forma productiva.
_En el día de hoy_
_Esta lib la necesitamos para agilizar las pruebas internas del equipo(Insurtech), la cual nos permite tener un manejo flexible de los scopes a los cuales apuntar, atributos en el header y demás_
- [Proxy implementation](https://github.com/mercadolibre/fury_insu-qpage-on-android/pull/30#issuecomment-814210 …
> Add Proxy-Insurtech library

- android-whitelist.json
> Add expire date un vip 5.x

- android-whitelist.json
- bump de rxBle 1.5.0 a 1.11.1
_No
_SI
_Tiene Min API level 18
_Creemos que no es necesario un wrapper de la lib. La …
> Bump rxble

- ios-whitelist.json
> Update libs y agregar fecha de expiración de libs legacy

- android-whitelist.json
- "com.mercadolibre.android.cart:cart"
_Sí, OkHttp es mantenida por una comunidad extensa e incluso …
> Update CartAndroid version

- android-whitelist.json
Se agrega los flavor (proxy y noproxy) para poder implementar la dependencia en los distintos buildtypes(debug, mds y release).
- "com.mercadolibre.android.insu_proxy.insu_proxy:proxy-1.+"
- "com.mercadolibre.android.insu_proxy.insu_proxy:noproxy-1.+"
Current version: **1.2.1**
_No, insu_proxy no requiere inicialización en el `Application`_
_El peso de la lib es de 20kb aproximadamente, es una librería de uso interno y en modo debug, y es considerablemente pequeña_
- No es necesario agregar el contexto ya que no va a operar en forma productiva.
_En el día de hoy_
_Esta lib la necesitamos para agilizar las pruebas internas del equipo(Insurtech), la cual nos permite tener un manejo flexible de los scopes a los cuales apuntar, los atributos …
> Proxy Insurtech - Flavors implementation

- android-whitelist.json
- Revert RXble por crash en ciertos dispositivos de 1.11.1 a 1.5.0
Encontramos dispositivos que crashean al finalizar la conexión con la nueva version agregamos un expire para trabajar en paralelo este error ya que el bump trae mejoras y utiliza android x
_No
_No
18
_Bastante madura, OkHttp tiene ya una larga trayectoria y es …
> Revert bump rxble to 1.5.0

- context_whitelist.json
Se crea el contexto para la nueva librería de Android que se encargará de la lectura y carga de tarjetas Semovi. Este nuevo modulo es parte del proyecto Single Player Prepaid Nativo
_No, no requiere inicialización en el `Application`_
_No, no tiene código con NDK_
_El modulo está pesando 4.136Mb
_Bastante madura_
_Sí, es mantenida por Spirtech_
_Hace 3 semana_
- [Single Player Prepaid Spirtech Android](https://github.com/mercadolibre/fury_spp-spirtech-android)
> [Feature] Se agrega contexto SinglePlayer Prepaid Spirtech

- android-whitelist.json
- "androidx.lifecycle:lifecycle-process:2.2.0"
_No debería
_Es una libreria nativa: [doc](https://developer.android.com/jetpack/androidx/releases/lifecycle)
_ Min API 14
_7kb maximun
_ Mercado libre
_ 
_Bastante madura, su primer versión salió en el 2018 y su última versión esta 2.4.0
_Esta mantenida
_24 de marzo de 2021
_No
_
_En developer mode utilizamos esta lib para observar los eventos del ciclo de vida de la aplicación
- 
-
> Add androidx lifecycle-process version 2.2.0

- ios-whitelist.json
InsuProxy
No
SI
ios min: 10
ios max: 14
NO
EL context no se agrega por ser una lib que solo se ejecuta en modo Debug
Esta lib esta pensada como herramienta de desarrollo, que solo se ejecuta en modo Debug para definir los scopes y header a donde apuntan nuestra lib Nativas tanto en ML como MP, via una pegada a un proxy-mobile.
https://github.com/mercadolibre/fury_insurance-check-mobile-ios/pull/74/files#diff-882f2c209bc157f488318aaa6c1c[…]8bd89973055808024a9dbd7dd0a19f0R52
> Add InsuProxy to whitelist

- android-whitelist.json
- "com.mercadolibre.android.ignite:core:3.0"
_No
_No
_Se mantiene Min version de ignite core
_No afecta
_Lib interna
_Necesitamos estos cambios para el uso de developer mode
Ver repositorio: https://github.com/mercadolibre/fury_ignite-android
> Update android-whitelist.json with ignite core 3.0

- android-whitelist.json
> Add Commons v17

- ios-whitelist.json
- "SPPSpirtech"
_No, SPPSpirtech no requiere inicialización en el `Application`._
_No._
_iOS 10.0 en adelante._
_La librería pesa 4.5MB._
_Ninguna, se desarrolló exclusivamente para nuestro uso._
_Sí, SPPSpirtech es mantenida por la empresa Spirtech._
_Hace 3 semanas._
_Sí, se va a wrappear, y el ownership va a ser el equipo [Single Player Prepaid](mailto:single-player-prepaid-it@mercadolibre.com)_
_No, fue desarrollado exclusivamente para nuestro uso._
_Se quiere integrar lectura de tarjetas de transporte vía NFC en la sección de recargas de transporte MLM. Este módulo interviene en dicha comunicación NFC._
- [fury_sp-prepaid-ios](https://github.com/mercadolibre/fury_sp-prepaid-ios)
> Addition of SPPSpirtech to iOS whitelist.

- android-whitelist.json
- "com.mercadolibre.android.point_smart_helpers:point_commons:1.+"
- "com.mercadolibre.android.point_recharge:cellphone:1.+"
- "com.mercadolibre.android.point_recharge:transport:1.+"
_No
_No
_Tiene Min API level 23_
_No
_Hoy
_Estamos migrando todos los modulos de Smart a librerías independientes para modularizar la aplicación
- [Recharge](https://github.com/mercadolibre/fury_point-recharge-android/pull/22)
- …
> Incluida librería de point_smart_commons

- android-whitelist.json
- "com.mercadolibre.android.pos_readers:posreaders:4.+"
- "com.mercadolibre.android.payment_flow:paymentflow:6+"
No
No
Ambas libs tiene Min API level 19
El proyecto en Jira en el que se van a crear los crashes que ocurran es: **_${point}_**
-
-
-
Menos de 1 semana
La lib pos readers se utiliza en las libs de **paymentflow** y **paymentflowfcu**
La lib de **paymentflow** se utiliza en la wallet
- [paymentflow](https://github.com/mercadolibre/fury_payment-flow-android)
- [posreaders](https://github.com/mercadolibre/fury_pos-readers-android)
> Se incluyen las libs de paymentflow y posreaders

- android-whitelist.json
Se actualiza el major de la lib de authentication ya que se modificaron sus dependencias internas. La misma deja de depender de security directamente y se le deben proveer mediante el configurator la implementacion del mecanismo de attestation y del device profile a usar. Esto se hizo para poder separar la logica del profile del device de authentication.
No
No
No se modifico nada significativo.
No aplica
No aplica
> Bump authentication major

- ios-whitelist.json
upgrade del major para https://github.com/mercadolibre/fury_startup-initializer-ios
_No, es un improvement a la libreria
_Si
_La configurada actualmente para iOS
_Ninguno
> startupInitializer major updated

- ios-whitelist.json
Upgrade CreditsUIComponents major version iOS
_Sí, OkHttp es mantenida por una comunidad extensa e …
> Update CreditUIComponent major version iOS

- android-whitelist.json
Actualmente tenemos disponible para usar workmanager 2.0.1, se quiere adicionar la version 2.1.0 manteniendo tambien la version anterior. 
Esto es debido a issues que tiene la lib 2.0.1 y tambien porque en la version siguiente se agregaron nuevas features para unit test.
- "androidx.work:work-runtime-ktx:2.1.0"
_No
_No
_Tiene Min API level 14
_20kb
_Bastante madura
_Sí
_Abril 2021
_No
_Se necesita para agendar push notifications.
- 
- [notifications](https://github.com/mercadolibre/fury_mobile-notifications-android)
> [Android] work maganer 2.1.0 added 

- ios-whitelist.json
- ios-whitelist.json: se agrega a la whitelist una librería para iOS. **NativeReauth** aún se sigue desarrollando
No
No
Minima 10.0 Maxima 14.0
NativeReauth - MercadoPago = 2.3mb
NativeReauth - MercadoLibre = 2.5mb 
Según https://meli.workplace.com/notes/330548445069853 es automatico
El proyecto en Jira en el que se van a crear los crashes que ocurran es: **_${sitesecurity}_**
_Esta lib es para realizar re-autenticaciones nativa, inicialmente en la sección de seguridad en la app_
> Se agrega lib NativeReauth

- context_whitelist.json
- "com.mercadolibre.AccountRecovery"
_No
_No
_Tiene Min iOS 10.
_Minimo
_Si
_Estamos creando un nuevo frontend 'AccountRecovery' el cual será llamado desde el Login en iOS, dicho flujo ya existe y se encuentra productivo en Android.
- [PR abierto](https://github.com/mercadolibre/fury_auth-account-recovery-ios/pull/3)
- [AccountRecovery](https://github.com/mercadolibre/fury_auth-account-recovery-ios)
> Added ios key context for account_recovery

- context_whitelist.json
Added context to commons and recharge Point Smart Libraries
_No
_No
_Creemos que no es necesario un wrapper de la lib. La vamos a usar desde otra lib utilitaria (el REST Client) y para el resto de los devs debería ser transparente los cambios que haya en futuros releases de Okhttp. El ownership va a ser el [equipo de …
> Added context to commons and recharge Point Smart Libraries

- android-whitelist.json
- context_whitelist.json
- ios-whitelist.json
- "com.mercadolibre.android.merch_realestates"
_Sí, OkHttp es mantenida por una comunidad extensa e …
> Add MerchRealestates

- android-whitelist.json
Add flipper network plugin
- com.facebook.flipper:flipper-network-plugin:0.45.0
_No
_No
Requirements
node >= 8
yarn >= 1.5
iOS developer tools (for developing iOS plugins)
Android SDK and adb
_Si, supongo que la van a empezar a usar todas
Entiendo que es bastante reciente pero es de facebook, supongo que va a estar bien mantenida. 
_Sí, es de facebook
Hace 3 horas atras
Es una lib de …
> add com.facebook.flipper

- android-whitelist.json
- ios-whitelist.json
Android:
- "androidx.camera:camera-camera2:1.0.0"
- "androidx.camera:camera-lifecycle:1.0.0"
- "com.google.android.gms:play-services-mlkit-text-recognition:16.1.3"
- "com.google.mlkit:barcode-scanning:16.1.4"
iOS:
- GoogleMLKit/BarcodeScanning
- GoogleMLKit/TextRecognition
[Análisis](https://docs.google.com/document/d/1QEynBztN6ZQAIcqvU4L8ZtHDgTK6avqxYOoj122vZdQ/edit#heading=h.2mm45kb28gk1)
_No, permite la opción de decargar los modelos al momento de su utilización._
_No_
Android:
_CameraX tiene Min API level 21_
iOS:
_MLKit es soportada en IOS 11+_
_MLKit Recognition Text tiene un peso de 758KB en Android y 30MB en iOS_
_MLKit barcode-scanning en Android tiene un peso de 2.8MB_
_Las dependencias de camera ambas tiene un peso 459.5 KB_
"androidx.camera:camera-camera2:1.0.0" …
> Feature] MLKit dependencies added (barcode and OCR) - Android and iOS

- android-whitelist.json
- `androidx.databinding:viewbinding:4.1.1`
_No_
_No_
_Min API level 19_
_-_
> Added "View Binding" dependency: v. 4.1.1

- android-whitelist.json
_Se corrige el package para el modulo commons de Multiplayer Android cargado en esta [PR](https://github.com/mercadolibre/mobile-dependencies_whitelist/pull/746)_
_No_
_Las mismas que MercadoPago_
_Estamos creando una nueva lib funds-movements y necesita acceder al módulo de commons de moneytransfer para reutilizar varios componentes._
- [PR](https://github.com/mercadolibre/fury_funds-movements-android/pull/2)
- [Funds Movements](https://github.com/mercadolibre/fury_funds-movements-android)
> Fix multiplayer commons package android

- ios-whitelist.json
Upgrade del major para MPMoneyTransfer iOS 
No
Las mismas de la app de Mercado Pago
> Upgrade MPMoneyTransfer major iOS 

- android-whitelist.json
Se agrega expire a las versiones 14.+, 15.+ y 16.+ del configurer ML, y ademas se agrega la version 17.+ removiendo restclient legacy.
_Si, OkHttp es actualmente usada por X, Y, Z, …
> Expire config provider ML 

- ios-whitelist.json
- [MLAddresses](https://github.com/mercadolibre/fury_addresses-ios)
La lib corresponde al equipo de Addresses. Ya existe en [Android](https://github.com/mercadolibre/fury_addresses-android). Hasta ahora no existía en iOS y estamos empezando a hacer las primeras pruebas.
Las pantallas que ofrece la lib son:
Formulario | Listado de direcciones | Mapa
------|------|------
No.
No.
- [Proximity Marketplace](https://github.com/mercadolibre/fury_discounts-center-ios/)
- Checkout
> iOS: Add MLAddresses lib

- android-whitelist.json
- context_whitelist.json
- "com.mercadolibre.android.spp_spirtech:spirtechmodule:1.+"
- "com.mercadolibre.android.spp_spirtech:decodingmanager:1.+"
- "com.mercadolibre.android.spp_spirtech:ccmmexico_enhanceddevice:1.+"
- "com.mercadolibre.android.spp_spirtech:ccmmexico:1.+"
- "com.mercadolibre.android.spp_spirtech:ccmgeneral:1.+"
_No
_No
_No
_Bastante madura
_Sí, OkHttp es mantenida por …
> librerías spirtech para Point smart

- scripts/notification.rb
> fix typo url

- .circleci/config.yml
ya terminadas las pruebas dejo el cron para q se ejecute solamente una vez por semana, (los dias lunes)
> final cron once a week

- android-whitelist.json
- "com.mercadolibre.android.security:native_reauth:mercadolibre-1.+"
- "com.mercadolibre.android.security:native_reauth:mercadopago-1.+"
_No
_No
- [x ] Ya agregué y/o actualicé el contexto en la [context-whitelist](https://github.com/mercadolibre/mobile-dependencies_whitelist/blob/master/context-whitelist.json)
> Se agrega nueva lib para reath nativa a la whitelist

- android-whitelist.json
- "com.mercadolibre.android:melidata-sdk:8.+"
_Sí, OkHttp es mantenida por una comunidad extensa e …
> update melidata sdk version

- ios-whitelist.json
- "ZIP Foundation", "0.9.12"
No
Si, adicionalmente utiliza CZlib
Versiones minimas:
Swift 4.0
Xcode 11.0
La nueva librería agrega menos de 200kb aproximadamente
No tenemos conocimiento de que la utilice una empresa conocida
Existe desde el 2017 y es muy utilizada por la comunidad
Si, es mantenida principalmente por su creador y por una comunidad
Ultimo release el 22 de Febrero
Creemos que no es necesario un wrapper de la lib
Esta es la más popular recientemente investigando en foros como Stackoverflow, no se ha considerado utilizar otra
Necesitamos descomprimir un zip que se utiliza para …
> Request ZIP Foundation pod whitelist

- android-whitelist.json
- context_whitelist.json
- "com.mercadolibre.android.point_virtualization:point_virtualization:1.+"
_No
_No
_Tiene Min API level 23_
_Hoy_
_Estamos migrando todos los modulos de Smart a librerías independientes para modularizar la aplicación_
- [Smart Point](https://github.com/mercadolibre/fury_mpmobile-smartpos)
fury_point-virtualization-android: Es una librería creada para el uso del Team de Point - Smart
> [SMARTY-2499] - Se agrega la lib de point_virtualization

- android-whitelist.json
Módulo con Kotlin Extensions que usamos en varios proyectos.
Módulo con clases base para el patrón MVP (que usamos en varios proyectos).
> ### **_Aclaración importante: son dos librerías de uso interno del equipo, no están en ningun otro proyecto que no sea de SX/TFS._**
-------
_No_
_No_
_No tiene un impacto significativo, ya que son muy pocos archivos en cada módulo._
El proyecto en Jira en el que se van a crear los crashes que ocurran es: [Tools For Sellers](https://mercadolibre.atlassian.net/secure/RapidBoard.jspa?rapidView=1090&projectKey=TFS)
> Nuevos módulos para la librería "com.mercadolibre.android.tfs_commons"

- android-whitelist.json
- "com.google.mlkit:barcode-scanning:16.1.2"
_No, MLKit no requiere inicialización en el `Application`_
_No, MLKit no tiene código con NDK_
La version que tienes los modelos para hacer scan agrega ~ 4.3 MB en apk release:
https://developers.google.com/ml-kit/case-studies
_Bastante madura, MLKit tiene ya una larga trayectoria y es utilizada incluso por Android internamente_
Posee gran madurez, el primer release de Android e iOS fue el 3 de Junio de 2020 y recibe manteniendo actual
25/05/2021
https://developers.google.com/ml-kit/release-notes
Android: https://github.com/mercadolibre/fury_ml-scanner-android
_Si, existe Zxing. Preferimos esta porque:_ …
> bundled mlkit scanner lib

- android-whitelist.json
- context_whitelist.json
- "com.mercadolibre.android.wallet.home:home:1.+"
- "com.mercadolibre.android.wallet.home:sections:1.+"
En nuestra librería de MoreOptions en Point Smart tenemos una serie de secciones configurables basadas en los componentes de la Home de la Wallet comenzando por el shortList de activities.
Antes no teniamos este problema porque consumiamos directamente la librería de Home así como lo hace la Wallet, pero como parte de una estrategía de modularización y escalabiliadd decidimos extraer la lógica relacionada a una librería aparte
_No_
_No_
_Hace 2 semanas_
_En …
> Libreria de Home para Point Smart

- scripts/clean_whitelists.rb
the list was a reference to the old one, so when deleting one item affected both list hence the current position, leading to not proper check the next item after a removed one.
> fix when removing item, and doesn't keep track of current position on list

- context_whitelist.json
- "CardsBanking"
- "com.mercadolibre.android.cardsbanking"
- No, es solo un modulo que utiliza la home
- Tiene soporte para arquitectura iOS y Android
- Min iOS deployment version --> iOS12
- Min Android deployment version --> API21
- No deberia existir un aumento del peso de la app, ya que lo estamos migrando desde otra lib
- Es el CardsBanking de la home, actualmente funcionando sin problema alguno.
- No externo a meli, mantenimiento por el equipo de CARDS. Se encuentra activo en cuanto a desarrollo.
- No, es un modulo desarrollado internamente en meli
- Es el componente que aparece en …
> Cards Banking

- android-whitelist.json
'com.google.firebase:firebase-ml-modeldownloader-ktx:23.0.0'
'org.tensorflow:tensorflow-lite:2.4.2'
Documento realizado:
https://docs.google.com/document/d/1DRFUVIGAl5qgWmDt-JtgPNJ7z1n-R3SOW4nPGLMFawQ/edit#heading=h.kbx3h11a3gp0
No
4,7 MB se agregan en Android según MDS (en el PR de ML eran 4,11 MB). Post instalado 68,73 (+6,32) MB.
Google para MLKit ObjectDetection.
Bastante madura, se usa como base para toado lo que es ML del lado de Android.
Sí
Hace 2 dias
En principio no se wrappearia porque la usariamos solo nosotros Identity Validation
Si existe MLKit Object detection de Google pero pesa 3 veces más que esta librería.
Queremos detectar que la imagen que nos envía el usuario cumpla ciertas condiciones, como que tenga un …
> Add tensor flow libs

- ios-whitelist.json
- "GoogleMLKit/TensorFlowLiteSwift", Sirve para interpretar modelos de ML.
- "Firebase/MLModelDownloader", Sirve para descargar modelos de forma remota.
No
No
[Minima, iOS 12](https://github.com/tensorflow/examples/tree/master/lite/examples/object_detection/ios)
Maxima, no tiene
Tiene un aumento de 2,9MB de descarga.
Instalación tiene un aumento de 8,9MB. 
Google
Ya es productiva, viene la versión beta , Firebase/MLInterpreter
Mantenida por Google
20/05/2021, [releases](https://libraries.io/cocoapods/TensorFlowLiteSwift)
No se va a wrappear, por ahora el equipo que va a usar la lib es, Identity Validation
MLKitObjectDetection, simplifica la implementación pero pesa 12MB
Queremos detectar que la imagen que nos envía el usuario cumpla ciertas condiciones, como que tenga un documento, no …
> Add TensorFlowLiteSwift

- android-whitelist.json
- context_whitelist.json
- "com.mercadolibre.android.point_smart_pos_sdk:PPCompAndroidLib:0.0.1"
No
Si, soporta las arquitecturas armeavi-v7 que son sobre las cuales está construido el SmartPos
Bastante madura, es un wrapper de una librería aar que se implementa en Point SmartPos
No
23/06/2021
Es un wrapper de una librería para uso solo del team de point_smartpos
Esta librería es necesaria en la implementación de Smart, ya que se encarga de controlar el Hardware del dispositivo
> Implemented new library for smartpos

- ios-whitelist.json
PointFlowEngine
PointUI
_No_
_No_
_No_
_Estamos creando un nuevo frontend 'example' y necesita hacer API calls con un websocket custom porque vamos a permitir llamados en real time (vamos a utilizar OkHttp para el mismo). Creamos una API example-module que nos wrappea la lógica de negocio_
- [Point](https://github.com/mercadolibre/fury_point-ios)
- [PointUI](https://github.com/mercadolibre/fury_point-ui-ios)
- [PointFlowEngine](https://github.com/mercadolibre/fury_point-flow-engine-ios)
> Updated Point Flow Engine and PointUI matching version

- android-whitelist.json
- context_whitelist.json
- "com.mercadolibre.android.point_more_options:point_moreoptions:1.+"
- 
_No
_No
_Tiene Min API level 23_
(Los devices utilizados en Smart son api 23 y api 29)
_Hoy_
_Estamos migrando todos los modulos de Smart a librerías independientes para modularizar la aplicación_
- [Smart Point](https://github.com/mercadolibre/fury_mpmobile-smartpos)
fury_point-more-options-android: Es una librería creada para el uso del Team de Point - Smart
> se agrega la libreria de more options

- android-whitelist.json
Debido al bump para min api level 21 necesitamos habilitar las nuevas versiones para poder usarlas. …
> Min api 21 para componentes de digital accounts

- android-whitelist.json
- "com.mercadolibre.android.insu_qpage_on:qpage_on:2.+"
_No, insu_qpage_on no requiere inicialización en el `Application`_
_No_
_Min API level 21_
_No_
_Hoy mismo_
_Se elimina Garex lib y qPageOn recibe las adaptaciones necesarias para permanecer en el flujo de Checkout_
- [PR-Checkout](https://github.com/mercadolibre/fury_buyingflow-mobile-android/pull/4971)
- [Checkout](https://github.com/mercadolibre/fury_buyingflow-mobile-android/)
> Bump major QPageOn - Insurtech 

- ios-whitelist.json
- CardsBanking
- No
- No
- iOS12 Minimun deployment version
- No cambiaria, ya que es un modulo que se migra de repo
- Ya tiene varios años, es un modulo de la Home Wallet que fue cedido
- No
- Hace menos de un dia
- No
- En la Home? 
- N/A
- CardsBanking
> CardsBanking iOS dependency added

- .github/pull_request_template.md
actualizamos el template del PR
> reducing + updating pr template

- android-whitelist.json
- ios-whitelist.json
- - "Pendings"
- [fury_pendings-ios](https://github.com/mercadolibre/fury_pendings-ios)
> add pendings

- .github/pull_request_template.md
> More template cleaning

- ios-whitelist.json
Actualización de Bugsnag a la versión 6.9.6 con soporte para la versión actual
- No
- Sin variación
- Bugsnag
- Sin variación
- Sin variación
- MLCommons: https://github.com/mercadolibre/fury_mobile-commons-ios
> Adding new version 6.9.6 with support for current version

- android-whitelist.json
- - "androidx.fragment:fragment-ktx:1.2.5"
Descripcion:
La dependencia provee una forma fácil para manejar los view models entre el activity el fragment. Ademas provee de APIs útiles para fragments, como por ejemplo "activityViewModels()"
Debido a que cada vez tenemos nuestras apps en kotlin y como estamos en un proceso de migración de multiples pantallas a fragment vemos conveniente utilizar la que nos provee kotlin a fin de estar alineados con el lenguaje. Además dentro de la whitelist permitimos dependencias de android ktx donde no se encuentra la de fragment
- [example …
> adding fragment-ktx dependency

- android-whitelist.json
- "com.mercadolibre.android.point_smart_pos_sdk:device:a910-1.+"
- "com.mercadolibre.android.point_smart_pos_sdk:device:d20-1.+"
- "com.mercadolibre.android.point_smart_pos_sdk:device:dev-1.+"
- No, mi Lib no requiere inicialización en el `Application`_
> Implemented new library for smartpos, icluding POS devices a910 and d20

- README.md
- android-whitelist.json
ya la teniamos
- _Si, mi Lib requiere inicialización en el `Application`_, no agrega mas tiempo al anterior. 
> Bugsnag bump v5.10.1

- android-whitelist.json
- " com.mercadolibre.android.payment_flow_fcu:entities_fcu:version"
- " com.mercadolibre.android.payment_flow_fcu:pointsmartpos_fcu:version"
En el proceso de desarrollo del Flujo de Cobro Unificado se decide crear nuevos modulos a fin de poder unificar entidades en comun y poder comenzar a desarrollar modulos independientes que consuman esas entidades en comun e implementar sus reglas del motor de FCU de acuerdo al lector con el que se trabaja.
mPOS (WalletMP) trabaja sobre `paymentflowfcu` y SmartPOS sobre `pointsmartpos_fcu`
De momento estas dependencias no tienen impacto actual sobre dichas apps ya que se encuentran en proceso de desarrollo.
No
No 
[Tienen que completar el form que esta en la wiki](https://sites.google.com/mercadolibre.com/mobile/arquitectura/libs …
> Nuevas dependencias de FCU

- android-whitelist.json
- "androidx.recyclerview:recyclerview:1.2.1"
> [Feature] Update Recyclerview Library from 1.1.0 -> 1.2.1

- android-whitelist.json
-  "org.jetbrains.kotlin:kotlin-reflect:1.3.40"
Se utiliza esta dependencia por temas de dynamic feature. (https://github.com/mercadolibre/mobile-android/pull/8907)
> Add kotlin reflect

- android-whitelist.json
> latest bugsnag v5.11.0

- android-whitelist.json
Update Credits UI Components version to 2.+.
Add expiration date to version 1.+
> Update Credits UI Components version to 2.+.

- android-whitelist.json
> Commons v19.+ & Expires 17.+

- android-whitelist.json
-  "com.mercadolibre.android.loyalty_ui_components:home-mp-components:4.+"
> loyalty ui v3 & v4

- android-whitelist.json
> Add new version df and expires date

- ios-whitelist.json
- - Cashout project (https://github.com/mercadolibre/fury_cashout-ios)
...
- NA
- [MoneyOut PR](https://github.com/mercadolibre/fury_money-out-ios/pull/432)
> Add Cashout project 

- ios-whitelist.json
PointFlowEngine
No
No
No
No
- [PR - Point](https://github.com/mercadolibre/fury_point-ios/pull/1493)
- [Point-iOS](https://github.com/mercadolibre/fury_point-ios)
- [PointFlowEngine](https://github.com/mercadolibre/fury_point-flow-engine-ios)
> Update FlowEngine to support v1.x and v2.x

- android-whitelist.json
- _N/A_
- _No, Se elimina por la migración de se realizó a workManager y no tiene mas uso por api 30_
> Delete dependency firebase-jobdispatcher

- ios-whitelist.json
- MLAdjust
Esta dependencia incluye un SDK (Adjust Signature) que complementa el SDK ya utilizado en la aplicación ML y MP (Adjust).
_Note: For the library to function at least version 4.21.1 of the public SDK library is needed._
- No, la lib no requiere inicialización en la aplicación ML ni MP
- Esta librería es un wrapper de Adjust Signature SDK v2 provista por esta empresa
- iOS6 minimum deployment version.
- 1 MB (tamaño del framework)
- La librería es un wrapper del Adjust Signature SDK v2 provista por la empresa tercerizada para mejorar la seguridad de la comunicación con los servidores.
Libs [internas](https://sites.google.com/mercadolibre.com/mobile/arquitectura/libs-utilitarias/libs-internas) o [externas](https://sites.google.com/mercadolibre.com/mobile/arquitectura/libs-utilitari …
> MLAdjust iOS dependency added

- ios-whitelist.json
PointUI
_No_
_No_
_No_
_Estamos creando un nuevo frontend 'example' y necesita hacer API calls con un websocket custom porque vamos a permitir llamados en real time (vamos a utilizar OkHttp para el mismo). Creamos una API example-module que nos wrappea la lógica de negocio_
- [Point](https://github.com/mercadolibre/fury_point-ios)
- [PointUI](https://github.com/mercadolibre/fury_point-ui-ios)
> PointUI new version

- ios-whitelist.json
- Eliminación de la versión anterior de Bugsnag
- MLCommons
- MPPoint
- MPConfigurationProvider
- MLConfigurationProvider
- Traceability
> Removal of the previous version of Bugsnag

- ios-whitelist.json
Se actualiza la versión de MLKit iOS
> MLKit version updated

- ios-whitelist.json
- - PointFlowEngine 3.0.0
- No
- No
- Si
- No
- No
- [PointFlowEngine](https://github.com/mercadolibre/fury_point-flow-engine-ios)
- [Pont](https://github.com/mercadolibre/fury_point-ios)
> Bump FlowEngine to support 3.0

- ios-whitelist.json
- [PointUI](https://github.com/mercadolibre/fury_point-ui-ios)
- No
- Si
- Si
- No
- 
- [PointUI](https://github.com/mercadolibre/fury_point-ui-ios)
- [PointUI](https://github.com/mercadolibre/fury_point-ios)
> Support new version 3.0 - PointUI

- ios-whitelist.json
- SmartCoupons
Esta lib se va a utilizar para centralizar el acceso a Smart Coupons desde MLCart, MLCheckout & Checkout ON: One Tap.
- No
- Minimum deployment target: iOS 12
- El modulo pesa 228kb
- N/A
- https://github.com/mercadolibre/fury_smart-coupons-ios
> Add SmartCoupons to iOS Whitelist

- ios-whitelist.json
SnapshotTesting
No, se usaría solo como test en mi proyecto de prueba.
No tiene dependencias, tiene soporte para osx y tvos.
La version minima es iOS 11
No, solo se quiere incluir en el proyecto de test de mi equipo. No seria parte de nuestro pod.
> Add SnapshotTesting to whitelist

- ios-whitelist.json
- No
- No
- [bump ml](https://github.com/mercadolibre/fury_mercadolibre-ios/pull/6019)
- [bump mp](https://github.com/mercadolibre/mpmobile-ios_wallet/pull/8230)
- [MLRemedy](https://github.com/mercadolibre/fury_remedy-ios)
> MLRemedy v4

- ios-whitelist.json
Support version 1.0 in PointFlowEngine and PointUI.
No
No
No
- [Point](https://github.com/mercadolibre/fury_point-ios)
> Support version 1.0 in PointFlowEngine and PointUI

- ios-whitelist.json
Lib : SecurityTwoFactor
Esta librería es la encargada de la interacción entre el Login y IV para el paso de FaceValidation ya existe para Android. Ahora se creo para iOS
- mercadolibre/fury_auth-security-two-fa-ios
- mercadolibre/mpmobile-ios_wallet
> Include SecurityTwoFactor

- android-whitelist.json
> bump vip_commons and vip versions

- android-whitelist.json
- Adjust SDK
- No
- No
- The minimum supported Android API level for the Adjust SDK integration is 9
- No
- No
- [Adjust android](https://github.com/mercadolibre/fury_adjust-android)
- Ya existe, no tengo que agregar ni modificar nada.
> Adjust SDK version updated

- android-whitelist.json
agregamos un expire a esta libreria que ya no se usa
> expire calligraphy

- android-whitelist.json
- - "com.squareup.okhttp3" -> 3.14.9
...
> Se actualiza version de okhttp3

- android-whitelist.json
- "com.mercadolibre.android.ml_scanner:scanner"
- "com.mercadolibre.android.ml_scanner:ocr"
- "com.mercadolibre.android.ml_scanner:barcode"
Biblioteca unificada responsable de escanear códigos de barras, QRCode y OCR
https://github.com/mercadolibre/fury_ml-scanner-android
No, mi Lib no requiere inicialización en el `Application`
No, ML_Scanner no tiene código con NDK_
Con todos los modulos [4.6 MB](https://github.com/mercadolibre/mpmobile-android_wallet/pull/14546)
Es una lib Interna
- [fury_billpayments-android](https://github.com/mercadolibre/fury_billpayments-android/pull/708)
- [mpmobile-android_wallet](https://github.com/mercadolibre/mpmobile-android_wallet/pull/14546)
- [fury_billpayments-android](https://github.com/mercadolibre/fury_billpayments-android)
- …
> Add ml_scanner libraries

- ios-whitelist.json
... MLAddresses 
- [fury_addresses-ios](https://github.com/mercadolibre/fury_addresses-ios/pull/99)
- [fury_discounts-center-ios](https://github.com/mercadolibre/fury_discounts-center-ios)
> Support MLAddresses v5.0.0

- ios-whitelist.json
Se actualiza la versión de MPAppRater iOS
> Update MPAppRater Version

- android-whitelist.json
Se sube el major de la librería de recommendations.
"com.mercadolibre.android.recommendations:rcm:10.0"
> recos bump

- android-whitelist.json
...
- [mercadolibre](www.github.com/mercadolibre)
- [fury search android](https://github.com/mercadolibre/fury_search-android)
> updating ui_component rule version

- android-whitelist.json
- "com.mercadolibre.android.security:attestation:4.0.0"
- No hubo cambios
- No, no tiene código con NDK_
- Soporta API level 30
> New attestation major

- android-whitelist.json
- context_whitelist.json
- ios-whitelist.json
- - "com.mercadolibre.android.merch_realestates"
- No
- No
- Tiene min API level 21
- iOS Deployment target 12.1
- https://github.com/mercadolibre/fury_merch-realestates-android
- https://github.com/mercadolibre/fury_merch-realestates-ios
- [] Hay que agregar lo que pongo a continuación... 👇
> Merch RealEstates

- android-whitelist.json
- scripts/notification.rb
> fix date & print date in notification for debug

- android-whitelist.json
ruleEngine  : "com.mercadolibre.android.rule.engine:rule-engine:5.0.0",
cart                    : "com.mercadolibre.android.cart:cart:mercadolibre-10.0.0",
cartManager             : "com.mercadolibre.android.cart:manager:mercadolibre-9.0.0",
map         : "com.mercadolibre.android.marketplace.map:marketplace-map:8.0.0",
flox-component         : "com.mercadolibre.android.buyingflow.flox.components:4.0.0",
...
- _No, mi Lib no requiere inicialización
> Checkout bump:

- android-whitelist.json
- - "com.mercadolibre.android:milestone-tracker:4.0.0"
- - "com.mercadolibre.android:multiimageview:4.0.0"
- - "com.mercadolibre.android:progress-circler:4.0.0"
- [x ] _No, mi Lib no requiere inicialización en el `Application`_
> Update of available and expired versions

- android-whitelist.json
- Se actualiza versión de librería interna de Adjust. 
- Se incluye mejora en la comunicación con los servidores de Adjust (adjust signature).
- No cambia
- Si, tiene soporte.
- minApiLevel=21
- maxApiLevel=29
- La librería pesa 1MB
- N/A
- [MPSP Config Provider](https://github.com/mercadolibre/fury_mpsp-config-provider-android)
- [Cross App Links](https://github.com/mercadolibre/fury_cross-app-links-android)
- [MP Config Provider](https://github.com/mercadolibre/fury_mp-config-provider-android)
- [ML Config Provider](https://github.com/mercadolibre/fury_ml-config-provider-android)
- [MP](https://github.com/mercadolibre/mpmobile-android_wallet)
- [ML](https://github.com/mercadolibre/mobile-android)
Libs [internas](https://sites.google.com/mercadolibre.com/mobile/arquitectura/libs-utilitari …
> Adjust bump version

- ios-whitelist.json
> Bump MLRecommendations

- android-whitelist.json
- - "com.mercadolibre.android.cardscomponents:cards-components:5.+"
- _No, mi cards-components no requiere inicialización en `MercadoPago`_
- [Cards acquisition](https://github.com/mercadolibre/fury_cards-acquisition-android)
- [Cards engagement](https://github.com/mercadolibre/fury_cards-engagement-android)
> Bump major cards components

- android-whitelist.json
- - "androidx.biometric:biometric:1.1.0"
- https://github.com/mercadolibre/fury_user-biometrics-android/pull/55
- https://github.com/mercadolibre/fury_user-biometrics-android/
> biometric update

- ios-whitelist.json
> Regex modified

- android-whitelist.json
- - "com.mercadolibre.android.profileengine:peui:2.+
...
> Add Profile Engine UI Api 21 support

- android-whitelist.json
> Adds PX libaries API 21 versions

- ios-whitelist.json
> bump adjust

- android-whitelist.json
'org.tensorflow:tensorflow-lite:2.6.0'
No
0,8 MB se agregan en Android según PR de ML.
Google para MLKit ObjectDetection.
Bastante madura, se usa como base para toado lo que es ML del lado de Android.
Sí
Hace 2 dias
En principio no se wrappearia porque la usariamos solo nosotros Identity Validation
Si existe MLKit Object detection de Google pero pesa 3 veces más que esta librería.
Queremos detectar que la imagen que nos envía el usuario cumpla ciertas condiciones, como que tenga un documento, no esté blureada, tenga una iluminación correcta, etc.
Esto nos permite reducir la cantidad de iteraciones que tiene el usuario intentando una y otra vez subiendo imágenes incorrectas.
- [example …
> Bump tensorflow version 2.6.0

- android-whitelist.json
- "com.mercadolibre.android.mlwebkit:webkit-component:2.+",
- "com.mercadolibre.android.mlwebkit:landing:2.+",
- "com.mercadolibre.android.mlwebkit:webkit:2.+"
> Se agrega la version 2.+ de MLWebkit a la whitelist

- ios-whitelist.json
Eliminando lib deprecada: SDWebimage
> Remove deprecated libs

- android-whitelist.json
> add new version for play core.

- android-whitelist.json
expire "androidx.lifecycle:lifecycle-extensions"
> Expire lifecycle-extensions

- ios-whitelist.json
- DaManagement (https://github.com/mercadolibre/fury_da-management-ios)
...
NA
> Add DaManagement project to whitelist.

- android-whitelist.json
Fixing date commited by Cleaning Bot
> Fixing date commited by Cleaning Bot

- android-whitelist.json
Creo un PR para modificar el "name" en la lib de RealEstates y agregar fecha de expiración para la version 0.+
> RealEstates Lib

- android-whitelist.json
- - "com.mercadolibre.android.bookmarks.bookmarks"
- - "com.mercadolibre.android.history.history"
- - "com.mercadolibre.android.navigationcp.navigationcp"
- - "com.mercadolibre.android.navigationcp.shipping-address"
- - "com.mercadolibre.android.uinavigationcp.addresshub"
- - "com.mercadolibre.android.variations.variations"
- [History](https://github.com/mercadolibre/fury_history-android/pull/44)
- [Variation](https://github.com/mercadolibre/fury_variations-android/pull/95)
- [Navigation CP](https://github.com/mercadolibre/fury_navigationcp-android/pull/55)
- [UI Navigation …
> BUMP Bookmark, HIstory, NavigationCp y Variation

- ios-whitelist.json
No aplica
- No, mi Lib no requiere inicialización
> feat: Update MLThreeDS support version to 2.0.0

- android-whitelist.json
- - "com.mercadolibre.android.credits.behaviour"
...
- Para version 2.+ minApiLevel = 19 y maxApiLevel=29
- - Para version 3.+ minApiLevel = 21 y maxApiLevel=29
- [MercadoLibre Configuration Providers](https://github.com/mercadolibre/fury_ml-config-provider-android)
> Credits behaviour update

- android-whitelist.json
- "com.mercadolibre.android.discounts_touchpoint:mercadolibre-2.+"
- "com.mercadolibre.android.discounts_touchpoint:mercadopago-2.+"
- [PR Bump API 21](https://github.com/mercadolibre/fury_discounts-touchpoint-android/pull/19)
- [Buying Flow](https://github.com/mercadolibre/fury_buyingflow-mobile-android)
- [Homes](https://github.com/mercadolibre/fury_homes-android)
Libs [internas](https://sites.google.com/mercadolibre.com/mobile/arquitectura/libs-utilitarias/libs-internas) o [externas](https://sites.google.com/mercadolibre.com/mobile/arquitectura/libs-utilitarias/libs-externas) en la …
> Update Discounts Touchpoint 

- android-whitelist.json
- - "com.mercadolibre.android.loyalty:webview:mercadolibre-11.5.0"
- - "com.mercadolibre.android.loyalty:webview:mercadopago-11.5.0"
> loyalty whitelist bump

- android-whitelist.json
- "com.mercadolibre.android.uicomponents"
> Expire uicomponents 11.+

- .circleci/config.yml
- android-whitelist.json
- scripts/checkdate.rb
- scripts/checks.sh
changes:
- change the CI image to allow node+ruby
- move the CI check steps from jobs in CI to a script file, to allow new checks and easy the way we handle the results.
- add error descriptions/messages
- add check in expire dates to avoid bad formatted dates.
> Valida expire date check and other little QOL changes

- ios-whitelist.json
- CreditsFloxClient
- No, mi Lib no requiere inicialización en el `Application`
> [CCF2-7536] iOS Credits Flox Client dependency

- android-whitelist.json
- com.mercadolibre.android:analytics:production-9.0
- com.mercadolibre.android:analytics:develop-9.0
> Bump major on analytics

- android-whitelist.json
Analytics 8 expire for minAPI 21
> Expires for analytics major

- android-whitelist.json
> Rollback RX libs

- scripts/checkkeynames.rb
- scripts/checks.sh
The idea is to verify that the properties in the nodes have the proper key name:
valid ones: ['group', "name", 'version', 'expires', 'whitelist', 'description', "source", "target"]
it does not validate if they are in the proper platform though
> check key names

- android-whitelist.json
-  "com.mercadolibre.android.addresses:core:5.+"
-  "com.mercadolibre.android.addresses:zipcode:5.+"
...
- _No, es solo un update de la versión_
- [[Trivial] Bump automatic MinAPI 21](https://github.com/mercadolibre/fury_addresses-android/pull/201)
- [MyMl-MyData Android](https://github.com/mercadolibre/fury_myml-mydata-android)
- [Discounts-Center Android](https://github.com/mercadolibre/fury_discounts-center-android)
- [Buyingflow-Cho-Sdk Android](https://github.com/mercadolibre/fury_buyingflow-cho-sdk-android)
- [Cards-Acquisition Android](https://github.com/mercadolibre/fury_cards-acquisition-android)
Libs …
> Support Addresses Android v5.0.0

- android-whitelist.json
- delete fotoapparat lib since its not referenced in the apps anymore.
> remove apparat lib

- android-whitelist.json
- - "com.mercadolibre.android.devices_sdk:devices:2.+"
...
_No, mi Lib no requiere inicialización en el `Application`_
_No, xxLib no tiene código con NDK_
_No debería impactar ya que es solo un update de la version de una lib.
- [PR de la lib](https://github.com/mercadolibre/fury_devices-sdk-android/pull/64)
> Update devices lib major

- android-whitelist.json
Módulo con una view configurable para handleo de errores.
> ### **_Aclaración importante: es un módulo de uso interno del equipo, no están en ningun otro proyecto que no sea de SX/TFS._**
> Se agrega un nuevo módulo "errorhandler" en tfs_commons

- android-whitelist.json
- androidx.room:room-rxjava2:2.2.5
- No
- No
- 
- [paymentflow-fcu](https://github.com/mercadolibre/fury_payment-flow-fcu-android)
- [paymentflow](https://github.com/mercadolibre/fury_payment-flow-android)
> add room-rxjava2

- android-whitelist.json
- context_whitelist.json
- "com.mercadolibre.android.point_printer:core:1.+"
- "com.mercadolibre.android.point_printer:controller_a910:1.+"
- "com.mercadolibre.android.point_printer:controller_d20:1.+"
- "com.mercadolibre.android.point_printer:renderer:1.+"
- No
- Si, soporta las arquitecturas armeavi-v7 que son sobre las cuales está construido el SmartPos
Esta librería es necesaria en la implementación de Smart, ya que se encarga de la impresion usando el HW del dispositivo POINT SMART Android.
> + Se agrega librerías para modulo de impresión equipo Point Smart

- android-whitelist.json
> add new version dynamic feature

- android-whitelist.json
The following dependencies  changed the expiration date to send HotFix MP 2.196.2 until tomorrow:
- com.mercadolibre.android.uicomponents:collaborators:11.+ (Expired)
- com.mercadolibre.android.uicomponents:mvp:11.+ (Expired)
- No
- No
Api level 21
- It isn' t affecting
- https://github.com/mercadolibre/fury_payment-flow-android
- https://github.com/mercadolibre/fury_payment-flow-fcu-android
> [POINTMPOS-2471]change expiration date

- android-whitelist.json
- - "com.mercadolibre.android.andesui:coachmark:4.+"
- - "com.mercadolibre.android.andesui:components:4.+"
> Andes 4.+ added (API 21 major)

- android-whitelist.json
> Bump Login new version

- android-whitelist.json
Se mueve la fecha porque:
-El equipo a cargo es nuevo y esta en proceso de capacitación
-Se debe hacer un desarrollo para reemplazar las función que cumple la lib
-El equipo ya tuvo reunión con Arquitectura para dar flexibilidad de tiempo en la migración de la librería nativa de bluetooth
Libs [internas](https://sites.google.com/mercadolibre.com/mobile/arquitectura/libs-utilitarias/libs-internas) o [externas](https://sites.google.com/mercadolibre.com/mobile/arquitectura/libs-utilitarias/libs-extern …
> rxble change expiration date

- android-whitelist.json
- - "com.mercadolibre.android.credits.floxclient:core:0.1.0"
...
> Flox Client Core deleted expire time Android.

- ios-whitelist.json
- 'NewRelicAgent'`: nueva dependencia de tracking y medición con el objetivo de recuperar las métricas pedidas que tenemos con firebase performance.
- inicialmente trabajaremos en probar su rendimiendo midiendo el tiempo de los configurators, pero a futuro al idea es que sea el remplazo de firebase performance
- necesitamos la librería en modo prueba hasta el 31 de enero 2022, fecha en la que sabremos si podemos remplazar firebase performance
...
NO
-
- [MLMetrics](https://github.com/mercadolibre/fury_metrics-ios)
>  New Relic Agent

- android-whitelist.json
Agregamos  cross app link version 3.+
Deprecamos la version de Cross App Link 2.+
Deprecamos mercadolibre android login version 13.+ ya que se agregan los flavors
> Agregamos y deprecamos algunas libs 

- android-whitelist.json
- "com.mercadolibre.android.on.demand.resources:renderer-fresco:8.0.0"
- "com.mercadolibre.android.on.demand.resources:core:8.0.0"
- https://github.com/mercadolibre/fury_mercadopago-android/pull/15301
- https://github.com/mercadolibre/fury_mercadolibre-android/pull/9456
- https://github.com/mercadolibre/fury_mercadopago-android
- https://github.com/mercadolibre/fury_mercadolibre-android
Libs [internas](https://sites.google.com/mercadolibre.com/mobile/arquitectura/libs-utilitarias/libs-internas) o [externas](https://sites.google.com/mercadolibre.com/mobile/arquitectura/libs-utilitarias/l …
> update odr version

- ios-whitelist.json
- - "MLScanner"
- Se hicieron pruebas de la integración de MLKit en iOS (27/10):
Develop sin MLKit - 134.4 mb
Develop con MLkit/Barcode - 136.1 mb
Develop con MLKit/Barcode y OCR - 143.8 mb
> MLScanner Dependencies version

- ios-whitelist.json
PointUI
- [PointUI](https://github.com/mercadolibre/fury_point-ui-ios)
- [MPPoint](https://github.com/mercadolibre/fury_point-ios)
- [PointFlowEngine](https://github.com/mercadolibre/fury_point-flow-engine-ios)
> Updating PointUI whitelisted version

- android-whitelist.json
UPDATE:
com.mercadolibre.android.wallet.home:home:mercadopago-2.+
com.mercadolibre.android.wallet.home:sections:mercadopago-2.+
NEW:
com.mercadolibre.android.usersections:sections:mercadopago-2.+
com.mercadolibre.android.usersections:ui-sections:mercadopago-2.+
> Bump home 2.+ and usersections 2.+

- android-whitelist.json
- "com.mercadolibre.android.home.toolkit:core:1.+"
> Added MP Home toolkit android

- android-whitelist.json
Se agrega la nueva version de kotlin  1.5.31 &  coroutine 1.5.2
> Update libs kotlin and coroutine

- android-whitelist.json
"com.mercadolibre.android.ml_scanner:scanner:3+"
"com.mercadolibre.android.ml_scanner:barcode:3+"
"com.mercadolibre.android.ml_scanner:ocr:3+
- [singleplayer-pospaid](https://github.com/mercadolibre/fury_billpayments-android/pull/809)
- [singleplayer-prepaid](https://github.com/mercadolibre/fury_sp-prepaid-android/pull/556)
- [singleplayer-pospaid](https://github.com/mercadolibre/fury_billpayments-android)
- [singleplayer-prepaid](https://github.com/mercadolibre/fury_sp-prepaid-android)
Libs [internas](https://sites.google.com/mercadolibre.com/mobile/arquitectura/libs-utilitarias/libs-i …
> udpate version ml_scanner

- android-whitelist.json
se agrega esta lib que esta en WIP
> add smartlook lib back

- android-whitelist.json
Se agrega la version `2.7.2` de Cameraview que tiene soporte para la versión `1.5.32` de Kotlin.
- "com.otaliastudios.cameraview:2.7.2"
> Update cameraview version

- android-whitelist.json
- - "com.mercadolibre.android.braze:braze:0.1.0"
- - "com.appboy:android-sdk-ui:15.0.0"
N/D
- [mobile-notifications-android](https://github.com/mercadolibre/fury_mobile-notifications-android/)
> Se agrega la app braze-android en el context y la whitelist de android

- android-whitelist.json
- "com.mercadolibre.android:melidata-sdk:11.+"
- _No, OkHttp no requiere inicialización en el `Application`_
> Bump melidataSdk version to 11.+ Android

- android-whitelist.json
- - "org.jetbrains.kotlin:kotlin-stdlib-jdk8:1.5.32"
...
> Add jdk8 kotlin

- android-whitelist.json
-  "androidx.lifecycle:lifecycle-common-java8:2.2.0"
- No, **lifecycle-common-java8** no requiere inicialización en el `Application`
- No, lifecycle-common-java8 no tiene código con NDK
-  NA
-  No tiene impacto en el peso de descarga
- [PXN-2952 Implements delegate for view binding](https://github.com/mercadolibre/fury_valkiria-android/pull/49)
- [Valkiria Android Library](https://github.com/mercadolibre/fury_valkiria-android)
Libs [internas](https://sites.google.com/mercadolibre.com/mobile/arquitectura/libs-utilitarias/libs-internas) o [externas](https://sites.google.com/mercadolibre.com/mobile/arquitectura/libs-utilitarias/libs-externas) en la …
> NO-TICKET: [Feat] Add lifecycle-common-java8

- android-whitelist.json
https://developer.android.com/reference/com/google/android/play/core/release-notes
...
> Update Play Core lib

- android-whitelist.json
- com.mercadolibre.android.px.tokenization:core
- com.mercadolibre.android.px.tokenization:px-tokenization
- _SI, mi Lib requiere inicialización en el `Application`_. Solo en Mercado libre. En Mercado Pago ya existe la inicialización.
_Sin SDK_
_Con SDK_
Este proyecto usa internamente:
```
{
"group": "com\\.mercadolibre\\.android\\.nfcpayments",
"name": "hce-sdk",
"version": "6\\.+"
}
```
- [Card form](https://github.com/mercadolibre/card-form-android)
- [PX](https://github.com/mercadopago/px-android)
- [Wallet](https://github.com/mercadolibre/fury_mercadopago-android)
- [Marketplace](https://github.com/mercadolibre/fury_mercadolibre-android) …
> Tokenization dependency lib added

- ios-whitelist.json
- - "MLScanner"
...
Se hicieron pruebas de la integración de Scanner en iOS:
Develop sin MLKit - 134.4 mb
Develop con MLkit/Barcode - 136.1 mb
Develop con MLKit/Barcode y OCR - 143.8 mb
> Add Scanner to whitelist

- android-whitelist.json
> [Feature] Update Spirtech libs version

- android-whitelist.json
- - "androidx.lifecycle:lifecycle-runtime-ktx:2.4.0"
> Add dependency lifecyle ktx

- android-whitelist.json
- - "com.android.installreferrer:installreferrer:1.1.2"
...
> Add installreferrer

- ios-whitelist.json
> [DO NOT MERGE] Updated expires for New Relic.

- android-whitelist.json
- "com.mercadolibre.android.navigation_manager:1.+"
> Add navigation manager

- android-whitelist.json
- "com.mercadolibre.android.fees_installments:mlfees:4.+"
...
- No, mi Lib no requiere inicialización en el `Application`
- N/A
- [PR Bump version Pricing-UI](https://github.com/mercadolibre/fury_pricing-ui-android/pull/58)
- [Pricing-UI](https://github.com/mercadolibre/fury_pricing-ui-android)
> Update mlfees version

- android-whitelist.json
> Adding new Notifications module

- android-whitelist.json
- "com.mercadolibre.android.usersections:ui-sections:mercadolibre-2.+"
- "com.mercadolibre.android.mercadocoin:mercadocoin:1.+"
- La lib nueva de mercadocoin cuenta con un configurator que debe ser inicializado en el startup
> [Feature] - Add Android mercadocoin and ML ui-sections dependencies

- android-whitelist.json
- - "com.google.zxing.core:3.3.2"
- - "com.journeyapps:zxing-android-embedded:3.6.0|4.0.2"
Estimado, necesitamos extender la fecha de vencimiento de estas librerías debido a que el ML kit todavía tiene errores:
https://issuetracker.google.com/u/0/issues/207732702?pli=1
- [billpayments-android](https://github.com/mercadolibre/fury_billpayments-android)
- [ml-scanner-android](https://github.com/mercadolibre/fury_ml-scanner-android) …
> SPPG-913 - libs deprecated update

- android-whitelist.json
Change in module name from "mercadocoin" to "cryptodata"
> [Fix] - Change in crypto module name

- android-whitelist.json
Se agrego la version 20+ de commons y se depreco la version 18+
> commons 20+ added

- android-whitelist.json
- com.mercadolibre.android.buyingflow.flox.components:5.0.0"
> Buyingflow Flox Components - Deprecated 3.+, add 5.+

- android-whitelist.json
- "com.mercadolibre.android.search:input:12.0.1"
- "com.mercadolibre.android.search:search:12.0.1"
- [Cart](https://github.com/mercadolibre/fury_buyingflow-cart-android)
- [Home](https://github.com/mercadolibre/fury_homes-android)
- [VPP](https://github.com/mercadolibre/fury_vpp-android/)
> Update search version to 12

- ios-whitelist.json
> adding source and target to apppboy dependency

- ios-whitelist.json
Reverts mercadolibre/mobile-dependencies_whitelist#1057
Esta generando errores en otros PRs
> Revert "adding source and target to apppboy dependency"

- ios-whitelist.json
> braze-ios dependency (params order corrected)

- android-whitelist.json
Se agrega nueva librería interna de criptografía
- - "com.mercadolibre.android.mobile_cryptography:core:1.+"
> New Crypto lib

- android-whitelist.json
- - "com.polidea.rxandroidble:rxandroidble:1.5.0"
- - "com.mercadolibre.android.scanner:scanner:mercadolibre-1.+|mercadopago-1.+"
> ScannerLib, rxble change expiration day

- android-whitelist.json
"com.mercadolibre.android.ml_scanner:scanner:4+"
"com.mercadolibre.android.ml_scanner:barcode:4+"
"com.mercadolibre.android.ml_scanner:ocr:4+"
N/A
[singleplayer-pospaid](https://github.com/mercadolibre/fury_billpayments-android)
[singleplayer-prepaid](https://github.com/mercadolibre/fury_sp-prepaid-android)
> add major version ml_scanner

- android-whitelist.json
Se suma el major de rest-client que se se sube por min api 21, api 30 y update de agp
-[X] _No, mi Lib no requiere inicialización en el `Application`_
> New major rest-client

- android-whitelist.json
- ios-whitelist.json
- **ReauthNativeAdapter** aun en desarrollo.
- No
- No
- 10.0 ya que sera usada por MLNetworking
- ReauthNativeAdapter = 500 kb aprox
> ReauthNativeAdapter iOS Lib

- ios-whitelist.json
> Add New Crypto Lib

- android-whitelist.json
- "com.mercadolibre.android:melidata-sdk:12.+"
- _No, OkHttp no requiere inicialización en el `Application`_
> Bump MelidataSDK to 12

- android-whitelist.json
- - "com.mercadolibre.android.commons:submodule:21.0.0"
...
> [expire] common  version

- android-whitelist.json
"com.mercadolibre.android.recommendations:rcm:12.+"
- [VPP](https://github.com/mercadolibre/fury_vpp-android/)
- [Reviews](https://github.com/mercadolibre/fury_reviews-mobile-android)
- [Home](https://github.com/mercadolibre/fury_homes-android)
- [Cart, Checkout](https://github.com/mercadolibre/fury_buyingflow-mobile-android)
- [Orders](https://github.com/mercadolibre/myml-android_orders)
- [Feedback](https://github.com/mercadolibre/fury_feedback-mobile-android)
- [Search](https://github.com/mercadolibre/fury_search-android) 
Libs …
> Add new version of recos

- android-whitelist.json
- "com.mercadolibre.android.dynamic_features:4.+",
...
> Update Dynamic Feature

- context_whitelist.json
- ios-whitelist.json
- "BfSplitPayment: 0.+"
No
No
Las mismas que ML
Este modulo es una migración de una parte del modulo MLCheckoutSDK, es construido a través de la tecnologia flox.
Si, utiliza:
- MLBFFloxComponent (mantenida por Checkout)
- MLCheckoutSDK (mantenida por Checkout)
Esta nueva libreria va a soportar nuevas features tales SplitPayment (pagar con dos medios).
> se agrega checkout_on_splitPayment

- android-whitelist.json
- com.google.android.play:core-ktx:1.8.1 
- androidx.lifecycle:lifecycle-runtime-ktx:2.2.0
- androidx.lifecycle:lifecycle-livedata-ktx:2.2.0
- androidx.lifecycle:lifecycle-viewmodel-ktx:2.2.0
...
> Add play core ktx and lifecycle ktx

- android-whitelist.json
- - "com.mercadolibre.android:login:mercadolibre-14.0.0"
- - "com.mercadolibre.android:login:mercadopago-14.0.0"
...
> Login 14 bump

- android-whitelist.json
- - "com.mercadolibre.android.reauth_native_adapter:reauth_adapter:1.+"
- [Reauth nativa](https://github.com/mercadolibre/fury_native-reauth-android/pull/35)
- [MP config provider](https://github.com/mercadolibre/fury_mp-config-provider-android/pull/711)
- [ML config provider](https://github.com/mercadolibre/fury_ml-config-provider-android/pull/625)
- [Reauth nativa](https://github.com/mercadolibre/fury_native-reauth-android)
- [MP config provider](https://github.com/mercadolibre/fury_mp-config-provider-android)
- [ML config provider](https://github.com/mercadolibre/fury_ml-config-provider-android)
[RFC Propagacion de tokens reauth nativa](https://docs.google.com/document/d/1wPJ41SxvDql1-qV6pqTJ1C3JrfyKAfrIgcxCUAV00bY/edit?usp=s …
> Bump reauth adapter

- android-whitelist.json
- context_whitelist.json
> Bump version 4.+ totp

- android-whitelist.json
- Valkiria
- _No, Valkiria es una librería utilitaria que de momento expone solo 2 funcionalidades, `showIfNeeded` y `showErrorScreen` ambas deben ser llamadas por otras libs para mostrar pantallas de restricciones en sus flujos, no se carga al inicio de la app por sí misma._
[Valkiria …
> [Feat] Adding Android Valkiria Library 

- context_whitelist.json
- ios-whitelist.json
- Valkiria
- No, Valkiria es una librería utilitaria que de momento expone solo 2 funcionalidades, `showInteractionScreen` y `showErrorScreen` ambas deben ser llamadas por otras libs para mostrar pantallas de restricciones en sus flujos, no se carga al inicio de la app por sí misma
No usa ninguna librería externa
- Ninguno
Vallkiria iOS: https://github.com/mercadolibre/fury_valkiria-ios
> Adding Valkiria library

- context_whitelist.json
- ios-whitelist.json
> feat: adding data privacy helper on whitelist

- android-whitelist.json
Actualizamos las version de checkout + la de carrito.
> Update version de CHO + CART

- android-whitelist.json
> Update Cards Banking

- ios-whitelist.json
> Updated New Relic expires.

- android-whitelist.json
Update expiration day libs
- - com.polidea.rxandroidble:rxandroidble:1.5.0
- - com.mercadolibre.android.scanner:scanner:mercadolibre-1.+|mercadopago-1.+
- - io.reactivex:rxjava:1.3.6
- - io.reactivex:rxandroid:1.2.1
> ScannerLib, rxble, rxjava change expiration day

- android-whitelist.json
Update por librería de Kotlin
- "com.mercadolibre.android.nfcpayments:core:2.+"
- "com.mercadolibre.android.nfcpayments:flows:2.+"
> bump nfc version 

- android-whitelist.json
- Adicionar la dependencia de la nueva libdataprivacy para android, que tiene kotlin 1.5
Sí, nuestra libreria impacta, porque guardamos las preferencia de ubicación en un Catalog LocalStorage y necesitamos borrar el caché cada vez que los usuarios inician la aplicación MP o ML
Sí, utiliza la libreria LocalStorage para guardas las preferencia de ubicación de los usuarios
No tiene
Example module está pesando 14kb y xxLib para la versión 1.0 ~4 terabytes.
[example PR](https://github.com/mercadolibre/mobile-dependencies_whitelist/pull/www.github.com/mercadolibre)
Repositorios afectados
[example …
> adicionar version 2 para kotlin 1,5

- android-whitelist.json
- - "com.mercadolibre.android.inappupdates:in-app-updates:4.+"
...
- [* ]  _No, OkHttp no tiene código con NDK_
- [* ] _Tiene Min API level 23_
- [ *] Mercado Libre
- [ *] Mercado Pago
> In App Updates - Nueva version Android

- android-whitelist.json
- "com.mercadolibre.android:melidata-sdk:13.+"
- _No, OkHttp no requiere inicialización en el `Application`_
- _No, OkHttp no tiene código con NDK_
- _Tiene Min API level 21_
- _Example module está pesando 14kb y xxLib para la versión 6.0 ~4 terabytes._
> Bump melidata to 13.0

- android-whitelist.json
Migration Kotlin 1.5.32
- - "com.mercadolibre.android.cardsbanking:card-widget:3.+"
- - "com.mercadolibre.android.cardsbanking:cards-home-section:3.+"
...
> Banking Version 3.+    - Migration Kotlin 1.5.32

- ios-whitelist.json
ADLayoutTest (1.0.1)
ADAssertLayout (1.0.1)
SwiftCheck (0.12.0)
No 
NO
-
-No aplica
https://github.com/mercadolibre/fury_andesui-ios/
Ninguna ..
> ADAssertLayout

- android-whitelist.json
- "com.mercadolibre.android.variations::6.+"
> Update variations version 5.+ -> 6.+

- android-whitelist.json
- - "com.mercadolibre.android.notifications:mercadolibre-18+"
- - "com.mercadolibre.android.notifications:mercadopago-18+"
- -  "com.mercadolibre.android.notifications_commons:mercadopago-18+"
- N/A
> bump notifications

- ios-whitelist.json
> feat: updating data privacy helper version on whitelist

- android-whitelist.json
- - "com.mercadolibre.android.userbiometrics:core:4+"
- - "com.mercadolibre.android.userbiometrics:core:5+"
...
> new version for userbiometric

- android-whitelist.json
- ios-whitelist.json
- - "com.mercadolibre.android.fees_installments:mlfees:5.+"
- - "com.mercadolibre.android.tfs_commons:tracking:3.+"
- - "com.mercadolibre.android.tfs_commons:imageutils:3.+"
- - "com.mercadolibre.android.tfs_commons:ktx:3.+"
- - "com.mercadolibre.android.tfs_commons:mvp:3.+"
- - "com.mercadolibre.android.tfs_commons:errorhandler:3.+"
- N/A
- [PR a Pricing UI](https://github.com/mercadolibre/fury_pricing-ui-android/pull/62)
- [PR a MLFees](https://github.com/mercadolibre/fury_fees-installments-android/pull/99)
- [Pricing UI](https://github.com/mercadolibre/fury_pricing-ui-android)
- …
> Update mlfees and tfs commons libraries

- ios-whitelist.json
- - "MLRecommendationsCombo"
- No, mi Lib no requiere inicialización en el `Application`_
- No, xxLib no tiene código con NDK_
> Add RecommendationsCombo in ios whitelist

- android-whitelist.json
Se realiza un bump del mayor de nuestra librería en el contexto de las migraciones de gradle y kotlin y api 23 (La v2.+ solo contenia gradle y koltin pero la v3.+ suma api 23 así que se volvio a bumpear el major)
- "com.mercadolibre.android.charts.melicharts:3.+"
No aplica
- Se utiliza en tfs-dashboard-android y se necesita para completar la migración de gradle 7 y kotlin
- [https://github.com/mercadolibre/fury_tfs-dashboard-android](https://github.com/mercadolibre/fury_tfs-dashboard-android)
> [Internal dependency] Update melicharts dependency

- android-whitelist.json
- - "com.somepackage.somelib:submodule:4.0.0" with expired date
...
> Added Congrats Lib version 4.+

- ios-whitelist.json
- "MLRemedies 4.X.X"
- "IvCommons 2.X.X"
- NO
- NO
- SI
- N/A
> add new iv modules versions

- android-whitelist.json
- - "com.mercadolibre.android.reauth_native_adapter:reauth_adapter:1.+"
- - "com.mercadolibre.android.reauth_native_adapter:reauth_adapter:2.+"
> Reauth Native v2

- android-whitelist.json
> add expire and description eventBus

- android-whitelist.json
Se realiza la migración de Gradle a 7.4.
- "com.mercadolibre.android.insu_flox_components:5.+"
- "com.mercadolibre.android.insu_qpage_on:6.+"
- _No.
> Update Insurance version

- android-whitelist.json
Security Preferences v5
- - "com.mercadolibre.android.security:security_preferences:4+"
- - "com.mercadolibre.android.security:security_preferences:5+"
...
> Security Preferences v5

- ios-whitelist.json
...
- 
- [AndesUI](https://github.com/mercadolibre/fury_andesui-ios/)
> Fix Andes version

- android-whitelist.json
- - "com.mercadolibre.android:login:12.0.0"
...
> Add expire date to Login version 12

- android-whitelist.json
Reauth Native v3
- - "com.mercadolibre.android.security:native_reauth:2.+"
- - "com.mercadolibre.android.security:native_reauth:3.+"
> Reauth Native v3

- ios-whitelist.json
AndesUI iOS soporte para v4
Repositorios afectados
https://github.com/mercadolibre/fury_andesui-ios/tree/master/LibraryComponents
¿Afecta al start-up time de alguna forma?
No
¿Utiliza libs nativas? ¿Tiene soporte para las diferentes arquitecturas de devices?
Si
Versiones mínimas y máximas del sistema operativo soportadas
iOS 13
Impacto en el peso de descarga e instalación de la app
No
Libs [internas](https://sites.google.com/mercadolibre.com/mobile/arquitectura/libs-utilitarias/libs-internas) o [externas](https://sites.google.com/mercadolibre.com/mobile/arqui …
> Fix Regex Andes

- android-whitelist.json
"com.mercadolibre.android.security:security_ui:4.+"
"com.mercadolibre.android.security:security_ui:5.+"
> Security UI v5

- ios-whitelist.json
> Adding Acquisition 2x to allowlist

- android-whitelist.json
- group: "com.mercadolibre.android.mlwebkit"
- version: "3.+"
> Add Webkit 2.0
